import React from "react";
import { SUPPORT } from "@/constants/testIds";
import { Paperclip, AlertTriangle, Trash2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { TicketReleaseIdentifiers } from "@/components/shared/TicketReleaseIdentifiers";
import { TicketCategoryFields, TicketField } from "./tickets/TicketCategoryFields";
import { ACTIVE_TICKET_CATEGORIES, AUTO_SUBJECT_CATEGORIES, CONTENT_ID_CATEGORIES, TAKEDOWN_REASONS, ticketSubject, metadataFromRelease } from "./tickets/ticketFormConfig";
import { ContentIdClaimForm } from "./tickets/ContentIdClaimForm";
import { newContentIdState } from "./tickets/contentIdForm";
import { ReleaseSelectOptions } from "./tickets/ReleaseSelectOptions";

export function SupportTicketModal({ open, close, submit, form, setForm, releases, releaseTracks, releaseInfo, releaseLoading, busy, err, handleAudioUpload, handleCoverUpload, handleAttachment }) {
  const autoSubject = AUTO_SUBJECT_CATEGORIES.includes(form.category);
  const optionalDescription = CONTENT_ID_CATEGORIES.includes(form.category);
  const changeCategory = (category) => setForm((current) => ({ ...current, ...newContentIdState(), category, subject: AUTO_SUBJECT_CATEGORIES.includes(category) ? ticketSubject(category, releaseInfo) : "", reason: "", description: "", new_audio_track_id: "", originality_declared: false, youtube_urls: [""] }));
  const changeRelease = (release_id) => setForm((current) => ({ ...current, ...newContentIdState(), release_id, subject: "", new_metadata: metadataFromRelease(null), new_audio_track_id: "", originality_declared: false }));
  return <Dialog open={open} onOpenChange={(value) => !value && !busy && close()}>
    <DialogContent className="w-[calc(100%-2rem)] max-w-2xl max-h-[90dvh] overflow-y-auto rounded-lg border-white/15 bg-zinc-950 p-5 text-white sm:p-6 data-[state=open]:animate-none" data-testid="support-ticket-modal" closeTestId="support-ticket-modal-close">
      <DialogHeader className="text-left"><DialogTitle data-testid="support-ticket-modal-title">Buat Tiket Support</DialogTitle><DialogDescription className="sr-only">Pengajuan bantuan untuk rilisan label.</DialogDescription></DialogHeader>
      <form onSubmit={submit} className="min-w-0 space-y-4" data-testid="support-ticket-form">
        {err && <div role="alert" className="flex items-start gap-2 rounded-md bg-red-500/15 p-3 text-sm text-red-300" data-testid="support-ticket-error"><AlertTriangle className="h-4 w-4 shrink-0" /><span className="break-words">{err}</span></div>}
        <fieldset disabled={busy} className="min-w-0 space-y-4">
          <div className="grid gap-3 md:grid-cols-2"><TicketField label="Kategori" htmlFor="support-category"><select id="support-category" className="rm-input w-full min-w-0" value={form.category} onChange={(e) => changeCategory(e.target.value)} data-testid={SUPPORT.categorySelect}>{ACTIVE_TICKET_CATEGORIES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></TicketField><TicketField label="Rilisan" htmlFor="support-release"><select id="support-release" className="rm-input w-full min-w-0" value={form.release_id} onChange={(e) => changeRelease(e.target.value)} data-testid={SUPPORT.releaseSelect} required><option value="">— Pilih rilisan —</option><ReleaseSelectOptions releases={releases} /></select></TicketField></div>
          {releaseLoading ? <p className="text-sm text-zinc-500" data-testid="support-release-loading">Memuat informasi rilisan…</p> : releaseInfo && releaseInfo.id === form.release_id && <TicketReleaseIdentifiers upc={releaseInfo.upc} tracks={releaseTracks} isrcs={releaseInfo.isrc ? [releaseInfo.isrc] : []} prefix="support-release" />}
          <TicketField label="Subjek" htmlFor="support-subject"><input id="support-subject" className="rm-input w-full" value={form.subject} readOnly={autoSubject} onChange={(e) => setForm((current) => ({ ...current, subject: e.target.value }))} data-testid={SUPPORT.subjectInput} required minLength={3} maxLength={200} /></TicketField>
          {form.category !== "edit_metadata" && <TicketField label={`Deskripsi${optionalDescription ? " (opsional)" : ""}`} htmlFor="support-description"><textarea id="support-description" className="rm-input min-h-24 w-full" value={form.description} onChange={(e) => setForm((current) => ({ ...current, description: e.target.value }))} data-testid={SUPPORT.descriptionInput} required={!optionalDescription} minLength={optionalDescription ? undefined : 3} maxLength={4000} /></TicketField>}
          {form.category === "takedown" && <TicketField label="Alasan Takedown" htmlFor="support-reason"><select id="support-reason" className="rm-input w-full" value={form.reason} onChange={(e) => setForm((current) => ({ ...current, reason: e.target.value }))} data-testid={SUPPORT.reasonInput} required><option value="">— Pilih alasan —</option>{TAKEDOWN_REASONS.map((reason) => <option key={reason} value={reason}>{reason}</option>)}</select></TicketField>}
          <TicketCategoryFields form={form} setForm={setForm} releaseTracks={releaseTracks} releaseLoading={releaseLoading} handleAudioUpload={handleAudioUpload} handleCoverUpload={handleCoverUpload} />
          {form.category === "content_id_claim" && <ContentIdClaimForm form={form} setForm={setForm} tracks={releaseTracks} />}
          {form.category === "edit_metadata" && <TicketField label="Alasan Perubahan" htmlFor="support-reason"><textarea id="support-reason" className="rm-input min-h-20 w-full" value={form.reason} onChange={(e) => setForm((current) => ({ ...current, reason: e.target.value }))} data-testid={SUPPORT.reasonInput} required maxLength={4000} /></TicketField>}
          <TicketField label="Lampiran Tambahan (opsional)" htmlFor="support-attachment"><input id="support-attachment" data-testid="support-ticket-attachment" type="file" className="rm-input w-full min-w-0" onChange={handleAttachment} accept=".jpg,.jpeg,.png,.pdf,.txt,.docx,.doc" />{form.attachments.length > 0 && <ul className="mt-2 space-y-2">{form.attachments.map((attachment, index) => <li key={attachment.url} className="flex min-w-0 items-center gap-2 text-xs text-zinc-300"><Paperclip className="h-3 w-3 shrink-0" /><span className="min-w-0 break-all" data-testid={`support-attachment-name-${index + 1}`}>{attachment.filename}</span><button type="button" title="Hapus lampiran" aria-label={`Hapus lampiran ${attachment.filename}`} data-testid={`support-attachment-remove-${index + 1}`} className="shrink-0 p-1 text-red-300 hover:text-red-200" onClick={() => setForm((current) => ({ ...current, attachments: current.attachments.filter((item) => item.url !== attachment.url) }))}><Trash2 className="h-4 w-4" /></button></li>)}</ul>}</TicketField>
        </fieldset>
        <div className="flex flex-wrap justify-end gap-2 pt-2"><button type="button" className="rm-btn-ghost" disabled={busy} onClick={close} data-testid="support-ticket-cancel">Batal</button><button className="rm-btn-primary disabled:opacity-50" disabled={busy || releaseLoading || !releaseInfo || releaseInfo.id !== form.release_id} data-testid={SUPPORT.submitButton}>{busy ? (form.category === "content_id_claim" ? "Menyiapkan surat…" : "Memproses…") : "Kirim Tiket"}</button></div>
      </form>
    </DialogContent>
  </Dialog>;
}