"""Default CMS landing-page settings (seeded into MongoDB on startup)."""
from typing import Dict, Any

DEFAULT_LANDING_SETTINGS: Dict[str, Any] = {
    "general": {
        "site_title": "RILIS MUSIK — Distribusi Musik Digital",
        "brand_name": "RILIS MUSIK",
        "logo_url": None,
        "favicon_url": None,
        "primary_color": "#FF3B30",
        "support_email": "support@rilismusik.com",
        "whatsapp": "+6281234567890",
        "social": {"instagram": "https://instagram.com/rilismusik", "tiktok": "", "twitter": ""},
    },
    "hero": {
        "headline": "Distribusi Musik Lebih Rapi, Royalti Lebih Transparan.",
        "subheadline": "Platform distribusi musik digital untuk label musik dan artis independen. Upload rilisan, kelola artist, dan pantau royalti dari satu dashboard.",
        "cta_primary_text": "Daftar Sekarang",
        "cta_primary_url": "/register",
        "cta_secondary_text": "Login Dashboard",
        "cta_secondary_url": "/login",
        "hero_image_url": "https://images.unsplash.com/photo-1580656449278-e8381933522c?w=1600&q=85",
    },
    "benefits": [
        {"title": "Upload Rilisan dari Dashboard", "desc": "Submit lagu, EP, atau album tanpa WhatsApp. Cukup dari dashboard."},
        {"title": "Laporan Royalti Transparan", "desc": "Lihat revenue per lagu, platform, dan negara dalam IDR."},
        {"title": "Withdraw Terjadwal", "desc": "Cairkan saldo setiap tanggal 1–14 dengan invoice yang rapi."},
        {"title": "Support Takedown & Edit", "desc": "Ajukan takedown, edit metadata, audio, atau cover dengan mudah."},
        {"title": "YouTube Content ID", "desc": "Ajukan dan kelola klaim Content ID untuk lagu Anda."},
        {"title": "Dashboard Artist", "desc": "Artist Anda punya akun sendiri dan bisa lihat royalti lagu mereka."},
        {"title": "Simulasi Royalti", "desc": "Hitung estimasi pendapatan dari revenue Believe."},
        {"title": "Data Granular", "desc": "Per lagu, platform, dan negara. Semuanya rapi & detail."},
    ],
    "how_it_works": [
        "Daftar akun label",
        "Submit rilisan",
        "Bayar per rilis atau aktifkan subscription",
        "Admin review",
        "Rilisan dikirim ke Believe",
        "Royalti masuk dari laporan bulanan",
        "Withdraw sesuai jadwal",
    ],
    "pricing": {
        "pay_per_release_price": 35000,
        "annual_normal_price": 350000,
        "annual_subscription_price": 500000,  # VIP — kept key for backwards compat
        "wami_addon_price": 100000,
        "distributor_fee_percent": 0,
        "description": "Pilih skema yang paling cocok untuk skala katalog Anda.",
        "features_pay": ["Unlimited revisi sebelum approve", "Audit metadata oleh admin", "Distribusi ke 150+ DSP via Believe"],
        "features_annual_normal": ["Submit unlimited release", "Prioritas review", "Tanpa biaya per release"],
        "features_sub": ["Submit unlimited release", "Prioritas review", "GRATIS pendaftaran LMKN-WAMI semua lagu", "GRATIS konten promosi (JPG postingan)", "Status WAMI real-time"],
    },
    "royalty_sim": {
        "default_revenue_eur": 100,
        "default_rate": 17500,
        "fee_percent": 0,
        "label_percent_default": 60,
    },
    "dashboard_previews": [
        "https://images.unsplash.com/photo-1636226570637-3fbda7ca09dc?w=1200&q=85",
    ],
    "testimonials": [
        {"name": "Adit Soemardi", "role": "Founder, Nada Kala Records", "quote": "Akhirnya nggak perlu chat-chat WA buat submit lagu lagi. Royalti juga jelas per lagu."},
        {"name": "Rara Wijaya", "role": "Artis Independen", "quote": "Dashboard-nya enak banget di HP. Withdraw juga cepet."},
    ],
    "faq": [
        {"q": "Apa itu RILIS MUSIK?", "a": "Platform distribusi musik digital ke 150+ DSP via Believe. Cocok untuk label dan artis independen Indonesia."},
        {"q": "Berapa biaya distribusi?", "a": "Tiga paket: Rp 35.000 per rilis (Pay Per Release), Rp 350.000 per tahun (Annual Normal), atau Rp 500.000 per tahun (Annual VIP — gratis WAMI + konten promosi)."},
        {"q": "Apakah bisa upload album?", "a": "Bisa. Kami mendukung Single, EP, Album, dan Compilation."},
        {"q": "Kapan royalti cair?", "a": "Request withdraw tanggal 1–14, pembayaran tanggal 15–20 setiap bulan."},
        {"q": "Apakah ada YouTube Content ID?", "a": "Ada. Anda bisa mengajukan klaim Content ID via support ticket."},
        {"q": "Apakah artis bisa lihat royalti?", "a": "Bisa. Label dapat membuat akun artist dengan visibilitas royalti yang diatur."},
        {"q": "Apakah bisa takedown?", "a": "Bisa via support ticket."},
    ],
    "seo": {
        "page_title": "RILIS MUSIK — Distribusi Musik Digital Indonesia",
        "meta_description": "Distribusi lagu Anda ke 150+ DSP via Believe. Royalti transparan dalam IDR. Cocok untuk label dan artis independen.",
        "og_title": "RILIS MUSIK",
        "og_description": "Distribusi musik digital. Laporan royalti transparan. Withdraw rapi.",
        "og_image": "",
        "canonical_url": "https://rilismusik.com",
    },
    "footer": {
        "description": "Platform distribusi musik digital Indonesia. Dari demo ke 150+ platform.",
        "support_email": "support@rilismusik.com",
        "legal_links": [{"text": "Syarat & Ketentuan", "url": "/terms"}, {"text": "Privacy Policy", "url": "/privacy"}],
    },
    "legal_entity": {
        "company_name": "PT. Jeeres Group Indonesia",
        "address_line1": "Jl. Sintang Pontianak",
        "address_line2": "RT 12 / RW 5, Kec. Sintang",
        "city": "Sintang",
        "postal_code": "78614",
        "country": "Indonesia",
        "whatsapp": "085864137150",
        "nib": "2202260059749",
    },
}
