import React from "react";
import { Languages, Sun, Moon, Clock3, Volume2, VolumeX, Check } from "lucide-react";
import { useAppPreferences } from "@/contexts/AppPreferencesContext";
import { playNotificationSound, unlockNotificationSound } from "@/lib/notificationSound";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator } from "@/components/ui/dropdown-menu";

export const HeaderPreferences = ({ instance = "header" }) => {
  const { locale, setLocale, t, mode, setMode, sound, setSound, volume, setVolume } = useAppPreferences();
  const ThemeIcon = mode === "auto" ? Clock3 : mode === "light" ? Sun : Moon;
  return <div className="flex shrink-0 items-center gap-1.5" data-testid={`header-preferences-${instance}`}>
    <DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="ui-icon-button" title={t("Suara notifikasi")} aria-label={t("Suara notifikasi")} data-testid={`sound-menu-${instance}`}>{sound ? <Volume2 className="h-4 w-4" /> : <VolumeX className="h-4 w-4" />}</button></DropdownMenuTrigger><DropdownMenuContent className="ui-menu w-60" align="end" data-testid={`sound-dropdown-${instance}`}><DropdownMenuLabel>{t("Suara notifikasi")}</DropdownMenuLabel><DropdownMenuItem onSelect={async () => { await unlockNotificationSound(); setSound(!sound); }} data-testid={`sound-toggle-${instance}`}>{sound ? <VolumeX className="mr-2 h-4 w-4" /> : <Volume2 className="mr-2 h-4 w-4" />}{sound ? t("Bisukan") : t("Aktifkan suara")}</DropdownMenuItem><div className="px-2 py-3"><label className="mb-2 flex justify-between text-xs" htmlFor={`sound-volume-${instance}`}>{t("Volume")}<span data-testid={`sound-volume-value-${instance}`}>{Math.round(volume * 100)}%</span></label><input id={`sound-volume-${instance}`} data-testid={`sound-volume-${instance}`} className="w-full accent-pink-600" type="range" min="0" max="1" step="0.05" value={volume} onChange={(event) => setVolume(Number(event.target.value))} /></div><DropdownMenuItem onSelect={async () => { setSound(true); await unlockNotificationSound(); playNotificationSound("notification", null, true); }} data-testid={`sound-test-${instance}`}>{t("Uji suara")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    <DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="ui-icon-button" title={t("Mode tampilan")} aria-label={t("Mode tampilan")} data-testid={`theme-menu-${instance}`}><ThemeIcon className="h-4 w-4" /></button></DropdownMenuTrigger><DropdownMenuContent className="ui-menu" align="end" data-testid={`theme-dropdown-${instance}`}><DropdownMenuLabel>{t("Mode tampilan")}</DropdownMenuLabel>{[["light", Sun, "Terang"], ["dark", Moon, "Gelap"], ["auto", Clock3, "Otomatis"]].map(([value, Icon, label]) => <DropdownMenuItem key={value} onSelect={() => setMode(value)} data-testid={`theme-${value}-${instance}`}><Icon className="mr-2 h-4 w-4" />{t(label)}{mode === value && <Check className="ml-auto h-3.5 w-3.5" />}</DropdownMenuItem>)}<DropdownMenuSeparator /><div className="px-2 py-1.5 text-[11px] text-[var(--ui-muted)]" data-testid={`theme-auto-hours-${instance}`}>WIB · 06.00–18.00</div></DropdownMenuContent></DropdownMenu>
    <DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="ui-icon-button w-auto gap-1 px-2" title={t("Bahasa")} aria-label={t("Bahasa")} data-testid={`language-menu-${instance}`}><Languages className="h-4 w-4" /><span className="text-[10px] font-bold" data-testid={`language-current-${instance}`}>{locale.toUpperCase()}</span></button></DropdownMenuTrigger><DropdownMenuContent className="ui-menu" align="end" data-testid={`language-dropdown-${instance}`}><DropdownMenuLabel>{t("Bahasa")}</DropdownMenuLabel>{[["id", "Bahasa Indonesia"], ["en", "English"]].map(([value, label]) => <DropdownMenuItem key={value} onSelect={() => setLocale(value)} data-testid={`language-${value}-${instance}`}>{label}{locale === value && <Check className="ml-auto h-3.5 w-3.5" />}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
  </div>;
};