import React from "react";
import { ArrowLeft, ArrowRight, LockKeyhole, Plus, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { newArtist } from "./releaseFormState";
import { SocialLinksEditor } from "@/components/artists/SocialLinksEditor";
import { SocialLinksList } from "@/components/artists/SocialLinksList";

const ArtistRow = ({ artist, index, savedArtists, updateArtist, remove, canRemove, prefix, roleLabel }) => {
  const stored = artist.artist_id ? savedArtists.find((item) => item.id === artist.artist_id) : null;
  const selectArtist = (artistId) => {
    if (!artistId) { updateArtist(newArtist()); return; }
    const selected = savedArtists.find((item) => item.id === artistId);
    if (!selected) return;
    const links = (selected.social_links || []).map((item) => ({ ...item, client_id: crypto.randomUUID() }));
    updateArtist({ ...artist, artist_id: selected.id, name: selected.artist_name, social_links: links, spotify_url: links.find((item) => item.platform === "spotify")?.url || null });
  };
  return <article className="py-6" data-testid={`${prefix}-row-${index}`}><div className="grid gap-4 md:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)_40px]"><div className="space-y-3"><label><span className="rm-label">Sumber {roleLabel}</span><select className="rm-input" value={artist.artist_id || ""} onChange={(event) => selectArtist(event.target.value)} data-testid={`${prefix}-source-${index}`}><option value="">Buat artis baru</option>{savedArtists.map((item) => <option key={item.id} value={item.id}>{item.artist_name}</option>)}</select></label>{artist.artist_id ? <div className="rounded-md border border-white/10 bg-white/[0.03] px-3 py-3"><div className="flex items-center justify-between gap-3"><strong data-testid={`${prefix}-stored-name-${index}`}>{artist.name}</strong><LockKeyhole className="h-4 w-4 text-zinc-500" /></div><p className="mt-1 text-xs text-zinc-500">Data tersimpan hanya dapat diedit dari Manajemen Artis.</p></div> : <label><span className="rm-label">Nama {roleLabel}</span><input className="rm-input" value={artist.name} onChange={(event) => updateArtist({ ...artist, name: event.target.value })} data-testid={`${prefix}-name-${index}`} /></label>}</div><div>{artist.artist_id ? <div><div className="mb-2 rm-label">Media Sosial Tersimpan</div><SocialLinksList links={stored?.social_links || artist.social_links} prefix={`${prefix}-stored-social-${index}`} emptyText="Tautan sosial belum lengkap" />{!(stored?.social_links || artist.social_links)?.length && <Link to="/label/artists" className="mt-3 inline-flex text-xs font-bold text-amber-300 hover:text-amber-200" data-testid={`${prefix}-complete-social-${index}`}>Lengkapi di Manajemen Artis →</Link>}</div> : <SocialLinksEditor links={artist.social_links} onChange={(social_links) => updateArtist({ ...artist, social_links })} prefix={`${prefix}-new-${index}`} />}</div><button type="button" title="Hapus artis" disabled={!canRemove} onClick={remove} className="self-start rounded-md p-3 text-red-300 transition-colors hover:bg-red-500/10 disabled:opacity-30" data-testid={`${prefix}-remove-${index}`}><Trash2 className="h-4 w-4" /></button></div></article>;
};

const ArtistList = ({ title, description, values, setValues, savedArtists, prefix, required }) => <div className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-display text-lg font-bold">{title}</h3><p className="text-xs text-zinc-500">{description}</p></div><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={() => setValues([...values, newArtist()])} data-testid={`${prefix}-add-button`}><Plus className="h-4 w-4" /> Tambah Artis</button></div><div className="divide-y divide-white/10 border-y border-white/10">{values.length === 0 && <div className="py-5 text-sm text-zinc-500">Tidak ada artis featuring.</div>}{values.map((artist, index) => <ArtistRow key={artist.client_id} artist={artist} index={index} savedArtists={savedArtists} roleLabel={required ? "Artis Utama" : "Artis Featuring"} prefix={prefix} canRemove={!required || values.length > 1} updateArtist={(next) => setValues(values.map((item, itemIndex) => itemIndex === index ? next : item))} remove={() => setValues(values.filter((_, itemIndex) => itemIndex !== index))} />)}</div></div>;

export const ArtistCreditsStep = ({ form, updateForm, savedArtists, onBack, onNext }) => <section className="space-y-10" data-testid="upload-release-artists-step"><div><h2 className="font-display text-2xl font-bold">Artis dan featuring</h2><p className="mt-1 text-sm text-zinc-400">Pilih profil tersimpan atau buat artis baru dengan minimal satu tautan media sosial.</p></div><ArtistList title="Artis Utama" description="Minimal satu artis; tidak ada batas jumlah." values={form.primary_artists} setValues={(primary_artists) => updateForm({ primary_artists })} savedArtists={savedArtists} prefix="upload-release-primary-artist" required /><ArtistList title="Artis Featuring" description="Kosongkan jika rilisan tidak memiliki featuring." values={form.featured_artists} setValues={(featured_artists) => updateForm({ featured_artists })} savedArtists={savedArtists} prefix="upload-release-featured-artist" /><div className="flex justify-between border-t border-white/10 pt-5"><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={onBack} data-testid="upload-release-artists-back-button"><ArrowLeft className="h-4 w-4" /> Kembali</button><button type="button" className="rm-btn-primary inline-flex items-center gap-2" onClick={onNext} data-testid="upload-release-artists-next-button">Lanjut ke Track <ArrowRight className="h-4 w-4" /></button></div></section>;