import React from "react";
import { ArrowLeft, ArrowRight, Plus, Trash2 } from "lucide-react";
import { newArtist } from "./releaseFormState";

function ArtistList({ title, description, values, setValues, prefix, required }) {
  const update = (index, field, value) => setValues(values.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  return <div className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-display text-lg font-bold">{title}</h3><p className="text-xs text-zinc-500">{description}</p></div><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={() => setValues([...values, newArtist()])} data-testid={`${prefix}-add-button`}><Plus className="h-4 w-4" /> Tambah Artist</button></div><div className="divide-y divide-white/10 border-y border-white/10">{values.length === 0 && <div className="py-5 text-sm text-zinc-500">Tidak ada featuring.</div>}{values.map((artist, index) => <div className="grid gap-3 py-4 md:grid-cols-[1fr_1.4fr_auto]" key={artist.client_id}><label><span className="rm-label">Nama {required ? "Artist" : "Featuring"}</span><input className="rm-input" value={artist.name} onChange={(event) => update(index, "name", event.target.value)} data-testid={`${prefix}-name-${index}`} /></label><label><span className="rm-label">URL Spotify Artist — jika ada</span><input type="url" className="rm-input" placeholder="https://open.spotify.com/artist/…" value={artist.spotify_url || ""} onChange={(event) => update(index, "spotify_url", event.target.value)} data-testid={`${prefix}-spotify-${index}`} /></label><button type="button" title="Hapus artist" disabled={required && values.length === 1} onClick={() => setValues(values.filter((_, itemIndex) => itemIndex !== index))} className="self-end rounded-md p-3 text-red-300 transition-colors hover:bg-red-500/10 disabled:opacity-30" data-testid={`${prefix}-remove-${index}`}><Trash2 className="h-4 w-4" /></button></div>)}</div></div>;
}

export const ArtistCreditsStep = ({ form, updateForm, onBack, onNext }) => <section className="space-y-10" data-testid="upload-release-artists-step"><div><h2 className="font-display text-2xl font-bold">Artist dan featuring</h2><p className="mt-1 text-sm text-zinc-400">Tambahkan seluruh artist yang dikreditkan. URL Spotify bersifat opsional.</p></div><ArtistList title="Artist Utama" description="Minimal satu artist; tidak ada batas jumlah." values={form.primary_artists} setValues={(primary_artists) => updateForm({ primary_artists })} prefix="upload-release-primary-artist" required /><ArtistList title="Featuring" description="Kosongkan jika rilisan tidak memiliki featuring." values={form.featured_artists} setValues={(featured_artists) => updateForm({ featured_artists })} prefix="upload-release-featured-artist" /><div className="flex justify-between border-t border-white/10 pt-5"><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={onBack} data-testid="upload-release-artists-back-button"><ArrowLeft className="h-4 w-4" /> Kembali</button><button type="button" className="rm-btn-primary inline-flex items-center gap-2" onClick={onNext} data-testid="upload-release-artists-next-button">Lanjut ke Track <ArrowRight className="h-4 w-4" /></button></div></section>;