import React, { useState } from "react";
import { ArrowLeft, CheckCircle2, FileAudio, ImageIcon, Loader2, Send, UploadCloud } from "lucide-react";
import { fileUrl } from "@/api/client";
import { api, formatApiError } from "@/api/client";
import { validateCoverFile, readWavSampleRate } from "./fileValidation";

export const AssetsReviewStep = ({ release, products, selectedAddons, setSelectedAddons, isPpr, addonTotal, declaration, setDeclaration, saving, setError, reloadRelease, onBack, onSubmit }) => {
  const [uploading, setUploading] = useState("");
  const upload = async (path, formData, key) => {
    setUploading(key); setError("");
    try { await api.post(path, formData, { headers: { "Content-Type": "multipart/form-data" } }); await reloadRelease(release.id); }
    catch (requestError) { setError(formatApiError(requestError.response?.data?.detail) || requestError.message || "Upload gagal"); }
    finally { setUploading(""); }
  };
  const coverChange = async (event) => {
    const file = event.target.files?.[0]; if (!file) return;
    try { await validateCoverFile(file); const data = new FormData(); data.append("file", file); await upload(`/releases/${release.id}/upload-cover`, data, "cover"); }
    catch (validationError) { setError(validationError.message); }
  };
  const audioChange = (track) => async (event) => {
    const file = event.target.files?.[0]; if (!file) return;
    try { await readWavSampleRate(file); const data = new FormData(); data.append("track_id", track.id); data.append("file", file); await upload(`/releases/${release.id}/upload-audio`, data, track.id); }
    catch (validationError) { setError(validationError.message); }
  };
  const filesReady = release.cover_url && release.tracks?.every((track) => track.audio_url && [44100, 48000].includes(track.audio_sample_rate));
  return <section className="space-y-10" data-testid="upload-release-assets-step"><div><h2 className="font-display text-2xl font-bold">File dan review</h2><p className="mt-1 text-sm text-zinc-400">Validasi dilakukan di browser dan di server sebelum rilisan dapat disubmit.</p></div><div className="grid gap-8 lg:grid-cols-[minmax(0,0.75fr)_minmax(0,1.25fr)]">
    <div><div className="mb-3 flex items-center gap-2 text-sm font-bold"><ImageIcon className="h-4 w-4" /> Cover 3000×3000</div><label className="block cursor-pointer border border-dashed border-white/20 p-4 transition-colors hover:bg-white/[0.03]" data-testid="upload-release-cover-dropzone">{release.cover_url ? <img src={fileUrl(release.cover_url)} alt="Cover rilisan" className="aspect-square w-full object-contain" data-testid="upload-release-cover-preview" /> : <div className="grid aspect-square place-items-center text-center text-zinc-500"><div><UploadCloud className="mx-auto h-8 w-8" /><p className="mt-3 text-sm font-bold">Pilih JPG atau PNG</p><p className="mt-1 text-xs">Wajib tepat 3000×3000 px</p></div></div>}<input hidden type="file" accept="image/jpeg,image/png" onChange={coverChange} data-testid="upload-release-cover-input" /></label>{uploading === "cover" && <div className="mt-2 flex items-center gap-2 text-xs text-zinc-400" data-testid="upload-release-cover-uploading"><Loader2 className="h-3.5 w-3.5 animate-spin" /> Mengunggah cover…</div>}</div>
    <div><div className="mb-3 flex items-center gap-2 text-sm font-bold"><FileAudio className="h-4 w-4" /> Audio WAV per track</div><div className="divide-y divide-white/10 border-y border-white/10">{release.tracks?.map((track) => <div className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between" key={track.id} data-testid={`upload-release-audio-row-${track.id}`}><div><div className="font-semibold">{track.track_number}. {track.track_title}</div><div className={`mt-1 text-xs ${track.audio_url ? "text-emerald-300" : "text-zinc-500"}`} data-testid={`upload-release-audio-status-${track.id}`}>{track.audio_url ? `Siap — WAV ${(track.audio_sample_rate / 1000).toLocaleString("id-ID")} kHz` : "Belum diunggah"}</div></div><label className="rm-btn-ghost inline-flex cursor-pointer items-center justify-center gap-2 text-xs" data-testid={`upload-release-audio-button-${track.id}`}>{uploading === track.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <UploadCloud className="h-4 w-4" />} {track.audio_url ? "Ganti WAV" : "Upload WAV"}<input hidden type="file" accept=".wav,audio/wav,audio/x-wav" onChange={audioChange(track)} data-testid={`upload-release-audio-input-${track.id}`} /></label></div>)}</div></div>
  </div>{isPpr && products.length > 0 && <div className="space-y-4 border-y border-white/10 py-7" data-testid="upload-release-addons-section"><div><h3 className="font-display text-xl font-bold">Layanan tambahan</h3><p className="mt-1 text-sm text-zinc-400">Dipilih sekarang dan ditagihkan setelah metadata dinyatakan valid oleh admin.</p></div><div className="grid gap-3 md:grid-cols-2">{products.map((product) => <label className="flex cursor-pointer items-start gap-3 rounded-md border border-white/10 p-4 transition-colors hover:bg-white/[0.03]" key={product.id} data-testid={`upload-release-addon-${product.id}`}><input type="checkbox" className="mt-1" checked={selectedAddons.includes(product.id)} onChange={() => setSelectedAddons((items) => items.includes(product.id) ? items.filter((value) => value !== product.id) : [...items, product.id])} data-testid={`upload-release-addon-checkbox-${product.id}`} /><span className="min-w-0 flex-1"><strong className="block text-sm">{product.name}</strong><span className="mt-1 block text-xs text-zinc-500">{product.description}</span></span><strong className="text-sm">Rp {Number(product.amount || 0).toLocaleString("id-ID")}</strong></label>)}</div><div className="flex justify-between border-t border-white/10 pt-4 text-sm"><span className="text-zinc-400">Estimasi invoice</span><strong data-testid="upload-release-invoice-estimate">Rp {(35000 + addonTotal).toLocaleString("id-ID")}</strong></div></div>}
  <div className="space-y-5 border-t border-white/10 pt-7"><label className="flex cursor-pointer items-start gap-3 text-sm leading-relaxed"><input type="checkbox" checked={declaration} onChange={(event) => setDeclaration(event.target.checked)} className="mt-1" data-testid="upload-release-declaration-checkbox" /><span>Saya menyatakan memiliki hak distribusi atas audio dan cover, seluruh metadata serta nama kredit benar, dan bertanggung jawab atas sengketa yang muncul.</span></label><div className={`flex items-center gap-2 text-sm ${filesReady ? "text-emerald-300" : "text-amber-300"}`} data-testid="upload-release-files-readiness">{filesReady ? <CheckCircle2 className="h-4 w-4" /> : <FileAudio className="h-4 w-4" />}{filesReady ? "Semua file lolos validasi" : "Cover dan seluruh audio wajib dilengkapi"}</div><div className="flex flex-wrap justify-between gap-3"><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={onBack} data-testid="upload-release-assets-back-button"><ArrowLeft className="h-4 w-4" /> Edit Metadata</button><button type="button" className="rm-btn-primary inline-flex items-center gap-2" disabled={saving || !declaration || !filesReady || Boolean(uploading)} onClick={onSubmit} data-testid="upload-release-submit-button"><Send className="h-4 w-4" /> {saving ? "Mengirim…" : "Kirim ke Admin"}</button></div></div>
  </section>;
};