import React, { useEffect, useState } from "react";
import { X } from "lucide-react";
import { ADMIN_USER } from "@/constants/testIds";

export const AdminUserDialog = ({ user, roles, onClose, onSave, saving }) => {
  const editing = Boolean(user?.id);
  const [form, setForm] = useState({ name: "", email: "", password: "", admin_role_id: roles[0]?.id || "", status: "active" });
  useEffect(() => setForm({ name: user?.name || "", email: user?.email || "", password: "", admin_role_id: user?.admin_role_id || user?.role || roles[0]?.id || "", status: user?.status || "active" }), [user, roles]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" data-testid="admin-user-dialog"><form onSubmit={(event) => { event.preventDefault(); onSave(form); }} className="w-full max-w-xl space-y-5 rounded-lg border border-white/10 bg-[#101010] p-6 shadow-2xl"><header className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-widest text-zinc-500">Kontrol Akses</div><h2 className="mt-1 font-display text-2xl font-extrabold">{editing ? "Edit Pengguna Admin" : "Tambah Pengguna Admin"}</h2></div><button type="button" onClick={onClose} className="rounded-md p-2 text-zinc-500 hover:bg-white/5 hover:text-white" data-testid="admin-user-dialog-close"><X className="h-5 w-5" /></button></header><div className="grid gap-4 md:grid-cols-2"><label><span className="rm-label">Nama</span><input className="rm-input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required data-testid={ADMIN_USER.nameInput} /></label><label><span className="rm-label">Email</span><input type="email" className="rm-input disabled:opacity-50" value={form.email} disabled={editing} onChange={(event) => setForm({ ...form, email: event.target.value })} required data-testid={ADMIN_USER.emailInput} /></label><label><span className="rm-label">Role</span><select className="rm-input" value={form.admin_role_id} onChange={(event) => setForm({ ...form, admin_role_id: event.target.value })} required data-testid={ADMIN_USER.roleSelect}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label>{editing ? <label><span className="rm-label">Status</span><select className="rm-input" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} data-testid="admin-user-status-select"><option value="active">Aktif</option><option value="suspended">Ditangguhkan</option></select></label> : <label><span className="rm-label">Password Sementara</span><input type="text" minLength={8} className="rm-input" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required data-testid={ADMIN_USER.passwordInput} /></label>}{editing && <label className="md:col-span-2"><span className="rm-label">Password Baru <span className="normal-case text-zinc-600">(opsional)</span></span><input type="text" minLength={8} className="rm-input" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} data-testid={ADMIN_USER.passwordInput} /></label>}</div><div className="flex justify-end gap-3 border-t border-white/10 pt-5"><button type="button" className="rm-btn-ghost" onClick={onClose} data-testid="admin-user-dialog-cancel">Batal</button><button type="submit" className="rm-btn-primary" disabled={saving} data-testid={ADMIN_USER.saveButton}>{saving ? "Menyimpan…" : "Simpan Pengguna"}</button></div></form></div>;
};