import React, { useCallback, useEffect, useRef, useState } from "react";
import { Eye, Monitor, Smartphone } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { useAppPreferences } from "@/contexts/AppPreferencesContext";

export const RoleNavPreview = ({ navigation = [], permissions = [], roleKey, roleName, active = true }) => {
  const { locale, theme, t } = useAppPreferences();
  const [open, setOpen] = useState(false); const [mobile, setMobile] = useState(false); const frame = useRef(null);
  const payload = useRef(null);
  payload.current = { type: "rilis-role-preview-config", navigation, permissions, roleKey, roleName, active, locale, theme };
  const send = useCallback(() => frame.current?.contentWindow?.postMessage(payload.current, window.location.origin), []);
  useEffect(() => { if (open) send(); }, [open, navigation, permissions, roleKey, roleName, active, locale, theme, send]);
  useEffect(() => { const receive = (event) => { if (event.origin === window.location.origin && event.source === frame.current?.contentWindow && event.data?.type === "rilis-role-preview-ready") send(); }; window.addEventListener("message", receive); return () => window.removeEventListener("message", receive); }, [send]);
  return <section className="space-y-3 border-y border-white/10 py-5" data-testid="admin-role-nav-preview"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 text-sm font-bold"><Eye className="h-4 w-4" />{t("Pratinjau Tampilan")}</h3><p className="mt-1 text-xs text-zinc-500">{t("Simulasi")} · {t("Baca-saja")}</p></div><button type="button" className="rm-btn-ghost inline-flex items-center gap-2" onClick={() => setOpen(true)} data-testid="admin-role-website-preview-open"><Monitor className="h-4 w-4" />{t("Pratinjau Role")}</button></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="ui-menu flex h-[92dvh] w-[calc(100%-1rem)] max-w-[1600px] flex-col gap-3 overflow-hidden rounded-lg p-3 sm:p-4" data-testid="admin-role-website-preview-dialog" closeTestId="admin-role-website-preview-close"><DialogHeader className="pr-9 text-left"><DialogTitle>{t("Pratinjau Role")}</DialogTitle><DialogDescription className="text-[var(--ui-muted)]">{t("Data contoh — bukan data bisnis asli")}</DialogDescription></DialogHeader><div className="flex items-center justify-between gap-3"><strong className="min-w-0 truncate text-sm" translate="no" data-testid="role-preview-role-name">{roleName || roleKey}</strong><div className="flex items-center gap-1"><button type="button" title="Desktop" onClick={() => setMobile(false)} className={`ui-icon-button ${!mobile ? "border-pink-500 text-pink-500" : ""}`} aria-pressed={!mobile} data-testid="role-preview-desktop"><Monitor className="h-4 w-4" /></button><button type="button" title="Mobile" onClick={() => setMobile(true)} className={`ui-icon-button ${mobile ? "border-pink-500 text-pink-500" : ""}`} aria-pressed={mobile} data-testid="role-preview-mobile"><Smartphone className="h-4 w-4" /></button></div></div><div className="min-h-0 flex-1 overflow-hidden rounded-md border border-[var(--ui-border)] bg-[var(--ui-bg)]"><iframe ref={frame} onLoad={send} src="/admin/role-preview" title="Role website preview" className="mx-auto h-full max-w-full border-0" style={{ width: mobile ? 390 : "100%" }} sandbox="allow-scripts allow-same-origin" data-testid="admin-role-preview-iframe" /></div></DialogContent></Dialog>
  </section>;
};