import React from "react";
import { GripVertical } from "lucide-react";
import { useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";

export const SortableNavRow = ({ item, allItems, onChange, readOnly = false }) => {
  const sortable = useSortable({ id: item.key, disabled: readOnly });
  const style = { transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition };
  return <div ref={sortable.setNodeRef} style={style} className="grid gap-3 border-b border-white/10 bg-[#090909] px-3 py-4 md:grid-cols-[32px_1fr_1fr_170px_90px] md:items-center" data-testid={`admin-ui-nav-row-${item.key}`}><button type="button" disabled={readOnly} className="cursor-grab touch-none rounded p-1 text-zinc-600 hover:text-white active:cursor-grabbing disabled:cursor-default" {...sortable.attributes} {...sortable.listeners} data-testid={`admin-ui-nav-drag-${item.key}`}><GripVertical className="h-5 w-5" /></button><label><span className="rm-label md:hidden">Label Indonesia</span><input className="rm-input" value={item.labels.id} disabled={readOnly} onChange={(event) => onChange({ ...item, labels: { ...item.labels, id: event.target.value } })} data-testid={`admin-ui-nav-label-id-${item.key}`} /></label><label><span className="rm-label md:hidden">English Label</span><input className="rm-input" value={item.labels.en} disabled={readOnly} onChange={(event) => onChange({ ...item, labels: { ...item.labels, en: event.target.value } })} data-testid={`admin-ui-nav-label-en-${item.key}`} /></label><label><span className="rm-label md:hidden">Parent Tab</span><select className="rm-input" value={item.parent_key || ""} disabled={readOnly} onChange={(event) => onChange({ ...item, parent_key: event.target.value || null })} data-testid={`admin-ui-nav-parent-${item.key}`}><option value="">Tab Utama</option>{allItems.filter((candidate) => candidate.key !== item.key && !candidate.parent_key).map((candidate) => <option key={candidate.key} value={candidate.key}>{candidate.labels.id}</option>)}</select></label><label className="flex items-center gap-2 text-xs text-zinc-400"><input type="checkbox" checked={item.visible} disabled={readOnly} onChange={(event) => onChange({ ...item, visible: event.target.checked })} data-testid={`admin-ui-nav-visible-${item.key}`} /> Tampil</label><div className="md:col-start-2 md:col-span-4 truncate text-[11px] text-zinc-700" data-testid={`admin-ui-nav-route-${item.key}`}>{item.route}</div></div>;
};