import React from "react";
import { LabelPackageCard } from "./LabelPackageCard";

const fmtIDR = (value) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value || 0);

export const DetailRow = ({ label, value }) => <div className="flex justify-between text-sm py-1.5 border-b border-white/5 last:border-0"><span className="text-zinc-500">{label}</span><span className="font-semibold capitalize">{value ?? "—"}</span></div>;

function AccountActions({ label, openEmail, openRevoke }) {
  if (!label.user_id) return label.previous_account_email ? <div className="pt-3 border-t border-white/5 text-xs"><div className="text-amber-300">Akun login dicabut sebelumnya.</div><div className="text-zinc-500 mt-0.5">Mantan email: <span className="font-mono">{label.previous_account_email}</span></div><div className="text-zinc-500">Gunakan tombol &quot;Buat Akun&quot; di halaman Label Management untuk akun baru.</div></div> : null;
  return <div className="pt-3 border-t border-white/5 space-y-2"><div className="text-[11px] uppercase tracking-widest font-bold text-zinc-500">Akun Login</div><div className="text-xs text-zinc-400">Email aktif: <span className="font-mono text-zinc-200">{label.email || "—"}</span></div><div className="flex gap-2 flex-wrap"><button className="rm-btn-ghost text-xs" onClick={openEmail} data-testid="admin-label-change-email">Ganti Email</button><button className="rm-btn-ghost text-xs text-amber-300 hover:text-amber-200" onClick={openRevoke} data-testid="admin-label-revoke-account">Cabut Akses</button></div><div className="text-[10px] text-zinc-500 leading-relaxed">Cabut akses akan menonaktifkan login tanpa menghapus data label/royalti. Akun baru bisa dibuat ulang dengan email lain.</div></div>;
}

export function LabelDetailCards({ data, permissions, actions, onChanged, onPackageChanged }) {
  const label = data.label;
  const packageName = label.payment_type === "annual_subscription" ? (label.subscription_tier === "annual_vip" ? "Annual VIP" : "Annual Normal") : "Pay Per Release";
  return <div className="grid md:grid-cols-2 gap-4">
    {data.financial_summary && <FinancialOverview summary={data.financial_summary} />}
    <div className="rm-card p-5 space-y-2"><h3 className="font-display font-bold tracking-tight text-lg">Info Label</h3><DetailRow label="Penanggung Jawab" value={label.pic_name} /><DetailRow label="Email" value={label.email} /><DetailRow label="WhatsApp" value={label.whatsapp} /><DetailRow label="Tipe" value={label.label_type} /><DetailRow label="Paket" value={packageName} /><DetailRow label="Subscription" value={label.subscription_status} /><DetailRow label="Masa Berlaku" value={label.subscription_expires_at ? new Date(label.subscription_expires_at).toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" }) : "—"} /><DetailRow label="Kontrak" value={label.contract_status} /><DetailRow label="Status Akun" value={label.account_status} /><DetailRow label="Royalti %" value={`${label.royalty_percentage_default}%`} /><DetailRow label="Created" value={label.created_at?.slice(0, 10)} /></div>
    {(permissions.canBlacklist || permissions.canAccounts || permissions.canBlacklistDirect || permissions.canBlacklistRequest) && <div className="rm-card p-5 space-y-3"><h3 className="font-display font-bold tracking-tight text-lg">Aksi</h3>{permissions.canBlacklist && <div className="flex gap-2 flex-wrap"><button className="rm-btn-ghost text-sm" onClick={() => actions.setStatus("active")} data-testid="admin-label-activate" disabled={permissions.isBlacklisted}>Aktifkan</button><button className="rm-btn-ghost text-sm" onClick={() => actions.setStatus("suspended")} data-testid="admin-label-suspend" disabled={permissions.isBlacklisted}>Suspend</button></div>}{(permissions.canBlacklistDirect || permissions.canBlacklistRequest) && <div className="flex gap-2 flex-wrap">{!permissions.isBlacklisted && <button className="rm-btn-ghost text-sm text-red-300" onClick={actions.openBlacklist} data-testid="admin-label-blacklist">{permissions.canBlacklistDirect ? "Blacklist…" : "Ajukan Blacklist…"}</button>}{permissions.isBlacklisted && <button className="rm-btn-ghost text-sm text-emerald-300" onClick={actions.unblacklist} data-testid="admin-label-unblacklist">{permissions.canBlacklistDirect ? "Lepas Blacklist" : "Ajukan Lepas Blacklist"}</button>}</div>}{permissions.canAccounts && <AccountActions label={label} openEmail={actions.openEmail} openRevoke={actions.openRevoke} />}</div>}
    {(permissions.canPackage || permissions.canPackageRequest) && <LabelPackageCard label={label} mode={permissions.canPackage ? "direct" : "request"} onChanged={onPackageChanged || onChanged} />}
    <div className="rm-card p-5 space-y-2"><h3 className="font-display font-bold tracking-tight text-lg">Rekening</h3>{data.bank_account ? <><DetailRow label="Bank" value={data.bank_account.bank_name} /><DetailRow label="Nomor" value={data.bank_account.account_number} /><DetailRow label="Atas Nama" value={data.bank_account.account_holder_name} /><DetailRow label="Verifikasi" value={data.bank_account.verified_status} />{permissions.canFinance && data.bank_account.verified_status !== "verified" && <button className="rm-btn-primary text-sm mt-2" onClick={actions.verifyBank} data-testid="admin-label-verify-bank">Verifikasi Rekening</button>}</> : <div className="text-sm text-zinc-500">Label belum input rekening.</div>}</div>
    <div className="rm-card p-5 space-y-2"><h3 className="font-display font-bold tracking-tight text-lg">Statistik</h3><DetailRow label="Artist" value={data.artists_count} /><DetailRow label="Rilisan" value={data.releases_count} /><DetailRow label="Report Pertama" value={data.financial_summary?.first_period} /><DetailRow label="Report Terbaru" value={data.financial_summary?.latest_period} /><DetailRow label="Withdraw Terakhir" value={data.financial_summary?.last_withdrawn_period} /></div>
  </div>;
}

function FinancialOverview({ summary }) {
  const metrics = [
    ["total-royalty", "Total Royalti", summary.total_royalty_idr, "text-zinc-50"],
    ["withdrawn", "Sudah Ditarik", summary.withdrawn_paid_idr, "text-zinc-200"],
    ["processing", "Sedang Diproses", summary.withdraw_processing_idr, "text-amber-300"],
    ["available", "Bisa Ditarik", summary.available_idr, "text-emerald-300"],
    ["pending", "Pending", summary.pending_idr, "text-amber-300"],
    ["unwithdrawn", "Total Belum Ditarik", summary.total_unwithdrawn_idr, "text-blue-300"],
  ];
  return <section className="md:col-span-2 border border-white/10 rounded-lg overflow-hidden" data-testid="admin-label-financial-summary"><div className="px-5 py-4 border-b border-white/10 flex flex-wrap justify-between gap-3"><div><h3 className="font-display font-bold tracking-normal text-lg">Ringkasan Royalti</h3><p className="text-xs text-zinc-500 mt-1">Source-of-truth royalty_lines FIFO</p></div><div className="text-xs text-zinc-500">{summary.first_period || "—"} — {summary.latest_period || "—"}</div></div><div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{metrics.map(([id, label, value, tone]) => <div className="px-4 py-4 border-r border-b xl:border-b-0 border-white/10 last:border-r-0" key={id} data-testid={`admin-label-finance-${id}`}><div className="text-[10px] uppercase tracking-widest text-zinc-500 font-bold">{label}</div><div className={`font-mono tabular-nums font-bold text-base mt-2 break-words ${tone}`}>{fmtIDR(value)}</div></div>)}</div></section>;
}

const ModalShell = ({ close, children }) => <div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={close}>{children}</div>;

export function LabelDetailModals({ data, modals }) {
  const label = data.label;
  return <>
    {modals.revoke.open && <ModalShell close={modals.revoke.close}><form onClick={(e) => e.stopPropagation()} onSubmit={modals.revoke.submit} className="w-full max-w-md rm-glass-strong rounded-[24px] p-6 space-y-4 border border-amber-500/30" data-testid="admin-label-revoke-modal"><h3 className="font-display font-extrabold text-xl text-amber-200">Cabut Akses Akun</h3><p className="text-sm text-zinc-300">Email login <b>{label.email}</b> akan dinonaktifkan. Data label, rilisan, dan royalti tidak dihapus.</p><div><label className="rm-label">Alasan (opsional)</label><input className="rm-input" value={modals.revoke.reason} onChange={(e) => modals.revoke.setReason(e.target.value)} data-testid="admin-label-revoke-reason" /></div><label className="flex items-center gap-2 text-sm text-zinc-300"><input type="checkbox" checked={modals.revoke.cascade} onChange={(e) => modals.revoke.setCascade(e.target.checked)} data-testid="admin-label-revoke-cascade" /><span>Ikut nonaktifkan {data.artists_count || 0} artist sub-account</span></label><div className="flex justify-end gap-2"><button type="button" className="rm-btn-ghost" onClick={modals.revoke.close}>Batal</button><button className="rm-btn-primary" data-testid="admin-label-revoke-submit">Cabut Akses</button></div></form></ModalShell>}
    {modals.email.open && <ModalShell close={modals.email.close}><form onClick={(e) => e.stopPropagation()} onSubmit={modals.email.submit} className="w-full max-w-md rm-glass-strong rounded-[24px] p-6 space-y-4 border border-sky-500/30" data-testid="admin-label-email-modal"><h3 className="font-display font-extrabold text-xl text-sky-200">Ganti Email Akun</h3><p className="text-sm text-zinc-300">Sesi login lama otomatis terputus setelah email diubah.</p><div><label className="rm-label">Email Lama</label><input className="rm-input opacity-70" disabled value={label.email || ""} /></div><div><label className="rm-label">Email Baru</label><input className="rm-input" type="email" value={modals.email.value} onChange={(e) => modals.email.setValue(e.target.value)} data-testid="admin-label-new-email" required /></div><label className="flex items-center gap-2 text-sm text-zinc-300"><input type="checkbox" checked={modals.email.notify} onChange={(e) => modals.email.setNotify(e.target.checked)} data-testid="admin-label-email-notify" /><span>Kirim notifikasi ke email lama & baru</span></label><div className="flex justify-end gap-2"><button type="button" className="rm-btn-ghost" onClick={modals.email.close}>Batal</button><button className="rm-btn-primary" disabled={!modals.email.value.includes("@")} data-testid="admin-label-email-submit">Ganti Email</button></div></form></ModalShell>}
    {modals.blacklist.open && <ModalShell close={modals.blacklist.close}><form onClick={(e) => e.stopPropagation()} onSubmit={modals.blacklist.submit} className="w-full max-w-md rm-glass-strong rounded-[24px] p-6 space-y-4 border border-red-500/30"><h3 className="font-display font-extrabold text-xl text-red-200">Blacklist Label</h3><p className="text-sm text-zinc-300">Label <b>{label.label_name}</b> tidak dapat login sampai blacklist dilepas.</p><div><label className="rm-label">Alasan Blacklist</label><textarea className="rm-input min-h-[100px]" value={modals.blacklist.reason} onChange={(e) => modals.blacklist.setReason(e.target.value)} data-testid="admin-label-blacklist-reason" required minLength={3} /></div><div className="flex justify-end gap-2"><button type="button" className="rm-btn-ghost" onClick={modals.blacklist.close}>Batal</button><button className="rm-btn-primary" disabled={modals.blacklist.reason.length < 3} data-testid="admin-label-blacklist-submit">Blacklist</button></div></form></ModalShell>}
  </>;
}