import React from "react";
import { Plus, Trash2, CheckCircle2 } from "lucide-react";
import { fileUrl } from "@/api/client";
import { SUPPORT } from "@/constants/testIds";
import { CONTENT_ID_CATEGORIES, METADATA_FIELDS } from "./ticketFormConfig";

export const TicketField = ({ label, htmlFor, children }) => <div className="min-w-0"><label htmlFor={htmlFor} className="rm-label">{label}</label>{children}</div>;

export const TicketCategoryFields = ({ form, setForm, releaseTracks, releaseLoading, handleAudioUpload, handleCoverUpload }) => {
  if (form.category === "edit_metadata") return <section className="space-y-3 border-y border-white/10 py-4" data-testid="support-metadata-fields"><h4 className="text-sm font-semibold">Metadata Baru</h4><div className="grid gap-3 md:grid-cols-2">{METADATA_FIELDS.map(([label, key]) => <TicketField key={key} label={label} htmlFor={`support-metadata-${key}`}><input id={`support-metadata-${key}`} data-testid={`support-metadata-${key}`} className="rm-input w-full min-w-0" disabled={!form.release_id || releaseLoading} value={form.new_metadata[key]} maxLength={1000} onChange={(e) => setForm((current) => ({ ...current, new_metadata: { ...current.new_metadata, [key]: e.target.value } }))} /></TicketField>)}</div></section>;
  if (CONTENT_ID_CATEGORIES.includes(form.category)) return <section className="space-y-4" data-testid="support-content-id-fields">
    <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-semibold">Link Video YouTube</h4><button type="button" className="inline-flex items-center gap-1 text-xs text-sky-300 transition-colors hover:text-sky-200 disabled:opacity-40" disabled={form.youtube_urls.length >= 20} data-testid="support-youtube-add" onClick={() => setForm((current) => ({ ...current, youtube_urls: [...current.youtube_urls, ""] }))}><Plus className="h-4 w-4" /> Tambah Link</button></div>{form.youtube_urls.map((url, index) => <div className="flex min-w-0 items-center gap-2" key={index}><input type="url" className="rm-input w-full min-w-0 flex-1" aria-label={`Link video YouTube ${index + 1}`} value={url} onChange={(e) => setForm((current) => ({ ...current, youtube_urls: current.youtube_urls.map((item, i) => i === index ? e.target.value : item) }))} placeholder="https://www.youtube.com/watch?v=…" data-testid={index === 0 ? SUPPORT.youtubeUrlInput : `support-youtube-url-${index + 1}`} maxLength={500} required />{form.youtube_urls.length > 1 && <button type="button" className="shrink-0 p-2 text-red-300 transition-colors hover:text-red-200" title={`Hapus link ${index + 1}`} aria-label={`Hapus link ${index + 1}`} data-testid={`support-youtube-remove-${index + 1}`} onClick={() => setForm((current) => ({ ...current, youtube_urls: current.youtube_urls.filter((_, i) => i !== index) }))}><Trash2 className="h-4 w-4" /></button>}</div>)}</div>
    <label className="flex items-start gap-3 border-y border-white/10 py-4"><input type="checkbox" checked={form.originality_declared} onChange={(e) => setForm((current) => ({ ...current, originality_declared: e.target.checked }))} data-testid={SUPPORT.originalityCheckbox} className="mt-1 shrink-0" required /><span className="text-sm text-zinc-300">Saya menyatakan bahwa lagu ini original 100% milik saya / label saya, dan tidak mengandung sample / copyright pihak lain yang dapat memicu konflik klaim Content ID. Saya bertanggung jawab penuh atas pernyataan ini.</span></label>
  </section>;
  if (form.category === "edit_audio") return <section className="space-y-3 border-y border-white/10 py-4"><h4 className="text-sm font-semibold">File Audio Baru (WAV)</h4><TicketField label="Track yang Diganti" htmlFor="support-audio-track"><select id="support-audio-track" className="rm-input w-full" value={form.new_audio_track_id} onChange={(e) => setForm((current) => ({ ...current, new_audio_track_id: e.target.value }))} data-testid={SUPPORT.trackSelect} required disabled={releaseLoading}><option value="">— Pilih track —</option>{releaseTracks.map((track) => <option key={track.id} value={track.id}>{track.track_number}. {track.track_title}</option>)}</select></TicketField><TicketField label="Upload WAV Baru" htmlFor="support-audio-upload"><input id="support-audio-upload" type="file" accept=".wav" className="rm-input w-full min-w-0" onChange={handleAudioUpload} data-testid={SUPPORT.audioUpload} required={!form.new_audio_url} />{form.new_audio_url && <div className="mt-2 flex items-center gap-2 break-all text-xs text-emerald-300" data-testid="support-audio-uploaded"><CheckCircle2 className="h-3 w-3" /> {form.new_audio_filename || "WAV terupload"}</div>}</TicketField></section>;
  if (form.category === "edit_cover") return <section className="space-y-3 border-y border-white/10 py-4"><h4 className="text-sm font-semibold">Cover Baru (3000×3000)</h4><input type="file" aria-label="Upload cover baru" accept=".jpg,.jpeg,.png" className="rm-input w-full min-w-0" onChange={handleCoverUpload} data-testid={SUPPORT.coverUpload} required={!form.new_cover_url} />{form.new_cover_url && <img src={fileUrl(form.new_cover_url)} alt="Cover baru" className="aspect-square w-20 object-contain" data-testid="support-cover-uploaded" />}</section>;
  return null;
};