import React from "react";
import { ExternalLink, FileAudio, Mic2 } from "lucide-react";
import { fileUrl } from "@/api/client";
import { SocialLinksList } from "@/components/artists/SocialLinksList";

const Row = ({ label, value, mono = false, testId }) => <div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)] gap-4 border-b border-white/5 py-2.5 last:border-0"><dt className="text-xs text-zinc-500">{label}</dt><dd className={`break-words text-right text-sm text-zinc-200 ${mono ? "font-mono" : "font-semibold"}`} data-testid={testId}>{value || "—"}</dd></div>;
const LinkValue = ({ href, children, testId }) => href ? <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sky-300 hover:text-sky-200" data-testid={testId}>{children}<ExternalLink className="h-3 w-3" /></a> : children;

const ArtistCredits = ({ title, artists, prefix }) => <section><h3 className="mb-3 text-xs font-bold uppercase text-zinc-500">{title}</h3><div className="space-y-3">{artists?.length ? artists.map((artist, index) => { const links = artist.social_links?.length ? artist.social_links : artist.spotify_url ? [{ platform: "spotify", url: artist.spotify_url }] : []; return <div className="border-l-2 border-white/10 pl-4 text-sm" key={`${artist.name}-${index}`} data-testid={`${prefix}-${index}`}><strong>{artist.name}</strong><div className="mt-2"><SocialLinksList links={links} prefix={`${prefix}-social-${index}`} /></div></div>; }) : <span className="text-sm text-zinc-500">Tidak ada</span>}</div></section>;

export const ReleaseMetadataView = ({ release }) => <div className="space-y-8" data-testid="release-metadata-view">
  <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><section><h2 className="mb-3 font-display text-lg font-bold">Informasi Rilisan</h2><dl className="border-y border-white/10"><Row label="Judul" value={release.release_title} testId="release-metadata-title" /><Row label="Nama Label" value={release.label_name_snapshot} testId="release-metadata-label" /><Row label="Tipe" value={String(release.release_type || "").toUpperCase()} testId="release-metadata-type" /><Row label="Genre / Sub Genre" value={[release.genre, release.subgenre].filter(Boolean).join(" / ")} testId="release-metadata-genre" /><Row label="Tanggal Rilis Digital" value={release.release_date} testId="release-metadata-release-date" /><Row label="Tahun Produksi" value={release.year} testId="release-metadata-year" /><Row label="C Line" value={release.copyright_line} mono testId="release-metadata-c-line" /><Row label="P Line" value={release.p_line} mono testId="release-metadata-p-line" /><Row label="UPC" value={release.upc} mono testId="release-metadata-upc" /><Row label="Penanggung Jawab" value={release.responsible_name} testId="release-metadata-responsible" /><Row label="Web Artis / YouTube" value={<LinkValue href={release.artist_web_url} testId="release-metadata-artist-web">{release.artist_web_url}</LinkValue>} testId="release-metadata-artist-web-value" /></dl></section><div className="space-y-7"><ArtistCredits title="Artis Utama" artists={release.primary_artists?.length ? release.primary_artists : [{ name: release.artist_name }]} prefix="release-primary-artist" /><ArtistCredits title="Artis Featuring" artists={release.featured_artists} prefix="release-featured-artist" />{release.cover_url && <section><h3 className="mb-3 text-xs font-bold uppercase text-zinc-500">Sampul 3000×3000</h3><img src={fileUrl(release.cover_url)} alt={`Sampul ${release.release_title}`} className="aspect-square w-full max-w-sm border border-white/10 object-contain" data-testid="release-metadata-cover" /></section>}</div></div>
  <section><div className="mb-4 flex items-center gap-2"><Mic2 className="h-5 w-5 text-zinc-500" /><h2 className="font-display text-lg font-bold">Track dan Kredit</h2></div><div className="divide-y divide-white/10 border-y border-white/10">{release.tracks?.map((track, index) => <article className="py-7" key={track.id} data-testid={`release-track-detail-${track.id}`}><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase text-zinc-500">Track {track.track_number || index + 1}</div><h3 className="font-display text-xl font-bold" data-testid={`release-track-title-${track.id}`}>{track.track_title}</h3><div className="mt-1 text-xs text-zinc-500">{release.artist_name}{release.featured_artists?.length ? ` feat. ${release.featured_artists.map((artist) => artist.name).join(", ")}` : ""}</div></div>{track.audio_url ? <audio controls src={fileUrl(track.audio_url)} className="h-10 max-w-full" data-testid={`release-track-audio-${track.id}`} /> : <span className="inline-flex items-center gap-2 text-xs text-zinc-500"><FileAudio className="h-4 w-4" /> Audio belum tersedia</span>}</div><div className="grid gap-x-8 lg:grid-cols-2"><dl><Row label="ISRC" value={track.isrc} mono testId={`release-track-isrc-${track.id}`} /><Row label="Vokal / Instrumental" value={track.vocal_type === "instrumental" ? "Instrumental" : "Ada Vokal"} testId={`release-track-vocal-type-${track.id}`} /><Row label="Writer" value={track.lyricist} testId={`release-track-writer-${track.id}`} /><Row label="Komposer" value={track.composer} testId={`release-track-composer-${track.id}`} /><Row label="Arranger" value={track.arranger} testId={`release-track-arranger-${track.id}`} /><Row label="Produser" value={track.producer} testId={`release-track-producer-${track.id}`} /></dl><dl><Row label="Explicit" value={track.explicit ? "YA" : "TIDAK"} testId={`release-track-explicit-${track.id}`} /><Row label="Preview" value={`${track.preview_start_seconds || 0} detik`} testId={`release-track-preview-${track.id}`} /><Row label="Bahasa Judul" value={track.title_language} testId={`release-track-title-language-${track.id}`} /><Row label="Bahasa Lirik" value={track.lyric_language} testId={`release-track-lyric-language-${track.id}`} /><Row label="Audio" value={track.audio_sample_rate ? `WAV ${(track.audio_sample_rate / 1000).toLocaleString("id-ID")} kHz` : "—"} testId={`release-track-audio-format-${track.id}`} /></dl></div><div className="mt-5"><div className="mb-2 text-xs font-bold uppercase text-zinc-500">Lirik</div><pre className="max-h-80 overflow-auto whitespace-pre-wrap border-l-2 border-white/10 pl-4 font-sans text-sm leading-7 text-zinc-300" data-testid={`release-track-lyrics-${track.id}`}>{track.lyrics || "—"}</pre></div></article>)}</div></section>
</div>;