import React from "react";
import { Link } from "react-router-dom";
import { ChevronDown, Sparkles, Music2, Wallet, TrendingUp, ShieldCheck, Headphones, Globe2, Users } from "lucide-react";
import { LANDING } from "@/constants/testIds";
import { LogoMark, LogoFull, BrandInline } from "@/components/shared/Brand";

const ICONS = [Music2, TrendingUp, Wallet, Headphones, ShieldCheck, Users, Sparkles, Globe2];
const CHART_BARS = [{ id: "jan", h: 40 }, { id: "feb", h: 55 }, { id: "mar", h: 38 }, { id: "apr", h: 70 }, { id: "may", h: 62 }, { id: "jun", h: 80 }, { id: "jul", h: 95 }];

export function LandingHeader() {
  return <header className="fixed top-4 left-1/2 -translate-x-1/2 w-[94%] max-w-6xl z-50 rm-glass rounded-full px-4 py-2 flex items-center justify-between">
    <Link to="/" className="flex items-center gap-2"><LogoMark size={36} /><span className="font-display font-extrabold tracking-tight text-white hidden sm:inline">RILIS MUSIK</span></Link>
    <nav className="hidden md:flex items-center gap-7 text-sm font-semibold text-zinc-300"><a href="#benefits" className="hover:text-white transition">Fitur</a><a href="#royalty" className="hover:text-white transition">Royalti</a><a href="#pricing" className="hover:text-white transition">Harga</a><a href="#faq" className="hover:text-white transition">FAQ</a></nav>
    <div className="flex items-center gap-2"><Link to="/login" data-testid={LANDING.navLogin} className="hidden sm:inline-block text-sm font-semibold text-zinc-200 px-3 py-2 rounded-full hover:bg-white/5 transition">Login</Link><Link to="/register" data-testid={LANDING.navRegister} className="rm-btn-primary text-sm">Daftar</Link></div>
  </header>;
}

export function HeroSection({ settings }) {
  const hero = settings.hero || {};
  return <section className="pt-36 md:pt-44 pb-24 px-6 md:px-12 lg:px-24 relative overflow-hidden"><div className="max-w-6xl mx-auto grid md:grid-cols-12 gap-12 items-center">
    <div className="md:col-span-7 rm-fade-up"><div className="inline-flex items-center gap-2 rm-glass rounded-full px-3 py-1.5 text-xs font-semibold text-zinc-300 mb-6"><Sparkles className="w-3.5 h-3.5 text-[#FF1F8E]" /> Distribusi via Believe ke 150+ DSP</div><h1 className="font-display text-5xl md:text-6xl lg:text-7xl font-extrabold leading-[1.02] tracking-tighter">Distribusi Musik <span className="rm-gradient-text">Lebih Rapi</span>, Royalti <span className="rm-gradient-text">Lebih Transparan.</span></h1><p className="mt-6 text-lg text-zinc-400 leading-relaxed max-w-xl">{hero.subheadline}</p>
      <div className="mt-8 flex flex-wrap gap-3"><Link to={hero.cta_primary_url || "/register"} data-testid={LANDING.heroCtaPrimary} className="rm-btn-primary inline-flex items-center gap-2">{hero.cta_primary_text || "Daftar Sekarang"}</Link><Link to={hero.cta_secondary_url || "/login"} data-testid={LANDING.heroCtaSecondary} className="rm-btn-ghost inline-flex items-center gap-2">{hero.cta_secondary_text || "Login Dashboard"}</Link></div>
      <div className="mt-10 flex items-center gap-5 text-xs text-zinc-500"><div><span className="font-bold text-white">150+</span> platform digital</div><div className="w-px h-4 bg-zinc-700" /><div><span className="font-bold text-white">Fleksibel</span> pembagian royalti</div><div className="w-px h-4 bg-zinc-700" /><div><span className="font-bold text-white">7 hari</span> minimal release date</div></div>
    </div>
    <div className="md:col-span-5 relative h-[460px]"><div className="absolute -top-6 -right-6 w-56 h-56 opacity-90 rm-pulse-glow rm-float"><LogoMark size={224} /></div><div className="absolute top-44 right-0 w-72 rm-glass-strong rounded-3xl p-5 rm-float"><div className="text-xs text-zinc-400 font-semibold uppercase tracking-widest">Saldo Tersedia</div><div className="font-display text-3xl font-extrabold tracking-tight mt-1">Rp 4.275.000</div><div className="text-xs font-bold mt-1 rm-gradient-text">+12% vs bulan lalu</div><div className="mt-4 h-16 flex items-end gap-1.5">{CHART_BARS.map((bar) => <div key={bar.id} className="flex-1 rounded-md" style={{ background: "linear-gradient(180deg, #FF1F8E 0%, #A24EFF 100%)", height: `${bar.h}%` }} />)}</div></div>
      <div className="absolute bottom-10 left-0 w-64 rm-glass-strong rounded-3xl p-4 rm-float" style={{ animationDelay: "1.2s" }}><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl" style={{ background: "linear-gradient(135deg, #FF1F8E, #A24EFF)" }} /><div><div className="text-xs text-zinc-400 font-semibold">Now Streaming</div><div className="font-semibold text-sm">Senja di Jakarta</div><div className="text-xs text-zinc-500">Adit Soemardi</div></div></div><div className="mt-3 h-1.5 bg-zinc-800 rounded-full overflow-hidden"><div className="h-full w-2/3" style={{ background: "linear-gradient(90deg, #FF1F8E, #A24EFF)" }} /></div><div className="flex justify-between text-[10px] text-zinc-500 mt-1.5"><span>1:42</span><span>3:08</span></div></div>
      <div className="absolute top-72 left-8 w-44 rm-glass rounded-3xl p-4 rm-float" style={{ animationDelay: "0.6s" }}><div className="text-xs font-semibold text-zinc-400">Status</div><div className="mt-1 inline-flex items-center gap-1.5 text-xs font-bold text-emerald-400"><span className="w-2 h-2 rounded-full bg-emerald-400" />LIVE on Spotify</div><div className="mt-3 text-[11px] text-zinc-500">ISRC: ID-A1Z-25-12345</div></div>
    </div>
  </div></section>;
}

export function BenefitsSection({ benefits = [] }) {
  return <section id="benefits" className="px-6 md:px-12 lg:px-24 py-20"><div className="max-w-6xl mx-auto"><div className="max-w-2xl"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">FITUR PLATFORM</div><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter">Semua yang Anda butuhkan, dalam satu dashboard.</h2><p className="mt-4 text-zinc-400 text-lg">Dari upload rilisan, kelola artist, sampai withdraw. Tanpa WhatsApp.</p></div><div className="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 rm-stagger">{benefits.map((benefit, index) => { const Icon = ICONS[index % ICONS.length]; return <div key={benefit.id || benefit.title} className="rm-glass rounded-3xl p-6 rm-fade-up hover:-translate-y-1 transition-transform duration-300 hover:border-[rgba(255,31,142,0.35)]"><div className="w-12 h-12 rounded-2xl grid place-items-center text-white mb-4" style={{ background: "linear-gradient(135deg, #FF1F8E, #A24EFF)" }}><Icon className="w-5 h-5" /></div><div className="font-display font-bold text-lg tracking-tight">{benefit.title}</div><div className="text-sm text-zinc-400 mt-2 leading-relaxed">{benefit.desc}</div></div>; })}</div></div></section>;
}

export function PlatformsAndFlow({ steps = [] }) {
  return <><section id="platforms" className="px-6 md:px-12 lg:px-24 py-16"><div className="max-w-6xl mx-auto"><div className="text-center max-w-2xl mx-auto mb-10"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">DISTRIBUSI KE 150+ PLATFORM</div><h2 className="font-display text-3xl md:text-4xl font-extrabold tracking-tighter">Lagu Anda tampil di platform terbesar dunia.</h2><p className="mt-3 text-zinc-400">Spotify, Apple Music, YouTube Music, TikTok, dan banyak lagi — semua dalam satu submission.</p></div><div className="rm-glass rounded-[32px] p-6 md:p-10"><img src="/brand/platforms.png" alt="Platform distribusi musik" className="w-full max-w-5xl mx-auto opacity-90 hover:opacity-100 transition-opacity" style={{ filter: "drop-shadow(0 0 24px rgba(255,31,142,0.08))" }} data-testid="landing-platforms-image" /></div></div></section>
    <section className="px-6 md:px-12 lg:px-24 py-20"><div className="max-w-6xl mx-auto"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">ALUR</div><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter mb-12">Dari demo ke 150+ platform.</h2><div className="grid md:grid-cols-2 gap-x-12 gap-y-10">{steps.map((step, index) => <div key={step} className="flex gap-5 rm-fade-up"><div className="text-7xl font-display font-extrabold tracking-tighter leading-none -mt-2 rm-gradient-text opacity-25">{String(index + 1).padStart(2, "0")}</div><div className="pt-2"><div className="font-display font-bold text-xl tracking-tight">{step}</div></div></div>)}</div></div></section></>;
}

const FeatureList = ({ items }) => <ul className="mt-5 space-y-2 text-sm text-zinc-200 flex-1">{items.map((feature) => <li key={feature} className="flex items-start gap-2"><span className="rm-gradient-text font-bold mt-0.5">✓</span>{feature}</li>)}</ul>;

export function PricingSection({ pricing = {} }) {
  const normalFeatures = pricing.features_annual_normal || ["Submit unlimited release", "Prioritas review", "Tanpa biaya per release"];
  return <section id="pricing" className="px-6 md:px-12 lg:px-24 py-24"><div className="max-w-6xl mx-auto"><div className="text-center max-w-2xl mx-auto"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">HARGA</div><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter">Pilih yang cocok untuk skala Anda.</h2><p className="mt-4 text-zinc-400 text-lg">{pricing.description}</p></div><div className="mt-12 grid md:grid-cols-3 gap-5 max-w-6xl mx-auto">
    <div data-testid={LANDING.pricingPay} className="rm-glass rounded-3xl p-7 flex flex-col"><div className="text-xs font-bold text-zinc-400 uppercase tracking-widest">Pay Per Release</div><div className="mt-3 flex items-baseline gap-1"><span className="font-display text-4xl font-extrabold tracking-tighter">Rp{(pricing.pay_per_release_price ?? 35000).toLocaleString("id-ID")}</span><span className="text-zinc-500 text-xs">/ rilis</span></div><p className="text-sm text-zinc-400 mt-2">Cocok untuk yang baru memulai atau ingin coba.</p><FeatureList items={pricing.features_pay || []} /><p className="text-sm text-zinc-400 italic mt-2">+ WAMI add-on Rp 100.000/lagu (opsional)</p><Link to="/register" className="rm-btn-ghost mt-7 text-center">Daftar Pay Per Release</Link></div>
    <div data-testid="landing-pricing-annual-normal" className="rm-glass rounded-3xl p-7 flex flex-col"><div className="text-xs font-bold text-zinc-400 uppercase tracking-widest">Annual Normal</div><div className="mt-3 flex items-baseline gap-1"><span className="font-display text-4xl font-extrabold tracking-tighter">Rp{(pricing.annual_normal_price ?? 350000).toLocaleString("id-ID")}</span><span className="text-zinc-500 text-xs">/ tahun</span></div><p className="text-sm text-zinc-400 mt-2">Submit unlimited rilisan tanpa biaya per release.</p><FeatureList items={normalFeatures} /><p className="text-sm text-zinc-400 italic mt-2">+ WAMI add-on Rp 100.000/lagu (opsional)</p><Link to="/register" className="rm-btn-ghost mt-7 text-center">Mulai Annual</Link></div>
    <div data-testid={LANDING.pricingSub} className="rm-glass-strong rounded-3xl p-7 relative flex flex-col border border-[rgba(255,31,142,0.45)]"><div className="absolute -top-3 left-7 text-[10px] font-bold uppercase tracking-widest px-3 py-1 rounded-full text-white bg-gradient-to-br from-[#FF1F8E] to-[#A24EFF]">VIP — Recommended</div><div className="text-xs font-bold text-zinc-400 uppercase tracking-widest mt-1">Annual VIP</div><div className="mt-3 flex items-baseline gap-1"><span className="font-display text-4xl font-extrabold tracking-tighter rm-gradient-text">Rp{(pricing.annual_subscription_price ?? 500000).toLocaleString("id-ID")}</span><span className="text-zinc-500 text-xs">/ tahun</span></div><p className="text-sm text-zinc-400 mt-2">Untuk label aktif yang serius — lengkap dengan WAMI gratis & konten promosi.</p><FeatureList items={["Submit unlimited release", "Prioritas review", "GRATIS daftar LMKN — WAMI semua lagu", "GRATIS konten promosi (JPG)", "Status pendaftaran WAMI real-time"]} /><Link to="/register" className="rm-btn-primary mt-7 text-center">Mulai VIP</Link></div>
  </div><p className="text-center text-xs text-zinc-500 mt-8">Semua paket sudah termasuk distribusi ke 150+ platform digital.</p></div></section>;
}

const RoyaltyRow = ({ label, value, bold, muted }) => <div className={`flex justify-between ${muted ? "text-zinc-500" : "text-zinc-300"} ${bold ? "font-bold text-white" : ""}`}><span>{label}</span><span>{value}</span></div>;

export function RoyaltySection({ settings, simulation, setSimulation }) {
  const labelPercent = settings.royalty_sim?.label_percent_default ?? 60;
  const labelEur = simulation.revenue * (labelPercent / 100);
  const labelIdr = labelEur * simulation.rate;
  return <section id="royalty" className="px-6 md:px-12 lg:px-24 py-20"><div className="max-w-6xl mx-auto rm-glass-strong rounded-[32px] p-8 md:p-12"><div className="grid md:grid-cols-2 gap-10 items-center"><div><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">SIMULASI ROYALTI</div><h2 className="font-display text-3xl md:text-4xl font-extrabold tracking-tighter">Hitung estimasi pendapatan Anda.</h2><p className="mt-3 text-zinc-400">Masukkan revenue Believe dan kurs EUR/IDR. Hasil bersifat estimasi.</p><div className="mt-6 space-y-4 max-w-sm"><div><label className="rm-label">Revenue (EUR)</label><input type="number" data-testid={LANDING.simRevenueInput} className="rm-input" value={simulation.revenue} onChange={(e) => setSimulation({ ...simulation, revenue: Number(e.target.value || 0) })} /></div><div><label className="rm-label">Kurs EUR → IDR</label><input type="number" data-testid={LANDING.simRateInput} className="rm-input" value={simulation.rate} onChange={(e) => setSimulation({ ...simulation, rate: Number(e.target.value || 0) })} /></div></div></div>
    <div className="rm-card p-6 md:p-8"><div className="text-xs uppercase tracking-widest text-zinc-400 font-bold">Estimasi Royalti Final</div><div data-testid={LANDING.simResult} className="font-display text-5xl font-extrabold tracking-tighter mt-2 rm-gradient-text">Rp {Math.round(labelIdr).toLocaleString("id-ID")}</div><div className="text-xs text-zinc-500 mt-1">/ periode estimasi berdasarkan bagian royalti label</div><div className="mt-6 space-y-2 text-sm"><RoyaltyRow label="Pendapatan kotor RILIS MUSIK" value={`€${simulation.revenue.toLocaleString()}`} /><RoyaltyRow label={`Bagian label (${labelPercent}%)`} value={`€${labelEur.toFixed(2)}`} muted /><RoyaltyRow label="Kurs EUR → IDR" value={`Rp ${simulation.rate.toLocaleString("id-ID")}`} muted /><div className="border-t border-white/5 pt-3 mt-2"><RoyaltyRow label="Estimasi royalti final" value={`Rp ${Math.round(labelIdr).toLocaleString("id-ID")}`} bold /></div></div><div className="text-[11px] text-zinc-500 mt-4">* Estimasi. Angka final akan ditampilkan di dashboard Anda setiap periode royalti masuk.</div></div>
  </div></div></section>;
}

export function SocialProofAndFaq({ settings, openFaq, setOpenFaq }) {
  return <><section className="px-6 md:px-12 lg:px-24 py-20"><div className="max-w-6xl mx-auto"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3">TESTIMONI</div><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter mb-10">Dipercaya oleh label & artis Indonesia.</h2><div className="grid md:grid-cols-2 gap-5">{(settings.testimonials || []).map((item) => <div key={`${item.name}-${item.quote}`} className="rm-glass rounded-3xl p-7"><div className="text-2xl font-display font-extrabold leading-none mb-3 rm-gradient-text">&ldquo;</div><p className="text-lg text-zinc-100 leading-relaxed font-display">{item.quote}</p><div className="mt-5 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#FF1F8E] to-[#A24EFF]" /><div><div className="font-semibold text-sm">{item.name}</div><div className="text-xs text-zinc-500">{item.role}</div></div></div></div>)}</div></div></section>
    <section id="faq" className="px-6 md:px-12 lg:px-24 py-20"><div className="max-w-3xl mx-auto"><div className="text-xs uppercase tracking-[0.18em] font-bold rm-gradient-text mb-3 text-center">FAQ</div><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter text-center mb-10">Pertanyaan yang sering diajukan.</h2><div className="divide-y divide-white/5">{(settings.faq || []).map((item, index) => <div key={item.id || item.q} data-testid={`${LANDING.faqItem}-${index}`} className="py-5"><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)} className="w-full flex justify-between items-center text-left"><div className="font-display font-bold text-lg tracking-tight pr-4">{item.q}</div><ChevronDown className={`w-5 h-5 text-zinc-400 transition-transform ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <div className="mt-3 text-zinc-400 leading-relaxed">{item.a}</div>}</div>)}</div></div></section></>;
}

export function LandingFooter({ settings }) {
  const legal = settings.legal_entity || {};
  return <><section className="px-6 md:px-12 lg:px-24 pb-24"><div className="max-w-5xl mx-auto rm-glass-strong rounded-[32px] p-10 md:p-14 text-center relative overflow-hidden"><div className="relative"><LogoFull width={140} className="mx-auto mb-6" /><h2 className="font-display text-4xl md:text-5xl font-extrabold tracking-tighter">Siap distribusikan musik Anda?</h2><p className="mt-3 text-zinc-400 text-lg">Daftar dalam 2 menit, mulai upload hari ini.</p><div className="mt-7 flex justify-center gap-3 flex-wrap"><Link to="/register" className="rm-btn-primary">Daftar Sekarang</Link><Link to="/login" className="rm-btn-ghost">Login Dashboard</Link></div></div></div></section>
    <footer className="px-6 md:px-12 lg:px-24 pb-14 pt-6 border-t border-white/5" data-testid="landing-footer"><div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-8"><div><BrandInline size={36} /><p className="text-sm text-zinc-500 mt-3 max-w-xs">{settings.footer?.description}</p></div><div data-testid="footer-legal-entity"><div className="text-xs uppercase tracking-widest font-bold text-zinc-400 mb-3">Badan Hukum</div><div className="text-sm text-zinc-200 font-semibold">{legal.company_name || "PT. Jeeres Group Indonesia"}</div><div className="text-xs text-zinc-500 mt-2 leading-relaxed">{legal.address_line1 || "Jl. Sintang Pontianak"}<br/>{legal.address_line2 || "RT 12 / RW 5, Kec. Sintang"}<br/>{legal.city || "Sintang"} {legal.postal_code || "78614"}, {legal.country || "Indonesia"}</div><div className="text-xs text-zinc-500 mt-2">NIB: <span className="text-zinc-300 font-mono">{legal.nib || "2202260059749"}</span></div></div><div><div className="text-xs uppercase tracking-widest font-bold text-zinc-400 mb-3">Support</div><div className="text-sm text-zinc-200" data-testid="footer-support-email">{settings.footer?.support_email}</div><div className="text-sm text-zinc-500 mt-1" data-testid="footer-whatsapp">WA/HP: {legal.whatsapp || "085864137150"}</div></div><div><div className="text-xs uppercase tracking-widest font-bold text-zinc-400 mb-3">Legal</div><ul className="space-y-2 text-sm text-zinc-200">{(settings.footer?.legal_links || []).map((link) => <li key={link.url || link.text}><a href={link.url} className="hover:rm-gradient-text">{link.text}</a></li>)}</ul></div></div><div className="max-w-6xl mx-auto mt-10 pt-6 border-t border-white/5 text-xs text-zinc-500 flex flex-col md:flex-row md:justify-between gap-2"><div data-testid="footer-copyright">© {new Date().getFullYear()} RILIS MUSIK — dikelola oleh {legal.company_name || "PT. Jeeres Group Indonesia"}. All rights reserved.</div><Link to="/login" className="hover:text-white">Login Dashboard →</Link></div></footer></>;
}