(function(root){'use strict';const cp=x=>JSON.parse(JSON.stringify(x)),H=3600000,ok=(x,m)=>{if(!x)throw Error(m)};
const seed=[{id:'promo',name:'Konten Promosi',unit:'set desain',type:'release',result:'1 gambar JPG untuk satu konsep dan satu rilisan',needs:'Arahan teks dan desain; cover dari katalog dapat digunakan.',price:70000,hours:8,revisions:1,included:['Pro','Business'],active:true},{id:'visualizer',name:'Video Visualizer',unit:'lagu',type:'track',result:'1 video landscape berdurasi penuh untuk satu lagu',needs:'Audio dan cover dari katalog; referensi visual bila diperlukan.',price:150000,hours:16,revisions:1,included:[],active:true},{id:'smartlink',name:'Smart Link',unit:'rilisan',type:'release',result:'1 halaman tautan untuk Single, EP, atau Album',needs:'Tautan platform yang sudah tersedia; tautan berikutnya dapat dilengkapi.',price:25000,hours:4,revisions:1,included:['Business'],active:true}];
function init(s){return s.addons111??={catalogue:cp(seed),orders:[],history:[],serial:0,version:1,benefitRestores:[]}}
function event(s,o,a,k,pub=true,note='',extra={}){o.history.push({at:s.now,actor:a.id,action:k,public:pub,note,...cp(extra)})}
function own(a,o){return a.role==='label'&&o.owner===a.member}
function act(s,a,k,p={},cal={}){const m=init(s);ok(['label','admin','super'].includes(a.role),'Akses tidak tersedia.');
if(k==='catalogue'){ok(a.role==='super','Hanya Super Admin mengatur layanan.');ok(p.version===m.version,'Katalog berubah. Muat ulang.');const v=cp(p.service);ok(v.name?.trim()&&v.result?.trim()&&v.needs?.trim(),'Lengkapi nama, hasil dan kebutuhan.');ok(['release','track'].includes(v.type)&&v.unit?.trim(),'Tentukan satuan layanan.');ok(Number.isSafeInteger(v.price)&&v.price>=0&&v.price<=100000000,'Harga tidak valid.');ok(Number.isInteger(v.hours)&&v.hours>=1&&v.hours<=720&&Number.isInteger(v.revisions)&&v.revisions>=0&&v.revisions<=20,'Estimasi atau jatah revisi tidak valid.');const old=m.catalogue.find(x=>x.id===v.id);v.id=old?.id||'service-'+(++m.serial);v.included=Array.isArray(v.included)?v.included:[];m.history.unshift({at:s.now,actor:a.id,before:cp(old||null),after:v});if(old)Object.assign(old,v);else m.catalogue.push(v);m.version++;return v.id}
if(k==='create'){ok(a.role==='label'&&a.active,'Aktivasi akun diperlukan untuk memesan.');const c=m.catalogue.find(c=>c.id===p.service&&c.active);ok(c&&p.catalogueVersion===m.version,'Layanan berubah. Tinjau kembali.');ok(a.scope.includes(p.member)&&p.release,'Rilisan di luar akunmu.');ok(c.type!=='track'||p.track,'Pilih satu lagu.');ok(p.brief?.trim(),'Tuliskan kebutuhan pesanan.');ok(!m.orders.some(o=>o.owner===a.member&&o.service.id===c.id&&o.release===p.release&&o.track===(p.track||'')&&!['done','closed'].includes(o.status)),'Pesanan layanan ini masih berjalan. Buka pesanan tersebut.');const benefitKey=[a.member,c.id,p.release,p.track||''].join(':'),used=m.orders.some(o=>o.benefitKey===benefitKey&&o.payment==='benefit'&&!o.benefitRestored),restored=m.benefitRestores.find(x=>x.key===benefitKey&&!x.used),included=!!restored||a.planActive&&c.included.includes(a.plan)&&!used;ok(p.quote===JSON.stringify({amount:included?0:c.price,benefit:included}),'Biaya atau benefit berubah. Tinjau kembali.');if(restored)restored.used=true;const o={id:'SVC-'+String(++m.serial).padStart(4,'0'),owner:a.member,member:p.member,release:p.release,track:p.track||'',title:p.title,artist:p.artist||'',cover:p.cover||'',materials:cp(p.materials||{}),brief:p.brief.trim(),attachments:cp(p.attachments||[]),service:cp(c),catalogueVersion:m.version,amount:included?0:c.price,payment:included?'benefit':c.price===0?'paid':'unpaid',benefitKey,benefit:included?a.plan||'Hak pengganti':'',status:included||!c.price?'queued':'unpaid',at:s.now,progress:s.now,version:1,handler:null,history:[],deliveries:[],draft:null,revisions:0,internal:'',message:'',refunded:0};event(s,o,a,'created',true);m.orders.push(o);return o.id}
const o=m.orders.find(o=>o.id===p.id);ok(o,'Pesanan tidak ditemukan.');ok(a.role!=='label'||own(a,o),'Pesanan di luar akunmu.');ok(p.version===o.version,'Pesanan telah berubah. Buka rincian terbaru.');const staff=a.role!=='label',note=()=>ok(p.note?.trim(),'Tuliskan keterangan yang jelas.');
if(k==='acknowledge'){ok(own(a,o)&&o.status==='closed'&&!o.ackAt,'Pemberitahuan tidak tersedia.');o.ackAt=s.now}
else if(k==='pay'){ok(own(a,o)&&o.status==='unpaid'&&p.checked,'Pembayaran belum dapat dikonfirmasi.');o.payment='paid';o.status='queued';o.paidAt=s.now}
else if(k==='complete-materials'){ok(own(a,o)&&o.status==='materials','Kelengkapan belum diminta.');note();o.originalBrief??=o.brief;o.brief=p.note.trim();o.attachments=cp(p.attachments||o.attachments);o.message='';o.status=o.started?'working':'queued';if(o.started&&o.pausedAt){o.due+=s.now-o.pausedAt;o.pausedAt=null}}
else if(k==='accept'){ok(own(a,o)&&o.status==='response','Hasil belum tersedia untuk diterima.');ok(o.deliveries.length,'Hasil belum tersedia.');o.status='done';o.acceptedAt=s.now}
else if(k==='revision'){ok(own(a,o)&&o.status==='response','Revisi belum tersedia.');note();o.status='revision';o.message=p.note.trim();o.revisionPending=true}
else if(k==='escalate'){ok(own(a,o)&&['revision','working','resolution','response'].includes(o.status),'Peninjauan tidak tersedia.');note();o.status='resolution';o.resolutionReason=p.note.trim();o.offer=null}
else if(k==='offer-accept'){ok(own(a,o)&&o.status==='resolution'&&o.offer,'Tawaran tidak tersedia.');const x=o.offer;o.agreements??=[];o.agreements.push({...cp(x),agreedAt:s.now,actor:a.id});if(x.kind==='addition'){const child={...cp(o),id:'SVC-'+String(++m.serial).padStart(4,'0'),parent:o.id,related:[],agreements:[],ackAt:null,benefitRestored:false,service:{...cp(o.service),result:x.note,hours:x.hours,included:[]},brief:x.note,originalBrief:x.note,amount:x.amount,payment:x.amount?'unpaid':'paid',benefit:'',benefitKey:'additional:'+o.id+':'+m.serial,status:x.amount?'unpaid':'queued',at:s.now,progress:s.now,version:1,handler:null,history:[],deliveries:[],draft:null,revisions:0,internal:'',message:'',refunded:0,started:null,due:null,originalDue:null,pausedAt:null,offer:null,resolutionReason:'',refundDue:null,acceptedAt:null,closedAt:null};event(s,child,a,'created',true,'Tambahan disetujui dari '+o.id);m.orders.push(child);o.related??=[];o.related.push(child.id);o.status=o.deliveries.length?'response':o.started?'working':'queued';o.offer=null;o.message='';}else if(x.kind==='refund'){o.payment=o.payment==='benefit'?'benefit_pending':'refund_pending';o.refundDue=x.amount;o.refundAgreement=x.note;o.offer=null}else{if(x.kind==='replacement')o.replacement=x.note;o.status='working';o.due=x.due;o.originalDue??=o.due;o.message='';o.offer=null}}
else if(k==='offer-decline'){ok(own(a,o)&&o.status==='resolution'&&o.offer,'Tawaran tidak tersedia.');note();if(o.offer.kind==='addition'){o.status=o.deliveries.length?'response':o.started?'working':'queued';o.message=''}o.offer=null;o.resolutionReason=p.note.trim()}
else{ok(staff,'Tindakan khusus petugas.');if(k==='claim'){ok(o.status==='queued','Pesanan tidak berada dalam antrean.');ok(!o.handler||o.handler===a.id||a.role==='super','Sudah ditangani petugas lain.');o.handler=a.id}
else {ok(o.handler===a.id||a.role==='super','Pesanan ditangani petugas lain.');
if(k==='assign'){ok(a.role==='super'&&p.handler,'Pilih petugas.');note();o.handler=p.handler}
else if(k==='materials'){ok(['queued','working'].includes(o.status),'Kelengkapan tidak tersedia.');note();o.status='materials';o.message=p.note.trim();if(o.started)o.pausedAt=s.now}
else if(k==='start'){ok(o.status==='queued'&&p.checked,'Pastikan bahan lengkap.');o.handler??=a.id;o.status='working';o.started=s.now;o.due=addHours(s.now,o.service.hours,cal);o.originalDue=o.due}
else if(k==='draft-result'){ok(o.status==='working','Pesanan belum dalam pengerjaan.');ok(p.file?.key||/^https:\/\//i.test(p.url||''),'Unggah berkas atau gunakan tautan HTTPS.');o.draft={file:cp(p.file||null),url:p.url||'',note:p.note||'',at:s.now};event(s,o,a,k,false);o.version++;return o.id}
else if(k==='send-result'){ok(o.status==='working'&&o.draft&&p.checked,'Periksa draft hasil sebelum mengirim.');o.deliveries.push({...cp(o.draft),version:o.deliveries.length+1,sent:s.now});o.draft=null;o.status='response';o.message='';o.internal=''}
else if(k==='review-revision'){ok(o.status==='revision'&&o.revisionPending,'Permintaan revisi sudah ditangani.');note();ok(['error','included','scope'].includes(p.kind),'Pilih jenis revisi.');if(p.kind==='scope'){o.status='resolution';o.resolutionReason=p.note.trim();o.offer=null}else{if(p.kind==='included')ok(o.revisions<o.service.revisions,'Jatah revisi habis. Ajukan penyelesaian tanpa tagihan otomatis.');if(p.kind==='included')o.revisions++;o.status='working';o.due=addHours(s.now,o.service.hours,cal)}o.revisionPending=false}
else if(k==='obstacle'){ok(['queued','working','materials','revision','response'].includes(o.status),'Pesanan sudah ditutup.');note();o.internal=p.note.trim();event(s,o,a,k,false,p.note);o.version++;return o.id}
else if(k==='resolution'){ok(!['done','closed','unpaid'].includes(o.status),'Penyelesaian tidak tersedia.');note();o.status='resolution';o.resolutionReason=p.note.trim();o.offer=null}
else if(k==='offer'){ok(a.role==='super'&&o.status==='resolution'&&!['refund_pending','benefit_pending'].includes(o.payment),'Keputusan khusus Super Admin.');note();ok(['schedule','replacement','refund','addition'].includes(p.kind),'Pilih penyelesaian.');if(p.kind==='addition')ok(Number.isSafeInteger(p.amount)&&p.amount>=0&&p.amount<=100000000&&Number.isInteger(p.hours)&&p.hours>=1&&p.hours<=720,'Biaya atau durasi tambahan tidak valid.');else if(p.kind==='refund')ok(Number.isSafeInteger(p.amount)&&p.amount>=0&&p.amount<=o.amount-o.refunded&&(o.payment==='benefit'||p.amount>0),'Nilai pengembalian tidak valid.');else ok(Number.isFinite(p.due)&&p.due>s.now,'Pilih estimasi baru.');o.offer={kind:p.kind,note:p.note.trim(),amount:p.amount||0,due:p.due||null,hours:p.hours||null,at:s.now}}
else if(k==='refund'){ok(a.role==='super'&&o.status==='resolution'&&['refund_pending','benefit_pending'].includes(o.payment)&&p.checked,'Pengembalian belum dapat dicatat.');note();if(o.payment==='benefit_pending'){o.benefitRestored=true;m.benefitRestores.push({key:o.benefitKey,order:o.id,at:s.now,used:false});o.payment='benefit_restored'}else{o.refunded+=o.refundDue;o.payment='refunded'}o.status='closed';o.closedAt=s.now}
else throw Error('Tindakan tidak tersedia.');}}
o.version++;if(!['claim','assign','offer','offer-decline'].includes(k))o.progress=s.now;event(s,o,a,k,true,p.note||'',k==='send-result'?{delivery:o.deliveries.length}:k==='offer'?{offer:cp(o.offer)}:{});return o.id}
function addHours(at,h,cal){let x=at,n=0;while(h>1e-8&&n++<1000000){const end=x+60000;h-=root.Wami11.businessHours(x,end,cal);x=end}ok(h<=1e-8,'Jadwal kerja tidak dapat memenuhi durasi layanan.');return x}
function attention(s,o,cal){let h;if(o.status==='closed'&&!o.ackAt)return {level:1,text:o.payment==='benefit_restored'?'Benefit layanan sudah dipulihkan':'Pengembalian biaya selesai'};if(o.status==='queued'){h=root.Wami11.businessHours(o.progress,s.now,cal);return h>=2?{level:h>=4?2:1,text:h>=4?'Pesanan belum ditangani':'Pesanan menunggu pemeriksaan'}:null}if(o.status==='materials'){h=(s.now-o.progress)/H;return h>=4?{level:h>=48?3:h>=24?2:1,text:h>=48?'Kelengkapan perlu ditindaklanjuti':'Lengkapi kebutuhan pesanan'}:null}if(o.status==='response'){h=(s.now-o.progress)/H;return h>=24?{level:h>=72?3:h>=48?2:1,text:h>=72?'Tanggapan perlu ditindaklanjuti':'Hasil menunggu tanggapan'}:null}if(o.status==='working'&&s.now>o.due)return {level:2,text:'Lewat estimasi'};if(o.status==='resolution')return {level:1,text:['refund_pending','benefit_pending'].includes(o.payment)?'Menunggu pengembalian':'Penyelesaian perlu ditinjau'};return null}
const api={init,act,attention,addHours,copy:cp};root.Addons111=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
