(function(root){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),H=3600000;
const defaults={daily:5,cost:{Standard:1,Express:2,MAX:3},temporaryHours:48,claimHours:48,priority:'expiry'};
function init(s){return s.credit11??={versions:[{id:1,effective:0,at:0,actor:'system',rules:clone(defaults)}],draft:null,revision:1,history:[]}}
function active(s){const c=init(s);return c.versions.filter(v=>v.effective<=s.now).sort((a,b)=>b.effective-a.effective||b.id-a.id)[0]}
function validate(r){if(!r||!Number.isInteger(r.daily)||r.daily<0||r.daily>100||!['expiry','daily','temporary'].includes(r.priority))throw Error('Aturan kredit tidak valid.');for(const k of ['Standard','Express','MAX'])if(!Number.isInteger(r.cost?.[k])||r.cost[k]<1||r.cost[k]>100)throw Error('Biaya layanan harus 1–100 kredit.');if(r.cost.Standard>r.cost.Express||r.cost.Express>r.cost.MAX)throw Error('Biaya Express/MAX tidak boleh lebih rendah dari layanan sebelumnya.');for(const k of ['temporaryHours','claimHours'])if(!Number.isInteger(r[k])||r[k]<1||r[k]>720)throw Error('Masa berlaku harus 1–720 jam.');return true}
function act(s,actor,action,p){if(actor.role!=='super')throw Error('Hanya Super Admin yang dapat mengubah aturan.');const c=init(s);if(p.revision!==c.revision)throw Error('Aturan telah berubah. Muat ulang sebelum melanjutkan.');if(action==='draft'){validate(p.rules);c.draft={rules:clone(p.rules),at:s.now,actor:actor.id};}else if(action==='publish'){if(!c.draft)throw Error('Simpan rancangan terlebih dahulu.');if(!Number.isFinite(p.effective)||p.effective<s.now)throw Error('Waktu berlaku tidak boleh di masa lalu.');if(c.versions.some(v=>v.effective>s.now))throw Error('Ada aturan terjadwal yang belum berlaku.');validate(c.draft.rules);const v={id:Math.max(...c.versions.map(v=>v.id))+1,at:s.now,effective:p.effective,actor:actor.id,rules:clone(c.draft.rules)};c.versions.push(v);c.history.unshift(clone(v));c.draft=null;}else throw Error('Tindakan tidak tersedia.');c.revision++;return c}
function forRelease(s,r){return r?.policy11||clone(active(s).rules)}
function compare(r,a,b){const rank=l=>r.priority==='daily'?(l.type==='daily'?0:l.type==='replacement'?1:2):r.priority==='temporary'?(l.type==='replacement'?0:l.type==='daily'?1:2):0;return rank(a)-rank(b)||(a.expires||Infinity)-(b.expires||Infinity)}
const api={init,active,validate,act,forRelease,compare,defaults,clone,H};root.Credit11=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
