/* Local reference lookups. Selecting a bank never verifies its account number. */
function directoryTitle(value){return String(value||'').trim().toLocaleLowerCase('id-ID').replace(/(^|[\s-])\p{L}/gu,c=>c.toLocaleUpperCase('id-ID')).replace(/\bDki\b/g,'DKI').replace(/\bDi Yogyakarta\b/g,'DI Yogyakarta');}
function directoryBank(value){const q=String(value||'').trim().toLowerCase();return RMDirectory.banks.find(b=>[b.id,b.name,b.displayName,...b.aliases].some(a=>a?.toLowerCase()===q));}
function directoryBankDisplay(value){return directoryBank(value)?.displayName||value||'';}
function directoryBankField(value){return `<label class="full bank-search-field">${T('Nama bank','Bank name')}<input name="bank" value="${E(directoryBankDisplay(value))}" required data-bank-search role="combobox" aria-autocomplete="list" aria-expanded="false" autocomplete="off" placeholder="${T('Cari bank atau tulis nama bank lain','Find a bank or enter another bank name')}"><small>${T('Bank tidak tersedia? Tulis nama lengkapnya.','Bank not listed? Enter its full name.')}</small></label>`;}
let bankSearchPopup=null,bankSearchInput=null,bankSearchIndex=-1;
function closeBankSearch(){bankSearchPopup?.remove();bankSearchInput?.setAttribute('aria-expanded','false');bankSearchInput?.removeAttribute('aria-activedescendant');bankSearchPopup=null;bankSearchInput=null;bankSearchIndex=-1;}
function openBankSearch(input,query=''){
 closeBankSearch();bankSearchInput=input;const q=query.trim().toLowerCase();
 const banks=RMDirectory.banks.filter(b=>!q||[b.displayName,b.name,...b.aliases].some(a=>a.toLowerCase().includes(q)));
 const popup=document.createElement('div');popup.className='bank-search-options';popup.id='bank-search-options';popup.setAttribute('role','listbox');
 popup.innerHTML=banks.map((b,i)=>`${!q&&(i===0||i===5)?`<small class="bank-group">${i===0?T('Pilihan utama','Common choices'):T('Bank lainnya','Other banks')}</small>`:''}<button type="button" role="option" aria-selected="false" tabindex="-1" id="bank-option-${i}" data-bank-id="${b.id}">${E(b.displayName)}</button>`).join('')||`<p>${T('Nama ini akan disimpan sesuai yang kamu tulis.','This name will be saved as entered.')}</p>`;
 (input.closest('dialog')||document.body).append(popup);bankSearchPopup=popup;input.setAttribute('aria-controls',popup.id);input.setAttribute('aria-expanded','true');
 const box=input.getBoundingClientRect();Object.assign(popup.style,{position:'fixed',left:Math.max(8,Math.min(box.left,innerWidth-300))+'px',top:(box.bottom+4)+'px',width:Math.min(Math.max(box.width,280),innerWidth-16)+'px',maxHeight:Math.max(100,Math.min(270,innerHeight-box.bottom-12))+'px'});
 popup.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-bank-id]');if(!b)return;e.preventDefault();input.value=directoryBank(b.dataset.bankId).displayName;closeBankSearch();input.dispatchEvent(new Event('change',{bubbles:true}));});
}
document.addEventListener('focusin',e=>{if(e.target.matches('[data-bank-search]'))openBankSearch(e.target);else if(!e.target.closest('.bank-search-options'))closeBankSearch();});
document.addEventListener('input',e=>{if(e.target.matches('[data-bank-search]'))openBankSearch(e.target,e.target.value);});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.bank-search-options,[data-bank-search]'))closeBankSearch();});
window.addEventListener('keydown',e=>{if(e.target!==bankSearchInput)return;const rows=[...bankSearchPopup.querySelectorAll('[role=option]')];if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();bankSearchIndex=Math.max(0,Math.min(rows.length-1,bankSearchIndex+(e.key==='ArrowDown'?1:-1)));rows.forEach((r,i)=>r.setAttribute('aria-selected',String(i===bankSearchIndex)));const row=rows[bankSearchIndex];if(row){e.target.setAttribute('aria-activedescendant',row.id);row.scrollIntoView({block:'nearest'});}}else if(e.key==='Enter'&&bankSearchIndex>=0){e.preventDefault();e.target.value=rows[bankSearchIndex].textContent;closeBankSearch();e.target.dispatchEvent(new Event('change',{bubbles:true}));}else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeBankSearch();}else if(e.key==='Tab')closeBankSearch();},true);
function directoryFind(rows,value,parent){return rows.find(r=>(parent===undefined||r.parent===parent)&&[r.id,r.name.toLowerCase()].includes(String(value||'').trim().toLowerCase()));}
function directoryLocationFields(identity){const l=identity.location||{},country=identity.country||'Indonesia',foreign=country.toLowerCase()!=='indonesia';
 const field=(name,idLabel,enLabel,value,rows,disabled=false)=>`<label>${T(idLabel,enLabel)}<input name="${name}" data-region-input value="${E(value||'')}" list="directory-${name}" autocomplete="off" ${disabled?'disabled':''} ${foreign?'':'required'}><datalist id="directory-${name}">${rows.map(r=>`<option value="${E(directoryTitle(r.name))}"></option>`).join('')}</datalist></label>`;
 const p=directoryFind(RMDirectory.provinces,l.provinceId||l.province),r=directoryFind(RMDirectory.regencies,l.regencyId||l.regency,p?.id);
 return `<div class="full directory-location-title"><h3>${T('Lokasi operasional label','Label operating location')}</h3>${info9('directory-source',T('Pilih wilayah sesuai lokasi operasional. Daftar BPS semester 2 tahun 2025; kode pos diisi terpisah.','Choose the operating location. BPS second-half 2025 directory; postal code is entered separately.'))}</div>${identity.address&&!l.complete?`<p class="full directory-legacy">${T('Alamat sebelumnya','Previous address')}: ${E(identity.address)}</p>`:''}${field10('country',T('Negara','Country'),country,'text','required data-region-country')}${field('province','Provinsi','Province',l.province,p?[...RMDirectory.provinces]:RMDirectory.provinces)}${field('regency','Kabupaten/kota','Regency/city',l.regency,RMDirectory.regencies.filter(x=>x.parent===p?.id),!foreign&&!p)}${field('district','Kecamatan','District',l.district,RMDirectory.districts.filter(x=>x.parent===r?.id),!foreign&&!r)}${field10('postal',T('Kode pos','Postal code'),identity.postal||'','text','required maxlength="20"')}`;
}
function directoryIdentity(values,strict=false,identity=member10().identity){const old=identity,country=String(values.country||'Indonesia').trim(),local=country.toLowerCase()==='indonesia';
 if(!('province' in values)&&!('regency' in values)&&!('district' in values))return {person:values.person,address:values.address??old.address,postal:values.postal,country};
 const p=directoryFind(RMDirectory.provinces,values.province),r=directoryFind(RMDirectory.regencies,values.regency,p?.id),d=directoryFind(RMDirectory.districts,values.district,r?.id);
 const complete=local?!!(p&&r&&r.parent===p.id&&d&&d.parent===r.id&&/^\d{5}$/.test(values.postal||'')):!!(values.province&&values.regency&&values.district&&values.postal);
 if(strict&&!complete)throw Error('location');
 const location={province:local?(p?directoryTitle(p.name):values.province||''):directoryTitle(values.province),regency:local?(r?directoryTitle(r.name):values.regency||''):directoryTitle(values.regency),district:local?(d?directoryTitle(d.name):values.district||''):directoryTitle(values.district),provinceId:local?p?.id||null:null,regencyId:local?r?.id||null:null,districtId:local?d?.id||null:null,source:local?'BPS':'manual',period:local?RMDirectory.regionPeriod:null,complete};
 return {person:values.person,postal:values.postal,country:local?'Indonesia':directoryTitle(country),location,address:complete?[location.district,location.regency,location.province].join(', '):old.address||'',legacyAddress:old.legacyAddress||(!old.location?.complete?old.address:'')||''};
}
function directoryRefresh(form,changed){const country=form.querySelector('[name=country]'),local=country.value.trim().toLowerCase()==='indonesia',fields=['province','regency','district'];
 if(changed==='country')fields.forEach(k=>form.elements[k].value='');
 if(changed==='province'){form.elements.regency.value='';form.elements.district.value='';}
 if(changed==='regency')form.elements.district.value='';
 const p=directoryFind(RMDirectory.provinces,form.elements.province.value),r=directoryFind(RMDirectory.regencies,form.elements.regency.value,p?.id);
 const choices={province:RMDirectory.provinces,regency:p?RMDirectory.regencies.filter(x=>x.parent===p.id):[],district:r?RMDirectory.districts.filter(x=>x.parent===r.id):[]};
 for(const k of fields){const input=form.elements[k];input.setCustomValidity('');input.disabled=local&&(k==='regency'&&!p||k==='district'&&!r);form.querySelector('#directory-'+k).innerHTML=local?choices[k].map(x=>`<option value="${E(directoryTitle(x.name))}"></option>`).join(''):'';}
}
window.addEventListener('input',event=>{if(event.target.matches('[data-region-input],[data-region-country]'))directoryRefresh(event.target.form,event.target.name);});
window.addEventListener('change',event=>{if(event.target.name==='bank'){const bank=directoryBank(event.target.value);if(bank)event.target.value=bank.displayName;}});
