const provinceCentersPending={'11':[96.8,4.5],'12':[99,2.3],'13':[100.5,-.8],'14':[101.7,.5],'15':[103,-1.6],'16':[104,-3.2],'17':[102.3,-3.5],'18':[105,-4.8],'19':[106.3,-2.6],'21':[104.5,1],'31':[106.8,-6.2],'32':[107.7,-6.9],'33':[110,-7.3],'34':[110.4,-7.9],'35':[112.7,-7.5],'36':[106.1,-6.5],'51':[115.2,-8.4],'52':[117.3,-8.6],'53':[121,-8.7],'61':[110.5,-.1],'62':[113.5,-1.8],'63':[115.4,-3],'64':[116.7,.5],'65':[116.7,3.3],'71':[124.5,1],'72':[121,-1],'73':[120,-4],'74':[122.2,-4.1],'75':[123,.6],'76':[119.3,-2.5],'81':[129,-3.5],'82':[127.8,.7],'91':[132.5,-2],'92':[131.5,-1],'94':[140,-2.7],'95':[139.8,-6.3],'96':[136.3,-3.5],'97':[138.5,-4]};
const flagPending=country=>{const iso=({singapura:'SG',singapore:'SG',malaysia:'MY',australia:'AU',jepang:'JP',japan:'JP',thailand:'TH',filipina:'PH',philippines:'PH',india:'IN',china:'CN',tiongkok:'CN','korea selatan':'KR','south korea':'KR','amerika serikat':'US','united states':'US',inggris:'GB','united kingdom':'GB',belanda:'NL',netherlands:'NL',jerman:'DE',germany:'DE'})[country.toLowerCase()];return iso?[...iso].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join(''):'🌐';};
const mapPointPending=([lon,lat])=>[(lon-94)*17,(6-lat)*23];
function indonesiaPathPending(){const geometry=RMIndonesia.features?.[0]?.geometry||RMIndonesia.geometry;return geometry.coordinates.map(polygon=>polygon.map(ring=>ring.map((p,i)=>(i?'L':'M')+mapPointPending(p).join(',')).join('')+'Z').join('')).join('');}
function memberMapPending(){const local=ten.members.filter(m=>m.identity.country.toLowerCase()==='indonesia'),foreign=ten.members.filter(m=>m.identity.country.toLowerCase()!=='indonesia'),groups={};for(const m of local){const id=m.identity.location?.provinceId;if(id)(groups[id]??=[]).push(m);}const known=Object.values(groups).flat().length;
 return `<section class="panel pad member-map-pending" data-widget-id="member-map"><div class="spread"><h2>${T('Member di Indonesia','Members in Indonesia')}</h2><span>${known} ${T('label terpetakan','mapped labels')}</span></div><svg viewBox="0 0 850 420" aria-label="${T('Peta sebaran label menurut provinsi','Label distribution by province')}"><path class="island-pending" d="${indonesiaPathPending()}"></path>${Object.entries(groups).filter(([id])=>provinceCentersPending[id]).map(([id,ms])=>{const [x,y]=mapPointPending(provinceCentersPending[id]);return `<g class="map-dot-pending" tabindex="0" role="button" data-map-province="${id}" aria-label="${E(ms[0].identity.location.province)}: ${ms.length} label"><circle class="map-pulse-pending" cx="${x}" cy="${y}" r="12"/><circle cx="${x}" cy="${y}" r="6"/><title>${E(ms[0].identity.location.province)} · ${ms.length} label</title></g>`;}).join('')}</svg><div id="map-detail-pending" aria-live="polite">${T('Arahkan ke titik provinsi untuk melihat label.','Point to a province marker to view labels.')}</div><footer><small>${T('Lokasi belum lengkap','Incomplete location')}: ${local.length-known}</small>${foreign.length?`<span>🌐 ${foreign.length} ${T('label di luar Indonesia','labels outside Indonesia')} · ${[...new Set(foreign.map(m=>m.identity.country))].map(c=>flagPending(c)+' '+E(c)+' '+foreign.filter(m=>m.identity.country===c).length).join(' · ')}</span>`:''}${info9('map-location',T('Titik mewakili provinsi operasional yang dipilih label, bukan alamat KTP atau lokasi jalan.','Markers represent the operating province selected by each label, not an identity card or street address.'))}</footer></section>`;
}
function mapDetailPending(target){const id=target?.dataset.mapProvince;if(!id)return;const ms=ten.members.filter(m=>m.identity.location?.provinceId===id);const detail=document.querySelector('#map-detail-pending');if(detail)detail.innerHTML=`<strong>${E(ms[0].identity.location.province)}</strong> · ${ms.length} label<p>${ms.map(m=>E(m.name)).join(' · ')}</p>`;}
document.addEventListener('pointerover',e=>mapDetailPending(e.target.closest('[data-map-province]')));document.addEventListener('focusin',e=>mapDetailPending(e.target.closest('[data-map-province]')));document.addEventListener('click',e=>mapDetailPending(e.target.closest('[data-map-province]')));

const memberMapRenderBase106=render;render=function(){memberMapRenderBase106();if(ten.role==='super'&&state.mode==='platform'&&state.page==='dashboard')document.querySelector('.footer')?.insertAdjacentHTML('beforebegin',memberMapPending());};
