/* Versioned prototype offers. Purchased rights are snapshots, never live catalogue references. */
(function(root){'use strict';
const copy=v=>structuredClone(v),ok=(v,m)=>{if(!v)throw Error(m)},names=['Basic','Studio','Pro','Business'],aliases={Basic:'Flex',Studio:'Go',Pro:'Pro',Business:'Business'},ranks={Basic:0,Studio:1,Pro:2,Business:3};
function name(id){return ({Flex:'Basic',Go:'Studio'})[id]||id||'Basic'}
function init(s,old){if(s.packages122)return s.packages122;
 const colors=[['#36576e','#7094ad'],['#096b80','#25b9a5'],['#075697','#19b6bd'],['#343587','#7876dc']];
 return s.packages122={schema:1,version:1,plans:names.map((id,i)=>{const p=old?.plans?.find(p=>p.id===aliases[id]);return {id,name:id,rank:i,monthly:id==='Basic'?0:p?.monthly??null,annual:id==='Basic'?0:p?.annual??null,enabled:true,discount:p?.discount||0,until:p?.until||'',limited:false,colors:colors[i],planning:i>0,campaign:i>1,wami:null,design:null,notes:''}}),subscriptions:[],usage:[],history:[]};
}
function offer(s,id){return init(s).plans.find(p=>p.id===name(id))}
function addMonths(start,n){const d=new Date(start),day=d.getUTCDate(),year=d.getUTCFullYear(),month=d.getUTCMonth()+n;d.setUTCDate(1);d.setUTCFullYear(year,month,1);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString()}
function current(s,member){return init(s).subscriptions.filter(x=>x.member===member&&x.status==='active'&&x.start&&Date.parse(x.start)<=s.now&&(x.plan==='Basic'&&!x.end||s.now<Date.parse(x.end))).at(-1)||null}
function tier(s,m){if(m.previewPlan121)return m.previewPlan121;const x=current(s,m.id);if(x)return x.plan;if(init(s).subscriptions.some(x=>x.member===m.id&&x.status==='active')&&m.subscriptionEnd&&Date.parse(m.subscriptionEnd)<=s.now)return 'Basic';return name(m.plan)}
function capability(s,m,kind){ok(['planning','campaign'].includes(kind),'Jenis manfaat tidak valid.');if(m.previewPlan121)return ranks[name(m.previewPlan121)]>=(kind==='campaign'?2:1);const x=current(s,m.id);if(x)return x.quote.benefits[kind]===true;return ranks[tier(s,m)]>=(kind==='campaign'?2:1)}
function quote(s,id,period){const p=offer(s,id);ok(p?.enabled,'Paket ini belum tersedia.');ok(['month','year'].includes(period),'Periode paket tidak valid.');if(p.limited&&p.until&&s.now>Date.parse(p.until+'T23:59:59+07:00'))return null;const base=period==='month'?p.monthly:p.annual;if(base===null)return null;const discount=p.discount&&(!p.until||s.now<=Date.parse(p.until+'T23:59:59+07:00'))?p.discount:0;return {base,total:Math.round(base*(100-discount)/100),discount,plan:p.id,name:p.name,period,version:init(s).version,benefits:copy({planning:p.planning,campaign:p.campaign,wami:p.wami,design:p.design}),draftOffer:true}}
function configure(s,a,p){ok(a.role==='super'&&a.authorized,'Hanya Super Admin dapat mengatur paket.');const m=init(s);ok(p.version===m.version,'Pengaturan paket telah berubah. Buka kembali.');const old=offer(s,p.id);ok(old,'Paket tidak ditemukan.');const v=copy(p.values);ok(typeof v.name==='string'&&v.name.trim().length>0&&v.name.length<=32,'Nama paket tidak valid.');ok(!m.plans.some(x=>x.id!==old.id&&x.name.toLowerCase()===v.name.trim().toLowerCase()),'Nama paket sudah digunakan.');for(const k of ['monthly','annual'])ok(v[k]===null||Number.isSafeInteger(v[k])&&v[k]>=0&&v[k]<=100000000,'Harga paket tidak valid.');if(old.id==='Basic')ok(v.monthly===0&&v.annual===0,'Basic tidak memiliki biaya berlangganan.');else for(const k of ['monthly','annual'])ok(v[k]===null||v[k]>0,'Harga langganan harus lebih dari nol.');for(const k of ['wami','design'])ok(v[k]===null||Number.isSafeInteger(v[k])&&v[k]>=0&&v[k]<=1000,'Jumlah manfaat tidak valid.');ok(Array.isArray(v.colors)&&v.colors.length===2&&v.colors.every(c=>/^#[0-9a-f]{6}$/i.test(c)),'Warna badge tidak valid.');ok(Number.isInteger(v.discount)&&v.discount>=0&&v.discount<=90,'Potongan harga tidak valid.');ok(!v.until||/^\d{4}-\d{2}-\d{2}$/.test(v.until)&&Number.isFinite(Date.parse(v.until))&&new Date(v.until+'T12:00Z').toISOString().slice(0,10)===v.until,'Tanggal penawaran tidak valid.');ok(!v.limited||v.until,'Tanggal akhir diperlukan.');for(const k of ['enabled','limited','planning','campaign'])ok(typeof v[k]==='boolean','Pengaturan manfaat tidak valid.');ok(typeof v.notes==='string'&&v.notes.length<=2000,'Catatan terlalu panjang.');Object.assign(old,v,{name:v.name.trim()});m.version++;m.history.unshift({id:'CFG-'+m.version,actor:a.id,at:s.now,kind:'configure',plan:old.id});return old}
function install(s,x){const db=init(s),m=s.members.find(m=>m.id===x.member);for(const old of db.subscriptions.filter(p=>p.member===x.member&&p.status==='active'&&p!==x))old.status='replaced';x.status='active';m.plan=aliases[x.plan];m.subscriptionEnd=x.end;m.period=x.period;m.paid=x.plan!=='Basic';}
function apply(s,member,q,order){const db=init(s),m=s.members.find(x=>x.id===member);ok(m,'Label tidak ditemukan.');ok(q&&names.includes(q.plan)&&['month','year'].includes(q.period)&&q.benefits,'Rincian paket tidak valid.');const duplicate=db.subscriptions.find(x=>x.order===order);if(duplicate)return duplicate;
 ok(!db.subscriptions.some(x=>x.member===member&&['scheduled','activation'].includes(x.status)),'Perubahan paket sudah terjadwal. Tinjau perubahan yang berjalan terlebih dahulu.');
 const prior=current(s,member),activeEnd=Math.max(0,Date.parse(m.subscriptionEnd)||0),oldPlan=prior?.plan||name(m.plan),scheduled=m.active&&activeEnd>s.now&&ranks[q.plan]<=ranks[oldPlan],start=m.active?(scheduled?activeEnd:s.now):null;
 const end=q.plan==='Basic'?null:start===null?null:addMonths(scheduled?start:Math.max(start,activeEnd),q.period==='year'?12:1),anchor=!scheduled&&prior?.anchor?prior.anchor:start===null?null:new Date(start).toISOString();
 const x={id:'SUB-'+order,member,order,plan:q.plan,period:q.period,quote:copy(q),status:!m.active?'activation':scheduled?'scheduled':'active',start:start===null?null:new Date(start).toISOString(),end,anchor,previous:{plan:m.plan,end:m.subscriptionEnd||null,benefits:copy(m.benefits104||[])}};
 db.subscriptions.push(x);if(x.status==='active')install(s,x);db.version++;db.history.unshift({id:x.id,actor:member,at:s.now,kind:x.status,plan:q.plan});return x;
}
function needsActivation(s){return init(s).subscriptions.some(x=>x.status==='activation'&&s.members.find(m=>m.id===x.member)?.active||x.status==='scheduled'&&Date.parse(x.start)<=s.now)}
function activate(s){const db=init(s);let changed=false;for(const x of db.subscriptions){const m=s.members.find(m=>m.id===x.member);if(!m)continue;let installed=false;if(x.status==='activation'&&m.active){x.start=x.anchor=new Date(s.now).toISOString();x.end=x.plan==='Basic'?null:addMonths(s.now,x.period==='year'?12:1);install(s,x);installed=true;}else if(x.status==='scheduled'&&Date.parse(x.start)<=s.now){install(s,x);installed=true;}if(installed){changed=true;const o=s.commerce113?.orders.find(o=>o.id===x.order);if(o){o.start=x.start;o.end=x.end;o.activationWaiting=false;}}}if(changed)db.version++;return changed}
function period(s,x){if(!x||!x.anchor)return null;let index=0;while(Date.parse(addMonths(x.anchor,index+1))<=s.now&&index<1200)index++;const start=addMonths(x.anchor,index),next=addMonths(x.anchor,index+1),end=x.end&&Date.parse(x.end)<Date.parse(next)?x.end:next;return {id:x.member+':'+start,index,start,end}}
function quota(s,member,kind){ok(['wami','design'].includes(kind),'Jenis manfaat tidak valid.');const x=current(s,member);if(!x)return null;const p=period(s,x),total=x.quote.benefits[kind];const entries=init(s).usage.filter(u=>u.member===member&&u.kind===kind&&u.period===p.id&&u.status!=='restored'),reserved=entries.filter(u=>u.status==='reserved').reduce((n,u)=>n+u.quantity,0),used=entries.filter(u=>u.status==='used').reduce((n,u)=>n+u.quantity,0);return {...p,total,reserved,used,available:total===null?null:Math.max(0,total-reserved-used),subscription:x.id}}
function reserve(s,member,kind,order,quantity){const db=init(s);const same=db.usage.find(u=>u.order===order&&u.kind===kind&&u.status!=='restored');if(same)return same;ok(Number.isSafeInteger(quantity)&&quantity>0,'Jumlah pemakaian tidak valid.');const q=quota(s,member,kind);ok(q&&q.available!==null&&q.available>=quantity,'Manfaat paket tidak mencukupi. Tinjau pembayaran layanan.');const u={id:'USE-'+order+':'+kind,member,kind,order,quantity,period:q.id,start:q.start,end:q.end,status:'reserved',at:s.now};db.usage.push(u);db.version++;return u}
function settle(s,order,restore=false){const db=init(s);let changed=false;for(const u of db.usage.filter(u=>u.order===order&&u.status==='reserved')){u.status=restore?'restored':'used';u.settled=s.now;changed=true;}if(changed)db.version++;}
root.Packages122={init,name,aliases,ranks,offer,tier,capability,current,quote,configure,apply,needsActivation,activate,period,quota,reserve,settle,addMonths};if(typeof module!=='undefined')module.exports=root.Packages122;
})(typeof window!=='undefined'?window:globalThis);
