/* Shared working interfaces for the pending workflows. Not a published release. */
const pendingUI={tab:'credits',filter:'',bonusDraft:null,cleanup:null};
const pb=(label,action,id='',cls='')=>`<button type="button" class="btn ${cls}" data-pending="${action}" data-id="${E(id)}">${label}</button>`;
const pendingErrorBase=error10;
error10=function(code){return ({identity_changed:T('Identitas label telah diperbarui. Periksa kembali sebelum menyetujui rekening.','Label identity has changed. Review it again before approving this account.'),offer_expired:T('Bonus tidak lagi tersedia untuk diklaim.','This bonus is no longer available to claim.'),locked_account:T('Nomor rekening hanya dapat diubah melalui pengajuan label.','Account numbers can only change through a label request.'),baseline:T('Tetapkan pencapaian awal sebelum mencatat kenaikan baru.','Set the initial achievement before recording a new level.'),royalty_correction:T('Koreksi royalti perlu ditinjau terpisah. Kredit tidak diubah.','Royalty corrections require a separate review. Credits are unchanged.'),duplicate:T('Perubahan ini sudah tercatat.','This change has already been recorded.')})[code]||pendingErrorBase(code);};
function pendingInit(){RM10.pending.baseline(ten,data.v9.labels);RM10.pending.reconcile(ten,data.v9.labels);}
function reconcilePayoutAchievements116(){RM10.pending.reconcile(ten,data.v9.labels);}
function emblemUI(m){const l=RM10.pending.levels.filter(l=>m.achievement?.earned.includes(l.id)).at(-1);return l?`<span class="emblem-pending ${l.family.toLowerCase()}" title="${E(l.name)}"><svg viewBox="0 0 40 46" aria-hidden="true"><path d="M20 2 36 11 34 32 20 44 6 32 4 11Z"/><path d="m20 9 9 12-9 15-9-15Z"/></svg><span>${E(l.name)}</span></span>`:'—';}
function availablePending(m){const b=RM10.balance(ten,m);return b.daily+b.paid+b.replacement;}
function bonusStateUI(b){return T(...({pending:['Menunggu klaim','Awaiting claim'],claimed:['Diklaim','Claimed'],expired:['Kedaluwarsa','Expired'],cancelled:['Dibatalkan','Cancelled']})[RM10.pending.status(ten,b)]);}
function bonusPopupBody(b,preview=false){const m=RM10.getMember(ten,b.member),pending=RM10.pending.status(ten,b)==='pending';return `<div class="reward-popup"><span class="reward-orbit" aria-hidden="true">✦</span><small>${T('Bonus dari Rilis Musik','A bonus from Rilis Musik')}</small><h2>${E(m.name)}</h2><strong class="reward-amount">+${b.amount} <small>${T('kredit','credits')}</small></strong><p>${E(b.message)}</p><div class="reward-terms"><span>${b.type==='temporary'?T('Kredit Sementara · berlaku 48 jam setelah klaim','Temporary Credit · valid for 48 hours after claiming'):T('Kredit Flex · tanpa kedaluwarsa setelah klaim','Flex Credit · no expiry after claiming')}</span><span>${T('Klaim sebelum','Claim before')} ${date10(b.claimBy,true)} WIB</span></div>${preview?`<button type="button" class="btn primary" disabled>${T('Klaim bonus','Claim bonus')}</button><small>${T('Pratinjau · belum dikirim','Preview · not sent')}</small>`:pending?pb(T('Klaim bonus','Claim bonus'),'bonus-claim',b.id,'primary'):`<strong>${bonusStateUI(b)}</strong>`}</div>`;}
function bonusPopup(id){const b=ten.bonuses.find(b=>b.id===id&&b.member===ten.member);if(!isLabel10()||!b)return;reviewDialogUI(T('Bonus dari Rilis Musik','A bonus from Rilis Musik'),bonusPopupBody(b));}
function bonusForm(){if(ten.role!=='super')return;const d=pendingUI.bonusDraft||{member:ten.members[0].id,amount:5,type:'flex',message:'Ada 5 kredit untuk rilisanmu berikutnya.',requestId:requestId119()};pendingUI.bonusDraft=d;reviewDialogUI(T('Buat bonus kredit','Create a credit bonus'),`<form class="ten-form" data-pending-form="bonus"><label class="full">Label<select name="member">${ten.members.map(m=>`<option value="${m.id}" ${m.id===d.member?'selected':''}>${E(m.name)}</option>`).join('')}</select></label>${field10('amount',T('Jumlah kredit','Credit amount'),d.amount,'number','required min="1" max="500" step="1"')}${select10('type',T('Jenis kredit','Credit type'),[['flex','Kredit Flex'],['temporary',T('Kredit Sementara','Temporary Credit')]],d.type)}<label class="full">${T('Pesan untuk label','Message to the label')}<textarea name="message" required maxlength="500" rows="3">${E(d.message)}</textarea></label><p class="full muted">${T(`Batas klaim ${Credit11.active(ten).rules.claimHours} jam sejak dikirim. Masa penggunaan kredit dimulai setelah klaim.`,`Claim within ${Credit11.active(ten).rules.claimHours} hours of sending. Credit validity starts after claiming.`)}</p><footer class="review-footer-ui full">${pb(T('Pratinjau popup','Preview popup'),'bonus-preview')}<button class="btn primary" type="submit">${T('Kirim bonus','Send bonus')}</button></footer></form>`);}
function pendingTable(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">${T('Belum ada catatan.','No records yet.')}</td></tr>`}</tbody></table></div>`;}
function monitorPending(){pendingInit();const members=ten.members.filter(m=>m.name.toLowerCase().includes(pendingUI.filter.toLowerCase()));let body='';
 if(pendingUI.tab==='credits')body=pendingTable(['Label',T('Tersedia','Available'),T('Harian','Daily'),'Flex',T('Sementara','Temporary'),T('Berlaku terdekat','Next expiry')],members.map(m=>{const b=RM10.balance(ten,m),expiry=m.lots.filter(l=>l.type==='replacement'&&l.available>0&&l.expires>ten.now).sort((a,b)=>a.expires-b.expires)[0];return `<tr><td>${E(m.name)}</td><td><strong>${availablePending(m)}</strong></td><td>${b.daily}</td><td>${b.paid}</td><td>${b.replacement}</td><td>${expiry?date10(expiry.expires,true)+' WIB':'—'}</td></tr>`;}));
 else if(pendingUI.tab==='achievements')body=pendingTable(['Label',T('Pencapaian','Achievement'),T('Royalti dibayarkan','Royalties paid'),T('Kredit tersedia','Available credits'),''],members.map(m=>`<tr><td>${E(m.name)}</td><td>${emblemUI(m)}</td><td>${money10(m.achievement.paid)}</td><td>${availablePending(m)}</td><td>${pb(T('Perjalanan','Journey'),'journey',m.id)}</td></tr>`))+`<h3>${T('Kenaikan terbaru','Recent level advances')}</h3>`+pendingTable(['Label',T('Pencapaian','Achievement'),T('Tanggal','Date'),T('Royalti saat naik','Royalties at advancement'),T('Hadiah','Reward'),T('Kredit sekarang','Credits now')],ten.achievementNews.map(n=>`<tr><td>${E(RM10.getMember(ten,n.member).name)}</td><td>${E(n.level)}</td><td>${date10(n.at,true)}</td><td>${money10(n.paid)}</td><td>+${n.amount}</td><td>${availablePending(RM10.getMember(ten,n.member))}</td></tr>`));
 else body=pb(T('Buat bonus','Create bonus'),'bonus-new','','primary')+pendingTable(['Label',T('Pesan','Message'),T('Kredit','Credits'),'Status',T('Kirim / klaim','Sent / claimed'),T('Batas klaim','Claim deadline'),''],ten.bonuses.filter(b=>members.some(m=>m.id===b.member)).map(b=>`<tr><td>${E(RM10.getMember(ten,b.member).name)}</td><td>${E(b.message)}</td><td>${b.amount} · ${b.type==='flex'?'Flex':T('Sementara','Temporary')}</td><td>${bonusStateUI(b)}</td><td>${date10(b.sent,true)}<small class="block102">${b.claimed?date10(b.claimed,true):'—'}</small></td><td>${date10(b.claimBy,true)}</td><td>${RM10.pending.status(ten,b)==='pending'?pb(T('Batalkan','Cancel'),'bonus-cancel',b.id):''}</td></tr>`));
 return pageHead(T('Label Monitor','Label Monitor'),'')+`<section class="panel pad"><div class="tabs">${[['credits','Kredit','Credits'],['achievements','Pencapaian','Achievements'],['bonuses','Bonus Kredit','Credit Bonuses']].map(([id,a,b])=>pb(T(a,b),'monitor-tab',id,pendingUI.tab===id?'active':'')).join('')}</div><label class="monitor-search">${T('Cari label','Find label')}<input type="search" data-pending-filter value="${E(pendingUI.filter)}"></label>${body}</section>`;
}
function journeyPending(id){const m=RM10.getMember(ten,id);if(!canJourney119(id)){closeModal();toast(T('Informasi di luar kewenangan atau cakupan akun.','This information is outside your account permissions or scope.'));return;}reviewDialogUI(T('Perjalanan pencapaian','Achievement journey'),`<div class="spread"><h2>${E(m.name)}</h2>${emblemUI(m)}</div><p>${T('Akumulasi royalti yang telah dibayarkan','Accumulated paid royalties')}: ${money10(m.achievement.paid)}</p><div class="level-grid">${RM10.pending.levels.map(l=>`<div class="${m.achievement.earned.includes(l.id)?'earned':''}"><strong>${l.name}</strong><span>${money10(l.threshold)}</span><small>+${l.reward} ${T('kredit','credits')}</small></div>`).join('')}</div>${info9('reward-draft',T('Angka turunan hadiah masih draf. Pencapaian historis ditampilkan tanpa menerbitkan seluruh hadiah lama. Kebijakan bonus transisi belum final.','Lower-tier rewards are draft values. Historical achievements do not issue cumulative past rewards. Transition policy is not final.'))}`);document.querySelector('#dialog').dataset.journey119=id;}
function cleanupPagePending(){return pageHead(T('Penyesuaian Data Label','Label Data Updates'),'')+card10(T('Data identitas dan rekening','Identity and bank details'),pendingTable(['Label',T('Lokasi operasional','Operating location'),T('Rekening','Bank account'),''],ten.members.map(m=>`<tr><td>${E(m.name)}</td><td>${m.identity.location?.complete?T('Lengkap','Complete'):T('Perlu dilengkapi','Incomplete')}</td><td>${E(directoryBankDisplay(m.bank.approved?.bank)||'—')}</td><td>${pb(T('Periksa data','Review details'),'cleanup-open',m.id)}</td></tr>`)))+card10(T('Riwayat perubahan','Change history'),ten.cleanupHistory.slice(0,20).map(h=>`<div class="approval-row-ui"><div><strong>${E(RM10.getMember(ten,h.member).name)}</strong><p>${date10(h.at,true)} WIB</p></div>${pb(T('Lihat perubahan','View changes'),'cleanup-history',h.id)}</div>`).join('')||T('Belum ada perubahan data.','No changes recorded.'));}
function cleanupOpen(id){if(ten.role!=='super')return;const m=RM10.getMember(ten,id);pendingUI.cleanup=id;const a=m.bank.approved;reviewDialogUI(T('Penyesuaian data','Data update'),`${reviewHeadingUI(m,'approved')}<form class="ten-form" data-pending-form="cleanup" data-id="${id}"><input type="hidden" name="base" value="${E(RM10.pending.bankFingerprint(m))}"><details class="full"><summary>${T('Lihat KTP penanggung jawab','View representative identity card')}</summary>${identityRead10(m.identity)}</details>${directoryLocationFields(m.identity).replaceAll('required','')}${a?`<h3 class="full">${T('Rekening penerima','Payout account')}</h3>${directoryBankField(a.bank)}<label>${T('Nomor rekening','Account number')}<input value="${E(a.number)}" readonly aria-readonly="true"></label>${field10('holder',T('Nama pemilik rekening','Account holder'),a.holder,'text','required')}${select10('mode',T('Penanganan koreksi rekening','Bank correction handling'),[['save',T('Simpan langsung','Save directly')],['proposal',T('Minta konfirmasi label','Ask the label to confirm')]],'proposal')}`:''}<footer class="full review-footer-ui"><button class="btn primary" type="submit">${T('Simpan perubahan','Save changes')}</button></footer></form>`);}
function cleanupProposalPending(){const m=member10(),q=m.bank.cleanupProposal;if(q?.status!=='pending')return;reviewDialogUI(T('Konfirmasi koreksi rekening','Confirm bank correction'),`<h3>${E(m.name)}</h3>${pendingTable([T('Data','Field'),T('Saat ini','Current'),T('Usulan','Proposed')],['bank','holder'].filter(k=>q.before[k]!==q.after[k]).map(k=>`<tr><th>${k==='bank'?T('Bank','Bank'):T('Pemilik','Holder')}</th><td>${E(k==='bank'?directoryBankDisplay(q.before[k]):q.before[k])}</td><td>${E(k==='bank'?directoryBankDisplay(q.after[k]):q.after[k])}</td></tr>`))}<p>${T('Nomor rekening tetap','Account number unchanged')}: ${E(q.before.number)}</p><footer class="review-footer-ui">${pb(T('Tidak sesuai','Decline'),'cleanup-decline',q.id)}${pb(T('Konfirmasi','Confirm'),'cleanup-accept',q.id,'primary')}</footer>`);}
const pendingModuleBase=modulePage;
modulePage=function(){if(['monitor-pending','cleanup-pending'].includes(v4.module))return ten.role==='super'?(v4.module==='monitor-pending'?monitorPending():cleanupPagePending()):denied9();return pendingModuleBase();};
const pendingLiabilityBase=liabilityPage9;
liabilityPage9=function(){if(ten.role!=='super')return denied9();if(pendingUI.tab==='royalties')return `<div class="tabs">${pb(T('Royalti','Royalties'),'monitor-tab','royalties','active')}${pb(T('Kredit','Credits'),'monitor-tab','credits')}${pb(T('Pencapaian','Achievements'),'monitor-tab','achievements')}</div>`+pendingLiabilityBase();return monitorPending().replace('<div class="tabs">','<div class="tabs">'+pb(T('Royalti','Royalties'),'monitor-tab','royalties'));};
const pendingActionBase=handleAction;
handleAction=async function(b){if(b.dataset.action==='nav'&&b.dataset.page==='liability9')pendingUI.tab='royalties';return pendingActionBase(b);};
const pendingAttentionBase=labelAttention102;
labelAttention102=function(){pendingInit();const m=member10(),bonus=ten.bonuses.find(b=>b.member===m.id&&RM10.pending.status(ten,b)==='pending'),news=ten.achievementNews.find(n=>n.member===m.id&&!n.seen),q=m.bank.cleanupProposal;let html=pendingAttentionBase();
 const attention=(title,detail,action,id)=>`<section class="attention9 attention-shared102"><div class="spread"><div><h2>${title}</h2><p>${detail}</p></div>${pb('↗',action,id)}</div></section>`;
 if(bonus)html+=attention(T('Bonus dari Rilis Musik','A bonus from Rilis Musik'),`${bonus.amount} ${T('kredit · klaim sebelum','credits · claim before')} ${date10(bonus.claimBy,true)} WIB`,'bonus-open',bonus.id);
 if(news)html+=attention(T('Pencapaian baru','New achievement'),`${E(news.level)} · +${news.amount} ${T('kredit telah ditambahkan','credits added')}`,'achievement-popup',news.id);
 if(q?.status==='pending')html+=attention(T('Konfirmasi koreksi rekening','Confirm bank correction'),T('Periksa usulan nama bank dan pemilik rekening.','Review the proposed bank and account holder names.'),'cleanup-proposal');
 const returns=ten.events.filter(e=>e.kind==='credit_return'&&ten.releases.some(r=>r.id===e.target&&r.member===m.id));for(const e of returns.slice(0,2)){const r=RM10.getRelease(ten,e.target);html+=attention(T('Pengembalian kredit rilisan','Release credit return'),`${E(r.title)} · ${(ten.creditReturns||[]).filter(x=>x.release===r.id).reduce((n,x)=>n+x.amount,0)} ${T('kredit dikembalikan','credits returned')}`,'return-detail',r.id);}return html;
};
const pendingNotificationBase=notification10;
notification10=function(){pendingInit();const items=isLabel10()?ten.bonuses.filter(b=>b.member===ten.member):[];return items.map(b=>`<div class="approval-row-ui"><div><strong>${T('Bonus dari Rilis Musik','A bonus from Rilis Musik')}</strong><p>${b.amount} ${T('kredit','credits')} · ${bonusStateUI(b)}</p></div>${pb(T('Lihat','View'),'bonus-open',b.id)}</div>`).join('')+(()=>{const original=ten.notifications;try{ten.notifications=original.filter(n=>!n.role&&!['bonus_send','achievement','bonus_claimed'].includes(n.key));return pendingNotificationBase();}finally{ten.notifications=original;}})();};
function newsPending(){return `<section class="panel pad pending-news" data-widget-id="achievement-news"><div class="spread"><h2>${T('Kabar label','Label news')}</h2>${pb('↗','monitor-open')}</div>${ten.achievementNews.slice(0,3).map(n=>`<article><strong>${E(RM10.getMember(ten,n.member).name)} · ${n.level}</strong><p>${date10(n.at,true)} · ${money10(n.paid)} · +${n.amount} ${T('kredit','credits')}</p></article>`).join('')||`<p>${T('Kabar kenaikan pencapaian label akan muncul di sini.','Label achievement updates will appear here.')}</p>`}${ten.bonuses.filter(b=>b.status==='claimed').slice(0,2).map(b=>`<p>${E(RM10.getMember(ten,b.member).name)} · ${T('mengklaim','claimed')} ${b.amount} ${T('kredit','credits')}</p>`).join('')}</section>`;}
window.addEventListener('click',e=>{const b=e.target.closest('[data-pending]');if(!b||/^(document-|layout-|map-)/.test(b.dataset.pending))return;e.preventDefault();e.stopImmediatePropagation();const a=b.dataset.pending,id=b.dataset.id;
 try{
 if(a==='monitor-open'||a==='cleanup-page'){if(ten.role!=='super')throw Error('permission');if(a==='monitor-open'){state.mode='platform';state.page='liability9';}else module102('cleanup-pending');closeModal();render();return;}
 if(a==='bonus-nav'){if(ten.role!=='super')throw Error('permission');pendingUI.tab='bonuses';state.page='liability9';state.mode='platform';closeModal();render();return;}
 if(a==='monitor-tab'){pendingUI.tab=id;render();return;}
 if(a==='bonus-new'){pendingUI.bonusDraft=null;bonusForm();return;}
 if(a==='bonus-back'){bonusForm();return;}
 if(a==='bonus-preview'){const f=b.closest('form');if(!f.reportValidity())return;Object.assign(pendingUI.bonusDraft,Object.fromEntries(new FormData(f)));const d={...pendingUI.bonusDraft,amount:+pendingUI.bonusDraft.amount,claimBy:ten.now+Credit11.active(ten).rules.claimHours*RM10.H,temporaryHours:Credit11.active(ten).rules.temporaryHours,status:'pending'};reviewDialogUI(T('Pratinjau bonus','Bonus preview'),bonusPopupBody(d,true)+pb(T('Kembali','Back'),'bonus-back'));return;}
 if(a==='bonus-open'){bonusPopup(id);return;}
 if(a==='bonus-claim'){atomic10(()=>RM10.act(ten,'bonus_claim',{id}));closeModal();render();toast(T('Bonus berhasil diklaim.','Bonus claimed.'));return;}
 if(a==='bonus-cancel'){const bonus=ten.bonuses.find(x=>x.id===id);atomic10(()=>RM10.act(ten,'bonus_cancel',{id,member:bonus.member}));closeModal();render();toast(T('Bonus dibatalkan.','Bonus cancelled.'));return;}
 if(a==='journey'){journeyPending(id);return;}
 if(a==='achievement-popup'){const n=ten.achievementNews.find(n=>n.id===id&&n.member===ten.member);if(!isLabel10()||!n)return;reviewDialogUI(T('Pencapaian baru','New achievement'),`<div class="reward-popup">${emblemEvent119(n)}<small>${T('Selamat atas pencapaianmu','Congratulations on your achievement')}</small><h2>${E(member10().name)}</h2><strong class="reward-amount">+${n.amount} <small>${T('kredit','credits')}</small></strong><p>${T('Kredit sudah ditambahkan untuk rilisanmu berikutnya.','Credits have been added for your next releases.')}</p>${pb(T('Lanjutkan','Continue'),'achievement-seen',id,'primary')}</div>`);return;}
 if(a==='achievement-seen')RM10.act(ten,'emblem_seen',{id});
 if(a==='cleanup-open'){cleanupOpen(id);return;}
 if(a==='cleanup-proposal'){cleanupProposalPending();return;}
 if(a==='cleanup-accept'||a==='cleanup-decline')RM10.act(ten,'cleanup_confirm',{id,decision:a==='cleanup-accept'?'accept':'decline'});
 if(a==='cleanup-history'){if(ten.role!=='super')throw Error('permission');const h=ten.cleanupHistory.find(h=>h.id===id);reviewDialogUI(T('Riwayat perubahan','Change history'),`<p>${date10(h.at,true)} WIB</p>${pendingTable([T('Data','Field'),T('Sebelum','Before'),T('Sesudah','After')],[['Lokasi',h.before.identity.address,h.after.identity.address],['Bank',directoryBankDisplay(h.before.bank?.bank),directoryBankDisplay(h.after.bank?.bank)],['Pemilik',h.before.bank?.holder,h.after.bank?.holder]].map(([k,v,w])=>`<tr><th>${k}</th><td>${E(v||'—')}</td><td>${E(w||'—')}</td></tr>`))}${h.after.proposal?`<p>${T('Koreksi rekening dikirim untuk konfirmasi label.','Bank correction sent for label confirmation.')}</p>`:''}`);return;}
 if(a==='return-detail'){const r=RM10.getRelease(ten,id);if(!r||r.member!==ten.member)return;reviewDialogUI(T('Pengembalian kredit','Credit return'),`<h3>${E(r.title)}</h3><p>${E(r.reason||r.incidentNote||T('Pengajuan tidak dilanjutkan.','Submission was not continued.'))}</p>${pendingTable([T('Jenis','Type'),T('Dikembalikan','Returned'),T('Berlaku sampai','Valid until')],(ten.creditReturns||[]).filter(l=>l.release===r.id).map(l=>`<tr><td>${l.type==='paid'?'Flex':l.type==='daily'?T('Harian','Daily'):T('Sementara','Temporary')}</td><td>${l.amount}</td><td>${!l.amount?T('Masa berlaku berakhir','Expired'):l.expires?date10(l.expires,true)+' WIB':T('Tanpa kedaluwarsa','No expiry')}</td></tr>`))}`);return;}
 save10();closeModal();render();toast(T('Perubahan tersimpan.','Changes saved.'));
 }catch(err){toast(error10(err.message));}
},true);
window.addEventListener('submit',e=>{const f=e.target,kind=f.dataset.pendingForm;if(!kind)return;e.preventDefault();e.stopImmediatePropagation();if(!f.reportValidity())return;const v=Object.fromEntries(new FormData(f));try{
 if(kind==='bonus'){pendingUI.bonusDraft??={requestId:requestId119()};Object.assign(pendingUI.bonusDraft,v);atomic10(()=>RM10.act(ten,'bonus_send',{...v,requestId:pendingUI.bonusDraft.requestId}));pendingUI.bonusDraft=null;closeModal();render();toast(T('Bonus telah dikirim.','Bonus sent.'));return;}
 if(kind==='cleanup'){if(ten.role!=='super')throw Error('permission');const m=RM10.getMember(ten,f.dataset.id),identity=(v.province||v.regency||v.district)?directoryIdentity(v,true,m.identity):null,bank=directoryBank(v.bank);RM10.act(ten,'cleanup_save',{member:m.id,base:v.base,identity,mode:v.mode,bank:m.bank.approved?{bank:bank?.name||v.bank.trim(),holder:directoryTitle(v.holder),directoryBankId:bank?.id}:null});}
 save10();closeModal();render();toast(T('Perubahan tersimpan.','Changes saved.'));
 }catch(err){if(kind==='bonus')saveError119(f,err);else toast(error10(err.message));}},true);
window.addEventListener('change',e=>{if(e.target.matches('[data-pending-filter]')){pendingUI.filter=e.target.value;render();}});
const pendingRenderBase=render;
render=function(){pendingInit();pendingRenderBase();document.querySelectorAll('[data-ten=config],.ten-config').forEach(x=>x.remove());if(ten.role==='super'){
 const anchor=document.querySelector('.side-scroll');anchor?.insertAdjacentHTML('beforeend',`<button class="side-link" data-pending="cleanup-page">${icon('shield')}<span>${T('Penyesuaian Data Label','Label Data Updates')}</span></button>`);
 if(ten.role==='super'&&state.page==='dashboard'&&state.mode==='platform'){const insight=document.querySelector('.insight7');if(insight&&(ten.achievementNews.length||ten.bonuses.some(b=>b.status==='claimed')))insight.innerHTML=newsPending();}
 }document.querySelectorAll('.payout-card-ui h3').forEach(h=>h.textContent=directoryBankDisplay(h.textContent));};
