/* Plans and templates link to the existing release, never to a second submission or debit. */
(function(root){
 'use strict';
 const DAY=86400000,copy=x=>JSON.parse(JSON.stringify(x)),fail=m=>{throw Error(m)},object=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
 const init=s=>s.planning121??={schema:1,version:0,items:[],templates:[],legacy:[],history:[]};
 const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
 const validAt=v=>typeof v==='string'&&Number.isFinite(Date.parse(v));
 function validate(s){return object(s)&&s.schema===1&&Number.isSafeInteger(s.version)&&s.version>=0&&['items','templates','legacy','history'].every(k=>Array.isArray(s[k])&&s[k].every(object))&&s.items.every(x=>typeof x.id==='string'&&typeof x.member==='string'&&typeof x.release==='string'&&validDate(x.target)&&Array.isArray(x.tasks)&&x.tasks.every(t=>typeof t.id==='string'&&typeof t.done==='boolean'&&validDate(t.date)))&&s.templates.every(x=>typeof x.member==='string'&&typeof x.name==='string'&&object(x.patch))&&s.legacy.every(x=>typeof x.member==='string'&&validAt(x.firstLoginAt)&&validAt(x.deadline));}
 const tier=(s,m)=>root.Packages122?root.Packages122.tier(s,m):m?.previewPlan121||m?.plan||'Basic';
 function writable(s,actor,campaign=false){const m=s.members.find(x=>x.id===actor?.member);if(actor?.role!=='label'||!m)fail('Hanya pemilik label dapat mengubah rencana ini.');const plan=tier(s,m);if(!(root.Packages122?root.Packages122.capability(s,m,campaign?'campaign':'planning'):(campaign?['Pro','Business']:['Studio','Pro','Business']).includes(plan)))fail(campaign?'Kampanye tersedia pada pratinjau Pro.':'Rencana tersedia pada pratinjau Studio dan Pro.');return m;}
 function own(s,actor,id){const r=s.releases.find(r=>r.id===id&&r.member===actor.member&&r.flow105);if(!r)fail('Rilisan tidak tersedia untuk label ini.');return r;}
 function save(s,actor,p,at){
  const m=writable(s,actor),model=init(s);if(p.version!==model.version)fail('Rencana berubah. Buka kembali data terbaru.');own(s,actor,p.release);
  if(!validDate(p.target)||typeof p.note!=='string'||p.note.length>2000||!Array.isArray(p.tasks)||p.tasks.length!==5||new Set(p.tasks.map(t=>t.id)).size!==5||p.tasks.some(t=>!['metadata','audio','artwork','promo','submission'].includes(t.id)||typeof t.done!=='boolean'||!validDate(t.date)||t.date>p.target))fail('Periksa tanggal rencana dan tahapan sebelum tanggal rilis.');
  let item=model.items.find(x=>x.release===p.release);if(item&&item.member!==m.id)fail('Pemilik rencana tidak cocok.');if(!item){item={id:'PLAN-'+(model.items.length+1),member:m.id,release:p.release,created:new Date(at).toISOString()};model.items.push(item)}Object.assign(item,{target:p.target,note:p.note.trim(),tasks:copy(p.tasks),updated:new Date(at).toISOString()});model.history.push({action:'plan-save',ref:item.id,member:m.id,at:item.updated});model.version++;return item.id;
 }
 function saveCampaign(s,actor,p,at){writable(s,actor,true);const model=init(s);if(p.version!==model.version)fail('Kampanye berubah. Buka kembali data terbaru.');const r=own(s,actor,p.release),item=model.items.find(x=>x.release===r.id&&x.member===actor.member);if(!item)fail('Simpan rencana rilisan terlebih dahulu.');if(typeof p.goal!=='string'||!p.goal.trim()||p.goal.length>1000||!validDate(p.publishDate))fail('Isi tujuan dan tanggal publikasi materi.');item.campaign={goal:p.goal.trim(),publishDate:p.publishDate,updated:new Date(at).toISOString()};model.history.push({action:'campaign-save',ref:item.id,member:actor.member,at:new Date(at).toISOString()});model.version++;return item.id;}
 function template(s,actor,p,at){writable(s,actor);const model=init(s);if(p.version!==model.version)fail('Template berubah. Buka kembali data terbaru.');const r=own(s,actor,p.release);if(!p.name?.trim()||p.name.length>80)fail('Isi nama template maksimal 80 karakter.');const patch={};for(const k of ['genre','subgenre','year','copyright','master'])patch[k]=copy(r[k]??'');const id='TPL-'+(model.templates.length+1);model.templates.push({id,member:actor.member,name:p.name.trim(),patch,at:new Date(at).toISOString()});model.version++;return id;}
 function templatePatch(s,actor,id){writable(s,actor);const t=init(s).templates.find(t=>t.id===id&&t.member===actor.member);if(!t)fail('Template tidak tersedia.');const patch={};for(const k of ['genre','subgenre','year','copyright','master'])if(k in t.patch)patch[k]=copy(t.patch[k]);return patch;}
 function legacyStatus(s,m,at){const row=init(s).legacy.find(x=>x.member===m.id);return {legacy:!!m.source9&&m.active===true,complete:m.identity?.location?.complete===true,firstLoginAt:row?.firstLoginAt||null,deadline:row?.deadline||null,overdue:!!row&&!m.identity?.location?.complete&&Date.parse(row.deadline)<at};}
 function touchLegacy(s,actor,at){const m=s.members.find(m=>m.id===actor?.member);if(actor?.role!=='label'||!m||!m.source9||m.active!==true||m.identity?.location?.complete)return false;const model=init(s);if(model.legacy.some(x=>x.member===m.id))return false;const row={member:m.id,firstLoginAt:new Date(at).toISOString(),deadline:new Date(at+30*DAY).toISOString()};model.legacy.push(row);model.history.push({action:'legacy-first-login',member:m.id,at:row.firstLoginAt});model.version++;return true;}
 const api={init,validate,validDate,tier,save,saveCampaign,template,templatePatch,legacyStatus,touchLegacy};root.Planning121=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
