/* Working design revision. Build/release only after the user's explicit approval. */
function reviewMarkUI(kind='pending'){
 const paths=kind==='bank'?'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h4"/>':kind==='approved'?'<path d="m7 12 3 3 7-7"/><circle cx="12" cy="12" r="9"/>':'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>';
 return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths}</svg>`;
}
function reviewStatusUI(status){return T(...({pending:['Sedang diperiksa','Under review'],approved:['Disetujui','Approved'],correction:['Perlu perbaikan','Needs corrections'],withdrawn:['Dibatalkan','Withdrawn']})[status]||['Menunggu pemeriksaan','Awaiting review']);}
function reviewHeadingUI(m,status,subtitle){return `<header class="review-heading-ui"><span class="review-avatar-ui" aria-hidden="true">${E(m.name.slice(0,1).toUpperCase())}</span><div><h3>${E(m.name)}</h3><p>${E(subtitle||m.email)}</p></div><span class="review-status-ui ${E(status)}"><i></i>${reviewStatusUI(status)}</span></header>`;}
function reviewDialogUI(title,body){modal10(title,body);$('#dialog').classList.add('review-dialog-ui');}
const accountBeforeReviewUI=account10;
account10=function(){const html=accountBeforeReviewUI(),q=member10().profileChange103;if(!q||ui103.profileTab!=='identity')return html;
 const node=document.createElement('template');node.innerHTML=html;const old=node.content.querySelector('.profile-status103');if(!old)return html;
 if(q.status==='pending')old.outerHTML=`<div class="identity-pending-ui" role="status"><span class="pending-icon-ui">${reviewMarkUI()}</span><strong>${T('Perubahan identitas sedang diperiksa','Identity changes under review')}</strong><span class="pending-context-ui">${T('Profil saat ini tetap berlaku.','Your current profile remains active.')}</span>${button103(T('Lihat perubahan','View changes'),'review',member10().id)}</div>`;
 else if(q.status==='correction')old.outerHTML=`<div class="identity-correction-ui"><span class="pending-icon-ui">${reviewMarkUI()}</span><div><strong>${T('Perbaiki perubahan identitas','Correct identity changes')}</strong><p>${E(q.note)}</p></div>${button103(T('Perbaiki','Make corrections'),'edit-profile')}</div>`;
 return node.innerHTML;
};
function changedFieldsUI(q){return [['name','Nama label','Label name'],['email','Email','Email'],['person','Penanggung jawab','Representative']].filter(([k])=>q.before[k]!==q.after[k]);}
reviewProfile103=function(id){const m=RM10.getMember(ten,id),q=m?.profileChange103;if(!q||isLabel10()&&m.id!==ten.member)return;
 const fields=changedFieldsUI(q),staff=!isLabel10()&&q.status==='pending';
 reviewDialogUI(T('Perubahan identitas','Identity changes'),`${reviewHeadingUI(m,q.status,T('Diajukan ','Submitted ')+date10(q.at,true))}<section class="identity-diff-ui" aria-label="${T('Perbandingan perubahan','Change comparison')}">${fields.map(([key,a,b])=>`<article class="identity-diff-row-ui"><h4>${T(a,b)}</h4><div class="identity-diff-values-ui"><div><small>${T('Saat ini','Current')}</small><p>${E(q.before[key])}</p></div><span class="diff-arrow-ui" aria-hidden="true">→</span><div class="requested-value-ui"><small>${T('Diajukan','Requested')}</small><p>${E(q.after[key])}</p></div></div></article>`).join('')}</section>${staff?`<form data-form103="review" data-id="${m.id}" data-version="${q.version}" class="review-decision-ui"><label class="review-note103">${T('Catatan perbaikan','Correction note')}<textarea name="note" rows="2" placeholder="${T('Isi jika ada data yang perlu diperbaiki.','Complete this if any details need correction.')}"></textarea></label><footer class="review-footer-ui"><button type="submit" name="decision" value="correct" class="btn">${T('Minta perbaikan','Request corrections')}</button><button type="submit" name="decision" value="approve" class="btn primary">${T('Setujui perubahan','Approve changes')}</button></footer></form>`:`<p class="review-footnote-ui">${q.status==='pending'?T('Profil saat ini tetap digunakan sampai perubahan disetujui.','Your current profile stays in use until the changes are approved.'):q.status==='approved'?T('Perubahan sudah diterapkan pada profil label.','The changes have been applied to the label profile.'):E(q.note||'')}</p>`}`);
};
labels102=function(){if(isLabel10())return labelsBase103();const pending=ten.members.filter(m=>m.profileChange103?.status==='pending');return labelsBase103()+(pending.length?`<section class="panel approval-list-ui"><header><div><h2>${T('Perubahan identitas','Identity changes')}</h2><p>${T('Pengajuan yang perlu diperiksa','Requests awaiting review')}</p></div><span class="review-count-ui">${pending.length}</span></header>${pending.map(m=>`<article class="approval-row-ui"><span class="review-avatar-ui" aria-hidden="true">${E(m.name.slice(0,1))}</span><div><h3>${E(m.name)}</h3><p>${changedFieldsUI(m.profileChange103).map(([,a,b])=>T(a,b)).join(' · ')}<span> · ${date10(m.profileChange103.at)}</span></p></div>${button103(T('Periksa','Review'),'review',m.id)}</article>`).join('')}</section>`:'');};labelsPage9=labels102;

function payoutCardUI(account,status='approved'){
 const a=account||{},empty=!account;
 return `<article class="payout-card-ui ${empty?'empty-ui':''}" aria-label="${T('Rekening penerima','Payout account')}"><div class="payout-card-top-ui"><span>${T('Rekening penerima','Payout account')}</span>${reviewMarkUI('bank')}</div><h3>${E(directoryBankDisplay(a.bank)||T('Belum ada rekening','No bank account yet'))}</h3><div class="payout-number-ui"><small>${T('Nomor rekening','Account number')}</small><p>${empty?'••••  ••••  ••••':E(a.number)}</p></div><footer><div><small>${T('Pemilik rekening','Account holder')}</small><strong>${E(a.holder||'—')}</strong></div>${empty?'':`<span class="payout-state-ui"><i class="${E(status)}"></i>${status==='approved'?T('Rekening aktif','Active account'):reviewStatusUI(status)}</span>`}</footer></article>`;
}
bankForm10=function(m){const p=m.bank.pending||{},a=m.bank.approved,pending=p.status==='pending';
 return `<div class="payout-layout-ui"><aside>${payoutCardUI(a)}${a?`<p class="review-footnote-ui">${T('Digunakan untuk penerimaan royalti.','Used to receive royalty payments.')}</p>`:''}</aside><section class="payout-editor-ui"><header><h3>${pending?T('Pengajuan rekening','Account request'):p.status==='correction'?T('Perbaiki rekening','Correct account details'):a?T('Ganti rekening penerima','Change payout account'):T('Tambahkan rekening','Add an account')}</h3><p>${pending?T('Rekening yang diajukan sedang diperiksa.','The requested account is being reviewed.'):a?T('Rekening saat ini tetap digunakan sampai rekening baru disetujui.','Your current account stays in use until the new account is approved.'):T('Isi rekening untuk menerima pembayaran royalti.','Enter an account to receive royalty payments.')}</p></header>${pending?`<dl class="payout-proposal-ui">${[[T('Bank','Bank'),directoryBankDisplay(p.bank)],[T('Nomor rekening','Account number'),p.number],[T('Pemilik rekening','Account holder'),p.holder]].map(([label,value])=>`<div><dt>${label}</dt><dd>${E(value)}</dd></div>`).join('')}</dl><span class="review-status-ui pending"><i></i>${reviewStatusUI('pending')}</span>`:`${p.status==='correction'?`<div class="payout-correction-ui">${E(p.note)}</div>`:''}${form10('bank',directoryBankField(p.bank||'')+field10('number',T('Nomor rekening','Account number'),p.number||'','text','required inputmode="numeric" pattern="[0-9]{6,24}"')+field10('holder',T('Nama pemilik rekening','Account holder'),p.holder||m.identity.person,'text','required'))}`}</section></div>`;
};
identityModal10=function(id){const m=RM10.getMember(ten,id);if(ten.role==='label'||!m.application)return;const q=m.application,i=q.snapshot;
 reviewDialogUI(T('Pemeriksaan aktivasi','Activation review'),`${reviewHeadingUI(m,q.status)}<dl class="review-facts-ui">${[[T('Penanggung jawab','Representative'),i.person],[T('Lokasi','Location'),[i.address,i.postal,i.country].filter(Boolean).join(' · ')],[T('Dokumen identitas','Identity document'),i.document?T('Tersedia','Available'):T('Belum dilengkapi','Not provided')]].map(([label,value])=>`<div><dt>${label}</dt><dd>${E(value)}</dd></div>`).join('')}</dl><details class="review-document-ui"><summary>${T('Lihat identitas yang diajukan','View submitted identity')}</summary>${identityRead10(i)}</details><div class="review-checks-ui"><span>${reviewMarkUI('approved')}${T('Pembayaran terkonfirmasi','Payment confirmed')}</span><span>${reviewMarkUI('approved')}${T('Kontrak disetujui','Contract accepted')}</span></div><form class="ten-form review-decision-ui" data-ten-form="identity_correct" data-id="${m.id}"><input type="hidden" name="version" value="${q.version}">${correctionSelectUI('note',T('Bagian yang perlu diperbaiki','What needs correction'),[[T('Foto identitas belum terbaca. Unggah foto yang lebih jelas.','The identity photo is unreadable. Upload a clearer image.'),T('Foto tidak terbaca','Unreadable photo')],[T('Lokasi belum lengkap. Periksa kembali wilayah yang dipilih.','The location is incomplete. Check the selected area.'),T('Lokasi belum lengkap','Incomplete location')],[T('Nama penanggung jawab tidak sesuai dokumen. Periksa kembali.','The representative name does not match. Please check it.'),T('Nama tidak sesuai','Name mismatch')]],'')}<footer class="review-footer-ui full"><button type="submit" class="btn">${T('Minta perbaikan','Request corrections')}</button>${b10(T('Setujui Aktivasi','Approve activation'),'identity_approve',id+'|'+q.version,'primary')}</footer></form>`);
};
bankModal10=function(id){if(ten.role!=='super')return;const m=RM10.getMember(ten,id),p=m.bank.pending;if(!p)return;
 reviewDialogUI(T('Pemeriksaan rekening','Bank review'),`${reviewHeadingUI(m,p.status)}${payoutCardUI(p,p.status)}<details class="review-document-ui"><summary>${T('Lihat identitas label','View label identity')}</summary>${identityRead10(m.identity)}</details><dl class="review-facts-ui"><div><dt>${T('Penanggung jawab label','Label representative')}</dt><dd>${E(m.identity.person)}</dd></div>${m.bank.approved?`<div><dt>${T('Rekening saat ini','Current account')}</dt><dd>${E(directoryBankDisplay(m.bank.approved.bank))} · ${E(m.bank.approved.number)}</dd></div>`:''}</dl><form class="ten-form review-decision-ui" data-ten-form="bank_correct" data-id="${m.id}"><input type="hidden" name="version" value="${p.version}">${correctionSelectUI('note',T('Bagian yang perlu diperbaiki','What needs correction'),[[T('Periksa kembali bank dan nomor rekening yang diajukan.','Check the submitted bank and account number.'),T('Bank atau nomor rekening salah','Incorrect bank or account number')],[T('Nama penerima tidak sesuai. Periksa nama pemilik rekening.','Check the account holder name.'),T('Nama penerima tidak sesuai','Recipient mismatch')],[T('Jelaskan hubungan penerima dengan penanggung jawab label.','Explain the recipient relationship to the label representative.'),T('Hubungan penerima perlu dijelaskan','Explain recipient relationship')]],'')}<footer class="review-footer-ui full"><button class="btn" type="submit">${T('Minta perbaikan','Request corrections')}</button>${b10(T('Setujui rekening','Approve account'),'bank_approve',id+'|'+p.version,'primary')}</footer></form>`);
};
function correctionSelectUI(name,label,options){return '<label>'+label+'<select name="'+name+'" required><option value="">'+T('Pilih bagian yang perlu diperbaiki','Choose what needs correction')+'</option>'+options.map(([v,l])=>'<option value="'+E(v)+'">'+E(l)+'</option>').join('')+'</select></label>';}
const bankReviewBaseUI=bankModal10;
bankModal10=function(id){bankReviewBaseUI(id);const m=RM10.getMember(ten,id),f=document.querySelector('[data-ten-form=bank_correct]');if(!f||!m)return;const token=RM10.pending.fingerprint(m);f.insertAdjacentHTML('afterbegin','<input type="hidden" name="identityReview" value="'+E(token)+'">');f.querySelector('[data-ten=bank_approve]').dataset.identityReview=token;};
render();
