/* Validate before any application module reads persisted data. Never seed over invalid data. */
(function(root){
 'use strict';
 const journeyKey='rm-v11-1-journey',sharedKey='rm-v11-1-shared',backupKey='rm-v11-7-last-good';
 const object=v=>v&&typeof v==='object'&&!Array.isArray(v),arrays=(v,keys)=>keys.every(k=>Array.isArray(v[k])),records=(v,keys)=>arrays(v,keys)&&keys.every(k=>v[k].every(object));
 function safeKeys(v,seen=new WeakSet()){if(!v||typeof v!=='object'||seen.has(v))return true;seen.add(v);return Object.entries(v).every(([key,value])=>!['__proto__','prototype','constructor'].includes(key)&&safeKeys(value,seen));}
 function optionalModels(v){
  for(const key of ['staffRuntime114','staff114','commerce113','royalty107','addons111','wami11','tickets112','credit11','system115','planning121','monitor121','packages122'])if(key in v&&!object(v[key]))return false;
  if(v.packages122){const p=v.packages122,n=x=>x===null||Number.isSafeInteger(x)&&x>=0&&x<=100000000,at=x=>x===null||typeof x==='string'&&Number.isFinite(Date.parse(x));if(p.schema!==1||!Number.isSafeInteger(p.version)||p.version<1||!records(p,['plans','subscriptions','usage','history'])||p.plans.length!==4||new Set(p.plans.map(x=>x.id)).size!==4||!p.plans.every(x=>['Basic','Studio','Pro','Business'].includes(x.id)&&typeof x.name==='string'&&n(x.monthly)&&n(x.annual)&&n(x.wami)&&n(x.design)&&Array.isArray(x.colors)&&x.colors.length===2&&x.colors.every(c=>/^#[0-9a-f]{6}$/i.test(c)))||!p.subscriptions.every(x=>typeof x.member==='string'&&typeof x.order==='string'&&['Basic','Studio','Pro','Business'].includes(x.plan)&&object(x.quote)&&object(x.quote.benefits)&&['active','activation','scheduled','replaced'].includes(x.status)&&at(x.start)&&at(x.end)&&at(x.anchor))||!p.usage.every(x=>typeof x.member==='string'&&typeof x.order==='string'&&['wami','design'].includes(x.kind)&&Number.isSafeInteger(x.quantity)&&x.quantity>0&&['reserved','used','restored'].includes(x.status)))return false;}
  const at121=x=>typeof x==='string'&&Number.isFinite(Date.parse(x));
  const date121=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x+'T12:00Z'))&&new Date(x+'T12:00Z').toISOString().slice(0,10)===x;
  if(v.monitor121&&(v.monitor121.schema!==1||!Number.isSafeInteger(v.monitor121.version)||v.monitor121.version<0||!records(v.monitor121,['cash','history'])||!v.monitor121.cash.every(x=>typeof x.id==='string'&&Number.isSafeInteger(x.amount)&&x.amount>=0&&at121(x.asof)&&typeof x.scope==='string'&&typeof x.note==='string')))return false;
  if(v.planning121&&(v.planning121.schema!==1||!Number.isSafeInteger(v.planning121.version)||v.planning121.version<0||!records(v.planning121,['items','templates','legacy','history'])||!v.planning121.items.every(x=>typeof x.id==='string'&&typeof x.member==='string'&&typeof x.release==='string'&&date121(x.target)&&records(x,['tasks'])&&x.tasks.every(t=>typeof t.id==='string'&&typeof t.done==='boolean'&&date121(t.date)))||!v.planning121.templates.every(x=>typeof x.member==='string'&&typeof x.name==='string'&&object(x.patch))||!v.planning121.legacy.every(x=>typeof x.member==='string'&&at121(x.firstLoginAt)&&at121(x.deadline))))return false;
  if(v.staffRuntime114&&(!object(v.staffRuntime114)||!object(v.staffRuntime114.profiles)||!object(v.staffRuntime114.assignments)||!records(v.staffRuntime114,['roles','tasks','ops'])))return false;
  if(v.staff114&&(v.staff114.schema!==1||!records(v.staff114,['users','roles','audit','notifications','handoffs'])||!v.staff114.users.length||!v.staff114.users.every(u=>typeof u.id==='string'&&typeof u.name==='string'&&typeof u.email==='string'&&['active','inactive','disabled','invited'].includes(u.status)&&typeof u.super==='boolean')))return false;
  if(v.commerce113&&(!records(v.commerce113,['orders','provider','refunds','notifications'])||!v.commerce113.orders.every(o=>typeof o.id==='string'&&records(o,['attempts','history'])&&o.attempts.length)))return false;
  if(v.royalty107&&(v.royalty107.schema!==1||!records(v.royalty107,['batches','ledger','receipts','history','corrections','cases'])||!v.royalty107.batches.every(b=>records(b,['rows'])&&Array.isArray(b.posted))||!v.royalty107.receipts.every(r=>records(r,['allocations']))))return false;
  if(v.addons111&&!records(v.addons111,['catalogue','orders','history']))return false;
  if(v.wami11&&!records(v.wami11,['orders','notifications']))return false;
  if(v.tickets112&&!records(v.tickets112,['tickets','drafts','notifications']))return false;
  if(v.credit11&&(!records(v.credit11,['versions','history'])||!v.credit11.versions.length||!v.credit11.versions.every(x=>object(x.rules)&&object(x.rules.cost))))return false;
  if(v.system115&&(v.system115.schema!==1||!object(v.system115.areas)||!records(v.system115,['audit'])||!['content','navigation','procedures'].every(k=>object(v.system115.areas[k])&&object(v.system115.areas[k].published)&&Array.isArray(v.system115.areas[k].history))))return false;
  return true;
 }
 function staff118(v){return v===undefined||object(v)&&v.schema===1&&object(v.compensation)&&records(v,['policies','migrations'])&&Object.values(v.compensation).every(a=>Array.isArray(a)&&a.length&&a.every(x=>object(x)&&typeof x.id==='string'&&typeof x.effective==='string'&&Number.isSafeInteger(x.sequence)&&Number.isSafeInteger(x.salary)&&x.salary>=0&&Number.isSafeInteger(x.allowance)&&x.allowance>=0&&Number.isFinite(x.percent)&&x.percent>=0&&x.percent<=100))&&v.policies.every(x=>object(x.policy)&&Array.isArray(x.policy.days)&&typeof x.effective==='string'&&Number.isSafeInteger(x.sequence));}
 function shared(v){return object(v)&&safeKeys(v)&&object(v.data)&&staff118(v.data.staff118)&&records(v,['profiles','contributions','rules','ruleHistory','requests','grants'])&&object(v.archives)&&records(v.data,['roles','tasks','history','events','leaves','notifications','issues','corrections','logs'])&&Array.isArray(v.data.holidays)&&['profiles','assignments','policy','chats','timeRecords'].every(k=>object(v.data[k]))&&Object.values(v.data.profiles).every(object)&&records(v.data.chats,['label','internal'])&&Array.isArray(v.data.policy.days)&&['workRules','ops','slips','todayDone'].every(k=>v.data[k]===undefined||Array.isArray(v.data[k])&&v.data[k].every(object))&&v.profiles.every(p=>typeof p.id==='string');}
 function journey(v){return object(v)&&safeKeys(v)&&v.schema===1&&Number.isFinite(v.now)&&['label','admin','super'].includes(v.role)&&typeof v.member==='string'&&records(v,['members','releases','events','notifications'])&&v.members.length>0&&v.members.some(m=>m.id===v.member)&&v.members.every(m=>typeof m.id==='string'&&typeof m.name==='string'&&records(m,['lots'])&&object(m.identity)&&object(m.bank))&&(!('storageRevision116'in v)||Number.isSafeInteger(v.storageRevision116)&&v.storageRevision116>=0)&&(!('legacyShared117'in v)||shared(v.legacyShared117))&&optionalModels(v);}
 const api=root.Persistence117={journeyKey,sharedKey,backupKey,blocked:false,problems:[],raw:{},journey:null,shared:null,validateJourney:journey,validateShared:shared};
 const interval117=root.setInterval.bind(root);root.setInterval=(fn,delay,...args)=>interval117(()=>{if(!api.blocked)fn(...args)},delay);
 for(const [key,validate,field]of [[journeyKey,journey,'journey'],[sharedKey,shared,'shared']]){try{const raw=localStorage.getItem(key);api.raw[key]=raw;if(raw!==null){let value;try{value=JSON.parse(raw)}catch{}if(!validate(value)){api.blocked=true;api.problems.push({key,reason:value?.schema&&value.schema!==1?'version':'structure'});}else api[field]=value;}}catch{api.blocked=true;api.problems.push({key,reason:'unavailable'});}}
 // Keep the original keys untouched; quarantine is supplementary, never a replacement.
 if(api.blocked){const envelope=JSON.stringify({format:'rm-recovery-117',capturedAt:new Date().toISOString(),sources:api.raw,problems:api.problems});try{const existing=Object.keys(localStorage).filter(k=>k.startsWith('rm-v11-7-quarantine-')).find(k=>{try{return JSON.stringify(JSON.parse(localStorage.getItem(k)).sources)===JSON.stringify(api.raw)}catch{return false}});const key=existing||'rm-v11-7-quarantine-'+Date.now();if(!existing)localStorage.setItem(key,envelope);api.quarantine=key;}catch{}document.documentElement.classList.add('recovery117');document.getElementById('app').setAttribute('inert','');}
 api.error=()=>Object.assign(Error('Data tersimpan perlu dipulihkan sebelum perubahan dapat disimpan.'),{code:'recovery_required'});
 api.readBackup=()=>{try{const value=JSON.parse(localStorage.getItem(backupKey));return journey(value)?value:null}catch{return null}};
 api.replace=value=>{if(!journey(value)||!value.legacyShared117||!shared(value.legacyShared117))throw Error('Berkas pemulihan belum lengkap atau berasal dari versi yang tidak didukung.');const raw=JSON.stringify(value);localStorage.setItem(journeyKey,raw);api.repaired=true;location.reload();};
 // A valid canonical snapshot contains all legacy data. Old shared data stays read-only.
 if(api.journey?.legacyShared117&&!api.problems.some(p=>p.key===journeyKey)){api.shared=api.journey.legacyShared117;api.problems=api.problems.filter(p=>p.key!==sharedKey);api.blocked=api.problems.length>0;if(!api.blocked){document.documentElement.classList.remove('recovery117');document.getElementById('app').removeAttribute('inert');}}
})(window);
