(function(root){'use strict';
const cp=x=>JSON.parse(JSON.stringify(x)),ok=(x,m)=>{if(!x)throw Error(m)},areas=['content','navigation','procedures','maintenance'];
function seed(values){return {schema:1,serial:0,revision:1,areas:Object.fromEntries(areas.map(k=>[k,{version:1,published:cp(values[k]),draft:null,draftVersion:0,base:1,history:[]}])) ,audit:[],notified:[]}}
function area(s,k){ok(areas.includes(k),'Bagian konfigurasi tidak dikenal.');return s.areas[k]}
function guard(a){ok(a?.super&&!a.preview,'Pengaturan Sistem khusus Super Admin. Pratinjau tidak dapat melakukan perubahan.')}
function changed(a,b,path=''){if(JSON.stringify(a)===JSON.stringify(b))return [];if(Array.isArray(a)&&Array.isArray(b)&&[...a,...b].length&&[...a,...b].every(x=>x&&typeof x==='object'&&x.id)){const order=a.map(x=>x.id).join('|')!==b.map(x=>x.id).join('|')?[{field:path+'.order',before:a.map(x=>x.name||x.title||x.id),after:b.map(x=>x.name||x.title||x.id)}]:[];return [...order,...new Set([...a,...b].map(x=>x.id))].flatMap(x=>typeof x==='object'?[x]:changed(a.find(y=>y.id===x),b.find(y=>y.id===x),path+'.'+x));}if(!a||!b||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)||Array.isArray(b))return [{field:path,before:cp(a??null),after:cp(b??null)}];return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>changed(a[k],b[k],path?path+'.'+k:k))}
function safe(x,key=''){if(/password|secret|token|document(image|pending)?|signature|stamp|ktp|imageurl|storagekey|attachment|cover|audio/i.test(key))return '[Data dilindungi]';if(/^(number|nik|accountnumber|banknumber)$/i.test(key))return '[Nomor dilindungi]';if(typeof x==='string'&&x.startsWith('data:'))return '[Berkas]';if(Array.isArray(x))return x.map(v=>safe(v));if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,safe(v,k)]));return x??null}
function log(s,a,kind,target,before,after,note,at){const e={id:'SYS-'+(++s.serial),actor:a.id,kind,target,before:safe(before),after:safe(after),note:note||'',at};s.audit.unshift(e);s.revision++;return e}
function url(v){if(!v)return;ok(/^(https:\/\/|mailto:|tel:|\/|#)/i.test(v),'Gunakan tautan HTTPS, kontak, atau tujuan dalam website.');ok(!/[<>\s]/.test(v),'Tautan tidak valid.')}
function validate(k,v){if(k==='content'){ok(v.blocks&&Object.keys(v.blocks).length,'Konten belum tersedia.');for(const b of Object.values(v.blocks)){ok(b.title?.trim()&&b.title.length<=160,'Judul bagian wajib diisi, maksimal 160 karakter.');ok((b.text||'').length<=5000,'Teks terlalu panjang.');url(b.link);ok(!b.image||/^data:image\/(png|jpeg|webp);base64,/.test(b.image),'Gambar harus PNG, JPG, atau WebP.');if(b.image)ok(b.image.length<2800000,'Gambar maksimal 2 MB.');for(const i of b.items||[])ok(i.title?.trim()&&i.title.length<=160,'Judul setiap item wajib diisi.');}ok(v.company?.name?.trim(),'Nama badan usaha wajib diisi.');ok(!v.company.email||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.company.email),'Email kontak tidak valid.');}
if(k==='navigation'){for(const [target,n] of Object.entries(v.targets)){const ids=n.items.map(x=>x.id);ok(new Set(ids).size===ids.length,'Menu duplikat.');const groups=n.groups.map(g=>g.id);ok(new Set(groups).size===groups.length&&n.groups.every(g=>g.id&&g.id!=='__proto__'&&g.name?.trim()&&g.en?.trim()),'Nama kelompok ID dan EN wajib diisi.');for(const x of n.items){ok(x.name?.trim()&&x.en?.trim(),'Nama menu ID dan EN wajib diisi.');ok(!x.protected||x.visible&&!x.parent,'Dashboard dan menu pengelolaan wajib tetap terlihat pada tingkat utama.');ok(!x.group||groups.includes(x.group),'Kelompok tujuan tidak tersedia.');ok(!x.parent||ids.includes(x.parent),'Menu induk tidak tersedia.');if(x.parent){const p=n.items.find(y=>y.id===x.parent);ok(!p.parent&&p.id!==x.id&&!p.protected,'Submenu hanya satu tingkat dan tidak boleh berputar.');ok(!x.visible||p.visible,'Pindahkan atau sembunyikan submenu sebelum menyembunyikan induk.');ok(!n.items.some(y=>y.parent===x.id),'Menu yang memiliki anak tidak dapat menjadi submenu.');}}}}
if(k==='procedures'){const c=v.calendar;ok(c.days?.length&&c.days.every(d=>Number.isInteger(d)&&d>=0&&d<=6),'Pilih hari kerja yang valid.');ok(/^\d{2}:\d{2}$/.test(c.start)&&/^\d{2}:\d{2}$/.test(c.end)&&c.start<c.end&&c.end<='23:59','Jam operasional tidak valid.');ok((c.holidays||[]).every(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d))),'Tanggal libur tidak valid.');for(const r of v.rules)if(r.mode!=='monthly'&&r.mode!=='nextday')ok(Number.isInteger(r.value)&&r.value>=1&&r.value<=720,'Batas waktu harus 1–720.');const w=v.wami;for(const x of Object.values(w))ok(Number.isInteger(x)&&x>0&&x<=720,'Waktu WAMI harus 1–720.');ok(w.queueWarn<w.queueDue&&w.workWarn<w.workDue&&w.labelWarn<w.labelSecond&&w.labelSecond<w.labelDue,'Pengingat harus meningkat sebelum batas tindak lanjut.');ok(Number.isInteger(v.ticketDays)&&v.ticketDays>0&&v.ticketDays<=90,'Tindak lanjut tiket harus 1–90 hari kerja.');ok(Number.isInteger(v.revisionHours)&&v.revisionHours>0&&v.revisionHours<=720,'Waktu perbaikan rilisan tidak valid.');}
if(k==='maintenance'){ok(Array.isArray(v?.windows),'Jadwal pemeliharaan tidak tersedia.');const ids=v.windows.map(w=>w.id);ok(new Set(ids).size===ids.length,'ID jadwal pemeliharaan duplikat.');for(const w of v.windows){ok(typeof w.id==='string'&&w.id.length<=40,'ID jadwal tidak valid.');ok(typeof w.title==='string'&&w.title.trim().length>=3&&w.title.length<=160,'Judul pemeliharaan wajib 3–160 karakter.');ok(['scheduled','emergency'].includes(w.kind),'Jenis pemeliharaan tidak dikenal.');ok(['info','readonly'].includes(w.mode),'Mode pemeliharaan tidak dikenal.');ok(['scheduled','active','completed','cancelled'].includes(w.status),'Status pemeliharaan tidak dikenal.');const s=Date.parse(w.startAt),e=Date.parse(w.endAt);ok(Number.isFinite(s)&&Number.isFinite(e)&&s<e,'Rentang waktu pemeliharaan tidak valid — selesai harus setelah mulai.');ok(Array.isArray(w.modules)&&w.modules.length&&w.modules.every(m=>['all','releases','payments','royalty','tickets','wami','addons','account'].includes(m)),'Pilih minimal satu modul terdampak.');ok(typeof w.message==='string'&&w.message.trim().length>=3&&w.message.length<=1000,'Pesan pemeliharaan wajib 3–1000 karakter.');ok(typeof w.note==='string'&&w.note.length<=1000,'Catatan internal terlalu panjang.');ok(['none','start','1h','24h'].includes(w.notify),'Pengingat pengumuman tidak dikenal.');}}}
function catalogue(r,k,v){if(k==='navigation'){ok(JSON.stringify(Object.keys(v.targets).sort())===JSON.stringify(Object.keys(r.published.targets).sort()),'Jenis akun tidak boleh diganti melalui Navigasi.');for(const [id,n]of Object.entries(v.targets)){const old=r.published.targets[id].items;ok(n.items.length===old.length,'Navigasi hanya menggunakan menu yang sudah tersedia.');for(const x of n.items){const o=old.find(o=>o.id===x.id);ok(o&&o.action===x.action&&o.dest===x.dest&&o.protected===x.protected,'Tujuan menu dan perlindungan akses tidak dapat diganti.');ok(['grid','people','release','wallet','music','shield','spark','support','settings','clock','activity','menu'].includes(x.icon),'Pilih ikon dari daftar standar.');}}}if(k==='procedures'){ok(v.rules.length===r.published.rules.length,'Daftar prosedur harus mengikuti alur yang tersedia.');for(const x of v.rules){const o=r.published.rules.find(o=>o.id===x.id);ok(o&&o.mode===x.mode,'Dasar waktu mengikuti jenis tahap.');if(['monthly','nextday'].includes(o.mode))ok(x.value===o.value&&x.end===o.end&&x.immediate===o.immediate,'Periode tetap dan pergantian tanggal dipertahankan.');}}}
function act(s,a,k,p,at){guard(a);const r=area(s,p.area);ok(p.version===r.version&&p.draftVersion===r.draftVersion,'Pengaturan telah berubah. Muat versi terbaru dan tinjau ulang.');if(k==='save'){validate(p.area,p.value);catalogue(r,p.area,p.value);const before=r.draft;r.draft=cp(p.value);r.base=r.version;r.draftVersion++;log(s,a,'draft-save',p.area,before,r.draft,p.note,at);return r}
if(k==='discard'){ok(r.draft,'Tidak ada draf.');log(s,a,'draft-discard',p.area,r.draft,null,p.note,at);r.draft=null;r.draftVersion++;return r}
if(k==='restore'){const h=r.history.find(h=>h.id===p.id);ok(h,'Versi tidak tersedia.');r.draft=cp(h.value);r.base=r.version;r.draftVersion++;log(s,a,'draft-restore',p.area,null,{source:h.id,value:r.draft},p.note,at);return r}
ok(k==='publish'&&r.draft,'Simpan draf sebelum menerapkan.');ok(r.base===r.version,'Draf dibuat dari versi lama. Tinjau ulang.');ok(p.note?.trim(),'Tuliskan catatan penerapan.');let next=cp(r.draft);if(p.area==='content'&&p.blocks){ok(p.blocks.length,'Pilih bagian yang akan dipublikasikan.');next=cp(r.published);for(const id of p.blocks){if(id==='company')next.company=cp(r.draft.company);else{ok(r.draft.blocks[id],'Bagian tidak tersedia.');next.blocks[id]=cp(r.draft.blocks[id]);}}}
validate(p.area,next);catalogue(r,p.area,next);const diff=changed(r.published,next);ok(diff.length,'Belum ada perubahan untuk diterapkan.');if(p.area==='procedures'&&p.ongoing)ok(p.confirmed&&p.impactToken,'Tinjau dan setujui perubahan tenggat pekerjaan berjalan.');const before=cp(r.published);r.history.unshift({id:'VER-'+(++s.serial),version:r.version,value:before,at:r.appliedAt||at,actor:r.actor||null,note:r.note||'Versi awal'});r.published=next;r.version++;r.appliedAt=at;r.actor=a.id;r.note=p.note.trim();r.draftVersion++;r.base=r.version;if(p.area==='content'&&JSON.stringify(next)!==JSON.stringify(r.draft))r.draft=cp(r.draft);else r.draft=null;return log(s,a,'publish',p.area,before,next,p.note,at)}
function reminder(s,key){if(s.notified.includes(key))return false;s.notified.push(key);return true}
const api={seed,area,act,validate,changed,safe,cp,log,reminder};root.System115=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
