(function(root){'use strict';
const cp=x=>JSON.parse(JSON.stringify(x)),ok=(x,msg)=>{if(!x)throw Error(msg)},categories=['metadata','audio','cover','takedown','cid','release-claim','disable-cid','availability','royalty-issue','general'];
const fields={release:['title','genre','subgenre','year','copyright','master','primary','featured'],track:['title','language','lyricLanguage','lyrics','composer','lyricist','arranger','producer','featured','explicit']};
function init(s){return s.tickets112??={serial:0,tickets:[],drafts:[],notifications:[],notified:[]}}
function catalogue(r){return {id:r.id,member:r.member,title:r.title,artist:r.artist||'',upc:r.upc||'',type:r.type,cover:cp(r.cover||null),release:Object.fromEntries(fields.release.map(k=>[k,cp(r[k]??(k==='primary'||k==='featured'?[]:''))])),songs:(r.songs||[]).map((t,i)=>({id:t.id,title:t.title||'',number:i+1,isrc:t.isrc||'',audio:cp(t.audio||null),preview:t.preview||0,metadata:Object.fromEntries(fields.track.map(k=>[k,cp(t[k]??(['composer','lyricist','arranger','producer','featured'].includes(k)?[]:k==='explicit'?false:''))]))}))};}
function visible(a,t){return a.role!=='label'||t.account===a.member}
function item(id,label,extra={}){return {id,label,status:'pending',...cp(extra)}}
function video(url){let u;try{u=new URL(url)}catch{throw Error('Gunakan tautan video YouTube yang lengkap.')}ok(u.protocol==='https:'&&!u.username&&!u.password,'Gunakan tautan HTTPS tanpa informasi login.');let id;if(u.hostname==='youtu.be')id=u.pathname.slice(1);else if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||(/^\/(shorts|embed)\/([^/]+)$/.exec(u.pathname)||[])[2];ok(/^[\w-]{11}$/.test(id||''),'Tautan harus menuju satu video YouTube.');return 'https://www.youtube.com/watch?v='+id;}
function diffs(snap,p){const out=[];for(const ch of p.changes||[]){ok(['release','track'].includes(ch.scope),'Bagian metadata tidak dikenal.');ok(fields[ch.scope].includes(ch.field),'Kolom ini tidak dapat diganti melalui Perubahan Metadata.');const source=ch.scope==='release'?snap.release:snap.songs.find(t=>t.id===ch.track)?.metadata;ok(source,'Lagu tidak ditemukan.');const value=cp(ch.value),arrays=['primary','featured','composer','lyricist','arranger','producer'];if(arrays.includes(ch.field)){ok(Array.isArray(value)&&value.every(v=>typeof v==='string'?!!v.trim():v&&typeof v.name==='string'&&!!v.name.trim()),'Nama artis atau pencipta tidak valid.');if(ch.field==='primary'||ch.field==='composer')ok(value.length,'Artis utama dan komposer harus terisi.');}else if(ch.field==='explicit')ok(typeof value==='boolean','Pilih status konten eksplisit.');else if(ch.field==='year')ok(Number.isInteger(value)&&value>=1900&&value<=new Date().getFullYear()+1,'Tahun tidak valid.');else {ok(typeof value==='string','Isian metadata tidak valid.');if(['title','genre','copyright','master','language'].includes(ch.field))ok(value.trim(),'Kolom wajib tidak boleh dikosongkan.');}if(JSON.stringify(source[ch.field])!==JSON.stringify(value))out.push(item([ch.scope,ch.track||'',ch.field].join(':'),ch.label||ch.field,{scope:ch.scope,track:ch.track||'',field:ch.field,before:cp(source[ch.field]),after:value}));}ok(new Set(out.map(i=>i.id)).size===out.length,'Kolom perubahan duplikat.');ok(out.length,'Belum ada perubahan metadata.');return out;}
function accountSnap112(a){return {id:'account:'+a.member,member:a.member,title:'Permintaan umum',artist:'',cover:null,release:{},songs:[]};}
function build(s,a,p){
 if(['royalty-issue','general'].includes(p.category)){
  let snap;
  if(p.release){const r0=s.releases.find(r=>r.id===p.release);ok(r0&&a.scope.includes(r0.member),'Rilisan berada di luar akunmu.');ok(['delivered','followup','partial','partial_closed','live','taken_down'].includes(r0.status),'Gunakan alur pada status rilisan saat ini.');snap=catalogue(r0);ok(JSON.stringify(snap)===JSON.stringify(p.source),'Data katalog berubah. Tinjau ulang data sebelum mengajukan.');}
  else{snap=accountSnap112(a);ok(JSON.stringify(snap)===JSON.stringify(p.source),'Sumber permintaan berubah. Muat ulang formulir.');}
  ok(p.note?.trim(),'Tuliskan penjelasan permintaan.');
  return {r:snap,snap,items:[item('request',p.category==='royalty-issue'?'Masalah royalti':'Permintaan lainnya')]};
 }
 const r=s.releases.find(r=>r.id===p.release);ok(r&&a.scope.includes(r.member),'Rilisan berada di luar akunmu.');ok(['delivered','followup','partial','partial_closed','live','taken_down'].includes(r.status),'Gunakan edit draft atau alur revisi pada menu Rilisan.');ok(categories.includes(p.category),'Pilih jenis permintaan.');const snap=catalogue(r);ok(JSON.stringify(snap)===JSON.stringify(p.source),'Data katalog berubah. Tinjau ulang data sebelum mengajukan.');ok(p.note?.trim(),'Tuliskan penjelasan permintaan.');let items=[];const picked=(p.tracks||[]).map(id=>{const t=snap.songs.find(t=>t.id===id);ok(t,'Lagu bukan bagian dari rilisan.');return t});ok(new Set(picked.map(t=>t.id)).size===picked.length,'Pilihan lagu duplikat.');
if(p.category==='metadata')items=diffs(snap,p);
if(p.category==='audio'){ok(picked.length===1&&p.audio?.key&&p.audio.valid&&p.audio.duration>0&&[44100,48000].includes(p.audio.sampleRate),'Pilih lagu dan unggah WAV baru yang valid.');ok(p.preview>=0&&p.preview<p.audio.duration,'Sesuaikan posisi cuplikan dengan durasi baru.');items=[item(picked[0].id,picked[0].title)];}
if(p.category==='cover'){ok(p.cover?.key&&p.cover.valid&&p.cover.width===3000&&p.cover.height===3000,'Unggah JPG/PNG 3000 × 3000 yang valid.');items=[item('cover','Cover rilisan')];}
if(p.category==='takedown'){ok(['Revisi Metadata','Pindah Aggregator','Konflik Hak Cipta','Konflik Internal'].includes(p.reason),'Pilih alasan penurunan.');ok(p.checked&&r.status!=='taken_down','Konfirmasikan penurunan seluruh rilisan.');items=[item('all','Seluruh rilisan dan semua lagu')];}
if(['cid','disable-cid'].includes(p.category)){ok(picked.length,'Pilih minimal satu lagu.');items=picked.map(t=>item(t.id,t.title));}
if(p.category==='cid'){ok(p.consent&&p.creators?.length,'Lengkapi data pencipta dan persetujuan.');for(const c of p.creators){ok(c.name?.trim()&&/^\d{16}$/.test(c.nik||'')&&c.domicile?.trim()&&c.city?.trim()&&c.ktp?.key&&c.ktp.reviewed&&c.signature?.key,'Lengkapi nama, NIK, domisili, kota, KTP dan tanda tangan tiap pencipta.');ok(c.tracks?.length&&c.tracks.every(id=>picked.some(t=>t.id===id)),'Tentukan lagu terkait tiap pencipta.');}ok(picked.every(t=>p.creators.some(c=>c.tracks.includes(t.id))),'Setiap lagu harus memiliki pencipta.');}
if(p.category==='disable-cid')ok(p.checked,'Konfirmasikan cakupan penonaktifan.');
if(p.category==='release-claim'){ok(picked.length,'Pilih lagu terkait klaim.');const urls=(p.urls||[]).map(video);ok(urls.length&&new Set(urls).size===urls.length,'Tambahkan video yang berbeda untuk tiap baris.');items=urls.map(u=>item(u,u,{url:u}));}
if(p.category==='availability'){for(const link of (p.urls||[]).filter(x=>x.trim())){let u;try{u=new URL(link)}catch{throw Error('Tautan terkait tidak valid.')}ok(u.protocol==='https:'&&!u.username&&!u.password,'Gunakan tautan HTTPS tanpa informasi login.');}ok(p.platforms?.every(x=>['Spotify','Apple Music','YouTube Music','TikTok','Deezer','Amazon Music','Platform lain','Belum yakin'].includes(x))&&new Set(p.platforms).size===p.platforms.length,'Platform tidak valid atau duplikat.');ok(p.platforms?.length&&picked.length,'Pilih platform dan lagu terdampak.');ok(['missing','disappeared'].includes(p.condition),'Pilih kondisi ketersediaan.');items=p.platforms.flatMap(platform=>picked.map(t=>item(platform+':'+t.id,platform+' · '+t.title,{platform,track:t.id})));}
return {r,snap,items};}
function sameTarget(t,category,release,items){if(t.release!==release||t.category!==category||t.status==='done')return false;return items.some(i=>t.items.some(j=>j.id===i.id))}
function conflicts(m,t){return m.tickets.filter(o=>o.id!==t.id&&o.release===t.release&&o.status!=='done'&&((t.category==='takedown'&&['metadata','audio','cover','cid'].includes(o.category))||(o.category==='takedown'&&['metadata','audio','cover','cid'].includes(t.category))||(['cid','disable-cid'].includes(t.category)&&['cid','disable-cid'].includes(o.category)&&t.category!==o.category&&t.items.some(i=>o.items.some(j=>i.id===j.id))))).map(o=>o.id)}
function log(s,t,a,k,note='',pub=true,extra={}){t.history.push({at:s.now,actor:a.id,action:k,note,public:pub,...cp(extra)});t.updated=s.now;}
function notify(m,s,t,a,k){m.notifications.unshift({id:t.id+':'+t.version,account:t.account,handler:t.handler,key:k,actor:a.id,at:s.now,ticket:t.id})}
function applyResult(r,t,it){const old=t.source,cur=catalogue(r);if(t.category==='metadata'){const source=it.scope==='release'?cur.release:cur.songs.find(x=>x.id===it.track)?.metadata;ok(source&&JSON.stringify(source[it.field])===JSON.stringify(it.before),'Katalog berubah pada kolom ini. Selaraskan data sebelum mencatat keberhasilan.');const dest=it.scope==='release'?r:r.songs.find(x=>x.id===it.track);dest[it.field]=cp(it.after);r.artist=(r.primary||[]).map(a=>a.name).join(', ');}
if(t.category==='cover'){ok(JSON.stringify(cur.cover)===JSON.stringify(old.cover),'Cover katalog berubah. Tinjau ulang.');r.cover=cp(t.request.cover);}
if(t.category==='audio'){const song=r.songs.find(x=>x.id===it.id),previous=old.songs.find(x=>x.id===it.id);ok(song&&JSON.stringify(song.audio||null)===JSON.stringify(previous.audio),'Audio katalog berubah. Tinjau ulang.');song.audio=cp(t.request.audio);song.preview=t.request.preview;}
if(t.category==='takedown'){r.status='taken_down';r.takenDownAt=safeDate(t);}
if(['cid','disable-cid'].includes(t.category)){const song=r.songs.find(x=>x.id===it.id);ok(song,'Lagu tidak ditemukan.');song.contentId112={status:t.category==='cid'?'active':'inactive',at:it.at,ticket:t.id,reference:it.reference};}
}
const safeDate=t=>t.items.find(i=>i.at)?.at||t.updated;
function act(s,a,k,p={},cal={}){const base=init(s),m=cp(base);ok(['label','admin','super'].includes(a.role),'Akses tidak tersedia.');if(a.role==='admin')ok(a.write!==false,'Akses hanya baca.');
if(k==='draft'){ok(a.role==='label','Draft hanya untuk label.');const d={id:p.draftId||'DRAFT-'+(++m.serial),account:a.member,at:s.now,payload:cp(p)};const old=m.drafts.find(x=>x.id===d.id&&x.account===a.member);if(old)Object.assign(old,d);else m.drafts.push(d);s.tickets112=m;return d.id;}
if(k==='create'){ok(a.role==='label'&&a.active,'Aktivasi akun diperlukan untuk mengajukan permintaan.');const {r,snap,items}=build(s,a,p),duplicate=m.tickets.find(t=>sameTarget(t,p.category,r.id,items));ok(!duplicate,'Permintaan yang sama masih aktif. Buka '+duplicate?.id+'.');const t={id:'TKT-'+String(++m.serial).padStart(4,'0'),account:a.member,member:r.member,release:r.id,category:p.category,source:snap,request:cp(p),items,status:'submitted',handler:null,created:s.now,updated:s.now,version:1,history:[],messages:[],internal:[],escalated:false,reopenRequest:null};log(s,t,a,'created',p.note);m.tickets.push(t);m.drafts=m.drafts.filter(x=>x.id!==p.draftId||x.account!==a.member);notify(m,s,t,a,k);s.tickets112=m;return t.id;}
const t=m.tickets.find(t=>t.id===p.id);ok(t&&visible(a,t),'Tiket tidak tersedia pada akunmu.');ok(t.version===p.version,'Tiket telah berubah. Buka detail terbaru.');const label=a.role==='label',staff=!label,manage=staff&&(t.handler===a.id||a.role==='super'),note=()=>ok(p.note?.trim(),'Tuliskan keterangan yang jelas.');let release=null,pub=true;
if(k==='message'){ok(t.status!=='done','Gunakan Laporkan Masalah Masih Ada untuk tiket selesai.');note();t.messages.push({at:s.now,actor:a.id,note:p.note.trim(),files:cp(p.files||[])});}
else if(k==='extend'){ok(label&&t.category==='availability'&&t.status!=='done'&&p.release===t.release&&p.category==='availability','Cakupan tambahan belum tersedia.');const built=build(s,a,p),newItems=built.items.filter(i=>!t.items.some(x=>x.id===i.id));ok(newItems.length,'Cakupan ini sudah tercatat pada tiket.');ok(!m.tickets.some(o=>o.id!==t.id&&sameTarget(o,t.category,t.release,newItems)),'Cakupan tambahan ada pada tiket aktif lain.');t.items.push(...newItems);t.amendments??=[];t.amendments.push({at:s.now,actor:a.id,request:cp(p),items:cp(newItems)});}
else if(k==='complete'){ok(label&&t.status==='label','Kelengkapan belum diminta.');note();t.messages.push({at:s.now,actor:a.id,note:p.note,files:cp(p.files||[])});t.status='handling';t.required='';}
else if(k==='report-again'){ok(label&&t.status==='done'&&!t.reopenRequest,'Laporan ulang belum tersedia.');note();t.reopenRequest={at:s.now,note:p.note.trim()};}
else if(k==='claim'){ok(staff&&t.status==='submitted'&&!t.handler,'Tiket sudah ditangani.');t.handler=a.id;t.status='handling';}
else if(k==='assign'){ok(a.role==='super'&&p.handler,'Pilih petugas.');note();t.handler=p.handler;if(t.status==='submitted')t.status='handling';}
else {ok(manage,'Tiket ditangani petugas lain.');if(k==='internal'){note();t.internal.push({at:s.now,actor:a.id,note:p.note});pub=false;}
else if(k==='request'){ok(['handling','distributor'].includes(t.status),'Permintaan kelengkapan belum tersedia.');note();t.resumeStatus=t.status;t.status='label';t.required=p.note;}
else if(k==='send'){ok(t.status==='handling'&&p.reference?.trim()&&p.checked,'Pastikan permintaan telah diteruskan dan catat referensinya.');note();const related=conflicts(m,t);ok(!related.length||p.aligned,'Ada permintaan terkait: '+related.join(', ')+'. Catat penyelarasan sebelum meneruskan.');if(related.length){t.alignments??=[];t.alignments.push({at:s.now,tickets:related,note:p.note,actor:a.id});}t.status='distributor';t.sentAt??=s.now;t.lastSent=s.now;t.reference=p.reference.trim();t.nextFollowup=root.Wami11.addBusinessDays(s.now,3,cal);}
else if(k==='followup'){ok(t.status==='distributor','Tiket belum menunggu distributor.');note();ok(p.next>s.now,'Pilih waktu tindak lanjut berikutnya.');t.lastChecked=s.now;t.nextFollowup=p.next;t.checks=(t.checks||0)+1;}
else if(k==='escalate'){ok(t.status!=='done','Tiket sudah selesai.');note();t.escalated=true;t.escalationNote=p.note;}
else if(k==='clear-escalation'){ok(a.role==='super'&&t.escalated,'Peninjauan tidak tersedia.');note();t.escalated=false;}
else if(k==='results'){ok(['handling','distributor'].includes(t.status)&&p.checked,'Periksa hasil sebelum mencatatnya.');note();ok(p.results?.length,'Pilih hasil yang akan dicatat.');release=t.release.startsWith('account:')?null:cp(s.releases.find(r=>r.id===t.release));ok(release||t.release.startsWith('account:'),'Rilisan tidak ditemukan.');for(const res of p.results){const it=t.items.find(i=>i.id===res.id);ok(it&&it.status!=='confirmed'&&['confirmed','pending','blocked'].includes(res.status),'Hasil ini sudah tercatat atau tidak valid.');ok(res.note?.trim(),'Jelaskan hasil setiap bagian.');if(res.status==='confirmed')ok(res.reference?.trim(),'Catat tautan atau referensi hasil konfirmasi.');Object.assign(it,{status:res.status,note:res.note.trim(),reference:res.reference?.trim()||'',at:s.now});if(res.status==='confirmed')applyResult(release,t,it);}if(release){release.version=(release.version||0)+1;release.updated=s.now;release.history??=[];release.history.push({at:s.now,actor:a.id,action:'ticket-result112',note:p.note,ticket:t.id,results:cp(p.results)});}}
else if(k==='finish'){ok(['handling','distributor'].includes(t.status)&&t.items.every(i=>i.status==='confirmed')&&p.checked,'Masih ada bagian belum selesai atau hasil belum diperiksa.');note();t.status='done';t.completed=s.now;t.summary=p.note;t.escalated=false;}
else if(k==='reopen'){ok(t.status==='done'&&t.reopenRequest,'Belum ada laporan masalah berulang.');note();ok(!m.tickets.some(o=>o.id!==t.id&&sameTarget(o,t.category,t.release,t.items)),'Ada tiket aktif dengan cakupan yang sama. Tautkan laporan ke tiket tersebut.');t.previousResults??=[];t.previousResults.push({completed:t.completed,summary:t.summary,items:cp(t.items),report:cp(t.reopenRequest)});{const found=s.releases.find(r=>r.id===t.release);t.source=found?catalogue(found):t.source;}t.items=t.items.map(i=>{const next={...i,status:'pending',note:'',reference:'',at:null};if(t.category==='metadata'){next.before=cp((i.scope==='release'?t.source.release:t.source.songs.find(x=>x.id===i.track)?.metadata)[i.field]);}return next});t.status='handling';t.completed=null;t.reopenRequest=null;t.nextFollowup=null;}
else if(k==='link-new'){ok(t.status==='done'&&t.reopenRequest&&p.related,'Pilih tiket terkait.');const other=m.tickets.find(o=>o.id===p.related&&o.account===t.account&&o.id!==t.id);ok(other,'Tiket terkait tidak tersedia.');note();t.related??=[];if(!t.related.includes(other.id))t.related.push(other.id);t.reopenRequest=null;}
else throw Error('Tindakan tidak tersedia.');}
t.version++;log(s,t,a,k,p.note||'',pub);if(k!=='internal')notify(m,s,t,a,k);if(release){const index=s.releases.findIndex(r=>r.id===release.id);s.releases[index]=release;}s.tickets112=m;return t.id;
}
function attention(s,t,a){if(!visible(a,t))return null;if(a.role==='label')return t.status==='label'?{tone:'mustard',text:'Lengkapi informasi tiket'}:null;if(t.reopenRequest)return {tone:'mustard',text:'Laporan masalah berulang'};if(t.escalated&&a.role==='super')return {tone:'mustard',text:'Kasus perlu peninjauan'};if(t.status==='submitted')return {tone:'info',text:'Laporan belum ditangani'};if(t.status==='distributor'&&t.nextFollowup<=s.now)return {tone:'urgent',text:'Tindak lanjut jatuh tempo'};return null;}
function tick(s){const m=init(s);for(const t of m.tickets.filter(t=>t.status==='distributor'&&t.nextFollowup<=s.now)){const key=t.id+':'+t.nextFollowup;if(!m.notified.includes(key)){m.notified.push(key);m.notifications.unshift({id:key,account:t.account,handler:t.handler,key:'followup-due',at:s.now,ticket:t.id});}}}
const api={init,act,catalogue,build,diffs,video,attention,tick,visible,fields,categories,conflicts};root.Tickets112=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);

