(function(root){'use strict';
const cp=x=>JSON.parse(JSON.stringify(x)),H=3600000,ok=(v,m)=>{if(!v)throw Error(m)},integer=n=>Number.isSafeInteger(n)&&n>0;
function init(s){return s.commerce113??={orders:[],provider:[],refunds:[],notifications:[],serial:0,check:{at:null,ok:null,rows:[]}}}
function visible(a,o){return a.role==='label'?o.account===a.member:!!a.view}
function log(s,o,a,key,note='',pub=true,extra={}){o.history.push({key,note,public:pub,actor:a.id,at:s.now,...cp(extra)});o.version++;if(pub)init(s).notifications.unshift({order:o.id,key,at:s.now,version:o.version,actor:a.id})}
function attempt(o){return o.attempts.at(-1)}
function refunded(s,o){return moneySum(init(s).refunds.filter(r=>r.order===o.id&&r.status==='done').map(r=>r.amount))}
function reserved(s,o,except=''){return moneySum(init(s).refunds.filter(r=>r.order===o.id&&r.id!==except&&['approved','processing','done'].includes(r.status)).map(r=>r.amount))}
const referenceKey=v=>String(v||'').normalize('NFKC').trim().toUpperCase();
function paymentRecords(s,o,strict=true){const byId=new Map(),byRef=new Map(),unique=[],badIds=new Set(),badRefs=new Set();for(const p of init(s).provider.filter(p=>p.order===o.id&&p.status==='paid'&&!p.refund)){const ref=referenceKey(p.reference),time=typeof p.at==='number'?p.at:Date.parse(p.at),valid=p.id&&ref&&integer(p.amount)&&p.currency==='IDR'&&o.attempts.some(t=>t.id===p.attempt)&&Number.isFinite(time);if(!valid){if(strict)ok(false,'Bukti pembayaran tidak valid. Periksa referensi, nominal, dan mata uang.');continue;}const signature=JSON.stringify([p.order,p.attempt,ref,p.amount,p.currency,p.status,time]),oldId=byId.get(p.id),oldRef=byRef.get(ref);if((oldId&&oldId!==signature)||(oldRef&&oldRef!==signature)){badIds.add(p.id);badRefs.add(ref);if(strict)ok(false,'Bukti pembayaran bertentangan. Periksa konfirmasi penyedia.');}if(!oldId&&!oldRef)unique.push(p);byId.set(p.id,signature);byRef.set(ref,signature);}return unique.filter(p=>!badIds.has(p.id)&&!badRefs.has(referenceKey(p.reference)));}
function moneySum(values){let n=0n;for(const v of values){ok(Number.isSafeInteger(v),'Nominal pembayaran tidak valid.');n+=BigInt(v);}ok(n<=BigInt(Number.MAX_SAFE_INTEGER)&&n>=BigInt(Number.MIN_SAFE_INTEGER),'Total pembayaran melampaui batas perhitungan yang aman.');return Number(n);}
function received(s,o){return moneySum(paymentRecords(s,o,false).map(p=>p.amount))}
function pendingRefund(s,o){return init(s).refunds.find(r=>r.order===o.id&&r.status!=='done'&&r.status!=='closed')}
function issue(s,o){const r=pendingRefund(s,o);if(r)return r.status==='info'?'info':r.status==='approved'?'refund-ready':r.status==='processing'?'refund-processing':'refund-review';if(o.case?.status==='info')return 'info';if(o.case?.status==='review')return 'review';if(o.payment==='paid'&&!o.fulfilled&&received(s,o)>refunded(s,o))return 'fulfillment';return null}
function tick(s){for(const o of init(s).orders){const t=attempt(o);if(t?.status==='pending'&&t.expires<=s.now){t.status='expired';if(o.payment!=='paid')o.payment='expired';o.version++}if(o.kind==='plan'&&o.fulfilled&&o.activationWaiting){const m=s.members?.find(m=>m.id===o.member);if(m?.active&&m.subscriptionEnd){o.activationWaiting=false;o.start=m.activatedAt||new Date(s.now).toISOString();o.end=m.subscriptionEnd;o.version++}}}}
function create(s,p){const m=init(s);if(p.kind==="credits")ok(integer(p.credits)&&Number.isSafeInteger(p.bonus||0)&&(p.bonus||0)>=0,"Jumlah kredit tidak valid.");ok(p.account&&p.member&&['plan','credits','service'].includes(p.kind),'Pembelian tidak valid.');ok(integer(p.amount),'Nominal pembayaran belum tersedia.');const id='TX-'+String(++m.serial).padStart(5,'0'),o={id,account:p.account,member:p.member,kind:p.kind,title:p.title,amount:p.amount,quantity:p.quantity||1,credits:p.credits||0,bonus:p.bonus||0,plan:p.plan||'',period:p.period||'year',benefits:cp(p.benefits||[]),items:cp(p.items||[]),source:p.source||null,sourceKey:p.sourceKey||'',method:p.method||'Penyedia pembayaran',quote:cp(p.quote||{}),created:s.now,payment:'pending',fulfilled:false,fulfilledQuantity:0,activationWaiting:false,baseEnd:p.baseEnd||null,start:null,end:null,attempts:[{id:p.invoice||'PAY-'+id+'-1',status:'pending',expires:p.expires||s.now+24*H,created:s.now}],case:null,handler:null,version:1,history:[{key:'created',at:s.now,actor:p.account,public:true,note:'Ringkasan pembelian disimpan.',snapshot:cp(p)}]};m.orders.unshift(o);return o}
function ingest(s,p){const m=init(s);let o=m.orders.find(o=>o.sourceKey===p.sourceKey);if(!o)o=create(s,p);if(!o)return;const t=attempt(o);if(p.status==='paid'){if(o.payment!=='paid'){t.status=o.payment='paid';t.paidAt=p.paidAt||s.now;const pid='SIM-'+t.id;if(!m.provider.some(x=>x.id===pid))m.provider.push({id:pid,order:o.id,attempt:t.id,reference:pid,amount:o.amount,status:'paid',currency:'IDR',at:t.paidAt,simulation:true});log(s,o,{id:p.account},'paid','Pembayaran simulasi terkonfirmasi.');}if(p.fulfilled&&!o.fulfilled){o.fulfilled=true;o.fulfilledQuantity=p.fulfilledQuantity||o.quantity;o.credited=p.credited||0;o.activationWaiting=!!p.activationWaiting;o.start=p.start||null;o.end=p.end||null;log(s,o,{id:p.account},'fulfilled','Hasil pembelian tercatat dari pesanan asal.')}}else if(p.status==='expired'&&o.payment!=='paid'&&t.status==='pending'){t.status=o.payment='expired';o.version++}return o}
const inRange=(at,from,to)=>at!==null&&at!==undefined&&(typeof at==='number'?at:Date.parse(at))>=from&&(typeof at==='number'?at:Date.parse(at))<=to;
function windowOrders(s,from=-Infinity,to=Infinity){const m=init(s);return m.orders.filter(o=>o.attempts.some(t=>inRange(t.paidAt??t.created,from,to))||m.provider.some(p=>p.order===o.id&&inRange(p.at,from,to))||m.refunds.some(r=>r.order===o.id&&inRange(r.completed,from,to)));}
function rows(s,from=-Infinity,to=Infinity){const m=init(s),out=[],orders=windowOrders(s,from,to);for(const o of orders){const ps=m.provider.filter(p=>p.order===o.id&&!p.refund),paid=ps.filter(p=>p.status==='paid');for(const p of ps.filter(p=>inRange(p.at,from,to))){const t=o.attempts.find(t=>t.id===p.attempt);if(!t){out.push({order:o.id,provider:p.id,kind:'unrecognized',text:'Referensi pembayaran belum cocok'});continue}if(p.currency!=='IDR'||p.amount!==o.amount){out.push({order:o.id,provider:p.id,kind:'amount',text:'Nominal atau mata uang berbeda'});continue}if(p.status==='paid'&&t.status!=='paid')out.push({order:o.id,provider:p.id,kind:'status',text:'Pembayaran belum tercatat'});else if(p.status!=='paid'&&t.status==='paid')out.push({order:o.id,provider:p.id,kind:'status',text:'Status pembayaran berbeda'});}if(paid.some(p=>inRange(p.at,from,to))&&paid.length>1&&received(s,o)-refunded(s,o)>o.amount)out.push({order:o.id,provider:paid.at(-1).id,kind:'duplicate',text:'Lebih dari satu pembayaran diterima'});if(o.payment==='paid'&&!paid.length&&o.attempts.some(t=>inRange(t.paidAt,from,to)))out.push({order:o.id,provider:'',kind:'missing',text:'Konfirmasi penyedia belum ditemukan'});const rs=m.refunds.filter(r=>r.order===o.id);for(const r of rs){if(r.status==='done'&&inRange(r.completed,from,to)&&r.method==='provider'&&!m.provider.some(p=>p.refund===r.id&&p.status==='refunded'&&p.amount===r.amount&&referenceKey(p.reference)===referenceKey(r.reference)))out.push({order:o.id,refund:r.id,kind:'refund',text:'Pengembalian belum cocok'});}}
for(const p of m.provider.filter(p=>p.at>=from&&p.at<=to&&!p.refund&&!m.orders.some(o=>o.id===p.order)))out.push({order:null,provider:p.id,kind:'unrecognized',text:'Pembayaran belum dikenali'});return out}
function evidence(s,o,tid){const m=init(s),t=o.attempts.find(t=>t.id===tid);ok(t,'Referensi pembayaran tidak ditemukan.');const ps=paymentRecords(s,o).filter(p=>p.attempt===t.id);ok(ps.length===1,'Pembayaran perlu ditinjau: konfirmasi tidak tersedia atau lebih dari satu.');const p=ps[0];ok(p.status==='paid'&&p.amount===o.amount&&p.currency==='IDR'&&p.reference,'Konfirmasi pembayaran atau nominal belum sesuai.');return {p,t}}
function fulfill(s,o,a){paymentRecords(s,o);ok(o.payment==='paid'&&received(s,o)-refunded(s,o)>=o.amount,'Pembayaran belum terkonfirmasi atau dana telah dikembalikan.');ok(!o.fulfilled,'Pembelian sudah dipenuhi; tidak diberikan kembali.');ok(!pendingRefund(s,o),'Selesaikan pemeriksaan pengembalian sebelum memberikan pembelian.');const m=s.members.find(m=>m.id===o.member);ok(m,'Label tidak ditemukan.');if(o.kind==='credits'){const key='commerce113-'+o.id,expected=o.credits+o.bonus;ok(integer(expected),'Jumlah kredit tidak valid.');let lot=m.lots.find(l=>l.id===key);if(!lot){lot={id:key,type:'paid',available:expected,expires:null,source:o.id};m.lots.push(lot)}else{ok(Number.isSafeInteger(lot.granted113)&&lot.granted113>=0&&lot.granted113<=expected,'Catatan pemberian perlu diperiksa.');lot.available+=expected-lot.granted113;}lot.granted113=expected;o.credited=expected;o.fulfilledQuantity=o.quantity;m.paid=true;}
else if(o.kind==='plan'){ok(o.plan&&o.plan!=='Flex','Paket perlu diperiksa.');m.plan=o.plan;m.period=o.period;m.paid=true;m.benefits104=cp(o.benefits);if(m.active){const d=new Date(Math.max(s.now,Date.parse(o.baseEnd)||0));if(o.period==='month')d.setUTCMonth(d.getUTCMonth()+1);else d.setUTCFullYear(d.getUTCFullYear()+1);m.subscriptionEnd=d.toISOString();o.start=new Date(Math.max(s.now,Date.parse(o.baseEnd)||0)).toISOString();o.end=m.subscriptionEnd}else{o.activationWaiting=true;o.start=o.end=null}o.fulfilledQuantity=1;}
else {const src=o.source,order=src?.type==='addon'?s.addons111?.orders.find(x=>x.id===src.id):s.wami11?.orders.find(x=>x.id===src?.id);ok(order,'Pesanan asal belum ditemukan; telusuri sebelum membuat permintaan baru.');if(src.type==='addon'){if(order.payment==='unpaid'){order.payment='paid';order.status='queued';order.paidAt=s.now;order.version++;order.history.push({at:s.now,actor:a.id,action:'pay',public:true,note:'Pembayaran dikonfirmasi dari Transaksi.'})}}else if(order.status==='unpaid'){order.status='queued';order.paid=s.now;order.version++;order.events.push({at:s.now,actor:a.id,action:'pay',public:true,note:'Pembayaran dikonfirmasi dari Transaksi.'})}o.fulfilledQuantity=o.quantity;}
o.fulfilled=true;if(o.source?.type==='invoice'&&m.invoice?.id===o.source.id)m.invoice.status='paid';log(s,o,a,'fulfilled',o.kind==='credits'?'Kredit telah ditambahkan.':o.kind==='plan'?'Paket telah dicatat.':'Permintaan layanan telah diterima.');if(o.case)o.case.status='resolved';}
function act(s,a,k,p={}){tick(s);const m=init(s);ok(['label','admin','super'].includes(a.role),'Akses tidak tersedia.');if(k==='check'){ok(a.role!=='label'&&a.view,'Akses pemeriksaan tidak tersedia.');ok(p.from<=p.to,'Rentang tanggal tidak valid.');m.check={at:s.now,ok:!p.fail,from:p.from,to:p.to,rows:p.fail?[]:rows(s,p.from,p.to),error:p.fail?'Data pembanding belum tersedia. Coba pemeriksaan kembali.':''};return m.check}
const o=m.orders.find(o=>o.id===p.id);ok(o&&visible(a,o),'Transaksi tidak ditemukan atau di luar aksesmu.');ok(p.version===o.version,'Transaksi berubah. Buka rincian terbaru.');const label=a.role==='label',staff=!label&&a.write,superuser=a.role==='super'&&a.write;const write=()=>ok(staff,'Akses tindakan tidak tersedia.'),note=()=>ok(typeof p.note==='string'&&p.note.trim().length>=5&&p.note.length<=4000,'Tuliskan keterangan yang jelas.');
if(k==='simulate-pay'){ok(label,'Pembayaran hanya melalui akun pemilik.');ok(s.members.some(x=>x.id===o.member),'Label tidak ditemukan.');ok(!pendingRefund(s,o),'Pemeriksaan pengembalian masih terbuka.');if(o.kind==='service')ok(o.source?.type==='addon'?s.addons111?.orders.some(x=>x.id===o.source.id):s.wami11?.orders.some(x=>x.id===o.source?.id),'Pesanan asal belum ditemukan.');const t=attempt(o);ok(t.status==='pending'&&t.expires>s.now&&p.checked,'Pembayaran ini tidak lagi tersedia.');ok(!m.provider.some(x=>x.attempt===t.id&&x.status==='paid'),'Pembayaran telah diterima; periksa statusnya.');const ref='SIM-'+t.id;m.provider.push({id:ref,order:o.id,attempt:t.id,reference:ref,amount:o.amount,status:'paid',currency:'IDR',at:s.now,simulation:true});t.status=o.payment='paid';t.paidAt=s.now;log(s,o,a,'paid','Pembayaran simulasi berhasil.');fulfill(s,o,a);}
else if(k==='retry'){ok(label&&o.payment!=='paid'&&attempt(o).status!=='pending','Pembayaran baru belum diperlukan.');ok(!m.provider.some(x=>x.order===o.id&&x.status==='paid'),'Dana sudah diterima. Periksa pembayaran sebelumnya dahulu.');ok(p.checked,'Tinjau ringkasan sebelum melanjutkan.');o.attempts.push({id:'PAY-'+o.id+'-'+(o.attempts.length+1),created:s.now,expires:s.now+24*H,status:'pending'});o.payment='pending';log(s,o,a,'retry','Pembayaran baru dibuat untuk pembelian yang sama.');}
else if(k==='sync'||k==='check-own'){if(k==='sync')write();else ok(label,'Akses tidak tersedia.');ok(m.check.ok!==false,'Penyedia belum dapat diperiksa.');const {p:record,t}=evidence(s,o,p.attempt||attempt(o).id);ok(t.status!=='paid'||o.payment!=='paid','Status sudah sesuai.');t.status=o.payment='paid';t.paidAt=record.at;if(o.case?.status==='review')o.case.status='resolved';log(s,o,a,'synced','Status diperbarui dari konfirmasi penyedia.',true,{reference:record.reference});}
else if(k==='review'){ok(label||staff,'Akses tindakan tidak tersedia.');note();ok(!o.case||o.case.status==='resolved','Pemeriksaan masih berlangsung. Buka kasus yang sama.');o.case={status:'review',reason:p.note.trim(),requested:s.now,handler:null,messages:[]};log(s,o,a,'review',p.note.trim());}
else if(k==='claim'){write();ok(issue(s,o),'Tidak ada tindakan tertunda.');ok(!o.handler||o.handler===a.id,'Kasus ditangani petugas lain.');o.handler=a.id;if(o.case)o.case.handler=a.id;log(s,o,a,'claim','Penanganan pemeriksaan dimulai.',false);}
else if(k==='assign'){ok(superuser,'Hanya Super Admin mengalihkan penanganan.');note();ok(p.handler,'Pilih petugas.');o.handler=p.handler;if(o.case)o.case.handler=p.handler;log(s,o,a,'assign',p.note,false,{handler:p.handler});}
else if(k==='request-info'){write();ok(!o.handler||o.handler===a.id||superuser,'Kasus ditangani petugas lain.');note();o.case??={status:'review',requested:s.now,messages:[]};o.case.status='info';o.case.prompt=p.note;log(s,o,a,'request-info',p.note);}
else if(k==='respond'){ok(label&&o.case?.status==='info','Informasi belum diminta.');note();o.case.messages.push({at:s.now,note:p.note});o.case.status='review';log(s,o,a,'respond',p.note);}
else if(k==='resolve'){write();note();ok(o.case&&o.case.status==='review','Kasus belum dalam pemeriksaan.');ok(!(o.payment==='paid'&&!o.fulfilled&&received(s,o)>refunded(s,o))&&!rows(s).some(x=>x.order===o.id),'Masalah pembayaran atau pemenuhan masih ada. Selesaikan sumbernya dahulu.');o.case.status='resolved';log(s,o,a,'resolve',p.note);}
else if(k==='fulfill'){write();ok(o.handler===a.id||superuser,'Ambil penanganan sebelum menyelesaikan pembelian.');ok(p.checked,'Konfirmasikan pemeriksaan hasil pembelian.');fulfill(s,o,a);}
else if(k==='refund-open'){write();note();ok(received(s,o)>0,'Dana diterima belum terkonfirmasi.');ok(!pendingRefund(s,o),'Kasus pengembalian masih terbuka.');const r={id:'RF-'+String(++m.serial).padStart(5,'0'),order:o.id,status:'review',reason:p.reason||'Alasan lain',note:p.note,amount:0,method:'origin',destination:null,confirmed:false,reference:'',created:s.now,history:[],handler:a.id};m.refunds.unshift(r);o.handler??=a.id;log(s,o,a,'refund-open',p.note);return r.id;}
else if(k.startsWith('refund-')){const r=m.refunds.find(r=>r.id===p.refund&&r.order===o.id);ok(r,'Kasus pengembalian tidak ditemukan.');if(k==='refund-destination'){ok(label&&r.status==='info','Konfirmasi rekening belum diminta.');ok(p.bank?.trim()&&/^\d{6,24}$/.test(p.number||'')&&p.holder?.trim()&&p.checked,'Lengkapi dan konfirmasikan rekening tujuan.');r.destination={bank:p.bank.trim(),number:p.number,holder:p.holder.trim()};r.confirmed=true;r.status='review';log(s,o,a,k,'Rekening tujuan dikonfirmasi pemilik akun.');}
else{write();if(['refund-approve','refund-process','refund-done'].includes(k)){paymentRecords(s,o);ok(received(s,o)>0&&reserved(s,o)<=received(s,o),'Dana atau bukti pembayaran perlu diperiksa kembali.');}ok(r.status!=='done'&&r.status!=='closed','Kasus sudah selesai.');note();if(k==='refund-info'){ok(r.status==='review','Kasus tidak sedang diperiksa.');r.status='info';r.prompt=p.note;log(s,o,a,k,p.note)}
else if(k==='refund-approve'){ok(superuser&&r.status==='review','Persetujuan hanya oleh Super Admin pada kasus yang diperiksa.');ok(integer(p.amount)&&p.amount<=received(s,o)-reserved(s,o,r.id),'Nominal melebihi sisa dana atau tidak valid.');ok(p.checked&&p.disposition?.trim().length>=5,'Jelaskan hasil pemeriksaan atas kredit, benefit, dan layanan.');ok(['origin','transfer'].includes(p.method),'Pilih jalur pengembalian.');ok(p.method!=='transfer'||r.confirmed&&r.destination,'Rekening tujuan harus dikonfirmasi Label.');r.amount=p.amount;r.method=p.method;r.disposition=p.disposition;r.status='approved';r.approvedAt=s.now;log(s,o,a,k,p.note,true,{amount:r.amount,disposition:r.disposition});}
else if(k==='refund-process'){ok(superuser&&r.status==='approved'&&p.reference?.trim()&&p.checked,'Konfirmasi pengiriman pengembalian dengan referensi.');ok(!m.refunds.some(x=>x.id!==r.id&&referenceKey(x.reference)===referenceKey(p.reference)),'Referensi sudah digunakan.');r.status='processing';r.reference=p.reference.trim();r.referenceOriginal=p.reference;r.referenceKey117=referenceKey(p.reference);log(s,o,a,k,p.note);}
else if(k==='refund-done'){ok(superuser&&['approved','processing'].includes(r.status)&&p.reference?.trim()&&p.checked,'Konfirmasi dana telah dikembalikan beserta referensi.');ok(!m.refunds.some(x=>x.id!==r.id&&referenceKey(x.reference)===referenceKey(p.reference)),'Referensi sudah digunakan.');ok(['provider','manual'].includes(p.method),'Metode pencatatan tidak valid.');if(p.method==='provider'){ok(m.provider.some(x=>x.refund===r.id&&x.amount===r.amount&&x.status==='refunded'&&referenceKey(x.reference)===referenceKey(p.reference)),'Pengembalian penyedia belum terkonfirmasi.');}else ok(r.method==='transfer'&&r.confirmed,'Pengembalian manual harus ke rekening yang dikonfirmasi Label.');ok(integer(p.at)&&p.at<=s.now&&p.at>=r.created,'Tanggal pengembalian tidak valid.');r.method=p.method;r.reference=p.reference.trim();r.referenceOriginal=p.reference;r.referenceKey117=referenceKey(p.reference);r.status='done';r.completed=p.at;log(s,o,a,k,p.note,true,{amount:r.amount,reference:r.reference});}
else if(k==='refund-close'){ok(r.status==='review','Kasus yang disetujui tidak ditutup tanpa pengembalian.');r.status='closed';r.resolution=p.note;log(s,o,a,k,p.note)}else throw Error('Tindakan tidak tersedia.');r.history.push({at:s.now,actor:a.id,key:k,note:p.note});}}
else throw Error('Tindakan tidak tersedia.');return o.id;}
function restoreGraph(target,source){if(!source||typeof source!=='object')return source;if(!target||typeof target!=='object'||Array.isArray(source)!==Array.isArray(target))target=Array.isArray(source)?[]:{};if(Array.isArray(source)){const old=target.slice(),used=new Set(),values=source.map((v,i)=>{const j=v&&typeof v==='object'&&v.id!==undefined?old.findIndex((x,n)=>!used.has(n)&&x&&x.id===v.id):i;used.add(j);return restoreGraph(old[j],v)});target.splice(0,target.length,...values);return target;}for(const k of Object.keys(target))if(!(k in source))delete target[k];for(const [k,v]of Object.entries(source))target[k]=restoreGraph(target[k],v);return target;}
function atomicAct(s,...args){const before=cp(s);try{return act(s,...args)}catch(err){restoreGraph(s,before);throw err}}
const api={init,create,ingest,visible,act:atomicAct,paymentRecords,referenceKey,tick,rows,issue,attempt,received,refunded,reserved,pendingRefund,evidence,windowOrders};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Transactions113=api;
})(typeof window!=='undefined'?window:globalThis);
