/* V10.1 linked label/staff journey, layered over the preserved V9 workspace. */
const V10KEY='rm-v11-1-journey';
let ten=Persistence117.blocked?RM10.seed():(Persistence117.journey||RM10.seed());
// Restore known staff before any legacy renderer resolves the signed-in identity.
if(ten.staff114)for(const u of ten.staff114.users){let p=person(u.id);if(!p){p={id:u.id,name:u.name,email:u.email,super:u.super,joined:u.joined||'2026-10-01',initials:u.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase(),color:'#a1aec1'};people.push(p);scores[u.id]??={'2026-07':[0,0,0],'2026-08':[0,0,0]};if(typeof sampleTime7!=='undefined')sampleTime7[u.id]??={active:[0,0,0,0,0],present:[0,0,0,0,0]};data.profiles[u.id]??={phone:'',location:'',contract:'Belum ditetapkan',legal:u.name};data.salaries[u.id]??=0;data.allowances[u.id]??=0;data.bonusRules[u.id]??=0;}Object.assign(p,{name:u.name,email:u.email,super:u.super});}
if(ten.role!=='label')state.user=ten.staffUser116||(ten.role==='super'?'jeck':'adovi');
const tenOldRender=render;let tenConfig=false,tenStep=1,tenDraftService='Standard',tenDetail=null;
v8.loggedOut=false;
const inheritedAction10=handleAction;
handleAction=async function(button){if(['nav','search-nav'].includes(button.dataset.action)&&['labels9','liability9','standards9','mywork9'].includes(button.dataset.page))return go(button.dataset.page,'platform');return inheritedAction10(button);};
const T=(a,b)=>ten.lang==='en'?b:a,E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const member10=()=>RM10.getMember(ten),isLabel10=()=>ten.role==='label';
const money10=n=>new Intl.NumberFormat(ten.lang==='en'?'en-US':'id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const date10=(v,time=false)=>v?new Intl.DateTimeFormat(ten.lang==='en'?'en-GB':'id-ID',{dateStyle:'long',...(time?{timeStyle:'short'}:{}),timeZone:'Asia/Jakarta'}).format(new Date(typeof v==='string'&&v.length===10?v+'T00:00:00+07:00':v)):'—';
// Every writer shares the persisted revision, including automatic saves.
let persistedRevision116=ten.storageRevision116||0;
let committedTen116=structuredClone(ten),committedData116=structuredClone(data),committedShared117=sharedSnapshot117();
let booting116=true;
function conflictError116(){window.storageConflict116=true;if(typeof conflictBanner116==='function')conflictBanner116();const err=Error(T('Data berubah di tab lain. Isianmu dipertahankan; tinjau pembaruan sebelum menyimpan.','Data changed in another tab. Your entries are kept; review the update before saving.'));err.code='storage_conflict';return err;}
function storageChanged116(){if(Persistence117.blocked)throw Persistence117.error();const raw=localStorage.getItem(V10KEY),saved=raw?(()=>{try{return JSON.parse(raw)}catch{throw Persistence117.error()}})():null;if(saved&&!Persistence117.validateJourney(saved))throw Persistence117.error();return (saved?.storageRevision116||0)!==persistedRevision116;}
function restoreGraph116(target,source,seen=new WeakMap()){if(!source||typeof source!=='object')return source;if(seen.has(source))return seen.get(source);if(!target||typeof target!=='object'||Array.isArray(source)!==Array.isArray(target))target=Array.isArray(source)?[]:{};seen.set(source,target);if(Array.isArray(source)){const existing=target.slice(),used=new Set(),values=source.map((v,i)=>{const j=v&&typeof v==='object'&&v.id!==undefined?existing.findIndex((x,n)=>!used.has(n)&&x&&x.id===v.id):i;used.add(j);return restoreGraph116(existing[j],v,seen)});target.splice(0,target.length,...values);return target;}for(const key of Object.keys(target))if(!(key in source))delete target[key];for(const [key,value]of Object.entries(source))target[key]=restoreGraph116(target[key],value,seen);return target;}
function restoreShared117(saved){restoreGraph116(data,saved.data);for(const p of saved.profiles)Object.assign(person(p.id)||{},p);for(const [key,value]of Object.entries({contributions:saved.contributions,kpiRules:saved.rules,ruleHistory:saved.ruleHistory,requests:saved.requests,grants:saved.grants,archives:saved.archives}))v8[key]=restoreGraph116(v8[key],value);}
function restoreState116(snapshot,oldData,shared){restoreGraph116(ten,snapshot);restoreGraph116(data,oldData);if(shared)restoreShared117(shared);}
let transactionDepth116=0;
function atomic10(fn){const before=structuredClone(ten),oldData=structuredClone(data),shared=sharedSnapshot117();let open=true;transactionDepth116++;try{if(storageChanged116())throw conflictError116();const result=fn();transactionDepth116--;open=false;if(!transactionDepth116)save10();return result}catch(err){if(open)transactionDepth116--;restoreState116(before,oldData,shared);throw err}}
function save10(){
 if(transactionDepth116||booting116)return;
 ten.legacyShared117=sharedSnapshot117();
 ten.themeMode105??='auto';ten.themeManual111??=false;
 if(ten.role!=='label')ten.staffUser116=state.user;
 try{if(storageChanged116())throw conflictError116();const raw=localStorage.getItem(V10KEY),candidate=JSON.stringify({...ten,storageRevision116:persistedRevision116});if(raw===candidate){committedTen116=structuredClone(ten);committedData116=structuredClone(data);committedShared117=sharedSnapshot117();return;}if(!Persistence117.validateJourney(ten))throw Persistence117.error();const next=persistedRevision116+1;localStorage.setItem(V10KEY,JSON.stringify({...ten,storageRevision116:next}));try{if(raw&&Persistence117.validateJourney(JSON.parse(raw))&&JSON.parse(raw).legacyShared117)localStorage.setItem(Persistence117.backupKey,raw)}catch{};ten.storageRevision116=next;persistedRevision116=next;committedTen116=structuredClone(ten);committedData116=structuredClone(data);committedShared117=sharedSnapshot117();}
 catch(err){if(err.code!=='storage_conflict')restoreState116(committedTen116,committedData116,committedShared117);throw err}
}
window.addEventListener('storage',e=>{if(e.key===V10KEY||e.key===null){window.storageConflict116=true;if(typeof toast==='function')toast(T('Data diperbarui di tab lain. Isianmu dipertahankan; tinjau data terbaru sebelum menyimpan.','Data changed in another tab. Your entries are kept; review the latest data before saving.'));}});
function b10(label,action,id='',kind=''){return `<button type="button" class="ten-btn ${kind}" data-ten="${action}" data-id="${E(id)}">${label}</button>`;}
function tag10(label,color=''){return `<span class="ten-chip ${color}">${label}</span>`;}
function info10(id,idText,enText){return info9('ten-'+id,E(T(idText,enText)));}
function card10(title,body,size=''){return `<section class="ten-card ${size}"><h2>${title}</h2>${body}</section>`;}
function field10(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${E(value)}" ${extra}></label>`;}
function select10(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select></label>`;}
function form10(kind,body,id=''){if(kind==='revision'){const r=RM10.getRelease(ten,id),friday=new Date(ten.now+7*RM10.H).getUTCDay()===5;if(r?.service==='MAX'&&friday)body+=field10('hours',T('Batas perbaikan MAX (jam)','MAX correction window (hours)'),2,'number','min="1" max="24" required')+`<p class="full ten-note">${T('Sesuaikan dengan waktu penanganan Believe yang masih tersedia. Dua jam adalah contoh pratinjau.','Match the remaining Believe processing window. Two hours is a preview example.')}</p>`;}const labels={identity_correct:['Minta perbaikan','Request corrections'],bank_correct:['Minta perbaikan','Request corrections'],revision:['Kirim permintaan perbaikan','Send correction request'],bank:['Ajukan rekening','Submit bank details'],codes:['Simpan UPC/ISRC','Save UPC/ISRC'],live:['Konfirmasi Tayang','Confirm Live'],deliver:['Konfirmasi pengiriman','Confirm delivery'],contract:['Setujui kontrak','Accept contract'],purchase:['Buat tagihan','Create invoice'],plan:['Buat tagihan','Create invoice'],profile:['Simpan identitas','Save identity'],cancel_confirm:['Konfirmasi pembatalan','Confirm cancellation'],reject:['Tolak pengajuan','Reject submission'],resubmit:['Kirim perbaikan','Submit corrections'],question:['Kirim pertanyaan','Send question'],answer:['Kirim jawaban','Send response'],followup:['Simpan tindak lanjut','Save follow-up'],downgrade_offer:['Kirim pilihan ke label','Send option to label']};return `<form class="ten-form" data-ten-form="${kind}" data-id="${E(id)}">${body}<div class="full ten-actions"><button class="btn primary" type="submit">${T(...(labels[kind]||['Simpan','Save']))}</button></div></form>`;}
function check10(name,label){return `<label class="ten-check full"><input type="checkbox" name="${name}" required>${label}</label>`;}
function draftKey10(f){return ten.member+':'+f.dataset.tenForm+':'+(f.dataset.id||'');}
function restoreDrafts10(){for(const f of document.querySelectorAll('[data-ten-form]')){const draft=ten.formDrafts?.[draftKey10(f)];if(!draft)continue;for(const el of f.elements){if(!el.name||el.type==='hidden'||el.type==='checkbox')continue;if(draft[el.name]!==undefined)el.value=draft[el.name];}}}
function flushProfile10(){const f=document.querySelector('[data-ten-form=profile]');if(f){const v=Object.fromEntries(new FormData(f));RM10.act(ten,'profile',{name:v.name,identity:directoryIdentity(v)});}}
function modal10(title,body){const d=document.querySelector('#dialog');d.className='ten-dialog';d.innerHTML=`<button class="ten-close" data-ten="close" aria-label="${T('Tutup','Close')}">×</button><h2 id="dialog-title">${title}</h2>${body}`;restoreDrafts10();if(!d.open)d.showModal();}
function error10(code){const texts={permission:['Tindakan ini tidak tersedia untuk akunmu.','This action is unavailable for your account.'],credits:['Kredit belum cukup. Tambah kredit atau kurangi jumlah lagu.','Not enough credits. Add credits or reduce the track count.'],stale:['Pengajuan sudah ditangani atau berubah. Muat ulang rincian.','This request was handled or changed. Reload its details.'],pending:['Pengajuan sedang diperiksa. Tunggu hasil sebelum mengirim perubahan.','Your request is under review. Wait before submitting changes.'],identity:['Lengkapi identitas terlebih dahulu agar kontrak memuat pihak yang benar.','Complete the identity first so the contract names the correct party.'],prerequisites:['Pembayaran, identitas, atau persetujuan kontrak belum lengkap.','Payment, identity, or contract consent is incomplete.'],invoice_expired:['Tagihan tidak lagi tersedia. Buat tagihan baru.','This invoice is no longer available. Create a new invoice.'],invoice_pending:['Masih ada tagihan yang menunggu pembayaran.','An invoice is still awaiting payment.'],inactive:['Selesaikan aktivasi untuk mengirim rilisan.','Complete activation to submit releases.'],date:['Tanggal belum tersedia untuk layanan ini. Periksa pilihan tanggal dan batas Jumat pukul 12.00 WIB.','This date is unavailable. Check the service date and Friday noon cutoff.'],unchanged:['Lakukan perbaikan atau berikan tanggapan sebelum mengirim ulang.','Make a correction or provide a response before resubmitting.'],pause_used:['Jeda penjelasan sudah digunakan pada putaran revisi ini.','The clarification pause has already been used for this revision round.'],check:['Lengkapi konfirmasi pemeriksaan terlebih dahulu.','Complete the review confirmation first.'],evidence:['Simpan UPC/ISRC dan sertakan tautan tayang HTTPS yang sudah diperiksa.','Save UPC/ISRC and provide a checked HTTPS live link.'],reason:['Pilih atau tulis bagian yang perlu ditangani.','Select or describe what needs attention.'],bank:['Lengkapi bank, nomor rekening 6–24 angka, dan nama penerima.','Enter the bank, a 6–24 digit account number, and recipient name.'],save_failed:['Perubahan belum tersimpan. Coba lagi; kredit belum berubah.','Changes were not saved. Try again; credits are unchanged.'],state:['Kondisi pengajuan sudah berubah. Buka kembali rinciannya.','The request state has changed. Reopen its details.'],invalid:['Periksa kembali data yang diisi.','Please check the entered information.']};return T(...(texts[code]||texts.invalid));}
let status10=key=>{const map={draft:['Draft','Draft'],submitted:['Menunggu pemeriksaan','Awaiting review'],review:['Dalam pemeriksaan','In review'],revision:['Menunggu perbaikan label','Awaiting label corrections'],clarification:['Menunggu jawaban petugas','Awaiting staff response'],approved:['Siap dikirim','Ready to deliver'],delivered:['Dalam distribusi','In distribution'],followup:['Tindak lanjut Believe','Believe follow-up'],live:['Tayang','Live'],closed:['Ditutup','Closed'],cancel_requested:['Permintaan pembatalan','Cancellation requested']};return T(...(map[key]||[key,key]));};
function config10(){return "";}
function activationCount10(m){return [m.emailConfirmed,m.contract,!!m.identity.document,!!m.bank.approved].filter(Boolean).length;}
function releaseList10(rows){return rows.length?`<div class="ten-list">${rows.map(r=>`<div class="ten-item"><div><strong>${E(r.title)}</strong><small>${isLabel10()?E(r.artist):E(RM10.getMember(ten,r.member).name)} · ${r.tracks} ${T('lagu','tracks')} · ${r.service}</small></div><div class="ten-row">${tag10(status10(r.status),r.status==='live'?'green':['revision','followup'].includes(r.status)?'copper':'')}${b10('↗','release',r.id)}</div></div>`).join('')}</div>`:`<div class="ten-empty">${T('Belum ada pengajuan. Rilisanmu akan tampil di sini.','No submissions yet. Your releases will appear here.')}</div>`;}
function releases10(){const rows=ten.releases.filter(r=>!isLabel10()||r.member===ten.member);return `<div class="ten-grid">${card10(T('Daftar rilisan','Release list'),`${isLabel10()?b10(T('Buat rilisan','Create release'),'newrelease','','primary'):''}${releaseList10(rows)}`,'full')}</div>`;}
function activation10(){const m=member10(),pending=m.application?.status==='pending';return `<div class="ten-grid">${card10(T(pending?'Akun sedang diperiksa':'Aktivasi akun',pending?'Your account is under review':'Account activation'),`<div class="ten-stepbar">${[T('Akun & kontak','Account & contact'),T('Persetujuan kontrak','Contract consent'),T('Identitas label','Label identity'),T('Rekening penerima','Payout account')].map((l,i)=>`<button class="ten-step ${tenStep===i+1?'active':''} ${[m.emailConfirmed,m.contract,m.identity.document,m.bank.approved][i]?'done':''}" data-ten="step" data-id="${i+1}">${i+1}<span>${l}</span></button>`).join('')}</div>${pending?`<p>${T('Pengajuan identitas telah diterima. Kamu dapat melengkapi rekening sambil menunggu.','Your identity application was received. You can add bank details while waiting.')}</p>`:''}${m.application?.status==='correction'?`<div class="ten-inline-msg">${E(m.application.note)}</div>`:''}${stepContent10(m)}<div class="ten-actions">${b10(T('Simpan & lanjutkan nanti','Save & continue later'),'later')}${!pending?b10(T('Kirim untuk diperiksa','Submit for review'),'apply','','primary'):''}</div>`,'full')}</div>`;}
function stepContent10(m){if(tenStep===1)return `<div class="ten-row"><div><h3>${E(m.name)}</h3><p>${E(m.email)}</p>${tag10(T('Email terkonfirmasi','Email confirmed'),'green')}</div>${tag10(m.plan)}</div>`;if(tenStep===2)return `<div class="ten-note"><h3>${T('Persetujuan layanan distribusi','Distribution service consent')}</h3><p>${T('Penanggung jawab','Responsible person')}: <strong>${E(m.identity.person||'—')}</strong><br>${T('Label','Label')}: ${E(m.name)} · ${m.plan}</p><p>${T('Label menyatakan memiliki kewenangan atas materi yang dikirim. Data pengiriman harus akurat. Hak layanan mengikuti paket dan kredit yang tersedia.','The label declares authority over submitted content. Submission information must be accurate. Service access follows the selected plan and available credits.')}</p>${info10('contract','Naskah ringkas ini hanya contoh UX, bukan kontrak hukum final. Persetujuan terikat pada versi identitas yang dikirim.','This abbreviated text is a UX sample, not a final legal contract. Consent is bound to the submitted identity version.')}${m.contract?tag10(T('Sudah disetujui','Accepted'),'green'):form10('contract',check10('consent',T('Saya sudah membaca dan menyetujui kontrak.','I have read and accept the contract.')))}</div>`;if(tenStep===4)return bankForm10(m);return `${m.application?.status==='pending'?identityRead10(m.application.snapshot):form10('profile',field10('name',T('Nama label','Label name'),m.name,'text','required')+field10('person',T('Nama penanggung jawab','Responsible person'),m.identity.person,'text','required')+directoryLocationFields(m.identity)+`<div class="full">${m.identity.document?tag10(T('Dokumen contoh tersedia','Sample document available'),'green'):''}<div class="ten-actions">${b10(T('Atur foto identitas','Adjust identity image'),'document')}</div>${info10('identity','Gunakan dokumen contoh dari Studio. OCR dan pemeriksaan keaslian belum terhubung; jangan unggah identitas asli.','Use the sample document from Studio. OCR and authenticity checks are not connected; do not upload real identity documents.')}</div>`)}`;}
function bankForm10(m){const p=m.bank.pending||{},a=m.bank.approved;return `${a?`<div class="ten-note">${tag10(T('Rekening disetujui','Approved bank'),'green')}<p>${E(a.bank)} · ${E(a.number)}<br>${E(a.holder)}</p></div>`:''}${p.status==='pending'?`<p>${T('Rekening sedang diperiksa.','Bank details are under review.')}</p>`:`${p.status==='correction'?`<div class="ten-inline-msg">${E(p.note)}</div>`:''}${form10('bank',directoryBankField(p.bank||'')+field10('number',T('Nomor rekening','Account number'),p.number||'','text','required inputmode="numeric" pattern="[0-9]{6,24}"')+field10('holder',T('Nama pemilik rekening','Account holder'),p.holder||m.identity.person,'text','required'))}`}<p class="ten-note">${T('Rekening baru hanya digunakan setelah disetujui. Tujuan transaksi yang sudah diproses tidak berubah otomatis.','A new account is used only after approval. Existing payment destinations do not change automatically.')}</p>`;}
function account10(){const m=member10();return `<div class="ten-grid">${card10(T('Profil label','Label profile'),`<h3>${E(m.name)}</h3><p>${E(m.email)}<br>${E(m.identity.person)}</p>${tag10(m.active?T('Aktif','Active'):T('Belum aktif','Not active'),m.active?'green':'')}<hr class="ten-divider">${form10('social',field10('social',T('Tautan resmi (opsional)','Official link (optional)'),m.social,'url'))}${info10('reputation','Centang reputasi tidak berasal dari aktivasi. Tautan opsional tidak menjamin atau menghalangi centang. Standar reputasi V9 berada di Platform → Standar & Penanda.','Reputation verification does not come from activation. An optional link neither guarantees nor blocks a badge. V9 reputation standards remain under Platform → Standards & Indicators.')}`)}${card10(T('Rekening penerima','Payout account'),bankForm10(m))}${card10(T('Kontrak & langganan','Contract & subscription'),`<p>${m.plan} · ${m.period==='year'?T('Tahunan','Annual'):T('Bulanan','Monthly')}</p><p>${T('Mulai layanan','Service started')}: ${date10(m.activatedAt)}<br>${T('Berakhir','Ends')}: ${date10(m.subscriptionEnd)}</p>${m.contract?tag10(T('Persetujuan tercatat','Consent recorded'),'green'):tag10(T('Belum disetujui','Not accepted'))}`,'full')}</div>`;}
function credits10(){const m=member10(),b=RM10.balance(ten,m);return `<div class="ten-grid">${card10(T('Paket saat ini','Current plan'),`<div class="ten-row"><div><div class="ten-value">${m.plan}</div><p>${m.subscriptionEnd?date10(m.subscriptionEnd):T('Bayar sesuai kredit yang dibeli','Pay for purchased credits')}</p></div>${b10(T('Lihat pilihan paket','View plans'),'plans')}</div>${m.plan!=='Flex'&&!RM10.daily(ten,m)&&m.active?`<p>${T('Paket berakhir. Kredit tambahan tetap bisa digunakan melalui layanan Flex.','Your plan has ended. Purchased credits remain usable through Flex.')}</p>`:''}${invoice10(m)}${info10('pricing','Rp35.000/kredit adalah acuan Flex. Harga tahunan memakai pembanding lama: Go Rp350.000, Pro Rp500.000, Business Rp1.500.000. Harga bulanan belum ditetapkan; pembayaran di sini hanya simulasi.','Rp35,000/credit is the Flex reference. Annual comparisons use old prices: Go Rp350,000, Pro Rp500,000, Business Rp1,500,000. Monthly prices are undecided; payment here is simulated.')}`,'full')}${card10(T('Kredit harian','Daily credits'),`<div class="ten-value">${b.daily}</div><p>${T('Diperbarui pukul 00.00 WIB','Renews at 00:00 WIB')}</p>`,'third')}${card10(T('Kredit tambahan','Purchased credits'),`<div class="ten-value">${b.paid}</div>${b10(T('Tambah kredit','Add credits'),'purchase','','primary')}`,'third')}${card10(T('Kredit pengganti','Replacement credits'),`<div class="ten-value">${b.replacement}</div>${m.lots.filter(l=>l.type==='replacement'&&l.available>0&&l.expires>ten.now).map(l=>`<p>${l.available} · ${date10(l.expires,true)} WIB</p>`).join('')}`,'third')}${card10(T('Alokasi rilisan','Release allocations'),releaseList10(ten.releases.filter(r=>r.member===m.id&&r.creditState==='reserved')),'full')}</div>`;}
function invoice10(m){if(!m.invoice)return '';const i=m.invoice,plan=i.plan||m.plan;return `<hr class="ten-divider"><p>${E(i.id)} · ${i.kind==='credits'||plan==='Flex'?i.credits+' '+T('kredit','credits')+' · '+money10(i.credits*35000):plan+' · '+(i.period==='year'?money10({Go:350000,Pro:500000,Business:1500000}[plan])+' / '+T('tahun','year'):T('Bulanan — harga belum ditetapkan','Monthly — price not yet set'))}</p>${i.status==='pending'?`<p>${T('Bayar sebelum','Pay before')} ${date10(i.expires,true)} WIB · <strong>${Math.max(0,Math.floor((i.expires-ten.now)/RM10.H))} ${T('jam tersisa','hours left')}</strong></p>${b10(T('Lanjutkan pembayaran','Continue payment'),'pay','','primary')}`:tag10(i.status==='paid'?T('Sudah dibayar','Paid'):T('Tagihan kedaluwarsa','Invoice expired'),i.status==='paid'?'green':'copper')}`;}
function members10(){const rows=ten.members.filter(m=>!m.active);return `<div class="ten-grid">${card10(T('Calon Member','Prospective Members'),`<div class="ten-scroll"><table class="ten-table"><thead><tr>${[T('Label','Label'),T('Paket','Plan'),T('Pembayaran','Payment'),T('Progres','Progress'),T('Kondisi','Status'),''].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(m=>`<tr><td>${E(m.name)}<small>${E(m.email)}</small></td><td>${m.plan}</td><td>${m.paid?T('Sudah dibayar','Paid'):T('Belum dibayar','Unpaid')}</td><td>${activationCount10(m)}/4<div class="ten-progress"><i style="width:${activationCount10(m)*25}%"></i></div></td><td>${m.application?.status==='pending'?T('Menunggu pemeriksaan','Awaiting review'):m.application?.status==='correction'?T('Perlu perbaikan','Needs corrections'):T('Belum lengkap','Incomplete')}</td><td>${m.application?.status==='pending'?b10('↗','identity',m.id):'—'}</td></tr>`).join('')}</tbody></table></div>${!rows.length?`<div class="ten-empty">${T('Semua calon member sudah aktif.','All prospective members are now active.')}</div>`:''}`,'full')}</div>`;}
function identityRead10(i){return `<div class="ten-id"><small>RILIS MUSIK · ${T('DOKUMEN CONTOH','SAMPLE DOCUMENT')}</small><strong>${E(i.person)}</strong><small>${E(i.address)}<br>${E(i.postal)} · ${E(i.country)}</small></div>`;}
function identityModal10(id){const m=RM10.getMember(ten,id);if(ten.role==='label'||!m.application)return;modal10(T('Pemeriksaan identitas','Identity review'),`<h3>${E(m.name)}</h3>${identityRead10(m.application.snapshot)}<p>${T('Kontrak disetujui dan pembayaran terkonfirmasi.','Contract accepted and payment confirmed.')}</p><div class="ten-actions">${b10(T('Setujui Aktivasi','Approve activation'),'identity_approve',id+'|'+m.application.version,'primary')}</div>${form10('identity_correct',`<input type="hidden" name="version" value="${m.application.version}">${select10('note',T('Minta perbaikan','Request corrections'),[[T('Foto identitas belum terbaca. Unggah foto yang lebih jelas.','The identity photo is unreadable. Upload a clearer image.'),T('Foto tidak terbaca','Unreadable photo')],[T('Alamat belum lengkap. Lengkapi alamat sesuai dokumen.','The address is incomplete. Complete it using the document.'),T('Alamat belum lengkap','Incomplete address')],[T('Nama penanggung jawab tidak sesuai dokumen. Periksa kembali.','The responsible person name does not match. Please check it.'),T('Nama tidak sesuai','Name mismatch')]],'')}`,id)}`);}
function banks10(){if(ten.role!=='super')return '';return `<div class="ten-grid">${card10(T('Pengajuan rekening','Bank applications'),ten.members.filter(m=>m.bank.pending?.status==='pending').map(m=>`<div class="ten-item"><div><strong>${E(m.name)}</strong><small>${E(m.bank.pending.bank)} · ${E(m.bank.pending.holder)}</small></div>${b10('↗','bank_review',m.id)}</div>`).join('')||`<div class="ten-empty">${T('Tidak ada rekening yang menunggu pemeriksaan.','No bank accounts awaiting review.')}</div>`,'full')}</div>`;}
function bankModal10(id){if(ten.role!=='super')return;const m=RM10.getMember(ten,id),p=m.bank.pending;if(!p)return;modal10(T('Pemeriksaan rekening','Bank review'),`<h3>${E(m.name)}</h3>${identityRead10(m.identity)}<p class="ten-bank">${E(p.bank)} · ${E(p.number)}<br><strong>${E(p.holder)}</strong></p>${m.bank.approved?`<p>${T('Rekening sebelumnya','Previous account')}: ${E(m.bank.approved.bank)} · ${E(m.bank.approved.number)}</p>`:''}<div class="ten-actions">${b10(T('Setujui rekening','Approve bank account'),'bank_approve',id+'|'+p.version,'primary')}</div>${form10('bank_correct',`<input type="hidden" name="version" value="${p.version}">${select10('note',T('Minta perbaikan','Request corrections'),[[T('Periksa kembali bank dan nomor rekening yang diajukan.','Check the submitted bank and account number.'),T('Bank atau nomor rekening salah','Incorrect bank or account number')],[T('Nama penerima tidak sesuai. Periksa nama pemilik rekening.','The recipient name does not match. Check the account holder.'),T('Nama penerima tidak sesuai','Recipient mismatch')],[T('Jelaskan hubungan penerima dengan penanggung jawab label.','Explain the recipient relationship to the label representative.'),T('Hubungan penerima perlu dijelaskan','Explain recipient relationship')]],'')}`,id)}`);}
function notification10(){const items=ten.notifications.filter(n=>n.member===ten.member).slice(0,5);const labels={activated:['Akun labelmu sudah aktif.','Your label account is active.'],revision:['Ada perbaikan yang perlu dikirim.','Corrections are required.'],reminder:['Batas revisi semakin dekat.','The revision deadline is approaching.'],timeout:['Pengajuan ditutup karena batas revisi terlewat.','Submission closed after the revision deadline.'],live:['Rilisan telah dikonfirmasi tayang.','Your release was confirmed live.'],identity_correction:['Identitas perlu diperbaiki.','Identity corrections are required.'],bank_correct:['Rekening perlu diperbaiki.','Bank details need corrections.'],bank_approve:['Rekening sudah disetujui.','Your bank account was approved.'],answer:['Petugas sudah menjawab pertanyaanmu.','Staff have answered your question.'],rejected:['Pengajuan tidak dapat dilanjutkan.','The submission could not proceed.'],date_error:['Tanggal rilis sedang kami perbaiki. Kamu tidak perlu mengirim ulang.','We are correcting the release date. No resubmission is needed.'],offer:['Ada pilihan jadwal dan layanan pengganti.','A revised date and service are available.'],not_found:['Rilisan belum ditemukan. Tim menindaklanjuti ke Believe.','The release was not found. Our team is following up with Believe.']};return items.map(n=>`<div class="ten-item"><div>${E(T(...(labels[n.key]||[T('Pengajuan tercatat','Submission recorded'),T('Pengajuan tercatat','Submission recorded')])))}<small>${date10(n.at,true)}</small></div></div>`).join('')||`<div class="ten-empty">${T('Belum ada pembaruan.','No updates yet.')}</div>`;}
function history10(){const rows=ten.events.filter(e=>!isLabel10()||e.target===ten.member||ten.releases.some(r=>r.id===e.target&&r.member===ten.member));const names={profile_edit:['Perubahan identitas disimpan atau diajukan','Identity changes saved or submitted'],profile_photo:['Foto profil diperbarui','Profile photo updated'],profile_approve:['Perubahan identitas disetujui','Identity changes approved'],profile_correct:['Perbaikan identitas diminta','Identity corrections requested'],draft:['Draft disimpan','Draft saved'],submit:['Pengajuan dikirim','Submission sent'],start:['Pemeriksaan dimulai','Review started'],revision:['Perbaikan diminta','Corrections requested'],resubmit:['Perbaikan dikirim','Corrections submitted'],approve:['Rilisan disetujui','Release approved'],deliver:['Dikirim ke Believe','Delivered to Believe'],codes:['Kode disimpan','Identifiers saved'],live:['Tayang dikonfirmasi','Live confirmed'],credit_return:['Alokasi kredit dikembalikan','Credit allocation returned'],identity_approve:['Aktivasi disetujui','Activation approved'],identity_correct:['Perbaikan identitas diminta','Identity correction requested'],bank_approve:['Rekening disetujui','Bank approved'],bank_correct:['Perbaikan rekening diminta','Bank correction requested'],bank_submit:['Rekening diajukan','Bank submitted'],apply:['Aktivasi diajukan','Activation submitted'],profile:['Identitas disimpan','Identity saved'],contract:['Kontrak disetujui','Contract accepted'],pay:['Pembayaran dikonfirmasi','Payment confirmed'],invoice:['Tagihan dibuat','Invoice created'],timeout:['Batas revisi terlewat','Revision deadline passed'],question:['Penjelasan diminta','Clarification requested'],answer:['Penjelasan diberikan','Clarification answered'],reject:['Pengajuan ditolak','Submission rejected'],cancel:['Pembatalan diminta','Cancellation requested'],cancel_confirm:['Pembatalan dikonfirmasi','Cancellation confirmed'],not_found:['Rilisan belum ditemukan','Release not found'],date_error:['Kesalahan tanggal dilaporkan','Date error reported'],followup:['Tindak lanjut dicatat','Follow-up recorded'],downgrade_offer:['Perubahan jadwal ditawarkan','Schedule change offered'],downgrade_accept:['Perubahan jadwal disetujui','Schedule change accepted'],reopen:['Draft baru dari pengajuan sebelumnya','New draft from previous submission']};return `<div class="ten-grid">${card10(T('Riwayat','History'),rows.slice(0,70).map(e=>`<div class="ten-item"><div><strong>${T(...(e.kind==='profile_edit'?(e.note==='submitted'?['Perubahan identitas diajukan','Identity changes submitted']:['Identitas diperbarui','Identity updated']):(names[e.kind]||[e.kind,e.kind])))}</strong><small>${E(e.target)} · ${date10(e.at,true)} · ${E(e.actor)}</small></div></div>`).join('')||`<div class="ten-empty">${T('Belum ada tindakan.','No actions yet.')}</div>`,'full')}</div>`;}
function plans10(){modal10(T('Pilihan paket','Plan selection'),form10('plan',select10('plan',T('Paket','Plan'),['Flex','Go','Pro','Business'].map(v=>[v,v]),member10().plan)+select10('period',T('Periode','Period'),[['month',T('Bulanan','Monthly')],['year',T('Tahunan','Annual')]],member10().period)+field10('credits',T('Kredit awal Flex','Initial Flex credits'),1,'number','min="1" max="500"')+`<p class="full">${T('Tagihan berlaku 24 jam. Masa langganan dimulai ketika akun siap beroperasi.','Invoices expire after 24 hours. Subscription time starts when the account can operate.')}</p>`));}
function purchase10(){modal10(T('Tambah kredit','Add credits'),`<p>${T('1 kredit = 1 lagu. Pilihan berikut hanya membantu mengisi jumlah pembelian.','1 credit = 1 track. These shortcuts only fill the purchase quantity.')}</p><div class="ten-actions">${[['single','Single'],['ep','EP'],['album','Album'],['manual',T('Jumlah sendiri','Custom')]].map(([id,l])=>b10(l,'creditpreset',id)).join('')}</div>${form10('purchase',field10('credits',T('Jumlah kredit','Credit quantity'),1,'number','min="1" max="500" required id="ten-quantity"')+`<div><small>${T('Total pembayaran','Payment total')}</small><div class="ten-value" id="ten-price">${money10(35000)}</div></div><p class="full">${T('Kredit tidak dikunci untuk jenis rilisan tertentu dan tidak kedaluwarsa.','Credits are not locked to a release type and never expire.')}</p>`)}`);}
function service10(v){return `<small class="ten-mini">Rilis Musik</small><div class="ten-service" style="--selected:${['Standard','Express','MAX'].indexOf(v)}">${['Standard','Express','MAX'].map(x=>`<button type="button" data-ten="service" data-id="${x}" class="${v===x?'active':''}">${x}</button>`).join('')}</div>`;}
function releaseForm10(id){const r=id?RM10.getRelease(ten,id):null;if(!member10().active){toast(T('Selesaikan aktivasi terlebih dahulu.','Complete activation first.'));return;}tenDraftService=r?.service||'Standard';modal10(T('Siapkan rilisan','Prepare a release'),`<form data-ten-form="release_draft" data-id="${id||''}"><div class="ten-form">${field10('title',T('Judul rilisan','Release title'),r?.title||'','text','required')}${field10('artist',T('Artis','Artist'),r?.artist||'','text','required')}${field10('tracks',T('Jumlah lagu','Track count'),r?.tracks||1,'number','min="1" max="12" required id="ten-tracks"')}</div><div style="margin-top:22px">${service10(tenDraftService)}</div><div id="ten-service-detail">${serviceDetail10(tenDraftService,r?.tracks||1,r?.date)}</div>${info10('service','Biaya Standard 1, Express 2, MAX 3 kredit per lagu adalah angka simulasi yang belum final. Kalender libur belum terhubung. Jumat MAX sebelum 12.00 WIB dapat memilih Minggu.','Standard 1, Express 2, MAX 3 credits per track are provisional preview values. Holiday calendars are not connected. Friday MAX before noon WIB allows Sunday release.')}<div class="ten-actions"><button class="btn primary" type="submit">${T('Simpan draft','Save draft')}</button></div></form>`);}
function serviceDetail10(service,n,selected){const first=RM10.earliest(ten,service);return `<div class="ten-date"><small>${T('KREDIT YANG DIALOKASIKAN','CREDIT ALLOCATION')}</small><strong>${n*({Standard:1,Express:2,MAX:3}[service])} ${T('kredit','credits')}</strong><small>${T('Terpakai final setelah Tayang dikonfirmasi.','Final usage after Live confirmation.')}</small></div>${first?field10('date',T('Tanggal rilis','Release date'),selected&&selected>=first?selected:first,'date',`required min="${first}"`):`<div class="ten-inline-msg">${T('MAX untuk Minggu tidak tersedia setelah Jumat pukul 12.00 WIB. Pilih Express atau Standard.','MAX for Sunday is unavailable after Friday noon WIB. Choose Express or Standard.')}</div>`}`;}
function releaseActions106(r){const id=r.id,staff=!isLabel10(),closed=r.status==='closed';let actions='';
 if(isLabel10()){
  if(r.status==='draft')actions+=b10(T('Ubah draft','Edit draft'),'editrelease',id)+b10(T('Kirim rilisan','Submit release'),'submit',id,'primary');
  if(r.status==='revision')actions+=form10('resubmit',field10('title',T('Judul','Title'),r.title)+field10('artist',T('Artis','Artist'),r.artist)+`<label class="full">${T('Perbaikan atau tanggapan','Correction or response')}<textarea name="response" required></textarea></label>`,id)+(!r.pauseUsed?b10(T('Minta penjelasan','Ask for clarification'),'ask',id):'');
  if(!['closed','live','cancel_requested'].includes(r.status))actions+=b10(T('Batalkan pengajuan','Cancel submission'),'cancel',id,'danger');
  if(closed)actions+=b10(T('Ajukan ulang','Submit again'),'reopen',id);
  if(r.offer)actions+=`<div class="ten-date"><small>${T('PILIHAN PENGGANTI','REVISED OPTION')}</small><strong>${r.offer.service} · ${date10(r.offer.date)}</strong>${b10(T('Setujui perubahan & pengembalian selisih','Accept change & credit difference'),'downgrade_accept',id)}</div>`;
 }else{
  if(r.status==='submitted')actions+=b10(T('Mulai pemeriksaan','Start review'),'start',id,'primary');
  if(r.status==='review')actions+=b10(T('Setujui rilisan','Approve release'),'approve',id,'primary')+b10(T('Minta perbaikan','Request corrections'),'revisionform',id);
  if(r.status==='clarification')actions+=form10('answer',`<label class="full">${T('Jawaban untuk label','Response to label')}<textarea name="note" required></textarea></label>`,id);
  if(r.status==='approved')actions+=form10('deliver',check10('checked',T('Tanggal di Believe sudah sesuai dengan tanggal permintaan label.','The Believe date matches the label requested date.')),id);
  if(['delivered','followup'].includes(r.status)){
   actions+=`<hr class="ten-divider"><h3>${T('Kode rilisan','Release identifiers')}</h3>${form10('codes',field10('upc','UPC',r.upc||'','text','required')+field10('isrc',T('ISRC per lagu (pisahkan dengan koma)','ISRC per track (comma separated)'),r.isrc||'','text','required'),id)}<p class="ten-note">${T('Menyimpan kode tidak mengubah status menjadi Tayang.','Saving identifiers does not mark the release Live.')}</p><h3>${T('Periksa hasil distribusi','Check distribution results')}</h3>${b10(T('Sudah tayang','Already live'),'liveform',id,'primary')}${b10(T('Belum ditemukan','Not found'),'not_found',id)}${b10(T('Laporkan kesalahan tanggal','Report a date error'),'dateerror',id)}`;
   if(r.status==='followup')actions+=form10('followup',`<label class="full">${T('Tindak lanjut ke Believe','Follow-up with Believe')}<textarea name="note" required>${E(r.followup||'')}</textarea></label>`,id)+b10(T('Tawarkan jadwal pengganti','Offer a revised schedule'),'offerform',id);
  }
  if(r.status==='live')actions+=b10(T('Koreksi penandaan Tayang','Correct Live marking'),'dateerror',id);
  if(r.status==='cancel_requested')actions+=form10('cancel_confirm',check10('checked',T('Proses sudah dihentikan; pembatalan ke Believe sudah dipastikan jika pernah dikirim.','Processing has stopped; Believe cancellation is confirmed if previously delivered.')),id);
  if(!['draft','closed','live','cancel_requested'].includes(r.status))actions+=b10(T('Tolak pengajuan','Reject submission'),'rejectform',id,'danger');
 }
return actions;}
function releaseModal10(id){const r=RM10.getRelease(ten,id);if(!r||isLabel10()&&r.member!==ten.member)return;tenDetail=id;const staff=!isLabel10(),closed=r.status==='closed',alloc=r.allocation.reduce((a,x)=>a+x.amount,0);const actions=releaseActions106(r);
 modal10(E(r.title),`<div class="ten-row">${tag10(status10(r.status),r.status==='live'?'green':'')}<span>${r.service} · ${r.tracks} ${T('lagu','tracks')}</span></div><p>${E(r.artist)} · ${E(RM10.getMember(ten,r.member).name)}</p><div class="ten-date"><small>${T('TANGGAL RILIS YANG DIMINTA','REQUESTED RELEASE DATE')}</small><strong>${date10(r.originalDate||r.date)}</strong><small>${T('Cocokkan tanggal ini pada kalender Believe.','Match this date on the Believe calendar.')}</small>${r.originalDate&&r.originalDate!==r.date?`<p>${T('Jadwal pengganti disetujui','Agreed revised date')}: ${date10(r.date)}</p>`:''}</div><p>${r.creditState==='reserved'?T('Kredit dialokasikan','Credits reserved'):r.creditState==='consumed'?T('Kredit terpakai','Credits used'):r.creditState==='returned'?T('Alokasi sudah dilepas sesuai sumber kredit','Allocation released according to credit source'):T('Belum menggunakan kredit','No credit allocated')}: ${alloc}</p>${r.note?`<div class="ten-inline-msg">${E(r.note)}${r.deadline?`<br>${T('Kirim sebelum','Submit before')} ${date10(r.deadline,true)} WIB`:''}</div>`:''}${r.question?`<p>${T('Pertanyaan label','Label question')}: ${E(r.question)}</p>`:''}${r.answer?`<p>${T('Jawaban petugas','Staff response')}: ${E(r.answer)}</p>`:''}${r.response?`<p>${T('Perbaikan terakhir','Latest correction')}: ${E(r.response)}</p>`:''}${r.baseline&&staff?`<p>${T('Sebelumnya','Previously')}: ${E(r.baseline.title)} · ${E(r.baseline.artist)}</p>`:''}${r.incident==='date_error'?`<p>${T('Tanggal rilis sedang kami perbaiki. Label tidak perlu mengirim ulang.','We are correcting the release date. No label resubmission is needed.')}</p>`:''}${closed?`<p>${r.reason==='timeout'?T('Batas revisi terlewat. Data tetap tersimpan.','The revision deadline passed. Your data is retained.'):E(r.reason)}</p>`:''}<div class="ten-actions">${actions}</div>`);
 // Forms must remain full-width, even when mixed with action buttons.
 document.querySelectorAll('.ten-dialog .ten-actions>form').forEach(f=>f.style.width='100%');
}
let studio10;
function scene10(key){const pref={lang:ten.lang,theme:ten.theme,layout:ten.layout};ten=Object.assign(RM10.seed(),pref);let m=member10();
 if(key==='new'){ten.member='embun';m=member10();m.paid=false;m.lots=[];ten.page='credits';}
 if(key==='identity'){ten.member='embun';m=member10();RM10.act(ten,'profile',{identity:{person:'Laras Senja',address:'Jl. Nada 8, Jakarta',postal:'10110',document:true,country:'Indonesia'}});RM10.act(ten,'contract');RM10.act(ten,'apply');ten.role='admin';ten.page='members';}
 if(key==='bank'){m.bank.approved=null;m.bank.pending={bank:'BCA',number:'12345678',holder:'Nama berbeda',status:'pending',version:1};m.bank.version=1;ten.role='super';ten.page='banks';}
 if(key==='expired'){m.subscriptionEnd=new Date(ten.now-1).toISOString();m.lots=m.lots.filter(l=>l.type==='paid');ten.page='credits';}
 if(key==='fridaylate')ten.now=Date.parse('2026-09-25T13:00:00+07:00');
 if(['revision','date','replacement'].includes(key)){
  const id=RM10.act(ten,'draft',{title:'Cahaya Pulang',artist:'Nara',tracks:1,service:'Standard',date:RM10.earliest(ten,'Standard')});RM10.act(ten,'submit',{id});ten.role='admin';RM10.act(ten,'start',{id});
  if(key==='revision'){RM10.act(ten,'revision',{id,note:T('Perbaiki penulisan nama artis sesuai profil resmi.','Correct the artist name to match the official profile.')});ten.now+=22*RM10.H;ten.role='label';}
  if(key==='date'){RM10.act(ten,'approve',{id});RM10.act(ten,'deliver',{id,checked:true});RM10.act(ten,'date_error',{id,note:T('Tanggal yang dipilih di Believe lebih lambat dari permintaan label.','The Believe date was entered later than requested.')});}
  if(key==='replacement'){ten.now+=24*RM10.H;RM10.act(ten,'reject',{id,note:T('Pengajuan ditolak setelah pergantian hari.','Submission rejected after the day changed.')});ten.role='label';ten.page='credits';}
  if(key!=='replacement')ten.page='releases';
 }
 if(ten.role!=='label')state.user=ten.role==='super'?'jeck':'adovi';RM10.tick(ten);save10();closeModal();render();
}
function welcome10(){const m=member10();if(m.active&&!m.welcome){modal10('',`<div class="ten-welcome"><p>${T('Selamat datang di Rilis Musik','Welcome to Rilis Musik')}</p><h1>${E(m.name)}</h1><p>${T('Akun labelmu sudah aktif. Saatnya menghadirkan musikmu.','Your label account is active. It is time to share your music.')}</p>${b10(T('Buka Dashboard','Open Dashboard'),'welcome','','primary')}</div>`);}}
function document10(){modal10(T('Foto identitas','Identity image'),`<p>${T('Gunakan gambar contoh untuk mencoba orientasi dan pemotongan.','Use the sample image to try rotation and cropping.')}</p><div id="ten-document" class="ten-id" style="transition:transform .2s"><small>IDENTITY · SAMPLE ONLY</small><strong>LARAS SENJA</strong><small>0000000000000000<br>Jl. Nada 8 · Indonesia</small></div><div class="ten-actions">${b10(T('Putar 90°','Rotate 90°'),'rotate')}${b10(T('Sesuaikan area','Adjust crop'),'crop')}${b10(T('Gunakan dokumen contoh','Use sample document'),'docsave','','primary')}</div>${info10('doc','Kontrol ini mendemonstrasikan penyesuaian tampilan, bukan OCR atau pengesahan dokumen. Tidak menerima unggahan KTP asli dalam prototype.','These controls demonstrate image framing, not OCR or identity approval. This prototype does not accept real identity uploads.')}`);}
document.addEventListener('click',async event=>{
 const el=event.target.closest('[data-ten]');if(!el)return;event.preventDefault();event.stopImmediatePropagation();const a=el.dataset.ten,id=el.dataset.id;
 try{
  if(a==='close'){closeModal();return;}
  if(a==='page'){ten.page=id;closeModal();render();return;}
  if(a==='language'){ten.lang=ten.lang==='id'?'en':'id';closeModal();render();return;}
  if(a==='theme'){ten.theme=ten.theme==='light'?'dark':'light';render();return;}
  if(a==='config')return;
  if(a==='studio'){studio10();return;}
  if(a==='role'){ten.role=id;ten.page='home';closeModal();render();if(isLabel10())welcome10();return;}
  if(a==='member'){ten.member=id;ten.role='label';ten.page='home';closeModal();render();welcome10();return;}
  if(a==='scene'){scene10(id);return;}
  if(a==='advance'){ten.now+=Number(id)*RM10.H;RM10.tick(ten);save10();closeModal();render();return;}
  if(a==='fail'){ten.failNext=true;save10();closeModal();toast(T('Prochain enregistrement simulé en échec.','Next save will fail.').replace('Prochain enregistrement simulé en échec.','Penyimpanan berikutnya akan gagal dalam simulasi.'));return;}
  if(a==='step'){flushProfile10();tenStep=Number(id);activationPopup102();return;}
  if(a==='plans'){plans10();return;}
  if(a==='purchase'){purchase10();return;}
  if(a==='creditpreset'){const input=document.querySelector('#ten-quantity');input.value=({single:1,ep:4,album:10,manual:1}[id]);input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();return;}
  if(a==='identity'){identityModal10(id);return;}
  if(a==='bank_review'){bankModal10(id);return;}
  if(a==='newrelease'||a==='editrelease'){releaseForm10(a==='editrelease'?id:null);return;}
  if(a==='release'){releaseModal10(id);return;}
  if(a==='service'){tenDraftService=id;document.querySelector('.ten-service').style.setProperty('--selected',['Standard','Express','MAX'].indexOf(id));document.querySelectorAll('.ten-service button').forEach(b=>b.classList.toggle('active',b.dataset.id===id));document.querySelector('#ten-service-detail').innerHTML=serviceDetail10(id,Number(document.querySelector('#ten-tracks').value)||1);return;}
  if(a==='welcome'){member10().welcome=true;ten.page='home';closeModal();render();return;}
  if(a==='document'){document10();return;}
  if(a==='rotate'){const d=document.querySelector('#ten-document');d.dataset.rotation=String((Number(d.dataset.rotation)||0)+90);d.style.transform=`rotate(${d.dataset.rotation}deg)`;return;}
  if(a==='crop'){const d=document.querySelector('#ten-document');d.style.clipPath=d.style.clipPath?'':'inset(7% round 12px)';return;}
  if(a==='docsave'){RM10.act(ten,'profile',{identity:{document:true}});save10();activationPopup102();return;}
  if(a==='later'){const f=document.querySelector('[data-ten-form=profile]');if(f){const v=Object.fromEntries(new FormData(f));RM10.act(ten,'profile',{name:v.name,identity:directoryIdentity(v)});}ten.page='home';closeModal();render();toast(T('Draft tersimpan.','Draft saved.'));return;}
  if(['revisionform','rejectform','dateerror','ask'].includes(a)){const titles={revisionform:T('Minta perbaikan','Request corrections'),rejectform:T('Tolak pengajuan','Reject submission'),dateerror:T('Koreksi kesalahan internal','Correct an internal error'),ask:T('Minta penjelasan','Ask for clarification')};modal10(titles[a],form10(({revisionform:'revision',rejectform:'reject',dateerror:'date_error',ask:'question'})[a],`<label class="full">${T('Keterangan','Details')}<textarea name="note" required></textarea></label>${a==='revisionform'?`<label class="ten-check full"><input type="checkbox" name="same">${T('Masalah sama dengan putaran sebelumnya','Same issue as the previous round')}</label>`:''}`,id));return;}
  if(a==='liveform'){modal10(T('Konfirmasi Tayang','Confirm Live'),form10('live',field10('link',T('Tautan platform yang diperiksa','Checked platform link'),'','url','required placeholder="https://…"')+check10('checked',T('Saya sudah memeriksa seluruh tautan distribusi yang tersedia.','I have checked all available distribution links.')),id));return;}
  if(a==='offerform'){modal10(T('Jadwal pengganti','Revised schedule'),form10('downgrade_offer',select10('service','Rilis Musik',[['Standard','Standard'],['Express','Express']],'Standard')+field10('date',T('Tanggal pengganti','Revised date'),RM10.earliest(ten,'Standard'),'date','required'),id));return;}
  if(a==='apply')flushProfile10();
  let payload={id};if(['identity_approve','bank_approve'].includes(a)){const parts=id.split('|');payload={member:parts[0],version:Number(parts[1]),identityReview:el.dataset.identityReview};}
  const result=RM10.act(ten,a,payload);save10();closeModal();render();if(a==='reopen')releaseForm10(result);else if(['start','approve','submit','not_found','downgrade_accept'].includes(a))releaseModal10(id);else toast(T('Perubahan tersimpan.','Changes saved.'));
 }catch(e){save10();toast(error10(e.message));}
},true);
document.addEventListener('submit',event=>{const f=event.target;if(!f.dataset.tenForm)return;event.preventDefault();event.stopImmediatePropagation();if(!f.reportValidity())return;const v=Object.fromEntries(new FormData(f)),kind=f.dataset.tenForm,id=f.dataset.id;
 try{let result;
  if(kind==='profile')result=RM10.act(ten,'profile',{name:v.name,identity:directoryIdentity(v)});
  else if(kind==='contract'){result=RM10.act(ten,'contract');acceptContract102(member10());}
  else if(kind==='bank')result=RM10.act(ten,'bank_submit',v);
  else if(kind==='social'){member10().social=v.social;}
  else if(kind==='plan')result=RM10.act(ten,'invoice',{...v,credits:Number(v.credits)});
  else if(kind==='purchase')result=RM10.act(ten,'invoice',{plan:member10().plan,period:member10().period,kind:'credits',credits:Number(v.credits)});
  else if(kind==='release_draft')result=RM10.act(ten,'draft',{...v,id:id||undefined,tracks:Number(v.tracks),service:tenDraftService});
  else if(['identity_correct','bank_correct'].includes(kind))result=RM10.act(ten,kind,{...v,member:id,version:Number(v.version)});
  else result=RM10.act(ten,kind,{...v,id,checked:!!v.checked,same:!!v.same});
  if(ten.formDrafts)delete ten.formDrafts[draftKey10(f)];save10();closeModal();if(['plan','purchase'].includes(kind))ten.page='credits';render();
  if(['profile','contract'].includes(kind)&&!member10().active)activationPopup102();else if(kind==='release_draft')releaseModal10(result);else if(['codes','deliver','followup','resubmit','answer','downgrade_offer'].includes(kind))releaseModal10(id);else toast(T('Perubahan tersimpan.','Changes saved.'));
 }catch(e){toast(error10(e.message));save10();}
},true);
document.addEventListener('input',event=>{const f=event.target.closest('[data-ten-form]');if(f){ten.formDrafts=ten.formDrafts||{};ten.formDrafts[draftKey10(f)]=Object.fromEntries(new FormData(f));save10();}if(event.target.id==='ten-quantity'){document.querySelector('#ten-price').textContent=money10(Math.max(0,Number(event.target.value)||0)*35000);}if(event.target.id==='ten-tracks'){const date=document.querySelector('#ten-service-detail [name=date]')?.value;document.querySelector('#ten-service-detail').innerHTML=serviceDetail10(tenDraftService,Number(event.target.value)||1,date);}});

