/* V10.3: one V9 shell, shared controls and connected role workflows. */
const base102={dashboard,sidebar:sidebar5,module:modulePage,labels:labelsPage9,action:handleAction,studio:studio8,task:taskModal,attention:taskAttention,step:stepContent10,account:account10};
let labelTab102='all';
let labelSummary102=null;
let clock102=null;
const navBase102=nav;
nav=function(){const list=navBase102();if(!isLabel10()&&state.mode==='platform'&&!list.some(x=>x[0]==='labels9'))list.push(['labels9','people']);return list;};
if(!ten.workspace102){ten.workspace102=true;ten.role='super';ten.page='home';state.user='jeck';state.mode='platform';state.page='dashboard';}
state.lang=ten.lang;state.theme=ten.theme;
const module102=id=>{v4.module=id;state.mode='platform';state.page='module';};
function connectCatalogue102(){
 if(ten.catalogueLinked102)return;
 ten.catalogueLinked102=true;
 const former={role:ten.role,member:ten.member};
 for(const name of [...new Set([...data.v9.labels.map(l=>l.name),...data.tasks.filter(x=>x.kind==='release').map(x=>x.label)])]){
  let m=ten.members.find(m=>m.name===name);const source=data.v9.labels.find(l=>l.name===name);
  if(!m){m=JSON.parse(JSON.stringify(ten.members[0]));m.id=source?.id||'catalogue-'+ten.members.length;m.name=name;m.email=m.id.toLowerCase()+'@example.test';m.identity={person:T('Penanggung jawab ','Representative of ')+name,address:'Jl. Musik 12, Jakarta',postal:'10110',country:'Indonesia',document:true};m.plan=source?.plan||'Go';m.bank={approved:null,pending:null,version:0};m.lots=[{id:'paid-'+m.id,type:'paid',available:10,expires:null}];m.application=null;m.invoice=null;m.contractSignatures102=undefined;ten.members.push(m);}
  m.source9=source?.id||null;if(source&&m.active&&m.plan!=='Flex')m.subscriptionEnd=source.expiry+'T23:59:59+07:00';
 }
 for(const x of data.tasks.filter(x=>x.kind==='release'&&!x.linked102)){
  if(ten.releases.some(r=>r.id===x.id))continue;
  const m=ten.members.find(m=>m.name===x.label);ten.member=m.id;ten.role='label';
  const id=modelAct102(ten,'draft',{title:x.title,artist:m.identity.person,tracks:1,service:'Standard',date:RM10.earliest(ten,'Standard')});modelAct102(ten,'submit',{id});
  if(x.stage!=='queued'){ten.role='admin';modelAct102(ten,'start',{id});if(['approval','believe','done'].includes(x.stage))modelAct102(ten,'approve',{id});if(['believe','done'].includes(x.stage))modelAct102(ten,'deliver',{id,checked:true});if(x.stage==='correction')modelAct102(ten,'revision',{id,note:T('Periksa nama artis pada metadata dan kirim perbaikannya.','Check the artist name in the metadata and submit the correction.')});}
  const r=RM10.getRelease(ten,id);r.id=x.id;r.handler102=x.handler;r.imported102=true;if(x.overdue&&x.stage==='believe'){ten.role='admin';modelAct102(ten,'not_found',{id:r.id});}
  for(const e of ten.events)if(e.target===id)e.target=r.id;for(const n of ten.notifications)if(n.ref===id)n.ref=r.id;
 }
 Object.assign(ten,former);RM10.tick(ten);
}
function role102(role,member){flushProfile10();closeModal();closePop();ten.role=role;ten.page='home';if(member)ten.member=member;if(role!=='label')state.user=role==='super'?'jeck':'adovi';state.mode='platform';state.page='dashboard';v8.loggedOut=false;v8.lastInput=Date.now();save10();render();if(role==='label')welcome10();}
function route102(id){
 if(isLabel10()&&id==='activation')return activationPopup102();
 if(isLabel10()&&id==='credits')return creditPopup102();
 closeModal();ten.page='home';
 if(id==='home')return go('dashboard','platform');
 if(id==='members'){labelTab102='prospects';return go('labels9','platform');}
 if(id==='account'&&!isLabel10())return account8();
 module102(id);render();window.scrollTo(0,0);
}
function b10(label,action,id='',kind=''){return `<button type="button" class="btn ${kind}" data-ten="${action}" data-id="${E(id)}">${label}</button>`;}
function card10(title,body,size=''){return `<section class="panel pad ten-card ${size}"><h2>${title}</h2>${body}</section>`;}
function tag10(label,color=''){return `<span class="badge ${color==='copper'?'amber':color}">${label}</span>`;}
function modal10(title,body){modal(title,body,true);$('#dialog').classList.add('flow102');restoreDrafts10();}
function activationPopup102(){if(!isLabel10())return;modal10(T('Aktivasi akun','Account activation'),activation10());}
function creditPopup102(){if(!isLabel10())return;modal10(T('Paket & kredit','Plan & credits'),credits10());$('#dialog').classList.add('credit102');}
const purchaseBase102=purchase10;
purchase10=function(){if(!isLabel10())return;purchaseBase102();$('#dialog').classList.add('credit102');};
function activationBar102(){const m=member10();if(m.active)return '';const done=[m.emailConfirmed,m.contract,!!m.identity.document,!!m.bank.approved],pending=m.application?.status==='pending';return `<section class="activation102" aria-label="${T('Progres aktivasi','Activation progress')}"><div><strong>${T(pending?'Akun sedang diperiksa':'Aktivasi akun',pending?'Your account is under review':'Account activation')}</strong><div class="activation-track102">${[T('Akun','Account'),T('Kontrak','Contract'),T('Identitas','Identity'),T('Rekening','Bank')].map((x,i)=>`<span class="${done[i]?'done':''}"><i>${done[i]?'✓':i+1}</i>${x}</span>`).join('')}</div></div>${b10(T(pending?'Lihat status':'Lanjutkan',pending?'View status':'Continue'),'page','activation','primary')}</section>`;}
function labelAttention102(){const m=member10(),r=ten.releases.find(r=>r.member===m.id&&r.status==='revision');if(r){const urgent=r.deadline-ten.now<=2*RM10.H;return `<section class="attention9 ${urgent?'red9':''}"><div class="spread"><h2><span class="status-dot9"></span>${T('Perbaikan rilisan menunggu','Release corrections pending')}</h2>${b10('↗','release',r.id)}</div><p>${E(r.title)} · ${T('Kirim sebelum','Submit before')} ${date10(r.deadline,true)} WIB</p></section>`;}if(m.active&&!m.bank.approved)return `<section class="attention9"><div class="spread"><h2><span class="status-dot9"></span>${T(m.bank.pending?.status==='correction'?'Perbaiki rekening':m.bank.pending?.status==='pending'?'Rekening sedang diperiksa':'Lengkapi rekening',m.bank.pending?.status==='correction'?'Correct your bank details':m.bank.pending?.status==='pending'?'Bank details under review':'Complete your bank details')}</h2>${b10('↗','page','account')}</div><p>${E(m.bank.pending?.note||T('Rilisan dapat dikirim. Rekening diperlukan saat mengajukan pencairan.','You can submit releases. A bank account is needed to request payouts.'))}</p></section>`;return '';}
function labelHome102(){const m=member10(),rs=ten.releases.filter(r=>r.member===m.id),summaries=[['Total rilisan','Total releases',rs.length],['Draft','Draft',rs.filter(r=>r.status==='draft').length],['Dalam penanganan','In progress',rs.filter(r=>['submitted','review','approved','delivered','followup'].includes(r.status)).length],['Perlu perbaikan','Needs corrections',rs.filter(r=>r.status==='revision').length],['Tayang','Live',rs.filter(r=>r.status==='live').length]];return pageHead(E(m.name),T('Musikmu, katalogmu, langkah berikutnya.','Your music, your catalogue, your next step.'))+labelAttention102()+`<div class="five-stats">${summaries.map(([id,en,n],i)=>`<article class="stat6"><span>${T(id,en)}</span><strong>${n}</strong><small>${T('Rilisan','Releases')}</small><button class="stat-open8" data-ten="summary102" data-id="${i}" aria-label="${T('Lihat','View')} ${T(id,en)}">${arrow8()}</button></article>`).join('')}</div><div class="dashboard-grid shared-label102">${deck('label-releases',T('Rilisan Saya','My Releases'),'',releaseList10(rs.slice(0,5))+`<div class="ten-actions">${b10(T('Buat rilisan','Create release'),'newrelease','','primary')}${b10(T('Lihat semua','View all'),'page','releases')}</div>`,8)}${deck('label-updates',T('Pembaruan','Updates'),'',notification10(),4)}</div>`;}
dashboard=function(){return isLabel10()?labelHome102():base102.dashboard();};
sidebar5=function(){if(!isLabel10())return base102.sidebar();const links=[['home','grid','Dashboard','Dashboard'],['releases','release','Rilisan','Releases'],['account','people','Profil & Rekening','Profile & Bank'],['contracts','shield','Kontrak','Contracts'],['history','activity','Riwayat','History']];return `<aside class="side5 ${v5.collapsed?'small':''}" aria-label="${T('Navigasi utama','Main navigation')}"><div class="side-brand"><span class="mark">RM</span><strong>RILIS MUSIK</strong></div><button class="collapse-side" data-action="v5-collapse" aria-label="${T('Ukuran sidebar','Sidebar size')}">${arrow8()}</button><div class="side-scroll">${links.map(([id,ic,a,b])=>`<button class="side-link ${(id==='home'?state.page==='dashboard':state.page==='module'&&v4.module===id)?'active':''}" data-ten="page" data-id="${id}" title="${T(a,b)}">${icon(ic)}<span>${T(a,b)}</span></button>`).join('')}</div><div class="side-person"><span class="mark">${E(member10().name.slice(0,1))}</span><div><small>Label</small><strong>${E(member10().name)}</strong><small>${E(member10().plan)}</small></div></div></aside>`;};
function identityDetails102(m){return `<dl class="identity102">${[[T('Nama label','Label name'),m.name],[T('Email','Email'),m.email],[T('Penanggung jawab','Representative'),m.identity.person],[T('Alamat','Address'),m.identity.address],[T('Kode pos','Postal code'),m.identity.postal],[T('Negara','Country'),m.identity.country],[T('Dokumen identitas','Identity document'),m.identity.document?T('Tersimpan','Saved'):T('Belum dilengkapi','Not provided')]].map(([a,b])=>`<div><dt>${a}</dt><dd>${E(b||'—')}</dd></div>`).join('')}</dl>`;}
account10=function(){const m=member10();return `<div class="ten-grid">${card10(T('Identitas label','Label identity'),identityDetails102(m)+(m.active?'':b10(T('Lengkapi identitas','Complete identity'),'page','activation')),'full')}${card10(T('Rekening penerima','Payout account'),bankForm10(m),'full')}${card10(T('Kontrak layanan','Service contract'),contractSummary102(m),'full')}</div>`;};
function labels102(){const rows=labelTab102==='prospects'?ten.members.filter(m=>!m.active):ten.members;return pageHead(T('Label & Akun','Labels & Accounts'),'')+`<div class="tabs">${[['all','Semua label','All labels'],['prospects','Calon member','Prospective members']].map(([id,a,b])=>b10(T(a,b),'labeltab102',id,labelTab102===id?'active':'text')).join('')}</div>`+card10(T('Label','Labels'),`<div class="table-wrap"><table><thead><tr><th>Label</th><th>${T('Paket','Plan')}</th><th>${T('Aktivasi','Activation')}</th><th>${T('Progres','Progress')}</th><th></th></tr></thead><tbody>${rows.map(m=>`<tr><td>${E(m.name)}<small class="block102">${E(m.email)}</small></td><td>${tag10(m.plan)}</td><td>${tag10(m.active?T('Akun aktif','Account active'):m.application?.status==='pending'?T('Sedang diperiksa','Under review'):m.application?.status==='correction'?T('Perlu perbaikan','Needs corrections'):T('Belum lengkap','Incomplete'),m.active?'green':'')}</td><td>${activationCount10(m)}/4</td><td>${b10('↗',m.application?.status==='pending'?'identity':'labeldetail102',m.id)}</td></tr>`).join('')||`<tr><td colspan="5">${T('Tidak ada calon member dalam daftar.','No prospective members in this list.')}</td></tr>`}</tbody></table></div>`,'full')+(labelTab102==='all'&&me().super?`<details class="existing-labels102"><summary>${T('Label katalog lainnya','Other catalogue labels')}</summary>${base102.labels()}</details>`:'');}
labels102=function(){const tabs=`<div class="tabs">${[['all','Semua label','All labels'],['prospects','Calon member','Prospective members']].map(([id,a,b])=>b10(T(a,b),'labeltab102',id,labelTab102===id?'active':'text')).join('')}${me().super?btn(T('Pemeriksaan rekening','Bank review'),'v4-module','data-id="banks"','text'):''}</div>`;if(labelTab102==='prospects')return pageHead(T('Manajemen Label','Label Management'),'')+tabs+members10();
 const rows=ten.members.filter(m=>{const l=data.v9.labels.find(l=>l.id===m.source9);return m.name.toLowerCase().includes(v9.labelSearch.toLowerCase())&&(v9.labelFilter==='all'||l&&(v9.labelFilter==='verified'&&verification9(l).status==='verified'||v9.labelFilter==='review'&&(verification9(l).status==='review'||verification9(l).newReview)||v9.labelFilter==='restricted'&&accessLabel9(l)!=='normal'||v9.labelFilter==='nonoperational'&&activity9(l)==='nonoperational'));});
 return pageHead(T('Manajemen Label','Label Management'),'')+tabs+`<section class="panel pad"><div class="table-controls7"><input id="label-search9" type="search" value="${E(v9.labelSearch)}" placeholder="${T('Cari label','Search labels')}" aria-label="${T('Cari label','Search labels')}"><select id="label-filter9" aria-label="${T('Tampilkan label','Show labels')}">${[['all','Semua label','All labels'],['verified','Terverifikasi','Verified'],['review','Dalam peninjauan','Under review'],['restricted','Akses dibatasi','Restricted access'],['nonoperational','Nonoperasional','Nonoperational']].map(([v,a,b])=>`<option value="${v}" ${v9.labelFilter===v?'selected':''}>${T(a,b)}</option>`).join('')}</select></div><div class="table-wrap"><table class="labels-table9"><thead><tr><th>Label</th><th>${T('Pencapaian','Achievement')}</th><th>${T('Akses','Access')}</th><th>${T('Aktivitas','Activity')}</th><th>${T('Aktivasi','Activation')}</th><th></th></tr></thead><tbody>${rows.map(m=>{const l=data.v9.labels.find(l=>l.id===m.source9),achievement=l&&emblem9(l);return `<tr><td><button class="label-name9" data-ten="labeldetail102" data-id="${m.id}"><span class="label-avatar9">${E(m.name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</span><span><strong>${E(m.name)} ${l?verificationMark9(l):''} <span class="plan9">${E(m.plan)}</span></strong><small>${E(m.id)}${l?.master?' · '+T('Master multi-label','Multi-label master'):''}</small></span></button></td><td>${achievement?`<span class="emblem9 ${achievement.toLowerCase()}">✦ ${achievement}</span>`:'—'}</td><td>${l?badge(labelStatus9('access',accessLabel9(l)),accessLabel9(l)==='blocked'?'red':accessLabel9(l)==='limited'?'amber':''):T('Normal','Normal')}</td><td>${l?labelStatus9('activity',activity9(l)):T('Aktif','Active')}</td><td>${m.active?T('Akun aktif','Account active'):m.application?.status==='pending'?T('Sedang diperiksa','Under review'):m.application?.status==='correction'?T('Perlu perbaikan','Needs corrections'):T('Belum lengkap','Incomplete')}</td><td>${b10('↗',m.application?.status==='pending'?'identity':'labeldetail102',m.id)}</td></tr>`;}).join('')||`<tr><td colspan="6">${T('Tidak ada label yang cocok.','No matching labels.')}</td></tr>`}</tbody></table></div></section>`;};
labelsPage9=labels102;
const contractModule102=modules.find(m=>m.id==='contracts');contractModule102.access='super';
modules.find(m=>m.id==='kyc').title=['Pemeriksaan Aktivasi','Activation Review'];
modulePage=function(){if(isLabel10()){const headings={releases:T('Rilisan','Releases'),account:T('Profil & Rekening','Profile & Bank'),contracts:T('Kontrak','Contracts'),history:T('Riwayat','History')};if(!headings[v4.module])return labelHome102();return pageHead(headings[v4.module],'')+({releases:releases10,account:account10,contracts:contracts102,history:history10})[v4.module]();}if(v4.module==='releases')return pageHead(T('Rilisan','Releases'),'')+releases10()+legacyReleases102();if(v4.module==='labels')return labels102();if(v4.module==='kyc')return pageHead(T('Pemeriksaan Aktivasi','Activation Review'),'')+members10();if(v4.module==='banks')return me().super?pageHead(T('Verifikasi Rekening','Bank Review'),'')+banks10():empty(T('Menu tidak tersedia','Menu unavailable'));if(v4.module==='contracts')return me().super?pageHead(T('Kontrak Label','Label Contracts'),'')+contracts102():empty(T('Menu tidak tersedia','Menu unavailable'));return base102.module();};
function legacyReleases102(){const rs=visibleTasks().filter(x=>x.kind==='release'&&!x.linked102);return rs.length?`<section class="panel pad"><h2>${T('Katalog dalam penanganan','Catalogue in progress')}</h2>${rs.map(x=>workRow9(x,true)).join('')}</section>`:'';}
function syncTasks102(){
 data.tasks=data.tasks.filter(x=>!x.linked102&&!ten.releases.some(r=>r.id===x.id));
 for(const r of ten.releases.filter(r=>!['draft','closed'].includes(r.status))){const m=RM10.getMember(ten,r.member),stage=({submitted:'queued',review:'review',revision:'correction',clarification:'review',approved:'review',delivered:'believe',followup:'believe',cancel_requested:'review',partial:'believe',partial_closed:'done',live:'done'})[r.status];data.tasks.unshift({id:r.id,title:r.title,label:m.name,kind:'release',stage,handler:Object.prototype.hasOwnProperty.call(r,'handler102')?r.handler102:(r.status==='submitted'?null:'adovi'),pct:r.status==='live'?100:null,last:new Date(ten.now).toISOString(),created:RM10.day(ten.now),due:r.date,overdue:r.status==='followup',reason:[r.note||'Tindak lanjut rilisan',r.note||'Release follow-up'],linked102:true});}
 for(const m of ten.members){if(m.application?.status==='pending')data.tasks.unshift({id:'activation:'+m.id,title:T('Aktivasi · ','Activation · ')+m.name,label:m.name,kind:'claim',stage:'queued',handler:null,last:null,created:RM10.day(ten.now),due:RM10.day(ten.now),pct:0,linked102:true});if(ten.role==='super'&&m.bank.pending?.status==='pending')data.tasks.unshift({id:'bank:'+m.id,title:T('Rekening · ','Bank account · ')+m.name,label:m.name,kind:'finance',stage:'approval',handler:'jeck',last:new Date(ten.now).toISOString(),created:RM10.day(ten.now),due:RM10.day(ten.now),pct:null,linked102:true});}
 const events={submitted:['Mengajukan rilisan','Submitted a release'],submit:['Mengajukan rilisan','Submitted a release'],start:['Memulai pemeriksaan','Started review'],revision:['Meminta perbaikan','Requested corrections'],approve:['Menyetujui rilisan','Approved release'],deliver:['Mengirim ke Believe','Delivered to Believe'],live:['Mengonfirmasi tayang','Confirmed live'],identity_approve:['Menyetujui aktivasi','Approved activation'],bank_correct:['Meminta perbaikan rekening','Requested bank corrections'],bank_approve:['Menyetujui rekening','Approved bank account'],followup:['Menindaklanjuti rilisan','Followed up release']};
 data.events=data.events.filter(e=>!e.linked102);for(const e of ten.events.slice().reverse()){if(!events[e.kind])continue;const r=RM10.getRelease(ten,e.target),who=e.actor==='label'?null:(people.some(p=>p.id===e.actorId102)?e.actorId102:r?.handler102||(e.actor==='super'?'jeck':e.actor==='admin'?'adovi':null));data.events.unshift({id:'flow-'+e.id,who,obj:e.target,text:events[e.kind],time:new Date(e.at+7*RM10.H).toISOString().slice(11,16),day:RM10.day(e.at),category:'work',linked102:true});}
}
taskAttention=function(x){if(x.linked102){const r=RM10.getRelease(ten,x.id);return !!r&&(r.urgent102||['followup','cancel_requested','clarification'].includes(r.status)||(r.status==='revision'&&r.deadline-ten.now<=2*RM10.H));}return base102.attention(x);};
taskModal=function(id){if(id.startsWith('activation:'))return identityModal10(id.split(':')[1]);if(id.startsWith('bank:'))return bankModal10(id.split(':')[1]);if(RM10.getRelease(ten,id))return releaseModal10(id);return base102.task(id);};
const modelAct102=RM10.act;
RM10.act=function(s,action,payload={}){const staffActions=['identity_approve','identity_correct','bank_approve','bank_correct','start','revision','answer','approve','deliver','codes','not_found','date_error','followup','live','reject','cancel_confirm','downgrade_offer'];if(s.role==='admin'&&staffActions.includes(action)&&['read','blocked'].includes(access8(payload.id)))throw Error('permission');const before=s.events[0]?.id,result=modelAct102(s,action,payload);if(s.role!=='label')for(const e of s.events){if(e.id===before)break;e.actorId102=state.user;}if(['start','approve','answer','deliver','followup'].includes(action)){const r=RM10.getRelease(s,payload.id);if(r)r.handler102=state.user;}return result;};
const rowBase102=workRow9,stepsBase102=steps9,recordsBase102=todayRecords;
const guardedAction102=RM10.act;
RM10.act=function(s,action,payload={}){const m=RM10.getMember(s,payload.member||s.member),source=data.v9.labels.find(l=>l.id===m?.source9);if(s.role==='label'&&['draft','submit'].includes(action)&&source?.restriction)throw Error('permission');const result=guardedAction102(s,action,payload);if(source&&action==='pay'){source.plan=m.plan;if(m.subscriptionEnd)source.expiry=RM10.day(Date.parse(m.subscriptionEnd));}if(source&&action==='identity_approve'){source.complete=true;source.contact=true;}return result;};
steps9=function(x){const r=RM10.getRelease(ten,x.id);if(!r)return stepsBase102(x);const labels=[T('Pemeriksaan','Review'),T('Siap dikirim','Ready to deliver'),T('Distribusi','Distribution'),T('Tayang','Live')],n=['live','partial_closed'].includes(r.status)?3:['delivered','followup','partial'].includes(r.status)?2:r.status==='approved'?1:0;return `<div class="steps9" style="--steps:4;--complete:${n/3*100}%">${labels.map((l,i)=>`<div class="step9 ${i<n?'done':i===n?'current':''}"><i class="${i===n&&r.status==='review'?'processing':''}">${i<n?'✓':''}</i><small>${l}</small></div>`).join('')}</div>`;};
workRow9=function(x,steps=false){const r=RM10.getRelease(ten,x.id);if(!r)return rowBase102(x,steps);return `<article class="work-row9"><div class="work-top9"><div><strong>${E(r.title)}</strong><small>${E(x.label)} · ${r.id}</small></div><div class="work-badges9">${condition8(x)}${r.status==='submitted'?'':badge(status10(r.status),'blue')}</div>${btn(arrow8(),'task',`data-id="${r.id}" aria-label="${T('Buka pekerjaan','Open work')} ${r.id}"`,'icon9')}</div>${steps?steps9(x):''}</article>`;};
todayRecords=function(){return [...recordsBase102(),...ten.events.filter(e=>e.kind==='live'&&RM10.day(e.at)===day()).map(e=>({id:'flow-'+e.id,staff:e.actorId102||'adovi',title:RM10.getRelease(ten,e.target)?.title||e.target,kind:'release',time:new Date(e.at+7*RM10.H).toISOString().slice(11,16)}))];};
function ensureContracts102(){if(!ten.contracts102)ten.contracts102=[{id:'CT-1',title:'Perjanjian Distribusi Musik',titleEn:'Music Distribution Agreement',body:'Label menyatakan memiliki kewenangan atas materi yang dikirim. Data pengiriman harus akurat. Hak layanan mengikuti paket dan kredit yang tersedia.',bodyEn:'The label declares authority over submitted content. Submission information must be accurate. Service access follows the selected plan and available credits.',at:ten.now,author:'jeck'}];for(const m of ten.members){if(m.contract&&!m.contractSignatures102)m.contractSignatures102=[{id:ten.contracts102[0].id,at:m.activatedAt||ten.now,identityVersion:m.version}];}}
function acceptContract102(m){ensureContracts102();const c=ten.contracts102.at(-1);m.contractSignatures102=m.contractSignatures102||[];if(!m.contractSignatures102.some(x=>x.id===c.id&&x.identityVersion===m.version))m.contractSignatures102.push({id:c.id,at:ten.now,identityVersion:m.version});save10();}
function contractSummary102(m){ensureContracts102();const signed=m.contractSignatures102?.at(-1),c=ten.contracts102.find(x=>x.id===signed?.id);return `<p>${c?E(ten.lang==='en'?c.titleEn||c.title:c.title):T('Persetujuan belum lengkap.','Consent is not complete.')}</p><p>${m.plan}${m.subscriptionEnd?' · '+T('Sampai ','Until ')+date10(m.subscriptionEnd):''}</p>${b10(T('Lihat kontrak','View contract'),'contractview102',c?.id||ten.contracts102.at(-1).id)}`;}
function contracts102(){ensureContracts102();if(isLabel10()){const m=member10(),latest=ten.contracts102.at(-1),signed=m.contractSignatures102?.some(x=>x.id===latest.id);return card10(T('Kontrak label','Label contract'),contractSummary102(m)+(signed?'':`<div class="attention9"><h2><span class="status-dot9"></span>${T('Kontrak baru tersedia','A new contract is available')}</h2>${b10(T('Baca kontrak','Read contract'),'contractview102',latest.id)}</div>`),'full');}if(ten.role!=='super')return '';return `<div class="ten-grid">${card10(T('Dokumen kontrak','Contract documents'),`<div class="ten-actions">${b10(T('Buat perubahan kontrak','Create a contract revision'),'contractnew102','','primary')}</div>${ten.contracts102.slice().reverse().map((c,i)=>`<div class="ten-item"><div><strong>${E(ten.lang==='en'?c.titleEn||c.title:c.title)}</strong><small>${c.id} · ${date10(c.at)} · ${i===0?T('Naskah terbaru','Latest document'):T('Versi sebelumnya','Previous version')}</small></div>${b10('↗','contractview102',c.id)}</div>`).join('')}`,'full')}${card10(T('Persetujuan label','Label consents'),ten.members.map(m=>`<div class="ten-item"><div><strong>${E(m.name)}</strong><small>${m.contractSignatures102?.at(-1)?.id||T('Belum disetujui','Not accepted')} · ${m.plan}</small></div>${b10('↗','labeldetail102',m.id)}</div>`).join(''),'full')}</div>`;}
function contractView102(id){ensureContracts102();const c=ten.contracts102.find(x=>x.id===id);if(!c)return;modal10(E(ten.lang==='en'?c.titleEn||c.title:c.title),`<p>${c.id} · ${date10(c.at)}</p><div class="contract-text102">${E(ten.lang==='en'?c.bodyEn||c.body:c.body)}</div>${info10('contract-sample','Dokumen dalam pratinjau adalah contoh. Perubahan membuat versi baru; persetujuan lama tetap tersimpan.','Documents in this preview are examples. Changes create a new version; earlier consents are retained.')}${isLabel10()&&!member10().contractSignatures102?.some(x=>x.id===id)&&id===ten.contracts102.at(-1).id?`<form data-contract102="accept"><label class="ten-check"><input type="checkbox" required>${T('Saya telah membaca dan menyetujui kontrak ini.','I have read and accept this agreement.')}</label><button class="btn primary" type="submit">${T('Setujui kontrak','Accept contract')}</button></form>`:''}`);}
stepContent10=function(m){if(tenStep!==2)return base102.step(m);ensureContracts102();const c=ten.contracts102.at(-1);return `<h3>${E(ten.lang==='en'?c.titleEn||c.title:c.title)}</h3><p>${E(m.name)} · ${E(m.identity.person||'—')}</p><div class="contract-text102">${E(ten.lang==='en'?c.bodyEn||c.body:c.body)}</div>${info10('activation-contract','Naskah ini adalah contoh untuk menguji alur persetujuan.','This is a sample document for testing the consent flow.')}${form10('contract',check10('accepted',T('Saya telah membaca dan menyetujui kontrak ini.','I have read and accept this agreement.')))}`;};
function service10(value){const services=['Standard','Express','MAX'],i=services.indexOf(value);return `<div class="service102" style="--level:${i*50}%;--thumb-offset:${i*24}px"><small>Rilis Musik</small><output id="service-label102">${value}</output><div class="service-track102"><div class="service-rail102"></div><div class="service-dots102"><i></i><i></i><i></i></div><i class="service-thumb102" aria-hidden="true"></i><input id="service-range102" type="range" min="0" max="2" step="1" value="${i}" aria-label="${T('Layanan rilisan','Release service')}" aria-valuetext="${value}"></div><div class="service-labels102">${services.map((x,j)=>`<button type="button" data-service102="${j}" class="${i===j?'active':''}">${x}</button>`).join('')}</div></div>`;}
function setService102(value){const previous=tenDraftService,n=Math.max(0,Math.min(2,Number(value)));tenDraftService=['Standard','Express','MAX'][n];const root=$('.service102');root.style.setProperty('--level',n*50+'%');root.style.setProperty('--thumb-offset',n*24+'px');$('#service-label102').textContent=tenDraftService;$('#service-range102').value=n;$('#service-range102').setAttribute('aria-valuetext',tenDraftService);root.querySelectorAll('[data-service102]').forEach((b,i)=>b.classList.toggle('active',n===i));const date=$('#ten-service-detail [name=date]')?.value;$('#ten-service-detail').innerHTML=serviceDetail10(tenDraftService,Number($('#ten-tracks').value)||1,date===RM10.earliest(ten,previous)?undefined:date);}
studio8=function(){base102.studio();const body=$('#dialog .dialog-body');body.insertAdjacentHTML('afterbegin',`<section class="studio-roles102"><h3>${T('Akun label','Label accounts')}</h3><div class="ten-actions">${ten.members.map(m=>b10(E(m.name),'member',m.id)).join('')}</div><p>${T('Ganti akun untuk mengikuti pengajuan yang sama.','Switch accounts to follow the same application.')}</p></section>`);body.insertAdjacentHTML('beforeend',`<h3>${T('Pengalaman label & petugas','Label & staff experiences')}</h3><div class="studio8-grid">${[['new','Calon member baru','New member'],['identity','Pemeriksaan aktivasi','Activation review'],['bank','Perbaikan rekening','Bank corrections'],['revision','Revisi mendekati tenggat','Revision near deadline'],['friday','MAX Jumat sebelum 12.00','Friday MAX before noon'],['fridaylate','MAX Jumat setelah 12.00','Friday MAX after noon'],['date','Kesalahan tanggal Believe','Believe date error'],['expired','Paket berakhir','Plan expired'],['replacement','Kredit pengganti','Replacement credits']].map(([id,a,b])=>b10(T(a,b),'scene',id)).join('')}</div><div class="ten-actions">${[1,4,24,49].map(n=>b10('+'+n+' '+T('jam','hours'),'advance',String(n))).join('')}</div>${info10('linked-preview','Skenario memulai contoh pengajuan baru. Pergantian akun mempertahankan pengajuan yang sama. Tidak ada pembayaran atau koneksi Believe nyata.','Scenarios start fresh example applications. Account switching retains the same application. No real payments or Believe connections are made.')}`);};
const studioUnified102=studio8;
studio8=function(){studioUnified102();$('.studio-roles102')?.remove();const select=$('#user9');select.innerHTML=`<optgroup label="${T('Tim Rilis Musik','Rilis Musik team')}">${people.map(p=>`<option value="${p.id}" ${!isLabel10()&&state.user===p.id?'selected':''}>${p.name} · ${p.super?'Super Admin':'Admin'}</option>`).join('')}</optgroup><optgroup label="Label">${ten.members.map(m=>`<option value="label:${m.id}" ${isLabel10()&&ten.member===m.id?'selected':''}>${E(m.name)} · Label</option>`).join('')}</optgroup>`;};
studio10=studio8;
const sceneBase102=scene10;
scene10=function(key){sceneBase102(key);ten.workspace102=true;if(ten.role!=='label')state.user=ten.role==='super'?'jeck':'adovi';const target=({new:'credits',expired:'credits',replacement:'credits'})[key]||ten.page;ten.page='home';state.mode='platform';state.page='dashboard';if(target==='members')labelTab102='prospects';if(target==='members')state.page='labels9';else if(['banks','releases'].includes(target))module102(target);closeModal();render();if(target==='credits')creditPopup102();};
handleAction=async function(b){const a=b.dataset.action,id=b.dataset.id;if(a==='v8-studio'||a==='guide')return studio8();if(a==='task'&&RM10.getRelease(ten,id))return releaseModal10(id);if(['nav','search-nav'].includes(a)&&['labels9','standards9','liability9','mywork9'].includes(b.dataset.page))return go(b.dataset.page,'platform');if(a==='v4-module'&&['labels','kyc','banks','releases','contracts'].includes(id)){if(['banks','contracts'].includes(id)&&!me().super)return;if(id==='labels'){labelTab102='all';return go('labels9','platform');}module102(id);closeModal();render();return;}if(isLabel10()){if(a==='account'||a==='v8-account')return route102('account');if(a==='notifications')return modal10(T('Pembaruan','Updates'),notification10());if(!['v5-collapse','theme','lang','close','v8-login','v8-logout','v8-studio'].includes(a))return;}return base102.action(b);};
const actionRoutes102=handleAction;
handleAction=async function(b){const a=b.dataset.action,id=b.dataset.id;if(a==='v8-reset')localStorage.removeItem(V10KEY);if(['scene9','v8-scene','v8-extra'].includes(a)&&isLabel10())role102('admin');const result=await actionRoutes102(b);if(['scene9','v8-scene'].includes(a)&&['red9','rednight9','normal','quiet'].includes(id)){for(const r of ten.releases)r.urgent102=false;if(id.startsWith('red')){const r=ten.releases.find(r=>r.status==='review');if(r)r.urgent102=true;}render();}return result;};
function normalizeAttention102(){document.querySelectorAll('.attention9,.decision7,.focus-banner,.ten-attention').forEach(e=>{e.classList.add('attention-shared102');if(e.matches('.red9,.red,.urgent8'))e.classList.add('critical102');});}
render=function(){
 if(clock102&&ten.now===clock102.now&&(v3.day!==clock102.day||v8.time!==clock102.time)){const time=Date.parse(v3.day+'T'+v8.time+':00+07:00');if(Number.isFinite(time))ten.now=time;}v3.day=RM10.day(ten.now);v8.time=new Date(ten.now+7*RM10.H).toISOString().slice(11,16);clock102={now:ten.now,day:v3.day,time:v8.time};
 RM10.tick(ten);if(!isLabel10())ten.role=me().super?'super':'admin';ten.lang=state.lang;ten.theme=state.theme;connectCatalogue102();ensureContracts102();syncTasks102();
 // Every role goes through the same V1–V9 render chain and component styles.
 tenOldRender();document.title='Rilis Musik · V10.3';document.body.dataset.role=ten.role;
 $('.version-pill').textContent='V10.3';$('.footer span').textContent='RILIS MUSIK · V10.3';
 if(!isLabel10()&&state.mode==='platform'&&me().super){const anchor=$('.side-scroll [data-page=labels9]');anchor?.insertAdjacentHTML('afterend',`<button class="side-link ${state.page==='module'&&v4.module==='contracts'?'active':''}" data-action="v4-module" data-id="contracts">${icon('shield')}<span>${T('Kontrak Label','Label Contracts')}</span></button>`);}
 if(isLabel10()){
  $('.header-left').innerHTML=`<span class="header-path">Label <i>/</i> ${state.page==='dashboard'?'Dashboard':({releases:T('Rilisan','Releases'),account:T('Profil & Rekening','Profile & Bank'),contracts:T('Kontrak','Contracts'),history:T('Riwayat','History')})[v4.module]||'Dashboard'}</span>`;
  $('.tools .search-trigger')?.remove();$('.tools [data-action=chat]')?.remove();const p=$('.tools [data-action=account]');p.innerHTML=`<span class="label-avatar102">${E(member10().name.slice(0,1))}</span>`;
  $('.tools [data-action=notifications] .dot')?.remove();const b=RM10.balance(ten,member10());$('.tools').insertAdjacentHTML('afterbegin',`<div class="label-commerce102">${b10(E(member10().plan)+' · '+T('Ubah paket','Change plan'),'plans')}${b10((b.daily+b.paid+b.replacement)+' '+T('kredit','credits'),'page','credits')}</div>`);
  document.querySelectorAll('.access8,.session8').forEach(e=>e.remove());
  if(state.page==='dashboard')$('.shell').insertAdjacentHTML('afterbegin',activationBar102());
  if(state.page==='dashboard'){const m=member10(),source=data.v9.labels.find(l=>l.id===m.source9);if(source?.restriction)$('.pagehead').insertAdjacentHTML('afterend',`<section class="attention9 ${source.restriction==='blocked'?'red9':''}"><h2><span class="status-dot9"></span>${T('Pengiriman rilisan belum tersedia','Release submissions are unavailable')}</h2><p>${T('Akses akun sedang dibatasi. Hubungi tim Rilis Musik untuk informasi lebih lanjut.','Account access is restricted. Contact Rilis Musik for more information.')}</p></section>`);else if(m.active&&m.plan!=='Flex'&&!RM10.daily(ten,m))$('.pagehead').insertAdjacentHTML('afterend',`<section class="attention9"><h2><span class="status-dot9"></span>${T('Paket '+m.plan+' berakhir',m.plan+' plan has ended')}</h2><p>${T('Kredit tambahan tetap dapat digunakan melalui layanan Flex.','Purchased credits remain available through Flex.')}</p>${b10(T('Perpanjang paket','Renew plan'),'plans')}</section>`);}
  if(state.page==='dashboard'){
   $('.five-stats .stat6')?.classList.add('featured');
   if(labelSummary102!==null){const i=labelSummary102,rs=ten.releases.filter(r=>r.member===ten.member).filter(r=>i===0||i===1&&r.status==='draft'||i===2&&['submitted','review','approved','delivered','followup'].includes(r.status)||i===3&&r.status==='revision'||i===4&&r.status==='live'),card=document.querySelectorAll('.five-stats .stat6')[i];card?.classList.add('selected');card?.querySelector('button')?.setAttribute('aria-expanded','true');$('.five-stats').insertAdjacentHTML('afterend',`<section class="panel filtered6"><div class="panel-head"><h2>${card?.querySelector('span')?.textContent||T('Rilisan','Releases')} · ${rs.length}</h2>${b10(T('Tutup filter','Close filter'),'summary102',String(i),'text')}</div><div class="body pad">${releaseList10(rs)}</div></section>`);}
  }
  document.querySelectorAll('[data-action=expand]').forEach(e=>e.remove());
 }
 normalizeAttention102();restoreDrafts10();save10();save8();
 if(ten.page==='credits'&&isLabel10()){ten.page='home';creditPopup102();}
};
window.addEventListener('click',e=>{const step=e.target.closest('[data-service102]');if(step){e.preventDefault();setService102(step.dataset.service102);return;}const b=e.target.closest('[data-ten]');if(!b)return;const a=b.dataset.ten,id=b.dataset.id;
 if(['page','role','member','studio','legacy','journey','summary102','labeltab102','labeldetail102','contractview102','contractnew102'].includes(a)){
  e.preventDefault();e.stopImmediatePropagation();
  if(a==='page')return route102(id);if(a==='role')return role102(id);if(a==='member')return role102('label',id);if(a==='studio')return studio8();
  if(a==='summary102'){labelSummary102=labelSummary102===Number(id)?null:Number(id);render();return;}
  if(a==='labeltab102'){labelTab102=id;return render();}
  if(a==='labeldetail102'){if(typeof labelDrawer104==='function')return labelDrawer104(id);if(isLabel10())return;const m=RM10.getMember(ten,id);return modal10(E(m.name),identityDetails102(m)+contractSummary102(m)+(ten.role==='super'?`<h3>${T('Rekening penerima','Payout account')}</h3><p>${E(m.bank.approved?.bank||'—')} · ${E(m.bank.approved?.number||'—')}</p>`:''));}
  if(a==='contractview102')return contractView102(id);
  if(a==='contractnew102'&&ten.role==='super')return modal10(T('Perubahan kontrak','Contract revision'),`<form class="ten-form" data-contract102="publish">${field10('title',T('Judul Indonesia','Indonesian title'),'','text','required')}${field10('titleEn',T('Judul Inggris','English title'),'','text','required')}<label class="full">${T('Naskah Indonesia','Indonesian text')}<textarea name="body" required rows="8"></textarea></label><label class="full">${T('Naskah Inggris','English text')}<textarea name="bodyEn" required rows="8"></textarea></label><p class="full">${T('Naskah baru tidak mengganti dokumen yang sudah disetujui label.','The new document does not replace agreements already accepted by labels.')}</p><button class="btn primary" type="submit">${T('Terbitkan versi baru','Publish new version')}</button></form>`);
 }
},true);
window.addEventListener('input',e=>{if(e.target.id==='service-range102')setService102(e.target.value);});
window.addEventListener('change',e=>{if(['user9','demo-user','user8'].includes(e.target.id)){e.stopImmediatePropagation();if(e.target.value.startsWith('label:'))return role102('label',e.target.value.slice(6));ten.role=people.find(p=>p.id===e.target.value)?.super?'super':'admin';state.user=e.target.value;state.mode='platform';state.page='dashboard';v8.loggedOut=false;closeModal();render();}},true);
window.addEventListener('submit',e=>{const f=e.target;if(!f.dataset.contract102)return;e.preventDefault();e.stopImmediatePropagation();if(!f.reportValidity())return;try{if(f.dataset.contract102==='publish'){if(ten.role!=='super')return;const values=Object.fromEntries(new FormData(f));ten.contracts102.push({...values,id:'CT-'+(ten.contracts102.length+1),at:ten.now,author:state.user});}else {if(!isLabel10())return;RM10.act(ten,'contract');acceptContract102(member10());}save10();closeModal();render();toast(T('Kontrak tersimpan.','Contract saved.'));}catch(err){toast(error10(err.message));}},true);
render();
