/* V10.3 extends the shared shell; no duplicate role workspace. */
const ui103={group:'single',period:'year',preset:'single',quantity:1,profileTab:'identity'};
const price103={Flex:35000,Go:350000,Pro:500000,Business:1500000};
const button103=(text,action,id='',cls='')=>`<button type="button" class="btn ${cls}" data-v103="${action}" data-id="${E(id)}">${text}</button>`;
const badge103=plan=>`<span class="plan9 plan103 ${E(plan.toLowerCase())}">${E(plan.toUpperCase())}</span>`;
function fullscreen103(title,body,cls){modal10(title,body);$('#dialog').classList.add('commerce103',cls);$('#dialog .dialog-body').scrollTop=0;}
function expiry103(m){return m.plan==='Flex'?T('Bayar sesuai jumlah lagu','Pay for the tracks you need'):m.subscriptionEnd?T('Berlaku sampai ','Valid until ')+date10(m.subscriptionEnd):T('Masa paket dimulai setelah akun aktif','Your plan starts when your account is active');}
function planFeatures103(plan){const common=[T('Distribusi ke platform musik digital','Distribution to digital music platforms'),T('Pemeriksaan metadata sebelum distribusi','Metadata review before distribution'),T('Laporan royalti dan katalog rilisan','Royalty reports and release catalogue')];return plan==='Flex'?[T('1 kredit untuk 1 lagu','1 credit for 1 track'),T('Kredit pembelian tidak kedaluwarsa','Purchased credits never expire'),...common]:[T('5 kredit harian, diperbarui setiap hari','5 daily credits, refreshed every day'),...common,...(plan==='Pro'||plan==='Business'?[T('Pendaftaran WAMI termasuk dalam paket','WAMI registration included'),T('Konten promosi JPG','Promotional JPG artwork')]:[]),...(plan==='Business'?[T('Kelola beberapa label dalam satu akun','Manage multiple labels in one account'),T('Dashboard pendapatan terintegrasi','Consolidated revenue dashboard')]:[])];}
plans10=function(){if(!isLabel10())return;const m=member10(),plans=ui103.group==='business'?['Pro','Business']:['Flex','Go','Pro'];fullscreen103(T('Pilihan paket','Choose your plan'),`<div class="plans103"><h1>${T('Pilih paketmu','Choose your plan')}</h1><p class="current-plan103">${badge103(m.plan)} <span>${T('Paket saat ini','Current plan')} · ${expiry103(m)}</span></p><div class="plan-switches103"><div class="switch103" role="group" aria-label="${T('Jenis pengelolaan','Management type')}">${[['single','Satu label','Single label'],['business','Multi-label','Multi-label']].map(([v,a,b])=>button103(T(a,b),'group',v,ui103.group===v?'selected':'')).join('')}</div><div class="switch103 period103" role="group" aria-label="${T('Periode langganan','Billing period')}">${[['year','Tahunan','Annual'],['month','Bulanan','Monthly']].map(([v,a,b])=>button103(T(a,b),'period',v,ui103.period===v?'selected':'')).join('')}</div>${info10('pricing103','Harga tahunan mengikuti harga acuan sebelumnya dan belum final. Harga bulanan belum ditetapkan. Pembayaran dalam Studio ini adalah simulasi.','Annual prices use the earlier reference prices and are not final. Monthly prices are not set. Payments in this Studio are simulated.')}</div><div class="plan-grid103 ${plans.length===2?'two':''}">${plans.map(plan=>{const current=plan===m.plan,available=plan==='Flex'||ui103.period==='year';return `<article class="plan-card103 ${current?'current':''}"><div class="spread"><h2>${plan}</h2>${current?`<span class="current-tag103">${T('Paketmu','Your plan')}</span>`:badge103(plan)}</div><div class="plan-price103">${available?`<small>Rp</small><strong>${new Intl.NumberFormat('id-ID').format(price103[plan])}</strong><span>/ ${plan==='Flex'?T('kredit','credit'):T('tahun','year')}</span>`:`<strong class="pending-price103">${T('Segera tersedia','Coming soon')}</strong>`}</div><p class="plan-purpose103">${T(...({Flex:['Rilis sesuai ritmemu.','Release at your own pace.'],Go:['Mulai membangun katalogmu.','Start building your catalogue.'],Pro:['Dukungan lebih untuk setiap rilisan.','More support for every release.'],Business:['Satu tempat untuk seluruh labelmu.','One place for all your labels.']})[plan])}</p><button type="button" class="btn plan-cta103 ${current?'primary':''}" data-v103="choose-plan" data-id="${plan}" ${available?'':'disabled'}>${plan==='Flex'?T('Beli kredit','Buy credits'):current?T('Perpanjang paket','Renew plan'):T('Pilih ','Choose ')+plan}</button><ul class="benefits103">${planFeatures103(plan).map((f,i)=>`<li><span aria-hidden="true">${['✧','↗','▤','♫'][i%4]}</span>${f}</li>`).join('')}</ul>${current?`<p class="plan-until103">${expiry103(m)}</p>`:''}</article>`;}).join('')}</div></div>`,'plan-dialog103');};
purchase10=function(){if(!isLabel10())return;if(member10().invoice?.status==='pending')return invoice103();const b=RM10.balance(ten,member10());fullscreen103(T('Tambah kredit','Add credits'),`<div class="checkout103"><h1>${T('Tambah kredit rilisan','Add release credits')}</h1><p class="checkout-intro103">${T('1 kredit = 1 lagu. Kredit pembelian tetap milikmu tanpa batas waktu.','1 credit = 1 track. Purchased credits stay yours with no expiry.')}</p><div class="balance-strip103">${[[T('Harian','Daily'),b.daily],[T('Pembelian','Purchased'),b.paid],[T('Sementara','Temporary'),b.replacement]].map(([l,n])=>`<span>${l}<strong>${n}</strong></span>`).join('')}</div><h2>${T('Pilih jumlah kredit','Choose your credit amount')}</h2><div class="credit-tiles103">${[['single','Single',1],['ep','EP',4],['album','Album',10],['manual',T('Jumlah sendiri','Custom'),null]].map(([id,l,n])=>`<button type="button" class="credit-tile103 ${ui103.preset===id?'selected':''}" data-v103="preset" data-id="${id}" aria-pressed="${ui103.preset===id}"><strong>${n?money10(n*35000):l}</strong><span>${n?n+' '+T('kredit','credits'):T('Tentukan jumlah','Set an amount')}</span>${n?`<small>${l}</small>`:''}</button>`).join('')}</div><form data-form103="credits"><label class="credit-quantity103">${T('Jumlah kredit','Credit quantity')}<input name="quantity" id="quantity103" type="number" min="1" max="500" step="1" value="${ui103.quantity}" required></label><div class="credit-note103"><span>✧</span><div><strong>${T('Tetap tersedia, kapan pun kamu merilis','Ready whenever you release')}</strong><p>${T('Kredit tambahan bisa dipakai setelah kredit harian habis, termasuk saat paket langganan berakhir.','Use extra credits after your daily credits run out, including after your subscription ends.')}</p></div></div>${paymentMethods103()}<section class="order103"><h2>${T('Ringkasan pembelian','Order summary')}</h2><div><span id="credit-count103">${ui103.quantity} ${T('kredit','credits')}</span><span id="credit-subtotal103">${money10(ui103.quantity*35000)}</span></div><div><span>${T('Harga per kredit','Price per credit')}</span><span>${money10(35000)}</span></div><div class="order-total103"><strong>${T('Total pembayaran','Total due')}</strong><strong id="credit-total103">${money10(ui103.quantity*35000)}</strong></div></section><button class="btn primary purchase103" type="submit"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></svg>${T('Lanjutkan pembayaran','Continue to payment')}</button>${info10('checkout103','Tidak ada transaksi uang sungguhan dalam pratinjau. QRIS dan transfer bank di sini memperagakan pilihan pembayaran; koneksi penyedia pembayaran belum dipasang.','No real money is transacted in this preview. QRIS and bank transfer demonstrate payment choices; no payment provider is connected.')}</form></div>`,'credit-dialog103');};
function paymentMethods103(){return `<fieldset class="payment103"><legend>${T('Metode pembayaran','Payment method')}</legend><label><input type="radio" name="method" value="QRIS" checked> <span>▦</span> QRIS</label><label><input type="radio" name="method" value="Virtual Account"> <span>▤</span> ${T('Transfer bank','Bank transfer')}</label></fieldset>`;}
creditPopup102=function(){purchase10();};
function invoice103(){const m=member10(),inv=m.invoice;if(!inv||inv.status!=='pending')return purchase10();const total=inv.kind==='credits'||inv.plan==='Flex'?inv.credits*35000:price103[inv.plan];fullscreen103(T('Pembayaran','Payment'),`<div class="checkout103 payment-review103"><h1>${T('Selesaikan pembayaran','Complete your payment')}</h1><p class="checkout-intro103">${E(inv.id)} · ${T('Berlaku sampai','Valid until')} ${date10(inv.expires,true)} WIB</p><div class="credit-note103"><span>◷</span><div><strong>${T('Menunggu pembayaran','Awaiting payment')}</strong><p>${T('Bayar sebelum batas waktu agar pesanan dapat dilanjutkan.','Pay before the deadline to continue your order.')}</p></div></div><section class="order103"><div><span>${inv.kind==='credits'?inv.credits+' '+T('kredit','credits'):inv.plan+' · '+T('Tahunan','Annual')}</span><strong>${money10(total)}</strong></div><div><span>${T('Metode pembayaran','Payment method')}</span><span>${E(inv.method103||'QRIS')}</span></div><div class="order-total103"><strong>${T('Total pembayaran','Total due')}</strong><strong>${money10(total)}</strong></div></section>${button103(T('Bayar sekarang','Pay now'),'pay','','primary purchase103')}${info10('payment103','Tombol ini menyimulasikan pembayaran berhasil. Tagihan tidak dikirim ke penyedia pembayaran dan tidak memotong uang.','This button simulates a successful payment. No invoice is sent to a payment provider and no money is charged.')}</div>`,'credit-dialog103');}

const releaseBase103=releaseForm10;
releaseForm10=function(id){releaseBase103(id);const f=$('[data-ten-form=release_draft]');if(!f)return;f.dataset.form103='release';const slider=f.querySelector('.service102'),wrapper=slider.parentElement,actions=f.querySelector('.ten-actions');actions.remove();const footer=document.createElement('div');footer.className='release-footer103';footer.append(slider);wrapper.remove();footer.insertAdjacentHTML('beforeend',`<div class="release-actions103"><button class="btn" type="submit" name="intent" value="save">${T('Simpan draft','Save draft')}</button><button class="btn primary" type="submit" name="intent" value="submit">${T('Ajukan rilisan','Submit release')} ↗</button></div>`);f.append(footer);$('#dialog').classList.add('release-dialog103');};

function avatar103(m,cls=''){return m.avatar103?`<img class="profile-photo103 ${cls}" src="${m.avatar103}" alt="${E(m.name)}">`:`<span class="profile-photo103 fallback103 ${cls}">${E(m.name.slice(0,1))}</span>`;}
account10=function(){const m=member10(),q=m.profileChange103;return `<section class="panel pad profile103"><div class="profile-head103">${avatar103(m)}<div><h2>${E(m.name)} ${badge103(m.plan)}</h2><p>${E(m.email)}</p></div><label class="btn photo-upload103">${T('Ubah foto','Change photo')}<input type="file" id="photo103" accept="image/png,image/jpeg,image/webp" aria-label="${T('Pilih foto profil','Choose profile photo')}"></label></div><div class="tabs profile-tabs103">${[['identity','Identitas label','Label identity'],['bank','Rekening penerima','Payout account'],['contract','Kontrak','Contract']].map(([id,a,b])=>button103(T(a,b),'profile-tab',id,ui103.profileTab===id?'active':'')).join('')}</div>${ui103.profileTab==='bank'?bankForm10(m):ui103.profileTab==='contract'?contractSummary102(m):`${q?.status==='pending'?`<div class="profile-status103">${tag10(T('Perubahan identitas sedang diperiksa','Identity changes under review'),'copper')}<p>${T('Identitas saat ini tetap digunakan sampai perubahan disetujui.','Your current identity remains in use until the changes are approved.')}</p>${button103(T('Lihat perubahan','View changes'),'review',m.id)}</div>`:q?.status==='correction'?`<div class="profile-status103">${tag10(T('Perbaiki perubahan identitas','Correct identity changes'),'copper')}<p>${E(q.note)}</p></div>`:''}${identityDetails102(m)}<div class="ten-actions">${m.active?button103(T('Edit identitas','Edit identity'),'edit-profile','','primary'):b10(T('Lengkapi identitas','Complete identity'),'page','activation')}</div>`}</section>`;};
function editProfile103(){const m=member10(),q=m.profileChange103,values=q?.status==='correction'?q.after:{name:m.name,email:m.email,person:m.identity.person},pending=q?.status==='pending';modal10(T('Edit identitas label','Edit label identity'),`<form class="ten-form" data-form103="profile">${field10('name',T('Nama label','Label name'),values.name,'text',`required maxlength="120" ${pending?'readonly':''}`)}${field10('email','Email',values.email,'email',`required ${pending?'readonly':''}`)}${field10('person',T('Penanggung jawab','Representative'),values.person,'text',`required maxlength="120" ${pending?'readonly':''}`)}<p class="full identity-explain103">${T('Perubahan nama label, email, atau penanggung jawab akan diperiksa sebelum digunakan.','Changes to the label name, email, or representative are reviewed before taking effect.')}</p>${directoryLocationFields(m.identity)}<div class="full ten-actions"><button class="btn primary" type="submit">${T('Simpan perubahan','Save changes')}</button></div></form>`);}
function reviewProfile103(id){const m=RM10.getMember(ten,id),q=m?.profileChange103;if(!q||isLabel10()&&m.id!==ten.member)return;modal10(T('Perubahan identitas','Identity changes')+' · '+E(m.name),`<div class="table-wrap"><table class="amendment103"><thead><tr><th>${T('Data','Field')}</th><th>${T('Saat ini','Current')}</th><th>${T('Diajukan','Requested')}</th></tr></thead><tbody>${[['name','Nama label','Label name'],['email','Email','Email'],['person','Penanggung jawab','Representative']].filter(([k])=>q.before[k]!==q.after[k]).map(([k,a,b])=>`<tr><th>${T(a,b)}</th><td>${E(q.before[k])}</td><td>${E(q.after[k])}</td></tr>`).join('')}</tbody></table></div>${!isLabel10()&&q.status==='pending'?`<form data-form103="review" data-id="${m.id}" data-version="${q.version}"><label class="review-note103">${T('Bagian yang perlu diperbaiki','What needs correction')}<textarea name="note" placeholder="${T('Contoh: nama penanggung jawab belum sesuai dokumen identitas.','Example: the representative name does not match the identity document.')}"></textarea></label><div class="ten-actions"><button type="submit" name="decision" value="correct" class="btn">${T('Minta perbaikan','Request corrections')}</button><button type="submit" name="decision" value="approve" class="btn primary">${T('Setujui perubahan','Approve changes')}</button></div></form>`:`<p class="space">${q.status==='pending'?T('Perubahan sedang diperiksa.','Changes are under review.'):q.status==='approved'?T('Perubahan sudah disetujui.','Changes were approved.'):E(q.note)}</p>`}`);}
const labelsBase103=labels102;
labels102=function(){const pending=ten.members.filter(m=>m.profileChange103?.status==='pending');return labelsBase103()+(pending.length?card10(T('Perubahan identitas','Identity changes'),pending.map(m=>`<div class="spread profile-request103"><div><strong>${E(m.name)}</strong><p>${T('Nama label, email, atau penanggung jawab','Label name, email, or representative')}</p></div>${button103(T('Periksa','Review'),'review',m.id)}</div>`).join(''),'full'):'');};labelsPage9=labels102;
const syncBase103=syncTasks102;syncTasks102=function(){syncBase103();for(const m of ten.members)if(m.profileChange103?.status==='pending')data.tasks.unshift({id:'profile:'+m.id,title:T('Perubahan identitas · ','Identity change · ')+m.name,label:m.name,kind:'claim',stage:'queued',handler:null,last:null,created:RM10.day(m.profileChange103.at),due:RM10.day(ten.now),pct:0,linked102:true});};
const taskBase103=taskModal;taskModal=function(id){return id.startsWith('profile:')?reviewProfile103(id.slice(8)):taskBase103(id);};
const actBase103=RM10.act;RM10.act=function(s,action,p={}){if(s.role==='admin'&&['profile_approve','profile_correct'].includes(action)&&['read','blocked'].includes(access8(p.member)))throw Error('permission');const result=actBase103(s,action,p);if(action==='profile_approve'){const m=RM10.getMember(s,p.member),source=data.v9.labels.find(l=>l.id===m.source9);if(source)source.name=m.name;}return result;};
const sidebarBase103=sidebar5;sidebar5=function(){const html=sidebarBase103();if(!isLabel10())return html;return html.replace(/<button[^>]*data-ten="page" data-id="contracts"[\s\S]*?<\/button>/,'').replaceAll('Profil & Rekening', 'Profil Label').replaceAll('Profile & Bank','Label Profile');};
const moduleBase103=modulePage;modulePage=function(){if(isLabel10()&&['account','contracts'].includes(v4.module)){v4.module='account';return pageHead(T('Profil Label','Label Profile'),'')+account10();}return moduleBase103();};
const renderBase103=render;render=function(){renderBase103();document.querySelectorAll('.plan9').forEach(el=>{const plan=el.textContent.trim().toLowerCase();if(['flex','go','pro','business'].includes(plan)){el.classList.add('plan103',plan);el.textContent=plan.toUpperCase();}});document.querySelectorAll('.label-name9[data-ten=labeldetail102]').forEach(el=>{const m=RM10.getMember(ten,el.dataset.id),avatar=el.querySelector('.label-avatar9');if(m?.avatar103&&avatar)avatar.outerHTML=avatar103(m,'tiny103');});if(isLabel10()){const m=member10();$('.tools [data-action=account]').innerHTML=avatar103(m,'tiny103');$('.side-person .mark').outerHTML=avatar103(m,'tiny103');const plan=$('.label-commerce102 [data-ten=plans]');plan.innerHTML=badge103(m.plan)+'<span>'+T('Ubah paket','Change plan')+'</span>';if(v4.module==='account'&&state.page==='module')$('.header-path').innerHTML='Label <i>/</i> '+T('Profil Label','Label Profile');}};
const notificationsOriginal103=notification10;const notificationsBase103=()=>{const all=ten.notifications;try{ten.notifications=all.filter(n=>!['profile_approve','profile_correct'].includes(n.key));return !ten.notifications.some(n=>n.member===ten.member)&&all.some(n=>n.member===ten.member&&['profile_approve','profile_correct'].includes(n.key))?'':notificationsOriginal103();}finally{ten.notifications=all;}};notification10=function(){const rows=ten.notifications.filter(n=>n.member===ten.member&&['profile_approve','profile_correct'].includes(n.key));return rows.slice(0,3).map(n=>`<div class="profile-notification103"><p>${n.key==='profile_approve'?T('Perubahan identitas disetujui. Profil labelmu sudah diperbarui.','Identity changes approved. Your label profile is updated.'):T('Perubahan identitas perlu diperbaiki. Buka Profil Label untuk melihat catatan.','Identity changes need correction. Open Label Profile for details.')}</p>${button103('↗','open-profile')}</div>`).join('')+notificationsBase103();};

window.addEventListener('click',e=>{const b=e.target.closest('[data-v103]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const a=b.dataset.v103,id=b.dataset.id;if(b.disabled)return;try{
 if(a==='group'){ui103.group=id;plans10();}else if(a==='period'){ui103.period=id;plans10();}
 else if(a==='choose-plan'){if(member10().invoice?.status==='pending')return invoice103();if(id==='Flex')return purchase10();if(ui103.period!=='year')return;RM10.act(ten,'invoice',{plan:id,period:'year',kind:'activation',credits:1});member10().invoice.method103='QRIS';save10();invoice103();}
 else if(a==='preset'){ui103.preset=id;ui103.quantity=({single:1,ep:4,album:10})[id]||ui103.quantity;purchase10();if(id==='manual')$('#quantity103').focus();}
 else if(a==='pay'){RM10.act(ten,'pay');save10();render();fullscreen103(T('Pembayaran berhasil','Payment successful'),`<div class="purchase-success103"><span>✓</span><h1>${T('Sudah siap untuk rilisan berikutnya','Ready for your next release')}</h1><p>${member10().invoice.kind==='credits'?member10().invoice.credits+' '+T('kredit ditambahkan ke akunmu.','credits added to your account.'):T('Paketmu telah diperbarui.','Your plan has been updated.')}</p>${button103(T('Buka Dashboard','Open Dashboard'),'done','','primary')}</div>`,'credit-dialog103');}
 else if(a==='preview')preview103(id);else if(a==='done')route102('home');else if(a==='profile-tab'){if(typeof ui106!=='undefined')ui106.profileDirection=Math.sign(['identity','bank','contract'].indexOf(id)-['identity','bank','contract'].indexOf(ui103.profileTab))*18;ui103.profileTab=id;render();}else if(a==='edit-profile')editProfile103();else if(a==='review')reviewProfile103(id);else if(a==='open-profile'){ui103.profileTab='identity';route102('account');}
 }catch(err){toast(error10(err.message));}},true);
window.addEventListener('input',e=>{if(e.target.id!=='quantity103')return;const n=Number(e.target.value);ui103.quantity=n;ui103.preset='manual';document.querySelectorAll('.credit-tile103').forEach(b=>{b.classList.toggle('selected',b.dataset.id==='manual');b.setAttribute('aria-pressed',b.dataset.id==='manual');});$('#credit-count103').textContent=(Number.isInteger(n)&&n>0?n:'—')+' '+T('kredit','credits');for(const id of ['credit-subtotal103','credit-total103'])$('#'+id).textContent=Number.isInteger(n)&&n>0&&n<=500?money10(n*35000):'—';});
window.addEventListener('change',async e=>{if(e.target.id!=='photo103')return;const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2000000){toast(T('Gunakan JPG, PNG, atau WebP maksimal 2 MB.','Use JPG, PNG, or WebP up to 2 MB.'));return;}const owner=ten.member;try{let photo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});if(!isLabel10()||ten.member!==owner)return;const im=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=photo;});const canvas=document.createElement('canvas'),ratio=Math.min(1,512/Math.max(im.width,im.height));canvas.width=Math.max(1,Math.round(im.width*ratio));canvas.height=Math.max(1,Math.round(im.height*ratio));canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);photo=canvas.toDataURL('image/webp',.88);if(!isLabel10()||ten.member!==owner)return;RM10.act(ten,'profile_photo',{photo});save10();render();toast(T('Foto profil tersimpan.','Profile photo saved.'));}catch(err){toast(error10(err.message));}});
window.addEventListener('submit',e=>{const f=e.target,kind=f.dataset.form103;if(!kind)return;e.preventDefault();e.stopImmediatePropagation();if(!f.reportValidity())return;const v=Object.fromEntries(new FormData(f));try{
 if(kind==='credits'){const n=Number(v.quantity);if(!Number.isInteger(n)||n<1||n>500)throw Error('invalid');RM10.act(ten,'invoice',{plan:'Flex',credits:n,kind:member10().paid?'credits':'activation'});member10().invoice.method103=v.method;save10();invoice103();}
 else if(kind==='profile'){const result=RM10.act(ten,'profile_edit',{name:v.name,email:v.email,identity:directoryIdentity(v,true)});save10();closeModal();render();toast(result==='pending'?T('Perubahan identitas dikirim untuk diperiksa.','Identity changes sent for review.'):T('Identitas tersimpan.','Identity saved.'));}
 else if(kind==='review'){const decision=e.submitter?.value;if(decision==='correct'&&!v.note.trim()){f.querySelector('textarea').setCustomValidity(T('Jelaskan bagian yang perlu diperbaiki.','Explain what needs correction.'));f.querySelector('textarea').reportValidity();f.querySelector('textarea').addEventListener('input',()=>f.querySelector('textarea').setCustomValidity(''),{once:true});return;}RM10.act(ten,decision==='approve'?'profile_approve':'profile_correct',{member:f.dataset.id,version:Number(f.dataset.version),note:v.note});save10();closeModal();render();toast(T('Pengajuan sudah ditangani.','Request handled.'));}
 else if(kind==='release'){const draftKey=draftKey10(f);const id=RM10.act(ten,'draft',{id:f.dataset.id||undefined,title:v.title,artist:v.artist,tracks:Number(v.tracks),service:tenDraftService,date:v.date});f.dataset.id=id;tenDetail=id;if(e.submitter?.value==='submit')RM10.act(ten,'submit',{id});if(ten.formDrafts)delete ten.formDrafts[draftKey];save10();render();releaseModal10(id);}
 }catch(err){save10();toast(error10(err.message));}},true);
// Preview entries exercise the same forms and queues used by each role.
const studioBase103=studio8;studio8=function(){studioBase103();$('#dialog .dialog-body').insertAdjacentHTML('beforeend',`<h3 class="space">${T('Paket, kredit & identitas','Plans, credits & identity')}</h3><div class="ten-actions">${button103(T('Bandingkan paket','Compare plans'),'preview','plans')}${button103(T('Pembelian kredit','Credit purchase'),'preview','credits')}${button103(T('Perubahan identitas menunggu','Identity changes pending'),'preview','identity')}</div>`);};
function preview103(id){const m=ten.members.find(m=>m.active&&m.plan==='Pro')||ten.members.find(m=>m.active);if(!m)return;role102('label',m.id);if(id==='plans')plans10();else if(id==='credits')purchase10();else{if(m.profileChange103?.status!=='pending')RM10.act(ten,'profile_edit',{name:m.name+' Studio'});ui103.profileTab='identity';save10();route102('account');}}
window.addEventListener('click',e=>{if(e.target.closest('[data-form103=review] [value=approve]'))$('[data-form103=review] textarea').setCustomValidity('');},true);
render();
