/* V10.4: shared presentation and ordinary navigation, not Studio-only screens. */
const motion104={duration:240,ease:'cubic-bezier(.2,.75,.25,1)'},switchPositions104=new Map();
const modalBase104=modal10;
modal10=function(title,body){modalBase104(title,body);enhanceSwitches104($('#dialog'));};
function enhanceSwitches104(root=document){if(typeof enhance105==='function')enhance105(root);}
window.addEventListener('resize',()=>enhanceSwitches104());
const fullDate104=value=>value?new Intl.DateTimeFormat(ten.lang==='en'?'en-GB':'id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date(value+'T12:00:00+07:00')):'—';
service10=function(value){const i=['Standard','Express','MAX'].indexOf(value);return `<div class="service-picker104"><button type="button" class="btn service-toggle104 ${value==='MAX'?'max104':''}" data-v104="service-toggle" aria-expanded="false"><span>${value}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 10 4 4 4-4"/></svg></button><div class="service-popover104" hidden><div class="service102 ${value==='MAX'?'max104':''}" style="--level:${i*50}%;--thumb-offset:${i*24}px"><header><small>Rilis Musik</small><output id="service-label102">${value}</output></header><div class="service-track102"><div class="service-rail102"></div><div class="service-dots102"><i></i><i></i><i></i></div><i class="service-thumb102" aria-hidden="true"></i><output class="service-cost104" aria-live="polite"></output><input id="service-range102" type="range" min="0" max="2" step="1" value="${i}" aria-label="${T('Layanan rilisan','Release service')}" aria-valuetext="${value}"></div><div class="service-labels102">${['Standard','Express','MAX'].map((v,j)=>`<button type="button" data-v104="service-choice" data-id="${j}" class="${j===i?'active':''}">${v}</button>`).join('')}</div></div></div></div>`;};
serviceDetail10=function(service,n,selected){const first=RM10.earliest(ten,service),value=selected||first||RM10.earliest(ten,'Express');return `<section class="release-date104"><div><small>${T('TANGGAL RILIS','RELEASE DATE')}</small><label class="date-choice104"><span id="date-label104">${fullDate104(value)}</span><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 11h18"/></svg><input type="date" name="date" value="${value}" required aria-label="${T('Pilih tanggal rilis','Choose release date')}"></label></div><div id="date-context104"></div></section>`;};
releaseForm10=function(id){const r=id?RM10.getRelease(ten,id):null;if(!member10().active){toast(T('Selesaikan aktivasi terlebih dahulu.','Complete activation first.'));return;}tenDraftService=r?.service||'Standard';const balance=RM10.balance(ten,member10());reviewDialogUI(T('Siapkan rilisan','Prepare a release'),`<form data-ten-form="release_draft" data-form103="release" data-id="${id||''}" class="release-form104"><header class="release-heading104"><span class="release-art104" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2"/><path d="M6 12a6 6 0 0 1 6-6M18 12a6 6 0 0 1-6 6"/></svg></span><div><small>${E(member10().name)}</small><h2>${T('Detail rilisan','Release details')}</h2></div></header><div class="ten-form">${field10('title',T('Judul rilisan','Release title'),r?.title||'','text','required')}${field10('artist',T('Artis','Artist'),r?.artist||'','text','required')}${field10('tracks',T('Jumlah lagu','Track count'),r?.tracks||1,'number','min="1" max="12" required id="ten-tracks"')}</div><div id="ten-service-detail">${serviceDetail10(tenDraftService,r?.tracks||1,r?.date)}</div><footer class="release-footer104"><button class="btn save-draft104" type="submit" name="intent" value="save">${T('Simpan draft','Save draft')}</button><div class="release-submit104"><span class="service-summary104"></span><span class="release-balance104" title="${T('Kredit tersedia','Available credits')}">${coin104()} ${balance.daily+balance.paid+balance.replacement}</span>${service10(tenDraftService)}<button class="btn primary" type="submit" name="intent" value="submit">${T('Ajukan rilisan','Submit release')} ↗</button></div></footer>${info10('release-cost104','Standard 1, Express 2, MAX 3 kredit per lagu adalah angka uji. Kredit dialokasikan saat pengajuan, terpakai setelah Konfirmasi Tayang. MAX hari Jumat tersedia sebelum pukul 12.00 WIB.','Standard 1, Express 2, MAX 3 credits per track are sample rates. Credits are allocated on submission and consumed after Live confirmation. Friday MAX orders are available before noon WIB.')}</form>`);$('#dialog').classList.add('release-dialog104');updateRelease104();};
function updateRelease104(){const f=$('.release-form104');if(!f)return;const input=f.querySelector('[name=date]'),date=input.value,n=+f.querySelector('[name=tracks]').value||1,first=RM10.earliest(ten,tenDraftService),now=RM10.day(ten.now),context=f.querySelector('#date-context104');f.querySelector('#date-label104').textContent=fullDate104(date);let message='',suggest='';
 if(!date||date<now){message=T('Pilih tanggal rilis mendatang.','Choose a future release date.');input.setCustomValidity(message);}
 else if(!first||date<first){const available=['Standard','Express','MAX'].filter(s=>RM10.earliest(ten,s)&&date>=RM10.earliest(ten,s));const target=available[0];message=!first?T('MAX hari Jumat tersedia sebelum pukul 12.00 WIB.','Friday MAX orders are available before noon WIB.'):T('Tanggal ini lebih awal dari jangkauan '+tenDraftService+'.','This date is earlier than '+tenDraftService+' allows.');if(target)suggest=action104(T('Gunakan ','Use ')+target,'suggest-service',target);else message+=' '+T('Tanggal terdekat yang tersedia: ','Earliest available date: ')+fullDate104(['Standard','Express','MAX'].map(s=>RM10.earliest(ten,s)).filter(Boolean).sort()[0])+'.';input.setCustomValidity(message);}
 else {message=T('Tanggal ini tersedia dengan '+tenDraftService+'.','This date is available with '+tenDraftService+'.');if(date>first)message+=' '+T('Rilisan akan dijadwalkan untuk tanggal pilihanmu.','Your release will be scheduled for your chosen date.');input.setCustomValidity('');}
 context.innerHTML=`<p>${E(message)}</p>${suggest}`;context.classList.toggle('date-warning104',!!input.validationMessage);
 const total=n*({Standard:1,Express:2,MAX:3}[tenDraftService]);f.querySelector('.service-summary104').textContent=tenDraftService==='Standard'?'':`${tenDraftService} · ${total} ${T('kredit','credits')}`;f.querySelector('.service-cost104').textContent=`${total} ${T('kredit','credits')}`;
 f.querySelector('.service-toggle104 span').textContent=tenDraftService;f.querySelector('.service-toggle104').classList.toggle('max104',tenDraftService==='MAX');f.querySelector('.service102').classList.toggle('max104',tenDraftService==='MAX');
}
setService102=function(value){const n=Math.max(0,Math.min(2,+value));tenDraftService=['Standard','Express','MAX'][n];const root=$('.service102');if(!root)return;root.style.setProperty('--level',n*50+'%');root.style.setProperty('--thumb-offset',n*24+'px');$('#service-label102').textContent=tenDraftService;$('#service-range102').value=n;$('#service-range102').setAttribute('aria-valuetext',tenDraftService);root.querySelectorAll('[data-v104=service-choice]').forEach((b,i)=>b.classList.toggle('active',n===i));updateRelease104();};
function closeService104(){const p=$('.service-popover104');if(p){p.hidden=true;$('.service-toggle104').setAttribute('aria-expanded','false');}}
window.addEventListener('input',e=>{if(e.target.closest('.release-form104')){updateRelease104();if(e.target.id==='service-range102')$('.service-cost104').classList.add('visible');}});
window.addEventListener('change',e=>{if(e.target.closest('.release-form104')){updateRelease104();$('.service-cost104')?.classList.remove('visible');}});
window.addEventListener('pointerup',()=>$('.service-cost104')?.classList.remove('visible'));
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.service-popover104:not([hidden])')){e.preventDefault();e.stopImmediatePropagation();closeService104();$('.service-toggle104').focus();}},true);
window.addEventListener('click',e=>{if(!e.target.closest('.service-picker104'))closeService104();});
// Distinct work-state meanings use a single style across queues and work lists.
condition8=function(x){if(x.stage==='done')return '';let label=T('Dalam penanganan','In progress'),tone='blue';if(taskAttention(x)&&x.stage!=='approval'&&!waiting(x)){label=T('Lewat tenggat','Past deadline');tone='red';}else if(taskAttention(x)){label=x.stage==='approval'?T('Prioritas','Priority'):T('Perlu tindak lanjut','Follow-up');tone='amber';}else if(x.stage==='queued')label=T('Baru','New');else return '';return `<span class="badge work-badge104 ${tone}">${label}</span>`;};
const labelsBefore104=labels102;
labels102=function(){const html=labelsBefore104();if(isLabel10())return html;const doc=document.createElement('template');doc.innerHTML=html;for(const table of doc.content.querySelectorAll('.labels-table9')){const head=table.querySelector('thead tr');const th=document.createElement('th');th.textContent=T('Paket','Plan');head.children[1].before(th);for(const row of table.querySelectorAll('tbody tr')){const name=row.querySelector('.label-name9');if(!name)continue;const m=RM10.getMember(ten,name.dataset.id);name.querySelector('.plan9')?.remove();const td=document.createElement('td');td.innerHTML=badge104(m.plan);row.children[1].before(td);row.dataset.plan104=m.plan;if(ui104.labelPackage!=='all'&&m.plan!==ui104.labelPackage)row.remove();}const controls=table.closest('.panel')?.querySelector('.table-controls7');controls?.insertAdjacentHTML('beforeend',`<select data-v104-filter="package" aria-label="${T('Filter paket','Filter plan')}"><option value="all">${T('Semua paket','All plans')}</option>${catalogue104().plans.map(p=>`<option value="${p.id}" ${ui104.labelPackage===p.id?'selected':''}>${E(p.name)}</option>`).join('')}</select>`);}
 // Give the prospects tab the same filtering affordance without exposing private data.
 if(!doc.content.querySelector('.table-controls7')&&doc.content.querySelector('table')){const table=doc.content.querySelector('table');table.closest('.panel')?.insertAdjacentHTML('afterbegin',`<div class="table-controls7"><input data-v104-filter="prospect-search" value="${E(ui104.prospectSearch||'')}" placeholder="${T('Cari label','Find label')}"><select data-v104-filter="prospect-status"><option value="all">${T('Semua status','All statuses')}</option>${[['pending','Sedang diperiksa'],['correction','Perlu perbaikan'],['incomplete','Belum lengkap']].map(([v,l])=>`<option value="${v}" ${ui104.prospectStatus===v?'selected':''}>${l}</option>`).join('')}</select></div>`);for(const row of table.querySelectorAll('tbody tr')){const m=ten.members.find(m=>row.textContent.includes(m.email));if(m&&((ui104.prospectSearch&&!m.name.toLowerCase().includes(ui104.prospectSearch.toLowerCase()))||(ui104.prospectStatus&&ui104.prospectStatus!=='all'&&(m.application?.status||'incomplete')!==ui104.prospectStatus)))row.remove();}}
 return doc.innerHTML;};labelsPage9=labels102;
function labelDrawer104(id){if(isLabel10())return;const m=RM10.getMember(ten,id);if(!m)return;const l=data.v9.labels.find(l=>l.id===m.source9);reviewDialogUI(T('Detail label','Label details'),`<header class="label-drawer-head104">${avatar103(m)}<div><h2>${E(m.name)} ${l?verificationMark9(l):''}</h2><p>${E(m.email)}</p><div class="drawer-marks104">${badge104(m.plan)}</div></div></header><div class="drawer-meta104"><span>${T('AKSES','ACCESS')}<strong>${l?labelStatus9('access',accessLabel9(l)):T('Normal','Normal')}</strong></span><span>${T('AKTIVITAS','ACTIVITY')}<strong>${l?labelStatus9('activity',activity9(l)):T('Aktif','Active')}</strong></span></div><section class="drawer-section104"><h3>${T('Identitas label','Label identity')}</h3>${identityDetails102(m)}</section><section class="drawer-section104"><h3>${T('Kontrak','Contract')}</h3>${contractSummary102(m)}</section>${ten.role==='super'?`<section class="drawer-section104">${payoutCardUI(m.bank.approved)}<div class="drawer-meta104"><span>${T('KREDIT TERSEDIA','AVAILABLE CREDITS')}<strong>${availablePending(m)}</strong></span><span>${T('MASA PAKET','PLAN PERIOD')}<strong>${expiry103(m)}</strong></span></div><div class="drawer-meta104"><span>${T('TARIF ROYALTI LABEL','LABEL ROYALTY RATE')}<strong>${m.royaltyRate??60}% ${T('untuk label','to label')}</strong></span><button type="button" class="btn small" data-v104="rate-edit" data-id="${m.id}">${T('Ubah tarif','Change rate')}</button></div></section>`:''}`);$('#dialog').classList.add('label-drawer104');}
cleanupPagePending=function(){return pageHead(T('Penyesuaian Data Label','Label Data Updates'),'')+`<section class="panel pad cleanup104"><header class="section-heading104"><div><small>${T('IDENTITAS & REKENING','IDENTITY & BANK ACCOUNT')}</small><h2>${T('Identitas dan rekening label','Label identity and bank details')}</h2></div>${info10('updates104','Gunakan data yang sudah dimiliki label sebagai acuan. Nomor rekening tidak dapat diubah di sini. Perubahan nama bank/pemilik bisa disimpan atau diajukan untuk konfirmasi label.','Use the existing label records as reference. Account numbers cannot be changed here. Bank and holder names can be saved or proposed for label confirmation.')}</header><div class="table-controls7"><input data-v104-filter="cleanup-search" placeholder="${T('Cari label','Find label')}" value="${E(ui104.cleanupSearch||'')}"><select data-v104-filter="cleanup-status"><option value="all">${T('Semua data','All records')}</option><option value="incomplete" ${ui104.cleanupStatus==='incomplete'?'selected':''}>${T('Lokasi belum lengkap','Location incomplete')}</option><option value="proposal" ${ui104.cleanupStatus==='proposal'?'selected':''}>${T('Menunggu konfirmasi','Awaiting confirmation')}</option></select></div>${pendingTable(['Label',T('Lokasi operasional','Operating location'),T('Rekening penerima','Payout account'),''],ten.members.filter(m=>(!ui104.cleanupSearch||m.name.toLowerCase().includes(ui104.cleanupSearch.toLowerCase()))&&(!ui104.cleanupStatus||ui104.cleanupStatus==='all'||ui104.cleanupStatus==='incomplete'&&!m.identity.location?.complete||ui104.cleanupStatus==='proposal'&&m.bank.cleanupProposal?.status==='pending')).map(m=>`<tr><td><div class="label-cell104">${avatar103(m,'tiny103')}<span><strong>${E(m.name)}</strong><small>${E(m.email)}</small></span></div></td><td><span class="badge work-badge104 ${m.identity.location?.complete?'green':'amber'}">${m.identity.location?.complete?T('Lengkap','Complete'):T('Belum lengkap','Incomplete')}</span></td><td>${E(directoryBankDisplay(m.bank.approved?.bank)||'—')}${m.bank.cleanupProposal?.status==='pending'?`<small class="block102">${T('Menunggu konfirmasi label','Awaiting label confirmation')}</small>`:''}</td><td>${pb(T('Periksa data','Review details'),'cleanup-open',m.id)}</td></tr>`))}<details class="change-history104"><summary>${T('Riwayat perubahan','Change history')} <span>${ten.cleanupHistory.length}</span></summary>${ten.cleanupHistory.map(h=>`<div class="approval-row-ui"><div><strong>${E(RM10.getMember(ten,h.member).name)}</strong><small>${date10(h.at,true)} WIB</small></div>${pb(T('Lihat perubahan','View changes'),'cleanup-history',h.id)}</div>`).join('')||`<p>${T('Belum ada perubahan data.','No changes recorded.')}</p>`}</details></section>`;};
const cleanupOpenBase104=cleanupOpen;
cleanupOpen=function(id){cleanupOpenBase104(id);const f=$('[data-pending-form=cleanup]');if(!f)return;$('#dialog').classList.add('cleanup-dialog104');const status=$('#dialog .review-status-ui');if(status)status.textContent=RM10.getMember(ten,id).active?T('Akun aktif','Account active'):T('Belum aktif','Not active');const mode=f.querySelector('[name=mode]');if(mode){const update=()=>f.querySelector('[type=submit]').textContent=mode.value==='proposal'?T('Kirim usulan','Send proposal'):T('Simpan perubahan','Save changes');mode.addEventListener('change',update);update();}};
// Every monitoring tab remains reachable through one ordinary sidebar destination.
const liabilityBase104=liabilityPage9;
liabilityPage9=function(){let html=liabilityBase104();if(ten.role!=='super')return html;if(pendingUI.tab==='royalties')html=html.replace('</div>',pb(T('Bonus Kredit','Credit Bonuses'),'monitor-tab','bonuses')+'</div>');return html;};
const moduleBase104=modulePage;
modulePage=function(){return v4.module==='catalogue104'?cataloguePage104():moduleBase104();};
const rulesBefore104=workRulesPage;
workRulesPage=function(){const node=document.createElement('template');node.innerHTML=rulesBefore104();const notice=node.content.querySelector('.notice');if(notice){node.content.querySelector('.pagehead h1')?.insertAdjacentHTML('beforeend',info9('procedure-status104',notice.textContent));notice.remove();}return node.innerHTML;};
const actionBefore104=handleAction;
handleAction=async function(b){if(b.dataset.action==='label-detail9'){const m=ten.members.find(m=>m.source9===b.dataset.id);if(m)return labelDrawer104(m.id);}return actionBefore104(b);};
window.addEventListener('click',e=>{const b=e.target.closest('[data-v104]');if(b){const a=b.dataset.v104,id=b.dataset.id;if(['service-toggle','service-choice','suggest-service'].includes(a)){e.preventDefault();e.stopImmediatePropagation();if(a==='service-toggle'){const p=$('.service-popover104');p.hidden=!p.hidden;b.setAttribute('aria-expanded',!p.hidden);}else{setService102(a==='service-choice'?+id:['Standard','Express','MAX'].indexOf(id));if(a==='suggest-service')closeService104();}return;}}
 const detail=e.target.closest('[data-ten=labeldetail102]');if(detail){e.preventDefault();e.stopImmediatePropagation();labelDrawer104(detail.dataset.id);}
 const rate=e.target.closest('[data-v104=rate-edit]');if(rate&&ten.role==='super'){e.preventDefault();e.stopImmediatePropagation();const m=RM10.getMember(ten,rate.dataset.id);if(!m)return;reviewDialogUI(T('Tarif royalti label','Label royalty rate'),`<form class="ten-form" data-v104-form="rate" data-id="${m.id}"><h3 class="full">${E(m.name)}</h3><p class="full muted">${T('Berlaku untuk label baru sebesar 60%. Label lama mempertahankan persentase masing-masing. Perubahan tercatat pada riwayat.','New labels default to 60%. Legacy labels keep their own percentage. Changes are recorded in history.')}</p>${field10('rate',T('Persentase untuk label (%)','Label share (%)'),m.royaltyRate??60,'number','required min="1" max="100" step="1"')}<label class="full">${T('Alasan perubahan','Reason for change')}<textarea name="note" required maxlength="300" rows="2"></textarea></label><footer class="full review-footer-ui"><button class="btn primary" type="submit">${T('Simpan tarif','Save rate')}</button></footer></form>`);}
},true);
window.addEventListener('submit',e=>{const f=e.target.closest('[data-v104-form=rate]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();try{const v=Object.fromEntries(new FormData(f));RM10.act(ten,'rate_set',{member:f.dataset.id,rate:v.rate,note:v.note});save10();closeModal();render();toast(T('Tarif royalti diperbarui.','Royalty rate updated.'));}catch(err){toast(error10(err.message));}},true);
window.addEventListener('change',e=>{const key=e.target.dataset.v104Filter;if(!key)return;const map={package:'labelPackage','prospect-search':'prospectSearch','prospect-status':'prospectStatus','cleanup-search':'cleanupSearch','cleanup-status':'cleanupStatus'};ui104[map[key]]=e.target.value;render();});
const renderBefore104=render;
render=function(){catalogue104();renderBefore104();document.title='Rilis Musik · V10.4';$('.version-pill').textContent='V10.4';$('.footer span').textContent='RILIS MUSIK · V10.4';document.querySelectorAll('[data-pending=bonus-nav]').forEach(x=>x.remove());
 if(ten.role==='super')$('.side-scroll')?.insertAdjacentHTML('beforeend',`<button class="side-link ${v4.module==='catalogue104'&&state.page==='module'?'active':''}" data-v104="catalogue-open">${icon('wallet')}<span>${T('Paket & Kredit','Plans & Credits')}</span></button>`);
 document.querySelectorAll('.plan9:not(.package104)').forEach(el=>{const id=catalogue104().plans.find(p=>p.id.toLowerCase()===el.textContent.trim().toLowerCase())?.id;if(id)el.outerHTML=badge104(id);});
 document.querySelectorAll('.label-commerce102 [data-ten=page][data-id=credits]').forEach(b=>{b.classList.add('credit-trigger104');b.innerHTML=coin104()+`<span>${availablePending(member10())} ${T('kredit','credits')}</span><span aria-hidden="true">+</span>`;});
 document.querySelectorAll('.badge').forEach(el=>{if(el.closest('.plan9'))return;const text=el.textContent.trim();if(['Baru','New'].includes(text)){el.classList.remove('red','amber');el.classList.add('blue','work-badge104');}if(el.closest('.work-badges9,.queued-item,.work-row9,.task-row,.action-row'))el.classList.add('work-badge104');});
 enhanceSwitches104();
};
const scenes104=[['v104-visual','super','Tema, penanda & atensi','Theme, indicators & attention'],['v104-plans','label','Paket dan periode pada kartu','Plans and card billing periods'],['v104-credit','label','Kredit dan penawaran pembelian','Credits and purchase offers'],['v104-release','label','Tanggal rilis dan pilihan layanan','Release date and service options'],['v104-catalogue','super','Atur paket dan kredit','Configure plans and credits'],['v104-labels','admin','Filter label dan panel detail','Label filters and detail drawer'],['v104-cleanup','super','Penyesuaian identitas dan rekening','Identity and bank updates'],['v104-bonus','super','Bonus di pemantauan label','Bonuses in label monitoring']];
studioCatalog.unshift(...scenes104.map(([id,role,a,b])=>({id,role,version:'10.4',title:[a,b],description:[T('Buka alur pada akun yang sesuai.','Open the flow with the relevant account.'),'Open the flow with the relevant account.']})));
const studioBefore104=studioStart;
studioStart=async function(id){const scene=scenes104.find(x=>x[0]===id);if(!scene)return studioBefore104(id);await studioBefore104('overview');studioAccount(scene[1]);studioSelected=id;let open=()=>{};
 if(id==='v104-plans')open=plans10;if(id==='v104-credit')open=purchase10;if(id==='v104-release')open=()=>releaseForm10();
 if(id==='v104-catalogue')module102('catalogue104');if(id==='v104-labels')module102('labels');if(id==='v104-cleanup')module102('cleanup-pending');if(id==='v104-bonus'){state.mode='platform';state.page='liability9';pendingUI.tab='bonuses';}
 render();open();};
render();
