/* Shared details complete the same record; no duplicate internal workspace. */
const reviewHeadingBefore105=reviewHeadingUI;reviewHeadingUI=function(m,status,subtitle){const t=document.createElement('template');t.innerHTML=reviewHeadingBefore105(m,status,subtitle);if(m.avatar103)t.content.querySelector('.review-avatar-ui').outerHTML=avatar103(m,'review-avatar-ui');return t.innerHTML;};
function creditUse105(r){let left=Math.max(0,Flow105.delta(r,ten));const used={daily:0,replacement:0,paid:0};for(const lot of member10().lots.filter(l=>l.available>0&&(!l.expires||l.expires>ten.now)&&(l.type!=='daily'||RM10.daily(ten,member10()))).sort((a,b)=>Credit11.compare(Credit11.forRelease(ten,r),a,b))){const amount=Math.min(left,lot.available);used[lot.type]=(used[lot.type]||0)+amount;left-=amount;if(!left)break;}return used;}
const submitDialogBefore105=submitCheck105;submitCheck105=function(){submitDialogBefore105();const box=document.querySelector('.submission-confirm105');if(!box)return;const r=r105(),use=creditUse105(r),target=box.querySelector('small');target.outerHTML=`<dl class="credit-use105"><div><dt>${L105('Tambahan alokasi dari kredit harian','New allocation from daily credits')}</dt><dd>${use.daily}</dd></div><div><dt>${L105('Dari kredit sementara','From temporary credits')}</dt><dd>${use.replacement}</dd></div><div><dt>${L105('Dari kredit tambahan / Flex','From purchased / Flex credits')}</dt><dd>${use.paid}</dd></div></dl>`;};
function readable105(value){if(value==null||value==='')return '—';if(typeof value==='boolean')return value?'Ya':'Tidak';if(Array.isArray(value))return value.map(v=>typeof v==='object'?v.name||v.title||'—':v).join(', ');if(typeof value==='object')return value.name||L105('Berkas diperbarui','File updated');return String(value)}
const diffTitles105={title:'Judul',type:'Jenis rilisan',genre:'Genre',subgenre:'Subgenre',year:'Tahun',copyright:'Pemilik karya',master:'Pemilik master',primary:'Artis utama',featured:'Artis tamu',cover:'Cover',date:'Tanggal',service:'Layanan',language:'Bahasa judul',lyricLanguage:'Bahasa lirik',lyrics:'Lirik',composer:'Komposer',lyricist:'Penulis lirik',arranger:'Arranger',producer:'Produser',audio:'Audio',preview:'Detik cuplikan',kind:'Vokal / instrumental',explicit:'Eksplisit',isrc:'ISRC'};
diff105=function(r){const out=[],row=(name,a,b)=>out.push(`<div class="diff105"><strong>${E(name)}</strong><div><small>${L105('Sebelumnya','Before')}</small><p>${E(readable105(a))}</p></div><div><small>${L105('Sekarang','After')}</small><p>${E(readable105(b))}</p></div></div>`),a=r.previous105,b=r.submitted105;for(const key of Object.keys(b)){if(key==='songs'||key==='declaration'||JSON.stringify(a[key])===JSON.stringify(b[key]))continue;row(diffTitles105[key]||key,a[key],b[key]);}for(const old of a.songs)if(!b.songs.some(t=>t.id===old.id))row(L105('Lagu dihapus','Track removed'),old.title,'—');b.songs.forEach((t,i)=>{const old=a.songs.find(s=>s.id===t.id);if(!old){row(L105('Lagu ditambahkan','Track added'),'—',t.title);return;}if(a.songs.findIndex(s=>s.id===t.id)!==i)row(t.title+' · '+L105('Urutan','Order'),a.songs.findIndex(s=>s.id===t.id)+1,i+1);for(const key of Object.keys(diffTitles105))if(key in t&&JSON.stringify(t[key])!==JSON.stringify(old[key]))row(t.title+' · '+diffTitles105[key],old[key],t[key]);});return out.join('')||L105('Tidak ada perubahan metadata.','No metadata changes.');};
const detailBefore105=detail105;detail105=function(){const r=r105(),tmp=document.createElement('template');tmp.innerHTML=detailBefore105();const columns=tmp.content.querySelector('.detail-columns105'),artists=[...r.primary.map(a=>({...a,role:L105('Artis utama','Primary artist')})),...r.featured.map(a=>({...a,role:L105('Artis tamu rilisan','Release featured artist')}))];columns?.insertAdjacentHTML('beforebegin',`<section class="panel detail-panel105 artist-review105"><h2>${L105('Artis & identitas rilisan','Artists & release identity')}</h2><div>${artists.map(a=>`<article><span class="artist-photo105">${a.photo?`<img src="${E(a.photo)}" alt="${E(a.name)}">`:''}</span><div><small>${a.role}</small><strong>${E(a.name)}</strong>${(a.social||[]).filter(validURL105).map(url=>`<a href="${E(url)}" target="_blank" rel="noopener noreferrer">${E(url)} ↗</a>`).join('')}${a.spotify&&validURL105(a.spotify)?`<a href="${E(a.spotify)}" target="_blank" rel="noopener noreferrer">Spotify ↗</a>`:''}</div></article>`).join('')}</div></section>`);
 if(r.confirmedDate&&r.confirmedDate!==r.date)tmp.content.querySelector('.detail-hero105').insertAdjacentHTML('afterend',`<section class="correction-note105"><strong>${L105('Tanggal pengiriman perlu dicocokkan','Delivery date needs checking')}</strong><p>${L105('Tanggal label','Label date')}: ${fullDate104(r.date)} · ${L105('Dicatat di Believe','Recorded in Believe')}: ${fullDate104(r.confirmedDate)}</p></section>`);
 const credit=tmp.content.querySelector('.credit-breakdown105');if(r.returns105?.length)credit?.insertAdjacentHTML('afterend',`<div class="return-details105">${r.returns105.map(x=>`<p><strong>${x.amount} ${L105('kredit','credits')} ${x.type==='paid'?'Flex':x.type==='daily'?L105('harian','daily'):L105('sementara','temporary')}</strong><small>${x.expires?L105('Berlaku sampai ','Expires ')+date10(x.expires,true)+' WIB':L105('Tanpa kedaluwarsa','No expiry')}</small></p>`).join('')}${r.reason?`<p>${E(r.reason==='timeout'?L105('Batas waktu perbaikan terlewat.','Correction deadline passed.'):r.reason)}</p>`:''}</div>`);
 const trackDetails=tmp.content.querySelectorAll('.detail-track105');trackDetails.forEach((el,i)=>{const t=r.songs[i];el.querySelector('dl')?.insertAdjacentHTML('beforeend',`<div><dt>${L105('Bahasa lirik','Lyric language')}</dt><dd>${t.kind==='instrumental'?'—':E(t.lyricLanguage||'—')}</dd></div><div><dt>${L105('Awal cuplikan','Preview start')}</dt><dd>${t.preview} ${L105('detik','seconds')}</dd></div>`);});return tmp.innerHTML;};
function metadataText105(r){return [r.title,'Label: '+RM10.getMember(ten,r.member).name,'Jenis: '+r.type,'Artis utama: '+names105(r.primary),'Artis tamu: '+names105(r.featured),'Genre: '+r.genre+' / '+r.subgenre,'Tahun: '+r.year,'C Line: '+r.copyright,'P Line: '+r.master,'Tanggal: '+fullDate104(r.date),'UPC: '+(r.upc||''),...r.songs.map((t,i)=>'\n'+(i+1)+'. '+t.title+'\n'+Object.entries(diffTitles105).filter(([k])=>k in t&&!['audio','cover'].includes(k)).map(([k,label])=>label+': '+readable105(t[k])).join('\n'))].join('\n');}
const opRowsBefore105=opRows;opRows=function(items,limit=4){return items.slice(0,limit).map(x=>{const late=x.kind==='withdraw'&&x.status!=='paid'&&x.status!=='rejected'&&Number(RM10.day(ten.now).slice(-2))>20&&(!x.period||x.period<=RM10.day(ten.now).slice(0,7)),title=late?T('Pencairan terlambat','Payout overdue'):opPriority(x)?T('Prioritas','Priority'):T('Baru','New'),tone=late?'red':opPriority(x)?'amber':'blue';return `<div class="action-row"><div class="grow"><strong>${L(x.title)}</strong><small>${x.id} · ${x.kind==='withdraw'&&x.status==='approved'?T('Terverifikasi · menunggu pembayaran','Verified · awaiting payment'):opLabel(x)}</small></div><span class="badge work-badge104 ${tone}">${title}</span>${btn(icon('arrow'),'op-detail',`data-id="${x.id}" aria-label="${T('Tinjau','Review')} ${esc(L(x.title))}"`,'small')}</div>`;}).join('');};
const guide105=standardsPage9;standardsPage9=function(){const t=document.createElement('template');t.innerHTML=guide105();const rows=[...t.content.querySelectorAll('tbody tr')],seen=new Set();for(const row of rows){const cell=row.querySelector('td');if(!cell)continue;const label=(cell.querySelector('strong,.badge')||cell).textContent.trim();if(['Prioritas','Lewat tenggat'].includes(label)){if(seen.has(label)){row.remove();continue;}seen.add(label);const strong=cell.querySelector('strong');if(strong)strong.outerHTML=`<span class="badge work-badge104 ${label==='Prioritas'?'amber':'red'}">${label}</span>`;}}return t.innerHTML;};
window.addEventListener('beforeunload',()=>{if(ui105.view==='edit')persist105()});
const setServiceBefore105=setService105;setService105=function(service,moving=false){setServiceBefore105(service,moving);const hint=document.querySelector('.service-hint105');if(hint)hint.textContent=service==='Standard'?'':service+' · '+Flow105.rate(r105(),ten)+' '+L105('kredit / lagu','credits / track');clearTimeout(ui105.costTimer);ui105.costTimer=setTimeout(()=>document.querySelector('.service-cost105')?.classList.remove('visible'),250);};
const editorBefore105=editor105;editor105=function(){return editorBefore105().replace('<span class="available105">',`<small class="service-hint105">${r105().service==='Standard'?'':r105().service+' · '+Flow105.rate(r105(),ten)+' '+L105('kredit / lagu','credits / track')}</small><span class="available105">`);};
const rowsBefore105=filterRows105;filterRows105=function(){return rowsBefore105().filter(r=>isLabel10()||r.status!=='draft').map(r=>!isLabel10()&&r.status==='revision'&&r.submitted105?{...r,...structuredClone(r.submitted105),artist:names105(r.submitted105.primary),tracks:r.submitted105.songs.length}:r);};
const releaseOpenBefore105=releaseModal10;releaseModal10=function(id){const r=RM10.getRelease(ten,id);if(!isLabel10()&&r?.status==='draft')return;return releaseOpenBefore105(id)};
const themeBefore105=themeMode105;themeMode105=function(mode){themeBefore105(mode);savePrefs();document.querySelectorAll('.theme-toggle').forEach(b=>{b.setAttribute('aria-checked',String(state.theme==='dark'));b.setAttribute('aria-label','Theme: '+(ten.themeMode105||state.theme));});};
if(ten.themeMode105)themeMode105(ten.themeMode105);
const formOpenBefore105=releaseForm10;releaseForm10=function(id){const r=id&&RM10.getRelease(ten,id);if(r&&!r.flow105){if(r.member!==ten.member||!isLabel10())return;if(r.status==='revision')return legacyReleaseForm105(id);if(r.status==='draft'){Object.assign(r,{flow105:true,type:r.tracks===1?'single':r.tracks<=6?'ep':'album',primary:r.artist?[{id:'legacy-artist-'+r.id,name:r.artist,social:[]}]:[],featured:[],genre:r.genre||'',subgenre:r.subgenre||'',year:r.year||2026,copyright:r.copyright||'',master:r.master||'',version:r.version||1,round:0,declaration:false,songs:Array.from({length:r.tracks||1},(_,i)=>Flow105.track(ten,i===0?r.title:''))});Flow105.sync(r);}}return formOpenBefore105(id);};
const invoicePanelBefore105=invoice103;invoice103=function(){if(document.querySelector('[data-plan104]'))ui105.planY=document.querySelector('#dialog .dialog-body')?.scrollTop||0;return invoicePanelBefore105();};
const invoiceBackBefore105=invoiceBack105;invoiceBack105=function(){invoiceBackBefore105();const body=document.querySelector('#dialog .dialog-body');if(body)body.scrollTop=ui105.planY||0;};
