/* Versioned local samples: every scenario opens its owning role. */
function fixture105(stage='draft',count=1){
 const role=ten.role,mem=ten.member;ten.role='label';ten.member='awan';const m=member10();m.active=true;m.contract=true;m.welcome=true;m.onboardingSeen105=true;
 const r=RM10.getRelease(ten,Flow105.apply(ten,'create'));Object.assign(r,{title:count===1?'Ruang untuk Pulang':'Cerita di Antara Kita',type:count===1?'single':count<7?'ep':'album',genre:'Pop',subgenre:'Indie Pop',year:2026,copyright:'Awan Records',master:'Awan Records',primary:[{id:'ART-NARA105',name:'Nara Senja',social:['https://instagram.com/narasenja.example'],photo:''}],date:RM10.earliest(ten,'Standard'),declaration:true,cover:{valid:true,name:'Cover contoh',url:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="3000" height="3000" viewBox="0 0 600 600"><defs><linearGradient id="a" x2="1" y2="1"><stop stop-color="#172c49"/><stop offset="1" stop-color="#ec8366"/></linearGradient></defs><path fill="url(#a)" d="M0 0h600v600H0z"/><circle cx="430" cy="210" r="160" fill="#f7c798" opacity=".4"/><path d="M0 500 300 270 600 400v200H0" fill="#152943"/><text x="42" y="80" fill="white" font-family="sans-serif" font-size="16" letter-spacing="6">NARA SENJA</text><text x="42" y="495" fill="white" font-family="sans-serif" font-size="34">Ruang untuk Pulang</text></svg>')}});
 r.songs=Array.from({length:count},(_,i)=>Object.assign(Flow105.track(ten),{title:count===1?r.title:['Ruang untuk Pulang','Hujan yang Sama','Pelan-Pelan','Cahaya Pagi'][i]||'Lagu '+(i+1),kind:'vocal',language:'Indonesia',lyricLanguage:'Indonesia',lyrics:'Di antara waktu, kita menemukan jalan pulang.\nNada ini menyimpan cerita kita.',composer:['Nara Pradana'],lyricist:['Nara Pradana'],audio:{valid:true,name:'Audio contoh.wav',duration:1,sampleRate:44100,key:'demo-wave105'}}));Flow105.sync(r);
 if(stage!=='draft'){Flow105.apply(ten,'submit',{id:r.id,version:r.version});ten.role='admin';ten.actor105='adovi';if(stage!=='submitted'){Flow105.apply(ten,'start',{id:r.id,version:r.version});if(stage==='revision')Flow105.apply(ten,'revision',{id:r.id,version:r.version,notes:[{field:'copyright',step:1,text:'Sesuaikan nama pemilik karya dengan dokumen izin distribusi.'}]});else if(stage!=='review'){Flow105.apply(ten,'approve',{id:r.id,version:r.version,checked:true});if(stage!=='approved'){Flow105.apply(ten,'deliver',{id:r.id,version:r.version,checked:true,date:r.date});Flow105.apply(ten,'codes',{id:r.id,version:r.version,upc:'8991234567890',codes:Object.fromEntries(r.songs.map((t,i)=>[t.id,'IDAAA260000'+i]))});if(stage==='partial'||stage==='live'){const ids=r.songs.slice(0,stage==='partial'?count-1:count).map(t=>t.id);Flow105.apply(ten,'live',{id:r.id,version:r.version,checked:true,ids,links:Object.fromEntries(ids.map(id=>[id,'https://open.spotify.com/track/example-'+id]))});}if(stage==='closed'){ten.role='super';Flow105.apply(ten,'close_failed',{id:r.id,version:r.version,checked:true,note:'Distribusi tidak dapat dilanjutkan. Kredit dikembalikan sesuai sumbernya.'});}}}}}
 ten.role=role;ten.member=mem;return r;
}
const scenes105=[
 ['welcome','label','Sambutan & jelajahi dashboard','Welcome & explore'],['claim','label','Klaim Label lama','Claim an existing label'],['activation','label','Identitas → kontrak → pemeriksaan','Identity → agreement → review'],
 ['list','label','Daftar Rilisan & filter','Release list & filters'],['editor','label','Formulir empat tahap','Four-step release editor'],['artists','label','Artis & foto opsional','Artists & optional photos'],['tracks','label','EP / Album & kontributor per lagu','EP / Album & track contributors'],['max','label','Tanggal & slider Standard–Express–MAX','Date & service slider'],
 ['review','admin','Pemeriksaan pengajuan yang sama','Review the same submission'],['revision','label','Perbaikan terarah & selisih kredit','Corrections & credit adjustment'],['delivery','admin','Pengiriman ke Believe','Delivery to Believe'],['live','admin','Kode & Konfirmasi Tayang','Codes & Live confirmation'],['partial','super','EP tayang 3 dari 4 lagu','EP with 3 of 4 tracks live'],['return','label','Pengembalian kredit di atensi','Returned credits in attention'],['plans','label','Bandingkan paket tanpa loncat scroll','Compare plans without scroll jumps'],['guide','super','Indicator Guide & penanda pekerjaan','Indicator Guide & work markers']
];
studioCatalog.unshift(...scenes105.map(([id,role,a,b])=>({id:'v105-'+id,role,version:'10.5',title:[a,b],description:['Langsung masuk ke akun dan kondisi terkait.','Open the relevant role and state directly.']})));
const studioPrevious105=studioStart;
studioStart=async function(id){if(!id.startsWith('v105-'))return studioPrevious105(id);const scene=scenes105.find(s=>'v105-'+s[0]===id);if(!scene)return;onboarding105.active=false;onboarding105.document=false;onboarding105.bank=false;await studioPrevious105('overview');ui105.view='list';ui105.id=null;ui105.tab='all';ui105.q='';ui105.status='all';ui105.type='all';ui105.from='';ui105.to='';studioSelected=id;const kind=scene[0];let open=()=>{};
 if(['welcome','claim','activation'].includes(kind)){studioAccount('label','embun');const m=member10();m.paid=kind==='activation';m.onboardingSeen105=false;m.name='';open=kind==='claim'?claimStart105:kind==='activation'?activationPopup102:welcomeStart105;}
 else {studioAccount(scene[1],'awan');member10().onboardingSeen105=true;let stage=({review:'submitted',revision:'revision',delivery:'approved',live:'delivered',partial:'partial',return:'closed'})[kind]||'draft';const r=fixture105(stage,['tracks','partial'].includes(kind)?4:1);if(kind==='list'){fixture105('submitted');fixture105('live');module102('releases');}else if(['editor','artists','tracks','max','revision'].includes(kind)){module102('releases');ui105.id=r.id;ui105.view='edit';ui105.step=({artists:2,tracks:3,max:4})[kind]||1;}else if(['review','delivery','live','partial'].includes(kind)){module102('releases');ui105.id=r.id;ui105.view='detail';}else if(kind==='plans')open=plans10;else if(kind==='guide'){state.page='standards9';state.mode='platform';}else state.page='dashboard';}
 save10();render();closeModal();open();
};
function demoWave105(){const data=new ArrayBuffer(44+44100*2),v=new DataView(data),str=(p,s)=>[...s].forEach((c,i)=>v.setUint8(p+i,c.charCodeAt(0)));str(0,'RIFF');v.setUint32(4,data.byteLength-8,true);str(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,44100,true);v.setUint32(28,88200,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,88200,true);for(let i=0;i<44100;i++)v.setInt16(44+i*2,Math.sin(i/44100*Math.PI*440)*1200,true);mediaStore105('readwrite','demo-wave105',new Blob([data],{type:'audio/wav'})).catch(()=>{});}
const studioComplete105=studioStart;studioStart=async function(id){onboarding105.document=false;onboarding105.bank=false;ui105.view='list';ui105.id=null;return studioComplete105(id);};
demoWave105();render();
