/* V10.5 global component repair and source-connected navigation. */
const switchMemory105=new Map();
function enhance105(root=document){root.querySelectorAll('.tabs,.switch103,.switch104,.ten-service,.mode-switch').forEach((el,index)=>{
 const buttons=[...el.children].filter(n=>n.tagName==='BUTTON'),selected=buttons.find(b=>b.matches('.active,.selected')||b.getAttribute('aria-pressed')==='true');if(buttons.length<2||!selected)return;
 const context=el.matches('.mode-switch')?'sidebar-mode:'+ten.role:el.closest('[data-plan104]')?.dataset.plan104||el.closest('#dialog')?.querySelector('#dialog-title')?.textContent||[ten.role,state.mode,state.page,v4.module].join(':');
 const key=context+'|'+(el.dataset.switchKey105||el.getAttribute('aria-label')||el.className.replace('shared-switch104','').trim())+'|'+index;
 el.classList.add('shared-switch104');const which=buttons.indexOf(selected),target={x:selected.offsetLeft,y:selected.offsetTop,w:selected.offsetWidth,h:selected.offsetHeight,which},old=switchMemory105.get(key);el.classList.add('shared-switch104');let bar=el.querySelector(':scope > .switch-indicator104');if(!bar){bar=document.createElement('i');bar.className='switch-indicator104';bar.setAttribute('aria-hidden','true');el.prepend(bar);}
 const changed=old&&old.which!==which;bar.style.transition='none';Object.assign(bar.style,{left:'0px',top:(changed?old.y:target.y)+'px',width:(changed?old.w:target.w)+'px',height:target.h+'px',transform:`translateX(${changed?old.x:target.x}px)`});if(changed){bar.getBoundingClientRect();bar.style.transition='transform 240ms cubic-bezier(.2,.75,.25,1),width 240ms cubic-bezier(.2,.75,.25,1),top 240ms cubic-bezier(.2,.75,.25,1)';bar.style.transform=`translateX(${target.x}px)`;bar.style.width=target.w+'px';bar.style.top=target.y+'px';}switchMemory105.set(key,target);
 });}
const actBefore105=RM10.act;
RM10.act=function(s,action,p={}){const r=p.id&&RM10.getRelease(s,p.id);if(r?.flow105&&['draft','submit','start','revision','resubmit','approve','deliver','codes','live','reject','cancel','cancel_confirm','not_found','date_error','followup','reopen','downgrade_accept','downgrade_offer'].includes(action))throw Error('state');const res=actBefore105(s,action,p);if(['profile','profile_edit','profile_approve','profile_photo'].includes(action)){const m=RM10.getMember(s,p.member||s.member),l=data.v9.labels.find(x=>x.id===m.source9);if(l){l.name=m.name;l.avatar103=m.avatar103;}}return res;};
const tickBefore105=RM10.tick;RM10.tick=function(s){tickBefore105(s);Flow105.tick(s)};
const moduleBefore105=modulePage;modulePage=function(){if(v4.module==='releases')return releases10();return moduleBefore105();};
const routeBefore105=route102;route102=function(id){if(id==='releases'){ui105.view='list';ui105.id=null;}return routeBefore105(id)};
const actionBefore105=handleAction;handleAction=async function(b){if(b.dataset.action==='v4-module'&&b.dataset.id==='releases'){ui105.view='list';ui105.id=null;}if(b.dataset.action==='theme'){themeDialog105();return;}if(b.dataset.action==='close'&&document.querySelector('#dialog [data-invoice105]')){invoiceBack105();return;}return actionBefore105(b);};
function themeMode105(mode){ten.themeMode105=mode;const h=new Date().getHours();state.theme=mode==='auto'?(h>=6&&h<18?'light':'dark'):mode;ten.theme=state.theme;document.documentElement.dataset.theme=state.theme;save10();}
function themeDialog105(onboarding=false){reviewDialogUI(L105('Pilih tampilanmu','Choose your appearance'),`<div class="theme-dialog105"><div class="theme-preview105"><i></i><span></span><span></span></div><h2>${L105('Nyaman di setiap waktu.','Comfortable at any hour.')}</h2><div class="theme-slider105"><input id="theme-range105" type="range" min="0" max="2" step="1" value="${['light','auto','dark'].indexOf(ten.themeMode105||state.theme)}" aria-label="Light, Auto, Dark"><div>${['Light','Auto','Dark'].map((x,i)=>`<button type="button" data-global105="theme" data-id="${['light','auto','dark'][i]}">${x}</button>`).join('')}</div></div><p>${L105('Auto mengikuti waktu: terang 06.00–17.59, gelap 18.00–05.59.','Auto follows local time: light 06:00–17:59, dark 18:00–05:59.')}</p>${onboarding?`<button class="btn primary" data-global105="theme-done">${L105('Buka Dashboard','Open Dashboard')}</button>`:''}</div>`);}
window.addEventListener('input',e=>{if(e.target.id==='theme-range105')themeMode105(['light','auto','dark'][+e.target.value]);});
window.addEventListener('click',e=>{const b=e.target.closest('[data-global105]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const a=b.dataset.global105;if(a==='theme'){themeMode105(b.dataset.id);document.querySelector('#theme-range105').value=['light','auto','dark'].indexOf(b.dataset.id);}if(a==='payment-done'){closeModal();state.page='dashboard';render();if(!member10().active)activationPopup102();return;}if(a==='theme-done'){member10().themeChosen106=true;save10();closeModal();state.page='dashboard';render();}if(a==='invoice-back')invoiceBack105();if(a==='invoice-wait'){closeModal();state.page='dashboard';ui105.view='list';render();}if(a==='show-identity'){const m=RM10.getMember(ten,b.dataset.id);if(ten.role!=='super')return;reviewDialogUI(L105('KTP Penanggung Jawab','Representative Identity Card'),identityRead10(m.identity));}},true);
setInterval(()=>{if(ten.themeMode105==='auto'&&!storageChanged116()){const previous=state.theme;themeMode105('auto');if(previous!==state.theme)document.documentElement.dataset.theme=state.theme;}},60000);
const verifyBefore105=verificationMark9;verificationMark9=function(l){return verifyBefore105(l).replace(/<span class="verify9"[^>]*>✓<\/span>/g,`<svg class="verified105" viewBox="0 0 24 24" role="img" aria-label="${L105('Terverifikasi','Verified')}"><path fill="#3b9feb" d="m9.2 1.5 2.8 1.6 2.8-1.6 1.8 2.7 3.3.2.2 3.3 2.7 1.8-1.6 2.8 1.6 2.8-2.7 1.8-.2 3.3-3.3.2-1.8 2.7-2.8-1.6-2.8 1.6-1.8-2.7-3.3-.2-.2-3.3L1.2 15l1.6-2.8-1.6-2.8 2.7-1.8.2-3.3 3.3-.2Z"/><path fill="none" stroke="white" stroke-width="2.5" d="m6.7 12 3.3 3.3 7.3-7.3"/></svg>`);};
const plansBefore105=plans10;plans10=function(){const body=document.querySelector('#dialog.plan-dialog103 .dialog-body'),y=body?.scrollTop||0;plansBefore105();const target=document.querySelector('#dialog .dialog-body');if(target)target.scrollTop=y;enhance105($('#dialog'));};
const invoiceBefore105=invoice103;invoice103=function(){invoiceBefore105();const body=document.querySelector('#dialog .dialog-body');if(!body)return;body.setAttribute('data-invoice105','true');body.insertAdjacentHTML('afterbegin',`<button type="button" class="btn text" data-global105="invoice-back">← ${L105('Kembali ke pilihan paket','Back to plans')}</button>`);body.insertAdjacentHTML('beforeend',`<p class="subscription-start105">${L105('Masa langganan dimulai setelah akun labelmu aktif.','Your subscription starts once your label account is activated.')}</p><button type="button" class="btn" data-global105="invoice-wait">${L105('Bayar nanti · Buka Dashboard','Pay later · Open Dashboard')}</button>`);};
function invoiceBack105(){const m=member10();if(m.invoice?.status==='pending'){m.invoice.status='cancelled';save10();}closeModal();plans10();}
document.querySelector('#dialog').addEventListener('cancel',e=>{if(document.querySelector('[data-invoice105]')){e.preventDefault();invoiceBack105();}});
const cleanupBase105=cleanupOpen;cleanupOpen=function(id){cleanupBase105(id);const m=RM10.getMember(ten,id),d=document.querySelector('[data-pending-form=cleanup] details');if(d)d.outerHTML=`<button class="identity-view105 full" type="button" data-global105="show-identity" data-id="${id}"><span class="id-card-art105"><i></i><b></b><b></b></span><span><strong>${L105('KTP Penanggung Jawab','Representative Identity Card')}</strong><small>${E(m.identity.person)} · ${L105('Buka dokumen','Open document')}</small></span><span>↗</span></button>`;const head=document.querySelector('#dialog .review-label-ui');if(head&&m.avatar103&&!head.querySelector('img'))head.insertAdjacentHTML('afterbegin',avatar103(m,'tiny103'));};
const locBefore105=directoryLocationFields;directoryLocationFields=function(identity){return locBefore105(identity).replaceAll('Lokasi operasional label','Lokasi').replaceAll('Lokasi operasional','Lokasi').replaceAll('Operating location','Location');};
const notificationBefore105=notification10;notification10=function(){const own=ten.notifications.filter(n=>n.member===ten.member&&['credit_return105','partial105'].includes(n.key));return own.slice(0,4).map(n=>`<div class="ten-item"><div><strong>${n.key==='credit_return105'?L105('Kredit pengajuan dikembalikan','Submission credits returned'):L105('Sebagian lagu telah tayang','Some tracks are live')}</strong><small>${date10(n.at,true)}</small></div>${btn105('↗','detail',n.ref)}</div>`).join('')+notificationBefore105();};
const attentionBefore105=labelAttention102;labelAttention102=function(){const n=ten.notifications.find(n=>n.member===ten.member&&n.key==='credit_return105');return attentionBefore105()+(n?`<section class="attention9"><div class="spread"><h2><span class="status-dot9"></span>${L105('Kredit rilisan dikembalikan','Release credits returned')}</h2>${btn105('↗','detail',n.ref)}</div><p>${L105('Lihat alasan, jumlah dan masa berlaku kredit pada rincian rilisan.','Review the reason, amount and expiry in the release details.')}</p></section>`:'');};
const guideBefore105=standardsPage9;standardsPage9=function(){const template=document.createElement('template');template.innerHTML=guideBefore105();const sections=[...template.content.querySelectorAll('section')],guide=sections.find(s=>/Kamus Penanda|Indicator Guide/.test(s.querySelector('h2,h3')?.textContent||''));if(guide){const anchor=template.content.querySelector('.standards-top9');anchor?.after(guide);const body=guide.querySelector('tbody');if(body)body.insertAdjacentHTML('beforeend',`<tr class="guide-group105"><th colspan="2">${L105('Kondisi pekerjaan & tenggat','Work conditions & deadlines')}</th></tr>${[['Prioritas','amber','Pekerjaan yang didahulukan; bukan nama layanan Express/MAX.'],['Lewat tenggat','red','Batas waktu tindakan telah terlewati.'],['Pencairan terlambat','red','Mulai tanggal 21 WIB untuk pencairan jatuh tempo periode terkait yang belum dibayar.'],['Sebagian tayang','amber','Sebagian lagu telah dikonfirmasi; alokasi lagu lainnya tetap ditahan.']].map(([name,color,text])=>`<tr><td><span class="badge work-badge104 ${color}">${name}</span></td><td>${text}</td></tr>`).join('')}`);}return template.innerHTML;};
const conditionBefore105=condition8;condition8=function(x){let html=conditionBefore105(x);if(x.kind==='withdraw'&&RM10.day(ten.now).slice(-2)>'20'&&x.due&&x.due<=RM10.day(ten.now))html=html.replaceAll('Lewat periode','Pencairan terlambat').replaceAll('amber','red');return html.replace(/class="badge /g,'class="badge work-badge104 ');};
const renderBefore105=render;
render=function(){const side=document.querySelector('.side-scroll'),sideY=side?.scrollTop||0;renderBefore105();document.title='Rilis Musik · V10.5';document.querySelector('.version-pill').textContent='V10.5';document.querySelector('.footer span').textContent='RILIS MUSIK · V10.5';document.querySelector('.side-scroll').scrollTop=sideY;
 document.querySelectorAll('.condition8,.status8,.work-badges9 .badge').forEach(el=>el.classList.add('work-badge104'));
 if(state.page==='module'&&v4.module==='releases'&&document.querySelector('.header-path'))document.querySelector('.header-path').innerHTML=(isLabel10()?'Label':ten.role==='super'?'Super Admin':'Admin')+' <i>/</i> '+L105('Rilisan','Releases');
 mountMedia105();
};
