/* Royalty prototype: integer IDR ledger; immutable posted values; role checks. */
(function(root){
'use strict';
const copy=x=>JSON.parse(JSON.stringify(x));
const fail=message=>{throw new Error(message)};
const checked=n=>{if(n>BigInt(Number.MAX_SAFE_INTEGER)||n<BigInt(Number.MIN_SAFE_INTEGER))fail('Total nominal melampaui batas perhitungan yang aman.');return Number(n)};
const sum=rows=>checked(rows.reduce((n,r)=>{if(!Number.isSafeInteger(r.amount))fail('Nominal laporan tidak valid.');return n+BigInt(r.amount)},0n));
const delta=(a,b)=>checked(BigInt(a)-BigInt(b));
const now=()=>new Date().toISOString();
const event=(s,kind,ref,actor,note='')=>s.history.push({kind,ref,actor,note,at:now()});
function seed(members){const a=members.find(m=>m.id==='awan')||members[0],b=members.find(m=>m.id!==a.id)||a;
 const make=(id,member,title,amount,platform,country)=>({id,member:member.id,track:id.split('-')[0],title,release:title,artist:member.id===a.id?'Nara Senja':'Laras Pagi',isrc:'IDRM026'+id.replace(/\D/g,'').padStart(5,'0'),upc:'899100000001',period:'2026-09',sales:'2026-07',platform,country,kind:'Streaming',quantity:Math.round(amount/10),amount,matched:true});
 const rows=[make('T1-1',a,'Ruang untuk Pulang',300000,'Spotify','Indonesia'),make('T1-2',a,'Ruang untuk Pulang',200000,'Apple Music','Malaysia'),make('T2-1',b,'Cahaya Pagi',300000,'Spotify','Indonesia')];rows[1].isrc=rows[0].isrc;
 return {schema:1,serial:2,batches:[{id:'IMP-001',name:'Believe_September_2026.csv',at:'2026-09-27T02:00:00Z',rate:18000,share:100,rows,posted:[],block:'',fingerprint:'example-september',version:1}],ledger:[],receipts:[],history:[],corrections:[],cases:[],version:0};
}
function access(actor,action){if(!actor||!['admin','super'].includes(actor.role))fail('Akses tidak tersedia.');if(['publish','receive','correct','replace','allocate','unmatched-receipt','archive'].includes(action)&&actor.role!=='super')fail('Tindakan ini hanya tersedia untuk Super Admin.');}
function batch(s,id){return s.batches.find(b=>b.id===id)||fail('Laporan tidak ditemukan.');}
function balance(s,member){const entries=s.ledger.filter(l=>l.member===member);const available=sum(entries.filter(l=>l.bucket==='available')),pending=sum(entries.filter(l=>l.bucket==='pending'));return {available,pending};}
function rows(s,actor){return s.batches.flatMap(b=>b.rows.filter(r=>b.posted.includes(r.member)&&r.matched&&(!actor.member||r.member===actor.member)).map(r=>({...r,batch:b.id,version:b.version})));}
const referenceKey=v=>String(v||'').trim().toLowerCase();
const sourceKey=r=>JSON.stringify([r.isrc,r.period,r.sales,r.platform,r.country,r.kind].map(v=>String(v||'').normalize('NFKC').trim().toLowerCase()));
function validateRows(rs){if(!rs?.length||rs.some(r=>!Number.isSafeInteger(r.amount)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(r.period)))fail('Periode atau nominal laporan tidak valid.');}
function assertUnique(s,rs,except=null){const own=new Set(),existing=new Map();for(const b of s.batches.filter(b=>b.id!==except&&!b.archived))for(const r of b.rows)existing.set(sourceKey(r),b.id);for(const r of rs){const key=sourceKey(r);if(own.has(key))fail('Baris sumber berulang dalam file. Periksa laporan sebelum mengimpor.');if(existing.has(key))fail('Data sumber sudah ada pada '+existing.get(key)+'. Tinjau laporan tersebut atau gunakan penggantian laporan.');own.add(key);}}
function act(s,actor,action,p={}){access(actor,action);const b=p.id?batch(s,p.id):null;
 if(action==='import'){if(s.batches.some(x=>!x.archived&&x.fingerprint===p.fingerprint))fail('File yang sama sudah diimpor.');validateRows(p.rows);assertUnique(s,p.rows);
 const id='IMP-'+String(s.serial++).padStart(3,'0');s.batches.push({id,name:p.name,at:now(),rate:p.rate,share:p.share,rows:copy(p.rows),fingerprint:p.fingerprint,block:'',posted:[],version:1});event(s,'import',id,actor.role);s.version++;return id;
 }
 if(action==='match'){const r=b.rows.find(r=>r.id===p.row);if(!r||b.posted.includes(r.member))fail('Data yang sudah diterbitkan harus melalui koreksi.');if(!p.member||!p.track||!p.note?.trim())fail('Pilih katalog, pemilik, dan alasan pencocokan.');Object.assign(r,{member:p.member,track:p.track,matched:true});event(s,'match',b.id,actor.role,p.note);}
 if(action==='archive'){if(b.posted.length||!p.note?.trim())fail('Hanya laporan yang belum diterbitkan dapat diarsipkan dengan alasan.');b.archived={at:now(),actor:actor.role,note:p.note.trim()};event(s,'archive',b.id,actor.role,p.note.trim());s.version++;return b.id;}
 if(action==='publish'){if(b.archived)fail('Laporan diarsipkan; tidak dapat diterbitkan.');validateRows(b.rows);assertUnique(s,b.rows,b.id);if(b.block)fail('Selesaikan dugaan duplikasi sebelum penerbitan.');if(b.rows.some(r=>!r.member))fail('Masih ada data tanpa pemilik; periksa potensi cakupannya terlebih dahulu.');const ids=[...new Set(p.members||[])];if(!ids.length)fail('Pilih label yang siap diterbitkan.');
 for(const m of ids){const rs=b.rows.filter(r=>r.member===m);if(!rs.length||rs.some(r=>!r.matched))fail('Data label belum selesai diperiksa.');}
 for(const m of ids){if(b.posted.includes(m))continue;b.posted.push(m);s.ledger.push({id:b.id+':publish:'+m,ref:b.id,member:m,amount:sum(b.rows.filter(r=>r.member===m)),bucket:'pending',kind:'published',at:now()});}event(s,'publish',b.id,actor.role,ids.join(', '));
 }
 if(action==='receive'){if(p.expectedVersion!==s.version)fail('Data berubah. Periksa kembali ringkasan penerimaan.');if(!p.reference?.trim()||!p.date||!Number.isSafeInteger(p.amount)||p.amount<=0)fail('Lengkapi referensi, tanggal, dan nominal penerimaan.');if(s.receipts.some(r=>referenceKey(r.reference)===referenceKey(p.reference)))fail('Referensi penerimaan sudah tercatat.');
 const ids=[...new Set(p.members||[])];if(!ids.length)fail('Pilih label yang sudah dicocokkan dengan penerimaan.');const amounts=ids.map(m=>({member:m,amount:sum(s.ledger.filter(l=>l.ref===b.id&&l.member===m&&l.bucket==='pending'))}));if(amounts.some(x=>!b.posted.includes(x.member)||x.amount<=0))fail('Tidak ada pendapatan menunggu dana untuk pilihan ini.');
 if(!p.checked)fail('Konfirmasikan kecocokan penerimaan dengan laporan.');if(sum(amounts)>p.amount)fail('Dana belum mencukupi hak label terpilih. Simpan sebagai penerimaan belum dicocokkan.');
 const receipt={id:'RC-'+(s.receipts.length+1),reference:p.reference.trim(),referenceOriginal:p.reference,date:p.date,amount:p.amount,note:p.note||'',allocations:amounts.map(x=>({...x,batch:b.id})),at:now()};s.receipts.push(receipt);
 for(const x of amounts){s.ledger.push({id:receipt.id+':out:'+x.member,ref:b.id,...x,amount:-x.amount,bucket:'pending',kind:'received',at:now()},{id:receipt.id+':in:'+x.member,ref:b.id,...x,bucket:'available',kind:'received',at:now()});}event(s,'receive',b.id,actor.role,p.reference);
 }
 if(action==='unmatched-receipt'){if(!p.reference?.trim()||!p.date||!Number.isSafeInteger(p.amount)||p.amount<=0)fail('Lengkapi penerimaan.');if(s.receipts.some(r=>referenceKey(r.reference)===referenceKey(p.reference)))fail('Referensi sudah tercatat.');s.receipts.push({id:'RC-'+(s.receipts.length+1),batch:b.id,reference:p.reference.trim(),referenceOriginal:p.reference,date:p.date,amount:p.amount,allocations:[],note:p.note||'',at:now()});event(s,'unmatched-receipt',b.id,actor.role,p.reference);}
 if(action==='allocate'){if(p.expectedVersion!==s.version)fail('Data berubah. Tinjau pencocokan kembali.');const receipt=s.receipts.find(r=>r.id===p.receipt);if(!receipt||!p.checked)fail('Konfirmasikan kecocokan penerimaan.');const available=receipt.amount-sum(receipt.allocations),allocations=(p.targets||[]).map(key=>{const [ref,member]=key.split('|'),target=batch(s,ref);if(!target.posted.includes(member))fail('Laporan label belum diterbitkan.');const amount=sum(s.ledger.filter(l=>l.ref===ref&&l.member===member&&l.bucket==='pending'));if(amount<=0)fail('Tidak ada saldo menunggu dana.');return {batch:ref,member,amount}});if(!allocations.length||new Set(p.targets).size!==allocations.length)fail('Pilih bagian laporan yang akan dicocokkan.');if(sum(allocations)>available)fail('Penerimaan belum mencukupi pilihan laporan.');for(const a of allocations){receipt.allocations.push(a);s.ledger.push({id:receipt.id+':out:'+a.batch+':'+a.member,ref:a.batch,member:a.member,amount:-a.amount,bucket:'pending',kind:'received',at:now()},{id:receipt.id+':in:'+a.batch+':'+a.member,ref:a.batch,member:a.member,amount:a.amount,bucket:'available',kind:'received',at:now()});event(s,'receive',a.batch,actor.role,receipt.reference);} }
 if(action==='replace'){validateRows(p.rows);assertUnique(s,p.rows,b.id);if(p.expectedVersion!==s.version)fail('Data berubah. Tinjau kembali perbandingan.');if(!p.reason?.trim()||!p.rows?.length||p.rows.some(r=>!r.matched||!r.member||!Number.isSafeInteger(r.amount)))fail('Selesaikan pemetaan dan alasan penggantian.');if(s.batches.some(x=>x.id!==b.id&&x.fingerprint===p.fingerprint))fail('File pengganti sudah digunakan laporan lain.');const members=[...new Set([...b.rows,...p.rows].map(r=>r.member))],diff=members.map(member=>({member,delta:delta(sum(p.rows.filter(r=>r.member===member)),sum(b.rows.filter(r=>r.member===member)))}));const c={id:'REP-'+((s.replacements?.length||0)+1),batch:b.id,oldRows:copy(b.rows),newRows:copy(p.rows),version:b.version,reason:p.reason,at:now(),diff};
 const blocked=diff.some(x=>b.posted.includes(x.member)&&(s.ledger.some(l=>l.member===x.member&&['withdrawn','processing'].includes(l.kind))||balance(s,x.member).available+x.delta<0&&s.ledger.some(l=>l.member===x.member&&l.ref===b.id&&l.bucket==='available')));
 if(blocked){s.cases.push({...c,status:'review'});event(s,'correction-review',b.id,actor.role,p.reason);s.version++;return 'review';}
 (s.replacements??=[]).push(c);for(const x of diff){if(!b.posted.includes(x.member)||!x.delta)continue;const received=s.ledger.some(l=>l.ref===b.id&&l.member===x.member&&l.bucket==='available');s.ledger.push({id:c.id+':'+x.member,ref:b.id,member:x.member,amount:x.delta,bucket:received&&x.delta<0?'available':'pending',kind:'adjustment',at:now()});}b.rows=copy(p.rows);b.version++;b.fingerprint=p.fingerprint||b.fingerprint;event(s,'correct',b.id,actor.role,p.reason);
 }
 if(action==='correct'){if(p.expectedVersion!==s.version)fail('Data berubah sejak pratinjau. Tinjau kembali koreksi.');const r=b.rows.find(x=>x.id===p.row);if(!r||!b.posted.includes(r.member)||!Number.isSafeInteger(p.amount)||!p.reason?.trim())fail('Lengkapi baris, nominal dan alasan koreksi.');const delta=checked(BigInt(p.amount)-BigInt(r.amount));if(!delta)fail('Tidak ada perubahan nominal.');
 const correction={id:'COR-'+(s.corrections.length+1),batch:b.id,row:r.id,member:r.member,before:r.amount,after:p.amount,delta,reason:p.reason,at:now(),oldRows:copy(b.rows),version:b.version};
 const paid=s.ledger.some(l=>l.member===r.member&&['withdrawn','processing'].includes(l.kind));const received=s.ledger.some(l=>l.ref===b.id&&l.member===r.member&&l.bucket==='available');
 if(paid||(received&&balance(s,r.member).available+delta<0)){s.cases.push({...correction,status:'review'});event(s,'correction-review',b.id,actor.role,p.reason);s.version++;return 'review';}
 correction.bucket=received&&delta<0?'available':'pending';s.corrections.push(correction);r.amount=p.amount;b.version++;s.ledger.push({id:correction.id,ref:b.id,member:r.member,amount:delta,bucket:correction.bucket,kind:'adjustment',at:now()});event(s,'correct',b.id,actor.role,p.reason);
 }
 s.version++;return b?.id;
}
// RFC4180-style CSV reader: quoted delimiters/newlines and escaped quotes.
function csv(text){text=text.replace(/^\uFEFF/,'');const delim=text.split(/\r?\n/)[0].split(';').length>text.split(/\r?\n/)[0].split(',').length?';':',';let out=[],row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===delim&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))out.push(row);row=[];cell='';}else cell+=c;}if(quote)fail('Tanda kutip CSV belum tertutup.');row.push(cell);if(row.some(Boolean))out.push(row);return out;}
function restoreGraph(target,source){if(!source||typeof source!=='object')return source;if(!target||typeof target!=='object'||Array.isArray(source)!==Array.isArray(target))target=Array.isArray(source)?[]:{};if(Array.isArray(source)){const old=target.slice(),used=new Set(),values=source.map((v,i)=>{const j=v&&typeof v==='object'&&v.id!==undefined?old.findIndex((x,n)=>!used.has(n)&&x&&x.id===v.id):i;used.add(j);return restoreGraph(old[j],v)});target.splice(0,target.length,...values);return target;}for(const k of Object.keys(target))if(!(k in source))delete target[k];for(const [k,v]of Object.entries(source))target[k]=restoreGraph(target[k],v);return target;}
function atomicAct(s,...args){const draft=copy(s),result=act(draft,...args);sum(draft.ledger);sum(draft.receipts);for(const b of draft.batches){sum(b.rows);for(const m of new Set(b.rows.map(r=>r.member)))sum(b.rows.filter(r=>r.member===m));}for(const m of new Set(draft.ledger.map(l=>l.member)))balance(draft,m);for(const r of draft.receipts)sum(r.allocations);restoreGraph(s,draft);return result;}
const api={seed,act:atomicAct,balance,rows,csv,batch,validateRows,sourceKey};if(typeof module!=='undefined')module.exports=api;root.Royalty107=api;
})(typeof window==='undefined'?globalThis:window);
