/* Local prototype ledger: account-level withdrawals; no bank requests. */
(function(root){
'use strict';
const copy=x=>JSON.parse(JSON.stringify(x)),fail=m=>{throw Error(m)},sum=rs=>rs.reduce((n,x)=>n+x.amount,0);
const day=at=>new Date(at+7*3600000).toISOString().slice(0,10);
function init(r){return r.withdraw108??={accounts:[],requests:[],serial:1,version:0}}
function account(r,id){return init(r).accounts.find(a=>a.id===id)||fail('Akun penarikan tidak ditemukan.')}
function owner(r,member){return init(r).accounts.find(a=>a.members.includes(member))}
function totals(r,id){const a=account(r,id),ls=r.ledger.filter(l=>a.members.includes(l.member));return {available:sum(ls.filter(l=>l.bucket==='available')),pending:sum(ls.filter(l=>l.bucket==='pending')),processing:sum(init(r).requests.filter(w=>w.account===id&&w.status!=='paid')),paid:sum(init(r).requests.filter(w=>w.account===id&&w.status==='paid'))}}
function portions(r,id){const a=account(r,id),out=new Map();for(const l of r.ledger.filter(l=>a.members.includes(l.member)&&l.bucket==='available')){const key=l.member+'|'+l.ref;if(!out.has(key))out.set(key,{member:l.member,ref:l.ref,amount:0});out.get(key).amount+=l.amount}return [...out.values()].filter(x=>x.amount!==0)}
function periods(r,parts){return [...new Set(parts.flatMap(p=>r.batches.find(b=>b.id===p.ref)?.rows.filter(x=>x.member===p.member).map(x=>x.period)||[]))].sort()}
function memo(ps){const p=ps.at(-1);if(!p)return '';let m=new Intl.DateTimeFormat('en',{month:'long',timeZone:'UTC'}).format(new Date(p+'-01T12:00Z')).toUpperCase();if(m.length>4)m=m.slice(0,3);return m+' ROYALTIES'}
const validBank=b=>!!(b&&b.bank&&b.number&&b.holder);
const fingerprint=b=>JSON.stringify(b||null);
function reason(r,id,bank,at){const a=account(r,id),s=init(r);if(s.requests.some(w=>w.account===id&&w.status!=='paid'))return 'Masih ada penarikan yang diproses.';if(!validBank(bank))return 'Rekening penerima belum disetujui.';if(a.hold)return a.hold;if(totals(r,id).available<1000000)return 'Minimal penarikan Rp1.000.000. Saldo tetap terkumpul untuk periode berikutnya.';if(+day(at).slice(-2)>14)return 'Pengajuan dibuka kembali tanggal 1 bulan berikutnya.';return ''}
function overdue(w,at){return w.status!=='paid'&&day(at)>w.cycle+'-20'}
function act(r,actor,action,p,ctx){const s=init(r),at=ctx.at,stamp=new Date(at).toISOString();if(p.version!==s.version)fail('Data berubah. Buka kembali pengajuan terbaru.');let w=p.id?s.requests.find(x=>x.id===p.id):null;if(p.id&&!w)fail('Pengajuan tidak ditemukan.');const isSuper=actor.role==='super',staff=['super','admin'].includes(actor.role);if(action==='request'){
 const a=account(r,p.account);if(actor.role!=='label'||actor.member!==a.id)fail('Hanya pemilik akun yang dapat mengajukan penarikan.');const why=reason(r,a.id,ctx.bank,at);if(why)fail(why);const parts=portions(r,a.id),amount=sum(parts);if(!Number.isSafeInteger(amount)||amount!==p.amount)fail('Saldo berubah. Periksa kembali nominal penarikan.');if(fingerprint(ctx.bank)!==p.bankFingerprint)fail('Rekening berubah. Periksa kembali tujuan pembayaran.');const ps=periods(r,parts);if(!ps.length)fail('Sumber periode saldo perlu diperiksa.');
 w={id:'WD-'+String(s.serial++).padStart(4,'0'),account:a.id,name:a.name,city:ctx.city||'—',amount,parts:copy(parts),periods:ps,memo:memo(ps),bank:copy(ctx.bank),status:'requested',cycle:day(at).slice(0,7),created:stamp,revision:1,events:[],handler:null,uncertain:false};s.requests.push(w);for(const part of parts)r.ledger.push({...part,id:w.id+':reserve:'+part.member+':'+part.ref,amount:-part.amount,bucket:'available',kind:'processing',at:stamp});
 }else{
 if(!staff)fail('Tindakan ini hanya tersedia untuk petugas.');if(['start','paid','resume','resolve-success','resolve-failed','correction','correction-keep','correction-reopen','bank'].includes(action)&&!isSuper)fail('Tindakan ini hanya tersedia untuk Super Admin.');
 if(action==='approve'){if(w.status!=='requested')fail('Pengajuan tidak sedang menunggu pemeriksaan.');if(!validBank(ctx.bank)||fingerprint(w.bank)!==fingerprint(ctx.bank))fail('Rekening berubah atau belum disetujui. Selesaikan pemeriksaan rekening terlebih dahulu.');w.status='ready'}
 else if(action==='start'){if(w.status!=='ready')fail('Pembayaran belum siap diproses.');if(account(r,w.account).hold)fail(account(r,w.account).hold);if(!validBank(ctx.bank)||fingerprint(w.bank)!==fingerprint(ctx.bank))fail('Rekening perlu diperiksa sebelum pembayaran.');w.status='processing';w.handler=actor.id;w.started=stamp}
 else if(action==='paid'||action==='resolve-success'){if(w.status!=='processing'||(action==='paid'&&w.uncertain))fail('Pastikan hasil transfer sebelum konfirmasi.');if(action==='paid'&&w.handler!==actor.id)fail('Pembayaran sedang ditangani petugas lain.');if(action==='resolve-success'&&(!w.uncertain||!p.note?.trim()))fail('Catat hasil pemeriksaan transfer.');w.status='paid';w.paid=stamp;w.uncertain=false;w.message='';for(const part of w.parts)r.ledger.push({...part,id:w.id+':paid:'+w.revision+':'+part.member+':'+part.ref,bucket:'paid',kind:'withdrawn',at:stamp})}
 else if(action==='delay'){if(!['requested','ready','processing'].includes(w.status)||w.uncertain)fail('Pengajuan tidak dapat ditunda pada kondisi ini.');if(actor.role==='admin'&&w.status==='processing')fail('Hanya petugas pembayaran yang dapat menindaklanjuti transfer.');if(!['bank','service','uncertain','other'].includes(p.reason)||!p.message?.trim())fail('Isi alasan dan pesan untuk label.');if(w.status==='processing'&&p.reason!=='uncertain'&&!p.failed)fail('Pastikan transfer belum terjadi atau telah dipastikan gagal.');w.resume=w.status==='requested'?'requested':'ready';w.reason=p.reason;w.message=p.message.trim();w.internal=p.note||'';w.uncertain=p.reason==='uncertain';w.status=w.uncertain?'processing':'delayed'}
 else if(action==='resume'){if(w.status!=='delayed')fail('Pembayaran tidak sedang ditunda.');if(!validBank(ctx.bank)||fingerprint(w.bank)!==fingerprint(ctx.bank))fail('Rekening terbaru belum disetujui untuk pengajuan ini.');if(w.reason==='bank'&&!w.bankResolved)fail('Konfirmasikan rekening yang sudah disetujui terlebih dahulu.');w.status=w.resume||'ready';w.message='';w.handler=null;w.bankResolved=false}
 else if(action==='resolve-failed'){if(w.status!=='processing'||!w.uncertain||!p.note?.trim())fail('Catat hasil pemeriksaan transfer terlebih dahulu.');w.status='ready';w.uncertain=false;w.handler=null;w.message='';}
 else if(action==='bank'){if(w.status!=='delayed'||!validBank(ctx.bank)||!p.note?.trim())fail('Rekening harus disetujui dan alasan perubahan dicatat.');w.events.push({action:'previous-bank',at:stamp,actor:actor.id,bank:copy(w.bank),internal:true});w.bank=copy(ctx.bank);w.bankResolved=true}
 else if(action==='correction'){if(w.status!=='paid'||!p.note?.trim())fail('Catat alasan koreksi pembayaran.');w.status='correction';w.message='Pencatatan pembayaran sedang diperiksa.';w.correctionNote=p.note;}
 else if(action==='correction-keep'){if(w.status!=='correction'||!p.note?.trim())fail('Catat hasil pemeriksaan.');w.status='paid';w.message=''}
 else if(action==='correction-reopen'){if(w.status!=='correction'||!p.note?.trim()||!p.failed)fail('Pastikan transfer tidak terjadi atau gagal dan catat hasil pemeriksaan.');for(const part of w.parts)r.ledger.push({...part,id:w.id+':reverse:'+w.revision+':'+part.member+':'+part.ref,amount:-part.amount,bucket:'paid',kind:'payment-correction',at:stamp});w.status='ready';w.handler=null;w.message='';w.paid=null}
 else fail('Tindakan tidak tersedia.');w.revision++;
 }
 w.events.push({action,at:stamp,actor:actor.id||actor.member,role:actor.role,note:p.note||'',message:w.message||'',status:w.status});s.version++;r.version++;return w.id;
}
const api={init,account,owner,totals,portions,periods,memo,reason,overdue,act,fingerprint};if(typeof module!=='undefined')module.exports=api;root.Withdraw108=api;
})(typeof window==='undefined'?globalThis:window);
