const scenes108=[['label','label','Penarikan: saldo siap diajukan','Withdrawals: available balance'],['master','label','Master: satu saldo seluruh label','Master: one aggregated balance'],['minimum','label','Saldo tepat Rp1.000.000','Exactly IDR 1,000,000'],['bank','label','Rekening belum disetujui','Bank account not approved'],['closed','label','Di luar periode pengajuan','Outside request window'],['review','admin','Pemeriksaan pengajuan','Review requests'],['payments','super','Daftar pembayaran & salin ke bank','Payment list & bank copy actions'],['delayed','label','Pembayaran ditunda','Deferred payment'],['uncertain','super','Hasil transfer belum pasti','Uncertain transfer result'],['paid','label','Pembayaran selesai & saldo baru','Paid and new earnings'],['correction','super','Koreksi pencatatan pembayaran','Payment record correction'],['expired','label','Paket berakhir, royalti tetap tersedia','Expired plan, royalties still available']];
studioCatalog.unshift(...scenes108.map(([id,role,a,b])=>({id:'v108-'+id,role,version:'10.8',title:[a,b],description:['Skenario penarikan lintas akun. Data contoh; tanpa transfer bank nyata.','Cross-role withdrawal scenario. Sample data; no real bank transfers.']})));
const studioBase108=studioStart;studioStart=async function(id){if(!id.startsWith('v108-'))return studioBase108(id);const scene=scenes108.find(s=>'v108-'+s[0]===id);if(!scene)return;await studioBase108('v107-royalty');const r=model107();delete r.withdraw108;const m=RM10.getMember(ten,'awan'),other=ten.members.find(x=>x.id!=='awan');m.bank.approved={bank:'Bank Central Asia',number:'0001234500',holder:'Nara Pradana',version:1};m.identity.location={...(m.identity.location||{}),regency:'Kota Bandung'};m.onboardingSeen105=true;m.themeChosen106=true;ten.now=Date.parse('2026-09-10T09:00:00+07:00');const s=Withdraw108.init(r);s.accounts=ten.members.map(m=>({id:m.id,name:m.name,members:[m.id],master:false}));if(scene[0]==='master'){s.accounts=s.accounts.filter(a=>a.id!==other.id);Object.assign(s.accounts.find(a=>a.id==='awan'),{members:['awan',other.id],master:true});}
 // Keep example report earnings and available funds consistent.
 const b=r.batches[0];b.rows.filter(x=>x.member==='awan').forEach((x,i)=>x.amount=scene[0]==='minimum'?[600000,400000][i]:scene[0]==='master'?[300000,400000][i]:[1500000,1000000][i]);b.rows.filter(x=>x.member===other.id).forEach(x=>x.amount=scene[0]==='master'?800000:300000);r.ledger=[];r.receipts=[];b.posted=[];Royalty107.act(r,{role:'super'},'publish',{id:b.id,members:[...new Set(b.rows.map(x=>x.member))]});Royalty107.act(r,{role:'super'},'receive',{id:b.id,members:[...b.posted],reference:'DEMO-108',date:'2026-09-10',amount:b.rows.reduce((n,x)=>n+x.amount,0),checked:true,expectedVersion:r.version});
 if(['review','payments','delayed','uncertain','paid','correction'].includes(scene[0])){const ctx=context108(s.accounts.find(a=>a.id==='awan')),call=(action,p={})=>Withdraw108.act(r,{role:action==='request'?'label':'super',member:'awan',id:action==='request'?'awan':'jeck'},action,{version:s.version,...p},ctx);const wd=call('request',{account:'awan',amount:2500000,bankFingerprint:Withdraw108.fingerprint(ctx.bank)});if(scene[0]!=='review')call('approve',{id:wd});if(['uncertain','paid','correction'].includes(scene[0]))call('start',{id:wd});if(scene[0]==='delayed'){call('delay',{id:wd,reason:'service',message:'Pembayaran akan dilanjutkan setelah layanan bank tersedia.'});ten.now=Date.parse('2026-09-23T09:00:00+07:00')}
 if(scene[0]==='uncertain')call('delay',{id:wd,reason:'uncertain',message:'Kami sedang memastikan hasil transfer. Kamu tidak perlu mengajukan penarikan ulang.'});if(['paid','correction'].includes(scene[0])){call('paid',{id:wd});r.ledger.push({id:'new-funds108',ref:b.id,member:'awan',amount:300000,bucket:'available',kind:'received',at:new Date(ten.now).toISOString()});if(scene[0]==='correction')call('correction',{id:wd,note:'Konfirmasi pembayaran perlu diperiksa kembali.'})}}
 if(scene[0]==='bank')m.bank.approved=null;if(scene[0]==='closed')ten.now=Date.parse('2026-09-28T09:00:00+07:00');if(scene[0]==='expired')m.subscriptionEnd='2026-08-31T00:00:00Z';if(['payments','paid','uncertain','correction'].includes(scene[0]))ten.now=Date.parse('2026-09-17T09:00:00+07:00');studioAccount(scene[1],'awan');ui108.tab=scene[0]==='payments'?'payment':'all';ui108.q='';ui108.detail=['uncertain','correction','paid','delayed'].includes(scene[0])?s.requests[0].id:null;state.page='module';state.mode='platform';v4.module='withdraw';studioSelected=id;save10();closeModal();render();window.scrollTo(0,0)};
render();
