/* One attention-card component for every role. Static surfaces; actions stay intact. */
const attentionSelectors109='.attention9,.attention-shared102,.attention-card106,.decision7,.focus-banner,.ten-attention,.identity-pending-ui,.identity-correction-ui,.profile-status103';
const attentionIcon109=tone=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">${tone==='urgent'?'<path d="M10.3 4.7 2.7 18a2 2 0 0 0 1.7 3h15.2a2 2 0 0 0 1.7-3L13.7 4.7a2 2 0 0 0-3.4 0Z"/><path d="M12 9v5m0 3v.1"/>':'<circle cx="12" cy="12" r="9"/><path d="M12 8v5m0 3v.1"/>'}</svg>`;
function attentionTone109(el){if(el.matches('.red9,.red,.urgent8,.critical102')||el.querySelector('.red107'))return 'urgent';if(el.matches('.identity-pending-ui')||el.querySelector('[data-r107=report],[data-rm105=detail]')&&/dikembalikan|diperbarui|returned|updated/i.test(el.textContent)||el.matches('.blue,.blue9'))return 'info';return 'mustard'}
function normalizeAttention109(root=document){const nodes=[...root.querySelectorAll(attentionSelectors109)];for(const el of nodes){if(!el.isConnected||el.closest('.attention-shell109')||el.closest('.insight7'))continue;const tone=attentionTone109(el);const title=el.querySelector('h2,h3,strong,.ten-chip')||el.querySelector('h4');if(!title)continue;
 const details=[...el.querySelectorAll('.reveal9')];details.forEach(d=>d.remove());
 const description=[...el.querySelectorAll('p,.pending-context-ui,small')].find(n=>!n.closest('.action-row,.approval-row-ui,.row,form,.table-wrap'));
 const actions=[...el.querySelectorAll('button,a')].filter(b=>!b.closest('.info9,form,.action-row,.approval-row-ui,.row,.facts,.table-wrap'));
 el.querySelectorAll('.pulse,.status-dot9,.pending-icon-ui').forEach(n=>n.remove());
 const card=document.createElement('div');card.className='attention109';card.dataset.tone=tone;card.innerHTML=`<span class="attention-symbol109">${attentionIcon109(tone)}</span><div class="attention-copy109"></div><div class="attention-actions109"></div>`;
 const copy=card.querySelector('.attention-copy109');const head=document.createElement('h3');while(title.firstChild)head.append(title.firstChild);title.remove();copy.append(head);
 if(description&&description.isConnected){const desc=document.createElement('p');while(description.firstChild)desc.append(description.firstChild);description.remove();copy.append(desc)}
 const actionBox=card.querySelector('.attention-actions109');actions.forEach(b=>{b.classList.add('attention-action109');actionBox.append(b)});if(!actions.length)actionBox.remove();
 // Approval lists / expanded work retain their controls below the compact summary.
 const remaining=document.createElement('div');remaining.className='attention-details109';while(el.firstChild)remaining.append(el.firstChild);details.forEach(d=>remaining.append(d));
 const isDecision=el.classList.contains('decision7');
 el.className='attention-shell109';el.dataset.tone=tone;el.replaceChildren(card);if(remaining.textContent.trim()||remaining.querySelector('button,input,.reveal9'))el.append(remaining);
 if(isDecision&&remaining.querySelector('button')){const count=remaining.querySelectorAll('button').length;const desc=document.createElement('p');desc.textContent=T(`${count} pengajuan menunggu keputusanmu.`,`${count} request${count>1?'s':''} awaiting your decision.`);copy.append(desc);const box=document.createElement('div');box.className='attention-actions109';const toggle=document.createElement('button');toggle.className='attention-action109';toggle.textContent=T('Tinjau','Review');toggle.setAttribute('aria-expanded','false');remaining.hidden=true;toggle.addEventListener('click',()=>{remaining.hidden=!remaining.hidden;toggle.setAttribute('aria-expanded',String(!remaining.hidden));toggle.textContent=remaining.hidden?T('Tinjau','Review'):T('Tutup','Close')});box.append(toggle);card.append(box)}
 }
}
// Original gold face: dark engraved R, light rim, shaded body with a real side edge.
coin104=function(){return `<span class="coin104 coin106 coin109" aria-hidden="true"><span class="coin-spin106"><i class="coin-face106 front106">R</i>${Array.from({length:9},(_,i)=>`<i class="coin-layer106" style="--depth:${-2+i*.5}px"></i>`).join('')}<i class="coin-face106 back106">R</i></span></span>`};
function enhance109(){normalizeAttention109();document.title='Rilis Musik · V10.9';document.querySelectorAll('.version-pill,.floating107>strong').forEach(e=>e.textContent='V10.9');const footer=document.querySelector('.footer span');if(footer)footer.textContent='RILIS MUSIK · V10.9';document.querySelectorAll('.coin104:not(.coin109)').forEach(el=>el.outerHTML=coin104())}
const renderBefore109=render;render=function(){renderBefore109();enhance109()};
const dialogBefore109=reviewDialogUI;reviewDialogUI=function(...args){const result=dialogBefore109(...args);normalizeAttention109();return result};
let queued109=false;const observer109=new MutationObserver(records=>{if(queued109||!records.some(r=>[...r.addedNodes].some(n=>n.nodeType===1&&(n.matches?.(attentionSelectors109)||n.querySelector?.(attentionSelectors109)))))return;queued109=true;queueMicrotask(()=>{queued109=false;normalizeAttention109()})});observer109.observe(document.body,{childList:true,subtree:true});
const guideBefore109=standardsPage9;standardsPage9=function(){return guideBefore109()+`<section class="panel107 guide109"><span class="eyebrow107">V10.9 · SHARED UI</span><h2>${T('Kartu Atensi','Attention Cards')}</h2><p>${T('Atensi menampilkan kebutuhan tindakan yang konkret: apa yang terjadi, dampaknya, dan tindakan berikutnya. Wawasan memberi konteks perkembangan; tidak mengulang pesan atensi.','Attention cards show concrete action needs: what happened, its impact and the next action. Insights explain developments without repeating attention messages.')}</p><div class="legend109"><span><i class="mustard109"></i>${T('Mustard · perlu perhatian atau perbaikan','Mustard · attention or correction needed')}</span><span><i class="urgent109"></i>${T('Merah · terlambat atau menghambat','Red · overdue or blocking')}</span><span><i class="info109"></i>${T('Biru · informasi untuk ditindaklanjuti','Blue · information to follow up')}</span></div><p>${T('Ukuran dasar 76 px, judul 14 px, keterangan 12 px. Informasi dan tombol terlihat tanpa hover. Permukaan statis; hanya tombol memberikan respons interaksi.','76 px base height, 14 px title and 12 px description. Information and actions stay visible without hover. Static surfaces; only buttons respond to interaction.')}</p></section>`};
const scenes109=[['super','super','Atensi Super Admin · keputusan tertunda','Super Admin attention · pending decisions'],['admin','admin','Atensi Admin · revisi & tenggat','Admin attention · revisions & deadlines'],['label','label','Atensi Label · pembayaran tertunda','Label attention · deferred payment'],['identity','label','Perbaikan identitas · kartu compact','Identity correction · compact card'],['dark','label','Dark mode lebih gelap & koin R','Darker theme & R coin']];
studioCatalog.unshift(...scenes109.map(([id,role,a,b])=>({id:'v109-'+id,role,version:'10.9',title:[a,b],description:['Desain atensi seragam, mustard adaptif, dan koin emas 3D.','Shared compact attention, adaptive mustard, and a 3D gold coin.']})));
const studioBefore109=studioStart;studioStart=async function(id){if(!id.startsWith('v109-'))return studioBefore109(id);const sc=scenes109.find(s=>'v109-'+s[0]===id);if(!sc)return;if(sc[0]==='admin'){await studioBefore109('v105-revision');role102('admin');const r=ten.releases.find(r=>r.status==='revision');if(r){r.deadline=ten.now-3600000;r.urgent102=true}state.page='dashboard'}else if(sc[0]==='super'){await studioBefore109('v108-review');role102('super');state.page='overview';state.mode='staff'}else if(sc[0]==='identity'){await studioBefore109('profile-owner');role102('label','awan');member10().profileChange103={...(member10().profileChange103||{}),status:'correction',note:'Nama penanggung jawab perlu disesuaikan dengan dokumen identitas.'};ui103.profileTab='identity';route102('account')}else{await studioBefore109('v108-delayed');role102('label','awan');state.page='dashboard'}if(sc[0]==='dark')themeMode105('dark');studioSelected=id;save10();closeModal();render();window.scrollTo(0,0)};
render();

