/* Shared visual foundation: semantic status, two-position theme, right-hand details. */
function clockTheme111(){const h=new Date().getHours();return h>=6&&h<18?'light':'dark'}
themeMode105=function(mode){if(mode==='auto'){ten.themeMode105='auto';ten.themeManual111=false}else{ten.themeMode105=mode;ten.themeManual111=true}const next=mode==='auto'?clockTheme111():mode;const previous=document.documentElement.dataset.theme;state.theme=next;ten.theme=next;document.documentElement.dataset.theme=next;if(previous!==next){document.documentElement.classList.add('theme-changing111');clearTimeout(window.themeTimer111);window.themeTimer111=setTimeout(()=>document.documentElement.classList.remove('theme-changing111'),700)}save10();syncTheme111()};
const sun111='<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',moon111='<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>';
themeControl106=function(){return `<button type="button" class="theme111 ${state.theme==='dark'?'is-dark':''}" data-theme111 role="switch" aria-checked="${state.theme==='dark'}" aria-label="${T('Tema gelap','Dark theme')}" title="${T('Ganti tema terang / gelap','Switch light / dark theme')}"><span class="theme-track111"><span class="theme-thumb111"><svg viewBox="0 0 24 24" aria-hidden="true">${state.theme==='dark'?moon111:sun111}</svg></span></span></button>`};
function syncTheme111(){document.querySelectorAll('[data-theme111]').forEach(b=>{b.classList.toggle('is-dark',state.theme==='dark');b.setAttribute('aria-checked',String(state.theme==='dark'));b.querySelector('svg').innerHTML=state.theme==='dark'?moon111:sun111})}
themeDialog105=function(onboarding=false){if(!onboarding)return;reviewDialogUI(T('Pilih tampilanmu','Choose your appearance'),`<div class="theme-dialog105"><div class="theme-preview105"><i></i><span></span><span></span></div><h2>${T('Nyaman di setiap waktu.','Comfortable at any hour.')}</h2><div class="theme-choice111"><span>Light</span>${themeControl106()}<span>Dark</span></div><p>${T('Tampilan mengikuti waktu setempat sampai kamu memilih tema sendiri.','Appearance follows local time until you choose your own theme.')}</p><button class="btn primary" data-global105="theme-done">${T('Buka Dashboard','Open Dashboard')}</button></div>`)};
window.addEventListener('click',e=>{const b=e.target.closest('[data-theme111]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();themeMode105(state.theme==='dark'?'light':'dark');document.querySelectorAll('[data-theme111]').forEach(x=>{x.classList.remove('moving111');void x.offsetWidth;x.classList.add('moving111')});clearTimeout(window.thumbTimer111);window.thumbTimer111=setTimeout(()=>document.querySelectorAll('[data-theme111]').forEach(x=>x.classList.remove('moving111')),650);savePrefs()},true);
if(!ten.themeManual111)themeMode105('auto');else themeMode105(ten.themeMode105);
const statusWords111=/^(baru|new|prioritas|priority|lewat tenggat|overdue|lewat periode|pencairan terlambat|payout overdue|menunggu pemeriksaan|awaiting review|pemeriksaan berlangsung|sedang diperiksa|under review|perlu perbaikan|corrections needed|menunggu pembayaran|awaiting payment|selesai|completed|diproses|in progress|terkirim|delivered|menunggu wami|awaiting wami|persiapan pendaftaran|preparing registration|dikerjakan|revisi|menunggu tanggapan|dalam penyelesaian|perlu kelengkapan|ditutup|lewat estimasi)$/i;
function badgeTone111(text,el){if(/lewat|overdue|terlambat/i.test(text)||el.matches('.red,.red107,.urgent'))return 'red';if(/prioritas|priority|perbaikan|correction|kelengkapan|revisi|penyelesaian/i.test(text)||el.matches('.amber,.amber107'))return 'mustard';if(/selesai|completed/i.test(text)||el.matches('.green,.green107'))return 'green';if(/baru|new|ditutup/i.test(text))return 'neutral';return 'blue'}
function statusBadge111(label,tone){return `<span class="status111" data-tone="${tone||badgeTone111(label,{matches:()=>false})}">${E(label)}</span>`}
function normalizeStatus111(root=document){root.querySelectorAll('.work-badge104,.task-badge,.condition8,.badge,.pill107,.ten-chip').forEach(el=>{if(el.matches('.status111')||el.closest('.package104,.emblem-pending,.plan9')||!statusWords111.test(el.textContent.trim()))return;el.classList.add('status111');el.dataset.tone=badgeTone111(el.textContent.trim(),el)})}
function normalizeDrawers111(){document.querySelectorAll('dialog.release-drawer106,dialog.label-drawer104,dialog.drawer8').forEach(d=>{if(d.classList.contains('detail-panel111'))return;d.classList.add('detail-panel111');if(d.matches('.label-drawer104,.drawer8')){d.querySelector('.drawer-meta104')?.classList.add('facts-grid111');return;}const head=d.querySelector(':scope>header');if(head)head.classList.add('detail-header111');let body=d.querySelector(':scope>.drawerbody11,:scope>.drawerbody111');if(!body){body=document.createElement('div');body.className='drawerbody111';[...d.children].filter(n=>n!==head).forEach(n=>body.append(n));d.append(body)}body.classList.add('detail-body111');if(d.id==='release-drawer106'){const hero=document.createElement('section');hero.className='detail-identity111';const children=[...body.children],stop=children.findIndex(e=>e.matches('dl'));children.slice(0,stop<0?4:stop).forEach(e=>hero.append(e));body.prepend(hero)}body.querySelectorAll('.history107').forEach(e=>e.classList.add('timeline-row111'));body.querySelectorAll('.drawer-facts106,.drawer-meta104').forEach(e=>e.classList.add('facts-grid111'));})}
function enhance111(root=document){normalizeStatus111(root);normalizeDrawers111();syncTheme111();document.title='Rilis Musik · V11.1';document.querySelectorAll('.version-pill,.floating107>strong').forEach(e=>e.textContent='V11.1');const f=document.querySelector('.footer span');if(f)f.textContent='RILIS MUSIK · V11.1'}
let pending111=false;new MutationObserver(rs=>{if(pending111||!rs.some(r=>r.addedNodes.length))return;pending111=true;requestAnimationFrame(()=>{pending111=false;normalizeStatus111();normalizeDrawers111();})}).observe(document.body,{childList:true,subtree:true});
