const scenes114=[['invite','super','Staff · undangan baru'],['activation','admin','Staff · aktivasi dan ruang kerja'],['existing','super','Staff · email sudah terdaftar'],['operations','admin','Peran · akses operasional'],['scope','admin','Cakupan · label tertentu'],['shared','super','Peran · perubahan berdampak pada tim'],['revoked','admin','Akses dicabut · panel lama terbuka'],['handoff','super','Pekerjaan · pengalihan sesuai izin'],['emergency','super','Akun · penghentian akses mendesak'],['reactivate','super','Akun · aktifkan kembali dengan tinjauan'],['new-permissions','super','Pengembangan · izin baru ditinjau'],['conflict','super','Perubahan bersamaan · lindungi versi terbaru']];
studioCatalog.unshift(...scenes114.map(([id,role,title])=>({id:'v114-'+id,role,version:'11.4',title:[title,title],description:['Staff, akses dan pekerjaan terhubung. Akun mengikuti kondisi yang dipilih.','Connected staff, access and assignments. Account follows the scenario.']})));
const studioBefore114=studioStart;
async function fixture114(scene){fixtureMode114=true;ui114.preview=null;ui114.activation=null;close114();try{await studioBefore114('v113-list');document.querySelectorAll('dialog[open]').forEach(d=>d.close());role102('super');const originals=people.filter(p=>['jeck','eka','adovi','cantika'].includes(p.id));ten.staff114=Staff114.seed(originals,data.roles.filter(r=>r.id==='ops'),{adovi:'ops',cantika:'ops'},ten.now);const s=model114(),ops=Staff114.role(s,'ops');ops.description='Verifikasi rilisan, layanan, dan transaksi sesuai kewenangan.';ops.permissions=Staff114.normalize(Staff114.catalog.filter(p=>!p.id.startsWith('team.')).map(p=>p.id));
 const viewRole={id:'view114',name:'Pemantauan',description:'Melihat perkembangan tanpa menjalankan tindakan.',permissions:Staff114.catalog.filter(p=>p.id.endsWith('.view')).map(p=>p.id),version:1,archived:false};s.roles.push(viewRole);v8.connected=true;v8.time='10:00';v8.calendarMode='workday';ten.releases.slice(0,2).forEach(r=>{r.status='review';r.handler102='adovi';r.version=r.version||1});
 for(const o of s.users)o.version=1;hydrate114();ui114.q='';ui114.status='all';ui114.role='all';ui114.tab='staff';route114();
 let invited;if(['invite','activation'].includes(scene)){invited=atomic114('invite',{name:'Nadia Putri',email:'nadia@example.test',role:'ops',scope:'all',labels:[]}).id;if(scene==='activation')activation114(invited);else staffDetail114(invited)}
 if(scene==='existing'){inviteForm114();const f=document.querySelector('[data-form114=invite]');f.elements.name.value='Adovi';f.elements.email.value='adovi@example.test'}
 if(scene==='operations'){role102('admin');state.user='adovi';state.mode='platform';state.page='dashboard';render()}
 if(scene==='scope'){const u=user114('adovi');u.scope='selected';u.labels=['awan'];role102('admin','awan');state.user='adovi';module102('releases');render()}
 if(scene==='shared'){ui114.tab='roles';render();previewChange114({kind:'save-role',role:'ops',name:ops.name,description:ops.description,version:ops.version,permissions:ops.permissions.filter(p=>!p.startsWith('releases.')||p==='releases.view')})}
 if(scene==='revoked'){role102('admin');state.user='adovi';route113();detail113(ten.commerce113.orders.find(o=>o.kind==='credits').id);ops.permissions=ops.permissions.filter(p=>p!=='transactions.fulfill');ops.version++;user114('adovi').version++;user114('adovi').session++;hideActions114();toast('Skenario: izin Selesaikan pembelian dicabut saat panel masih terbuka.')}
 if(scene==='handoff'){disableForm114('adovi')}
 if(scene==='emergency'){atomic114('disable',{user:'adovi',version:1,note:'Simulasi penghentian akses mendesak.',emergency:true});render();handoffPanel114()}
 if(scene==='reactivate'){atomic114('disable',{user:'adovi',version:1,note:'Simulasi pergantian tugas.',emergency:true});render();accessForm114('adovi','reactivate')}
 if(scene==='new-permissions'){const id='labels.export';s.reviewed=s.reviewed.filter(p=>p!==id);for(const r of s.roles)r.permissions=r.permissions.filter(p=>p!==id);render()}
 if(scene==='conflict'){accessForm114('adovi');user114('adovi').version++;s.revision++;toast('Skenario: pengaturan terbaru disimpan oleh Super Admin lain.')}
 studioSelected='v114-'+scene;save10();
 }finally{fixtureMode114=false;document.title='Rilis Musik · V11.4';document.querySelectorAll('.floating107>strong').forEach(e=>e.textContent='V11.4')}
}
studioStart=async function(id){close114();if(id.startsWith('v114-'))return fixture114(id.slice(5));ui114.preview=null;ui114.activation=null;fixtureMode114=true;try{return await studioBefore114(id)}finally{fixtureMode114=false;hydrate114();render()}};
render();
