/* V11.6 audit correction — prepared for review; the published version remains V11.5. */
// Restore the staff identity before the first final render checks permissions.
if(ten.role!=='label'){const id=ten.staffUser116||state.user,u=user114(id);state.user=u&&!!u.super===(ten.role==='super')?id:ten.role==='super'?'jeck':'adovi';}
const errorBefore116=error10;
error10=function(code){return code==='storage_conflict'?T('Data berubah di tab lain. Isianmu belum disimpan. Tinjau pembaruan sebelum melanjutkan.','Data changed in another tab. Your entries have not been saved. Review the update before continuing.'):errorBefore116(code)};
const toastBefore116=toast;
toast=function(message){if(message==='storage_conflict'){window.storageConflict116=true;conflictBanner116();message=error10(message);}return toastBefore116(message)};
function conflictBanner116(){if(!window.storageConflict116||document.querySelector('.conflict116'))return;const el=document.createElement('aside');el.className='conflict116';el.setAttribute('role','alert');el.innerHTML=`<p>${T('Pembaruan tersedia dari tab lain. Isian yang sedang kamu kerjakan tetap terbuka.','An update is available from another tab. Your current entries remain open.')}</p><button class="btn small" type="button" data-review116>${T('Tinjau pembaruan','Review update')}</button>`;document.body.append(el);}
function conflictReview116(){const saved=JSON.parse(localStorage.getItem(V10KEY)||'null');const fields=[...document.querySelectorAll('form input,form textarea,form select')].filter(el=>el.name&&!['password','file','hidden'].includes(el.type)).map(el=>({name:el.closest('label')?.textContent.trim().slice(0,90)||el.name,value:el.type==='checkbox'?String(el.checked):el.value}));reviewDialogUI(T('Pembaruan dari tab lain','Update from another tab'),`<div class="form111"><h3>${T('Penyimpanan dihentikan untuk menjaga perubahan terbaru.','Saving stopped to protect the latest changes.')}</h3><p>${T('Revisi yang kamu buka','Your open revision')}: ${persistedRevision116} · ${T('Revisi tersimpan','Saved revision')}: ${saved?.storageRevision116||0}</p><p>${T('Salin isian yang masih kamu perlukan sebelum memuat ulang. Setelah itu, tinjau data terbaru dan lakukan perubahan kembali. Tidak ada perubahan yang digabungkan otomatis.','Copy any entries you still need before reloading. Then review the latest data and make your changes again. Changes are not merged automatically.')}</p><div class="recovery116">${fields.map(f=>`<article><strong>${E(f.name)}</strong><p>${E(f.value)}</p></article>`).join('')}</div><button class="btn primary" data-review-close116>${T('Kembali ke isian','Return to entries')}</button></div>`);}
document.addEventListener('click',e=>{if(e.target.closest('[data-review116]')){e.preventDefault();conflictReview116();}if(e.target.closest('[data-review-close116]'))closeModal();});
window.addEventListener('storage',e=>{if(e.key===V10KEY||e.key===null)conflictBanner116()});
const renderBefore116=render;
render=function(){renderBefore116();stampVersion116();document.title='Rilis Musik · V11.6';document.querySelectorAll('.version-pill,.floating107>strong').forEach(el=>el.textContent='V11.6');const foot=document.querySelector('.footer span');if(foot)foot.textContent='RILIS MUSIK · V11.6';const main=document.querySelector('#main');main?.classList.toggle('standards116',state.page==='standards9');document.querySelectorAll('#transaction-drawer113 [data-t113=close-drawer]').forEach(el=>el.setAttribute('aria-label',T('Tutup rincian transaksi','Close transaction details')));conflictBanner116();};
// Nested legacy operations now commit once, after all related effects succeed.
for(const name of ['atomic113','atomic114','atomic115']){const original=window[name];window[name]=function(...args){return atomic10(()=>original(...args))};}
function stampVersion116(){document.title='Rilis Musik · V11.6';document.querySelectorAll('.version-pill,.floating107>strong').forEach(el=>el.textContent='V11.6');const foot=document.querySelector('.footer span');if(foot)foot.textContent='RILIS MUSIK · V11.6';}
window.addEventListener('error',e=>{if(e.error?.code==='storage_conflict'){e.preventDefault();toast(e.error.message)}});
const studioBefore116=studioStart;
const scenes116=[
 ['v116-export-view','admin','Royalti dengan akses lihat','Royalty view access','Ekspor tersembunyi tanpa izin dan mengikuti cakupan label.','Export requires permission and follows label scope.'],
 ['v116-transaction-en','label','Transaksi dalam bahasa Inggris','Transactions in English','Telusuri rincian, panduan dan pemeriksaan pembayaran.','Explore details, guides, and payment review.'],
 ['v116-standards','super','Panduan indikator pada layar kecil','Indicator guide on small screens','Susunan panduan mengikuti lebar layar tanpa teks terpotong.','The guide adapts to screen width without clipping text.'],
 ['v116-catalogue-source','super','Sumber Paket & Kredit dari Sistem','Plans & Credits source from System','Tautan mengarah ke konfigurasi yang sama.','The link opens the existing shared configuration.']
];
studioCatalog.unshift(...scenes116.map(([id,role,a,b,c,d])=>({version:'11.6',id,role,title:[a,b],description:[c,d]})));
studioStart=async function(id){if(!id.startsWith('v116-')){const result=await studioBefore116(id);stampVersion116();return result;}if(id==='v116-export-view'){await studioBefore116('v107-details');role102('admin');state.user='adovi';user114().scope='selected';user114().labels=['awan'];Staff114.role(model114(),user114().role).permissions=Staff114.normalize(['royalty.view']);ui107.tab='details';royaltyRoute107('analytics');}else if(id==='v116-transaction-en'){await studioBefore116('v113-pending');document.querySelectorAll('dialog[open]').forEach(d=>d.close());role102('label','awan');ten.lang=state.lang='en';route113('transactions');}else if(id==='v116-standards'){await studioBefore116('standards');go('standards9','platform');}else{await studioBefore116('v115-content-draft');close115(true);route115('content');}studioSelected=id;save10();stampVersion116();};
render();
// V11.7 completes startup after persistence and legacy guards are installed.
