/* Shared typography, compact status indicators and semantic arrows for all roles. */
const arrowPath124={down:'M12 5v14 M6 13l6 6 6-6',up:'M12 19V5 M6 11l6-6 6 6',right:'M5 12h14 M13 6l6 6-6 6'};
const arrowSVG124=direction=>`<svg class="action-arrow124" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${arrowPath124[direction]||arrowPath124.right}"/></svg>`;
// Legacy helpers are immutable. Resolve their arrows after mounting using each
// control's real state rather than changing the shared legacy binding.
function expandedAttr124(button,value){const text=String(value);if(button.getAttribute('aria-expanded')!==text)button.setAttribute('aria-expanded',text)}
function arrowDirection124(button){const a=button.dataset.action;if(a==='v6-clear'){expandedAttr124(button,true);return 'up'}if(button.dataset.ten==='summary102'){const expanded=labelSummary102===Number(button.dataset.id);expandedAttr124(button,expanded);return expanded?'up':'down'}if(a==='v6-filter'){const expanded=v6.filter===button.dataset.id;expandedAttr124(button,expanded);return expanded?'up':'down'}if(a==='attention9'){expandedAttr124(button,!!v9.attention);return v9.attention?'up':'down'}if(button.hasAttribute('aria-expanded'))return button.getAttribute('aria-expanded')==='true'?'up':'down';return 'right'}
function arrowText124(button){const nodes=[],walk=document.createTreeWalker(button,NodeFilter.SHOW_TEXT),pattern=button.hasAttribute('aria-expanded')?/[↗↘→↑↓]/:/[↗↘→]/;for(let node;node=walk.nextNode();)if(!node.parentElement.closest('svg')&&pattern.test(node.nodeValue))nodes.push(node);return nodes}
function normalizeArrows124(root=document){root.querySelectorAll('button,a[role=button],a.btn').forEach(b=>{const expansion=['v6-filter','v6-clear','attention9','expand','master-expand9'].includes(b.dataset.action)||b.dataset.ten==='summary102',paths=[...b.querySelectorAll('svg path')],known=paths.find(p=>{const d=(p.getAttribute('d')||'').replace(/\s/g,'');return p.closest('.action-arrow124')||/^M618L186M76h11v11$/i.test(d)||/^M512h14M136l66-66$/i.test(d)||/^M95l77-77$/i.test(d)||(b.hasAttribute('aria-expanded')&&/^M66l1212M186L618$/i.test(d))})||(expansion?paths[0]:null),textNodes=arrowText124(b);if(!known&&!expansion&&!textNodes.length)return;const direction=arrowDirection124(b);b.dataset.arrow124=direction;if(known){const svg=known.closest('svg'),path=arrowPath124[direction];if(svg.innerHTML!==`<path d="${path}"></path>`)svg.innerHTML=`<path d="${path}"></path>`;svg.classList.add('action-arrow124');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.6');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true')}else if(textNodes.some(n=>n.parentNode!==b)){const symbol={down:'↓',up:'↑',right:'→'}[direction];textNodes.forEach(n=>n.nodeValue=n.nodeValue.replace(/[↗↘→↑↓]/g,symbol))}else if(expansion||textNodes.some(n=>/^[\s↗↘→]+$/.test(n.nodeValue))){textNodes.forEach(n=>n.nodeValue=n.nodeValue.replace(/[↗↘→]/g,''));b.insertAdjacentHTML('beforeend',arrowSVG124(direction))}else{textNodes.forEach(n=>n.nodeValue=n.nodeValue.replace(/[↗↘]/g,'→'))}if(expansion&&b.matches('.stat-open8,.attention-action109')){const title=b.closest('.stat6')?.querySelector(':scope>span')?.textContent||T('daftar','the list');b.setAttribute('aria-label',(direction==='up'?T('Tutup rincian','Collapse details'):T('Buka rincian','Expand details'))+' '+title)}})}

function normalizeType124(root=document){const targets=root.querySelectorAll('h1,h2,h3,h4,h5,h6,p,small,span,strong,b,label,button,a,th,td,dt,dd,legend,input,select,textarea,kbd,time,li,summary,figcaption');for(const el of targets){if(!el.isConnected||el.closest('svg,.coin104,.coin-face106,.coin-layer106'))continue;const style=getComputedStyle(el),weight=Number(style.fontWeight),value=weight<350?300:weight>=575?600:400;if(weight!==value)el.style.setProperty('font-weight',String(value),'important');const badge=el.closest('.status111,.work-badge104,.condition8,.task-badge'),size=parseFloat(style.fontSize);if(size<12&&!badge&&!el.closest('.avatar,.mark,.profile-photo103,.notification-count,.package104,.plan9'))el.style.setProperty('font-size','12px','important')}}
function normalizeBadges124(root=document){normalizeStatus111(root);root.querySelectorAll('.work-badge104,.condition8,.task-badge').forEach(b=>{if(b.classList.contains('status111'))return;b.classList.add('status111');b.dataset.tone=badgeTone111(b.textContent,b)})}
function enhanceUI124(root=document){normalizeBadges124(root);normalizeArrows124(root);normalizeType124(root);stamp124()}
let pendingUI124=false;new MutationObserver(records=>{if(pendingUI124||!records.some(r=>r.type==='childList'&&r.addedNodes.length||r.type==='attributes'))return;pendingUI124=true;requestAnimationFrame(()=>{pendingUI124=false;enhanceUI124()})}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded']});

// Preserve the established search contents; make its trigger a real toggle.
const searchBefore124=searchModal;searchModal=function(){if(document.querySelector('.search-popover')){closePop();return}searchBefore124();document.querySelector('[data-action=search]')?.setAttribute('aria-expanded','true')};
window.addEventListener('click',e=>{const b=e.target.closest('[data-action=search]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();searchModal();b.setAttribute('aria-expanded',String(!!document.querySelector('.search-popover')))},true);
const closePopBefore124=closePop;closePop=function(){closePopBefore124();document.querySelector('[data-action=search]')?.setAttribute('aria-expanded','false')};

const actionBefore124=handleAction;handleAction=async function(b){if(b.dataset.action==='v6-metric'&&b.dataset.id!=='withdraw'){const x=platformData6.find(x=>x[0]===b.dataset.id);if(!x||x[0]==='royalty'&&!(ten.role==='super'&&super114()))return;const pct=(x[3]-x[4])/x[4]*100,n=new Intl.NumberFormat(state.lang==='id'?'id-ID':'en-US',{maximumFractionDigits:1}).format(Math.abs(pct));modal(T(x[1],x[2]),`<p class="sub">${T(x[6],x[7])}</p><div class="row"><span>${T('Periode saat ini','Current period')}</span><strong>${x[5]?money(x[3]):fmt(x[3])}</strong></div><div class="row"><span>${T('Periode sebelumnya','Previous period')}</span><strong>${x[5]?money(x[4]):fmt(x[4])}</strong></div><p class="scope-note">${T(pct>=0?'Naik':'Turun',pct>=0?'Up':'Down')} ${n}%. ${T('Perbandingan dua periode · data simulasi.','Comparison of two periods · preview data.')}</p>`);return}return actionBefore124(b)};

const guideBefore124=standardsPage9;standardsPage9=function(){const box=document.createElement('div');box.innerHTML=guideBefore124();const old=box.querySelector('.guide109>p:last-child');if(old)old.textContent=T('Kartu ringkas dengan judul 15 px dan keterangan 13 px. Permukaan tetap; ikon merah memberi isyarat glow yang lembut.','Compact cards use 15 px headings and 13 px descriptions. Surfaces remain steady; red icons have a subtle glow.');const intro=document.createElement('section');intro.className='panel guide124';intro.innerHTML=`<h2>${T('Navigasi & tipografi','Navigation & typography')}</h2><p>${T('Aturan visual yang sama berlaku pada semua akun dan menu.','The same visual rules apply to all roles and menus.')}</p><div class="arrow-guide124"><span>${arrowSVG124('down')}${T('Buka rincian','Expand details')}</span><span>${arrowSVG124('up')}${T('Tutup rincian','Collapse details')}</span><span>${arrowSVG124('right')}${T('Pindah ke rincian atau menu','Go to details or another menu')}</span></div><p>${T('Light, Regular, Semi Bold. Judul bagian 20–22 px, isi 14–16 px, keterangan 12–13 px, indikator pekerjaan 11–12 px.','Light, Regular, Semi Bold. Section headings 20–22 px, body text 14–16 px, metadata 12–13 px, work indicators 11–12 px.')}</p>`;box.append(intro);return box.innerHTML};
render();
