/* V12.5 · glass with an actual backdrop; gestures respect the reading position. */
const mastheadArt125=`<svg class="masthead-art125" viewBox="0 0 1440 300" preserveAspectRatio="none" aria-hidden="true" focusable="false"><defs><linearGradient id="base125" x2="1" y2=".7"><stop stop-color="#06192b"/><stop offset=".58" stop-color="#0a3553"/><stop offset="1" stop-color="#075967"/></linearGradient><linearGradient id="fold125" x1=".7" y1="0" x2=".25" y2="1"><stop stop-color="#69b3de" stop-opacity=".18"/><stop offset=".3" stop-color="#1b729d" stop-opacity=".5"/><stop offset=".64" stop-color="#031b2e" stop-opacity=".75"/><stop offset="1" stop-color="#082536" stop-opacity="0"/></linearGradient><linearGradient id="sheen125" x1="0" y1="1" x2=".9" y2="0"><stop stop-color="#041522"/><stop offset=".44" stop-color="#168e9c" stop-opacity=".56"/><stop offset=".6" stop-color="#b5e5e4" stop-opacity=".26"/><stop offset=".64" stop-color="#051a2c"/><stop offset="1" stop-color="#0c5268"/></linearGradient><linearGradient id="edge125" x1="0" y1="1" x2="1" y2="0"><stop stop-color="#b8dcf8" stop-opacity="0"/><stop offset=".58" stop-color="#acd8ed" stop-opacity=".4"/><stop offset="1" stop-color="#98ebea" stop-opacity=".08"/></linearGradient></defs><rect width="1440" height="300" fill="url(#base125)"/><path d="M350 350 940-95 1170-95 660 350Z" fill="url(#fold125)"/><path d="M475 330 1010-80" fill="none" stroke="url(#edge125)" stroke-width="1.2"/><path d="M690 330C810 265 880 127 1030 73S1280 24 1460-80V300Z" fill="url(#sheen125)"/><path d="M845 350C883 257 990 218 1134 157S1325 105 1475 4V300Z" fill="url(#fold125)"/><path d="M870 340C926 236 1043 211 1157 154S1348 88 1460 15" fill="none" stroke="url(#edge125)" stroke-width="1.5"/><path d="M1125 340C1159 244 1290 180 1445 146" fill="none" stroke="#46c7ca" stroke-opacity=".12" stroke-width="80"/></svg>`;
function stamp125(){document.title='Rilis Musik · V12.5';document.documentElement.dataset.release='12.5';document.querySelectorAll('.version-pill,.floating107>strong').forEach(e=>{if(e.textContent!=='V12.5')e.textContent='V12.5'});const f=document.querySelector('.footer span');if(f&&f.textContent!=='RILIS MUSIK · V12.5')f.textContent='RILIS MUSIK · V12.5'}
function decorate125(root=document){const frame=root.querySelector('.masthead124.has-hero124');if(frame&&!frame.querySelector('.masthead-art125'))frame.insertAdjacentHTML('afterbegin',mastheadArt125);root.querySelectorAll('.metric124').forEach(b=>{const x=platformData6.find(x=>x[0]===b.dataset.id),trend=b.querySelector('.metric-foot124>span');if(!x||!trend)return;trend.classList.add('metric-trend125');trend.dataset.trend=x[3]>x[4]?'up':x[3]<x[4]?'down':'flat'});root.querySelectorAll('button').forEach(b=>{if(b.querySelector('.action-arrow124')&&!b.textContent.trim())b.classList.add('arrow-circle125')});stamp125()}
stamp124=stamp125;
const enhanceBefore125=enhanceUI124;enhanceUI124=function(root=document){enhanceBefore125(root);decorate125(root)};
const renderBefore125=render;render=function(){document.body.classList.add('release125');renderBefore125();decorate125()};

const gesture125={direction:0,at:0,touch:null};
function track125(direction){gesture125.direction=direction;gesture125.at=performance.now()}
function atTop125(){return(document.scrollingElement?.scrollTop||0)<=2}
function eligible125(target){return!!document.querySelector('.hero-clip124')&&!innerScroll124(target)}
// Stop the previous "open anywhere" gesture handler, but preserve native scrolling.
window.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)||!eligible125(e.target))return;track125(Math.sign(e.deltaY));if(e.deltaY<0&&!atTop125()){ui124.wheelTotal=0;e.stopImmediatePropagation()}},{capture:true,passive:false});
window.addEventListener('touchstart',e=>{gesture125.touch=e.touches.length===1&&eligible125(e.target)?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{capture:true,passive:true});
window.addEventListener('touchmove',e=>{const t=gesture125.touch;if(!t||e.touches.length!==1||!eligible125(e.target))return;const dx=t.x-e.touches[0].clientX,dy=t.y-e.touches[0].clientY;if(Math.abs(dy)<24||Math.abs(dx)>Math.abs(dy))return;track125(Math.sign(dy));if(dy<0&&!atTop125())e.stopImmediatePropagation()},{capture:true,passive:false});
window.addEventListener('touchend',()=>gesture125.touch=null,{capture:true,passive:true});
window.addEventListener('keydown',e=>{if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey||!eligible125(e.target))return;if(['PageUp','Home','ArrowUp'].includes(e.key)){track125(-1);if(e.key==='PageUp'&&!atTop125())e.stopImmediatePropagation()}else if(['PageDown','ArrowDown','End'].includes(e.key))track125(1)},{capture:true});
let scrollFrame125=0;window.addEventListener('scroll',()=>{if(scrollFrame125)return;scrollFrame125=requestAnimationFrame(()=>{scrollFrame125=0;if(gesture125.direction<0&&performance.now()-gesture125.at<1500&&atTop125()&&!ui124.expanded&&document.querySelector('.hero-clip124'))setHero124(true)})},{passive:true});

const scenes125=[['super','super','v124-super','Kaca, tombol bulat & indikator ringkas','Glass, circular controls & compact indicators'],['scroll','super','v124-super','Sapaan hanya kembali di bagian atas','Greeting returns only at the top'],['admin','admin','v124-admin','Tampilan seragam · Admin','Consistent appearance · Admin'],['label','label','v124-label','Tampilan seragam · Label','Consistent appearance · Label']];
studioCatalog.unshift(...scenes125.map(([id,role,,a,b])=>({id:'v125-'+id,role,version:'12.5',title:[a,b],description:['Persentase berwarna, pencarian dekat logo, dan indikator tanpa pulse.','Colored percentages, search beside the logo and status markers without pulse.']})));
const studioBefore125=studioStart;studioStart=async function(id){const s=scenes125.find(x=>'v125-'+x[0]===id);if(!s)return studioBefore125(id);await studioBefore125(s[2]);studioSelected=id;if(s[0]==='scroll'){setHero124(false);window.scrollTo({top:document.querySelector('.geography124')?.offsetTop||900,behavior:'instant'})}decorate125()};
const guideBefore125=standardsPage9;standardsPage9=function(){const box=document.createElement('div');box.innerHTML=guideBefore125();const attention=box.querySelector('.guide109>p:last-child');if(attention)attention.textContent=T('Kartu atensi ringkas tanpa garis tebal atau pulse. Tombol panah bulat menyesuaikan arah buka, tutup, atau navigasi.','Compact attention cards without thick borders or pulse. Circular arrow buttons reflect expansion, collapse or navigation.');const p=box.querySelector('.guide124>p:last-child');if(p)p.textContent=T('Light, Regular, Semi Bold. Indikator pekerjaan berupa penanda 18 px dengan teks 10,5 px dan titik solid, tanpa pulse. Tombol panah bulat mengikuti arah buka, tutup, dan navigasi.','Light, Regular, Semi Bold. Work indicators are 18 px markers with 10.5 px text and solid dots, without pulse. Circular arrows reflect expansion, collapse and navigation.');return box.innerHTML};
render();
