'use strict';
const v4={group:null,module:null};
// Module descriptions are a read-only map of the repository, not live service actions.
const modules=[
['work','ops','Pusat Pekerjaan','Work Centre','Semua antrean dan riwayat tahapan dalam satu tempat.','All queues and stage history in one place.','Filter jenis pekerjaan, tahap, tanggal, dan penanganan terakhir. Telusuri bukti penyelesaian.','Filter work type, stage, date and last handler. Inspect completion evidence.','Ringkasan dan simulasi pekerjaan sudah tersedia di Dashboard.','Work summaries and simulations are available on the Dashboard.','release'],
['releases','ops','Rilisan','Releases','Dari pemeriksaan materi sampai finalisasi tayang.','From material review to go-live checks.','Periksa metadata dan berkas; minta revisi; setujui; lanjutkan pengiriman; isi UPC/ISRC; tinjau takedown.','Review metadata and files; request revisions; approve; deliver; add UPC/ISRC; review takedowns.','Tahapan dan In Progress terhubung ke catatan tindakan nyata, bukan sekadar membuka halaman.','Stages and In Progress reflect recorded actions, not page visits.','release'],
['labels','ops','Label & Akun','Labels & Accounts','Identitas label, akun, paket, dan ketentuan layanan.','Label identity, accounts, packages and service terms.','Cari label, lihat profil, kelola akun, paket, rate/fee, serta status label.','Find labels, inspect profiles, manage accounts, packages, rates/fees and status.','Perubahan sensitif mengikuti akses langsung atau alur approval yang diberikan.','Sensitive changes follow direct or approval-based permissions.','claim'],
['approvals','ops','Persetujuan Sensitif','Sensitive Approvals','Keputusan atas perubahan paket, rate/fee, dan blacklist.','Decisions on package, rate/fee and blacklist changes.','Bandingkan nilai awal dan usulan, baca alasan, lalu setujui atau tolak.','Compare existing and proposed values, review reasons, then approve or reject.','Permintaan belum selesai diprioritaskan saat hari berganti; tersedia juga di My Work.','Pending requests become priorities at the next date change; also available in My Work.','super'],
['kyc','ops','Verifikasi Akun','Account Verification','Pemeriksaan identitas dan dokumen label.','Review label identity and documents.','Tinjau kelengkapan, catat alasan, dan putuskan hasil verifikasi.','Review completeness, record reasons and decide verification outcomes.','Keputusan Super Admin. Hari berikutnya menjadi pengingat, bukan 24 jam berjalan.','Super Admin decisions. Reminder at the next date, not after 24 elapsed hours.','super'],
['multi','ops','Multi Label','Multi Label','Permintaan penggabungan dan hubungan antarlabel.','Merge requests and label relationships.','Tinjau permintaan, validasi label sumber dan tujuan, lalu periksa hasil penggabungan.','Review requests, validate source and destination, then inspect merge results.','Validasi dan dampak perubahan perlu terlihat sebelum tindakan dilakukan.','Validation and impact must be visible before an action.','claim'],
['migrate','ops','Migrasi & Klaim','Migration & Claims','Menghubungkan akun baru dengan data label lama.','Connect new accounts with legacy label records.','Cocokkan bukti kepemilikan, telusuri data lama, terima atau tolak klaim.','Match ownership evidence, inspect legacy records, accept or reject claims.','Riwayat keputusan dan alasan penolakan harus dapat ditelusuri.','Decision history and rejection reasons must remain traceable.','claim'],
['contracts','ops','Kontrak Label','Label Contracts','Dokumen perjanjian kerja sama dengan label.','Agreements with labels.','Unggah dokumen, buat kontrak, perpanjang masa berlaku, atau akhiri dengan alasan.','Upload documents, create contracts, extend validity or terminate with reasons.','Kontrak kerja staf berada di Staff. Kedua jenis kontrak tetap terpisah.','Employment contracts belong in Staff. These contract types remain separate.','claim'],
['analytics','royalty','Analitik Royalti','Royalty Analytics','Membaca pendapatan dan pola pemakaian katalog.','Understand earnings and catalogue usage.','Pilih periode; telusuri pendapatan menurut label, artis, platform, dan wilayah.','Choose periods; explore earnings by label, artist, platform and territory.','Periode laporan harus jelas karena berbeda dari tanggal pembayaran.','Report periods must be clear and distinct from payment dates.','finance'],
['artists','royalty','Pendapatan Artis','Artist Earnings','Pendapatan artis dari laporan royalti.','Artist earnings from royalty reports.','Cari artis, pilih periode, bandingkan pendapatan, dan telusuri laporan terkait.','Find artists, select periods, compare earnings and inspect reports.','Nama diperjelas dari Manajemen Artis sesuai fokus halaman di repo.','Renamed from Artist Management to reflect the repository page.','finance'],
['imports','royalty','Laporan & Impor','Reports & Imports','Memasukkan dan memeriksa laporan royalti.','Import and inspect royalty reports.','Unggah laporan, periksa proses dan hasil, tinjau kesalahan, lalu publikasikan sesuai kewenangan.','Upload reports, inspect processing and results, review errors and publish with permission.','Perbaikan data dan tindakan pemeliharaan akan ditempatkan di opsi lanjutan.','Data repair and maintenance actions will be placed in advanced options.','finance'],
['withdraw','royalty','Penarikan','Withdrawals','Permintaan pencairan royalti dan bukti pembayaran.','Royalty payout requests and payment evidence.','Tinjau nominal dan rekening, setujui atau tolak, lalu catat pembayaran dan buktinya.','Review amounts and bank details, approve or reject, then record payment evidence.','Jendela pencairan tanggal 15–20. Persetujuan dan pembayaran adalah tahap berbeda.','Payout window: the 15th–20th. Approval and payment are separate stages.','finance'],
['banks','royalty','Verifikasi Rekening','Bank Verification','Memastikan rekening tujuan sebelum pencairan.','Check destination accounts before payouts.','Periksa pemilik dan detail rekening; catat hasil verifikasi.','Review account ownership and details; record verification outcomes.','Antrean ini harus tetap terlihat bagi Super Admin meski bukan menu bawaan sidebar.','This queue remains reachable by Super Admin even outside the default sidebar.','super'],
['balances','royalty','Penyesuaian Saldo','Balance Adjustments','Koreksi saldo label dengan alasan yang dapat ditelusuri.','Correct label balances with traceable reasons.','Pilih label, tinjau saldo dan perubahan yang diusulkan, kemudian lihat riwayat koreksi.','Select a label, review balance and proposed changes, inspect correction history.','Rancangan detail akan memperjelas validasi dan dampak sebelum perubahan.','Detailed design will clarify validation and impact before changes.','super'],
['audit','royalty','Audit Konsistensi','Consistency Audit','Mencari selisih antarhasil perhitungan royalti.','Find discrepancies across royalty calculations.','Bandingkan sumber dan ringkasan perhitungan, telusuri selisih hingga laporan asal.','Compare sources and calculated summaries, trace differences to source reports.','Audit tetap terpisah dari analitik sehari-hari agar alat pemeriksaan mudah dikenali.','Audit stays separate from everyday analytics.','super'],
['payments','payments','Transaksi','Transactions','Pembayaran layanan yang masuk ke platform.','Service payments received by the platform.','Cari transaksi, periksa invoice, detail, dan status pembayaran.','Find transactions and inspect invoices, details and payment status.','Pendapatan layanan berbeda dari royalti milik label.','Service revenue is distinct from label royalties.','finance'],
['refunds','payments','Refund','Refunds','Penanganan dan pencatatan pengembalian pembayaran.','Handle and record payment refunds.','Tinjau kasus dan alasan; catat refund yang sudah dilakukan beserta keterangannya.','Review cases and reasons; record completed refunds with notes.','Pencatatan refund tidak boleh disamakan dengan transfer uang otomatis.','Recording a refund is not an automatic money transfer.','finance'],
['recon','payments','Rekonsiliasi Xendit','Xendit Reconciliation','Mencocokkan catatan transaksi dengan penyedia pembayaran.','Match transactions with payment-provider records.','Pilih tanggal, bandingkan total, dan telusuri ketidaksesuaian.','Select dates, compare totals and investigate differences.','Selisih perlu dijelaskan sebelum mengambil tindakan koreksi.','Differences need explanation before corrective action.','finance'],
['addons','services','Layanan Tambahan','Add-on Services','Pesanan, hasil layanan, dan katalog produk tambahan.','Orders, deliverables and the add-on catalogue.','Kelola status pesanan, lampirkan hasil atau tautan, serta atur katalog layanan.','Manage order status, attach deliverables or links and manage the catalogue.','Pesanan dan katalog akan dipisahkan sebagai tab dalam satu area.','Orders and catalogue will be tabs in one area.','release'],
['wami','services','Registrasi WAMI','WAMI Registration','Pengajuan registrasi dan tindak lanjut hasilnya.','Registration requests and outcome follow-up.','Periksa pengajuan, perbarui tahap, dan telusuri hasil serta data migrasi.','Review submissions, update stages and inspect outcomes and migrated data.','Waktu tunggu pihak luar dicatat terpisah dari penanganan internal.','External waiting is recorded separately from internal handling.','release'],
['tickets','services','Tiket Bantuan','Support Tickets','Kasus dukungan yang membutuhkan penyelesaian tercatat.','Support cases requiring traceable resolution.','Baca laporan, balas dengan lampiran, ubah status, dan catat tindak lanjut.','Read reports, reply with attachments, change status and record follow-up.','Chat untuk percakapan; tiket menjaga konteks, riwayat, dan penyelesaian kasus.','Chat supports conversation; tickets preserve case history and resolution.','support'],
['cms','system','Konten Website','Website Content','Konten halaman publik Rilis Musik.','Content on the public Rilis Musik website.','Tinjau dan ubah konten landing page melalui area pengelolaan.','Review and edit landing-page content in its management area.','Prototype ini hanya menjelaskan cakupan; tidak menerbitkan perubahan website.','This prototype describes scope only; it does not publish website changes.','super'],
['appearance','system','Tampilan & Navigasi','Appearance & Navigation','Nama, kelompok, urutan menu, dan preferensi suara.','Menu names, groups, order and sound preferences.','Atur susunan menu dan visibilitas; kelola preferensi tampilan serta suara.','Arrange menus and visibility; manage appearance and sound preferences.','Pengaturan menu tidak memberikan izin akses baru kepada pengguna.','Menu configuration does not grant new user permissions.','super'],
['auditlog','system','Log Aktivitas','Activity Log','Riwayat tindakan lintas platform untuk penelusuran.','Cross-platform action history for investigation.','Filter pelaku, waktu, objek, dan jenis tindakan; buka konteks perubahan.','Filter actor, time, object and action; inspect change context.','Aktivitas menjelaskan apa yang terjadi; notifikasi menandai hal yang perlu diketahui.','Activity explains what happened; notifications flag what needs attention.','super']
].map(([id,group,idTitle,enTitle,idDesc,enDesc,idActions,enActions,idNote,enNote,access])=>({id,group,title:[idTitle,enTitle],desc:[idDesc,enDesc],actions:[idActions,enActions],note:[idNote,enNote],access}));
const groupNames={ops:['Operasional','Operations'],royalty:['Royalti','Royalties'],payments:['Pembayaran','Payments'],services:['Layanan','Services'],system:['Sistem','System']};
let allowedModule=m=>me().super||(m.access!=='super'&&permission(m.access)!=='none');
const oldV4={render,nav,pages,handleAction,go};
pages=function(){return {...oldV4.pages(),module:v4.module?L(modules.find(m=>m.id===v4.module)?.title||['Modul','Module']):'Modul'};};
nav=function(){return [...oldV4.nav(),...(state.page==='module'?[['module','grid']]:[])];};
function modulePage(){const m=modules.find(x=>x.id===v4.module&&allowedModule(x));if(!m)return empty(t('Menu tidak tersedia','Menu unavailable'));return `<div class="module-intro"><div class="eyebrow">${L(groupNames[m.group])} / ${t('Rancangan modul','Module outline')}</div>${pageHead(L(m.title),L(m.desc))}<div class="module-status"><span></span>${t('Struktur siap · antarmuka detail belum dirancang','Structure ready · detailed interface not designed yet')}</div></div><section class="module-content"><div><h2>${t('Yang bisa dilakukan di sini','What happens here')}</h2><p>${L(m.actions)}</p><h2>${t('Bagaimana menu ini bekerja','How this fits your work')}</h2><p>${L(m.note)}</p><div class="module-boundary">${t('Ini adalah penjelasan fungsi berdasarkan repo, bukan halaman transaksi aktif. Kita akan merancang daftar, filter, detail, dan tindakan modul ini pada tahap berikutnya.','This repository-based outline is not an active transaction page. Lists, filters, details and actions will be designed in the next phase.')}</div>${btn(t('Kembali ke Dashboard','Back to Dashboard'),'v4-home','','primary')}</div><aside><span class="eyebrow">${t('DALAM AREA INI','IN THIS AREA')}</span>${modules.filter(x=>x.group===m.group&&x.id!==m.id&&allowedModule(x)).map(x=>`<button data-action="v4-module" data-id="${x.id}">${L(x.title)} ${icon('arrow')}</button>`).join('')}</aside></section>`;}
function groupPanel(){if(!v4.group)return '';const items=modules.filter(m=>m.group===v4.group&&allowedModule(m));return `<div class="mega" id="mega"><div class="mega-inner"><div class="mega-heading"><span class="eyebrow">${L(groupNames[v4.group])}</span><p>${t('Pilih urusan yang ingin kamu telusuri.','Choose an area to explore.')}</p></div><div class="mega-links">${items.map(m=>`<button data-action="v4-module" data-id="${m.id}"><strong>${L(m.title)}</strong><small>${L(m.desc)}</small></button>`).join('')}${v4.group==='ops'&&me().super?`<button data-action="nav" data-page="workrules"><strong>${t('Aturan Pekerjaan','Work Rules')}</strong><small>${t('Tenggat, prioritas, dan dasar perhitungan waktu.','Deadlines, priorities and timing rules.')}</small></button>`:''}</div><button class="mega-close" data-action="v4-close" aria-label="${t('Tutup submenu','Close submenu')}">×</button></div></div>`;}
render=function(){oldV4.render();const header=$('.header'),mode=$('.mode-switch'),brand=$('.brand'),tools=$('.tools');const currentModule=modules.find(x=>x.id===v4.module);const mainNav=state.mode==='platform'?`<button data-action="v4-home" class="${state.page==='dashboard'?'active':''}">Dashboard</button>${Object.keys(groupNames).filter(g=>g!=='system'&&modules.some(m=>m.group===g&&allowedModule(m))).map(g=>`<button data-action="v4-group" data-id="${g}" aria-expanded="${v4.group===g}" aria-controls="mega" class="${v4.group===g||(state.page==='module'&&currentModule?.group===g)?'active':''}">${L(groupNames[g])}<span>⌄</span></button>`).join('')}`:oldV4.nav().filter(([p])=>p!=='logs').map(([p])=>`<button data-action="nav" data-page="${p}" class="${state.page===p?'active':''}">${pages()[p]}</button>`).join('');header.innerHTML=`<div class="header-top"><div class="header-identity">${brand.outerHTML}${mode.outerHTML}</div>${tools.outerHTML}</div><div class="header-bottom"><nav class="top-nav" aria-label="${t('Navigasi utama','Main navigation')}">${mainNav}</nav><div class="header-context">${state.mode==='staff'?`<span>${t('Halo','Hello')}, ${esc(me().name.split(' ')[0])}</span>`:''}${me().super?`<button data-action="v4-group" data-id="system" aria-expanded="${v4.group==='system'}">${icon('settings')}<span>${L(groupNames.system)}</span></button>`:''}</div></div>${groupPanel()}`;$('.sidebar').remove();$('.scrim').remove();$('.version-pill').textContent='V4';$('.footer span').textContent='RILIS MUSIK · V4 / '+t('Konsep interaktif','Interactive concept');document.title='Rilis Musik · V4';};
go=function(page,mode){v4.group=null;return oldV4.go(page,mode);};
handleAction=async function(b){const a=b.dataset.action;if(a==='v4-group'){v4.group=v4.group===b.dataset.id?null:b.dataset.id;render();$(`[data-action="v4-group"][data-id="${b.dataset.id}"]`)?.focus();return;}if(a==='v4-close'){v4.group=null;render();return;}if(a==='v4-home'){return go('dashboard','platform');}if(a==='v4-module'){const m=modules.find(x=>x.id===b.dataset.id&&allowedModule(x));if(!m)return;v4.module=m.id;return go('module','platform');}if(['mode','nav','search-nav','exit-preview'].includes(a))v4.group=null;return oldV4.handleAction(b);};
guide=function(){modal(t('Selamat datang di V4.','Welcome to V4.'),`<p class="reflection">${t('Ruang yang lebih tenang. Navigasi yang lebih jelas.','A calmer workspace. Clearer navigation.')}</p><ol class="guide-list"><li>${t('Jelajahi menu header. Modul lanjutan memiliki penjelasan fungsi dan rencana tindakan.','Explore the header. Future modules include purpose and action outlines.')}</li><li>${t('Masuk Staff untuk mencoba kehadiran, kinerja, kompensasi, dan pratinjau role.','Enter Staff to try attendance, performance, compensation and role preview.')}</li><li>${t('Ganti akun dan skenario melalui Studio pratinjau. Semua data adalah simulasi lokal.','Change accounts and scenarios in Preview Studio. All data is locally simulated.')}</li></ol>${btn(t('Mulai menjelajah','Start exploring'),'close','','primary')}`);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&v4.group){v4.group=null;render();}});
document.addEventListener('click',e=>{if(v4.group&&!e.target.closest('.header')){v4.group=null;render();}});
// Initial render: V5.