'use strict';
// Local preview model. No production identity, payment or verification service is implied.
const v9={work:'all',labelFilter:'all',labelSearch:'',months:6,volume:5,photo:null,attStatus:'all',attPerson:'all',week:0,help:null};
const iso9=d=>d.toISOString().slice(0,10);
function shifted9(s,months){const d=new Date(s+'T12:00Z'),date=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(date,last));return iso9(d);}
function old9(s,months,asof=day()){return !!s&&shifted9(s,months)<=asof;}
function seedLabels9(){
 const defs=[['L01','Awan Records','Pro','2023-02-10','2026-09-17',18,8,60000000],['L02','Ruang Nada','Go','2024-01-08','2026-09-12',16,7,115000000],['L03','Sora Music','Flex','2026-08-01','2026-09-16',2,1,0],['L04','Pijar Records','Pro','2024-04-03','2026-04-01',10,4,9000000],['L05','Arsip Senja','Go','2021-01-01','2025-08-01',18,8,510000000],['L06','Nusa Sound','Business','2022-01-01','2026-09-18',0,0,0],['L07','Lintang Records','Go','2024-01-01','2026-09-03',20,9,30000000],['L08','Embun Label','Flex','2026-09-01',null,0,0,0]];
 const labels=defs.map(([id,name,plan,joined,last,count,months,paid],i)=>({id,name,plan,joined,last,paid,credit:paid+[12000000,8000000,0,2500000,18500000,0,3400000,0][i],adjustment:0,processing:i===0?2000000:0,held:i===4?18500000:0,periodIncome:[2800000,1700000,0,400000,920000,0,800000,0][i],report:'2026-08',expiry:i===5?'2026-09-17':'2027-03-01',complete:i!==2&&i!==7,contact:i!==2&&i!==7,issue:i===6,restriction:i===4?'blocked':i===6?'limited':null,suspended:i===4?'2026-08-01':null,earned:['L01','L02','L05','L06'].includes(id),review:i===6,master:i===5,managedSince:i===5?'2024-04-01':null,children:i===5?[{id:'L01',since:'2024-04-01'},{id:'L02',since:'2024-05-01'},{id:'L03',since:'2026-09-16'}]:[],releases:Array.from({length:count},(_,n)=>({id:id+'-R'+n,date:shifted9('2026-09-01',-(n%Math.max(months,1))),valid:true})),lastPayment:paid?'2026-08-20':null,emblemVersion:1}));
 return {labels,standards:{version:1,labelMonths:12,releases:12,activeMonths:6,masterMonths:12,managedMonths:6,masterCount:2,masterPercent:80,emblems:[50000000,100000000,500000000]},versions:[],audit:[],asof:day()};
}
if(!data.v9)data.v9=seedLabels9();
function activity9(l,asof=day()){const last=l.last||l.joined;if(shifted9(last,12)<asof||l.ceased)return 'nonoperational';if(!l.last)return 'new';return (new Date(asof+'T12:00Z')-new Date(l.last+'T12:00Z'))/86400000>90?'dormant':'active';}
function reasons9(l){return [...(l.expiry<day()&&l.plan!=='Flex'?['package']:[]),...(l.restriction?[l.restriction]:[])];}
function accessLabel9(l){return l.restriction==='blocked'?'blocked':reasons9(l).length?'limited':'normal';}
function labelChecks9(l){const s=data.v9.standards,start=shifted9(day(),-12),releases=[...new Map(l.releases.filter(r=>r.valid&&r.date>=start&&r.date<=day()).map(r=>[r.id,r])).values()],months=new Set(releases.map(r=>r.date.slice(0,7))).size;return [{key:'age',ok:old9(l.joined,s.labelMonths),text:t(`Bergabung minimal ${s.labelMonths} bulan`,`Member for at least ${s.labelMonths} months`)},{key:'releases',ok:releases.length>=s.releases,text:t(`${releases.length}/${s.releases} rilisan berbeda dalam 12 bulan`,`${releases.length}/${s.releases} distinct releases in 12 months`)},{key:'consistency',ok:months>=s.activeMonths,text:t(`Rilis pada ${months}/${s.activeMonths} bulan berbeda`,`Releases across ${months}/${s.activeMonths} different months`)},{key:'data',ok:l.complete&&l.contact,text:t('Data label dan kontak terkonfirmasi','Label information and contact confirmed')},{key:'safety',ok:!l.issue&&!l.restriction&&(!l.suspended||old9(l.suspended,6)),text:t('Tanpa masalah berat terbukti atau pembatasan pelanggaran; enam bulan tanpa penangguhan','No confirmed serious issue or violation restriction; six months without suspension')}];}
function verification9(l){if(l.master)return masterVerification9(l);const checks=labelChecks9(l),problem=l.issue||l.restriction||!l.complete||!l.contact;return {status:l.earned?(problem?'review':'verified'):checks.every(x=>x.ok)?'verified':l.review?'review':'unverified',checks};}
function masterVerification9(l){const s=data.v9.standards,children=l.children.map(c=>({...c,label:data.v9.labels.find(x=>x.id===c.id)})).filter(c=>c.label),eligible=children.filter(c=>old9(c.since,s.managedMonths)),verified=eligible.filter(c=>verification9(c.label).status==='verified').length,need=Math.max(s.masterCount,Math.ceil(eligible.length*s.masterPercent/100)),unsafe=l.issue||l.restriction||children.some(c=>c.label.issue||c.label.restriction),checks=[{ok:old9(l.joined,s.masterMonths),text:t(`Akun master minimal ${s.masterMonths} bulan`,`Master account at least ${s.masterMonths} months`)},{ok:old9(l.managedSince,s.managedMonths),text:t(`Riwayat pengelolaan minimal ${s.managedMonths} bulan`,`Management history at least ${s.managedMonths} months`)},{ok:eligible.length>=s.masterCount,text:t(`${eligible.length} label sudah dikelola minimal ${s.managedMonths} bulan`,`${eligible.length} labels managed for at least ${s.managedMonths} months`)},{ok:verified>=need,text:t(`${verified}/${need} label terverifikasi yang diperlukan (${s.masterPercent}%)`,`${verified}/${need} verified labels required (${s.masterPercent}%)`)},{ok:l.complete&&l.contact&&children.every(c=>c.label.complete&&c.label.contact),text:t('Data dan hubungan semua label terkonfirmasi','All label information and management relationships confirmed')},{ok:!unsafe&&(!l.suspended||old9(l.suspended,6)),text:t('Tidak ada masalah berat terbukti; enam bulan tanpa penangguhan master','No confirmed serious issues; master has no suspension in six months')}];return {status:l.earned?(unsafe?'review':'verified'):checks.every(c=>c.ok)?'verified':'unverified',checks,newReview:children.some(c=>!old9(c.since,s.managedMonths)||!c.label.complete)};}
function emblem9(l){if(l.master)return '';const thresholds=data.v9.versions.find(v=>v.version===l.emblemVersion)?.standards.emblems||[50000000,100000000,500000000];return l.paid>=thresholds[2]?'Platinum':l.paid>=thresholds[1]?'Gold':l.paid>=thresholds[0]?'Silver':'';}
function ledger9(l){const balance=l.credit+l.adjustment-l.paid;return {balance,available:balance-l.processing-l.held,processing:l.processing,held:l.held};}
function liabilityTotals9(asof=day()){return data.v9.labels.filter(l=>!l.master).reduce((a,l)=>{const b=ledger9(l).balance,key=activity9(l,asof)==='nonoperational'?'nonoperational':'operational';a[key]+=b;a.total+=b;return a;},{operational:0,nonoperational:0,total:0});}
const indicatorDefs9=[['work.new','Baru','New','Pekerjaan diterima dan belum ditangani.','Received and not yet handled.'],['work.priority','Prioritas','Priority','Perlu didahulukan sesuai tenggat dan kebutuhan penanganan.','Needs earlier handling according to its deadline and context.'],['work.overdue','Lewat tenggat','Past deadline','Tenggat tahap saat ini sudah lewat; hilang setelah tahap diselesaikan.','Current stage deadline has passed; cleared when the stage completes.'],['work.followup','Perlu tindak lanjut','Follow-up','Waktu menunggu telah melewati pengingat; periksa jawaban pihak terkait.','Waiting has passed its reminder; check the other party’s response.'],['access.normal','Normal','Normal','Tindakan tersedia sesuai paket dan kewenangan.','Actions are available within package and permission limits.'],['access.limited','Dibatasi','Limited','Sebagian tindakan dibatasi oleh paket berakhir atau keputusan Rilis Musik.','Some actions are restricted by an expired plan or a Rilis Musik decision.'],['access.blocked','Ditangguhkan','Suspended','Pembatasan karena keputusan Rilis Musik; pencatatan royalti tetap berlangsung.','Restricted by a Rilis Musik decision; royalty accounting continues.'],['activity.active','Aktif','Active','Ada kegiatan pekerjaan dalam 90 hari terakhir.','Qualifying work activity in the last 90 days.'],['activity.new','Belum aktif','Not yet active','Belum ada kegiatan pekerjaan yang memenuhi syarat.','No qualifying work activity yet.'],['activity.dormant','Lama tidak beraktivitas','Inactive for a while','Lebih dari 90 hari sampai satu tahun tanpa kegiatan pekerjaan.','More than 90 days and up to one year without work activity.'],['activity.nonoperational','Nonoperasional','Nonoperational','Lebih dari satu tahun tanpa kegiatan, atau berhenti beroperasi terkonfirmasi.','More than one year without work activity, or confirmed cessation.']];
function labelStatus9(group,key){const def=indicatorDefs9.find(x=>x[0]===group+'.'+key);return def?t(def[1],def[2]):key;}
