(function(root){'use strict';
const H=3600000,D=24*H,copy=x=>JSON.parse(JSON.stringify(x)),check=(v,m)=>{if(!v)throw Error(m)};
const defaults={queueWarn:2,queueDue:4,workWarn:2,workDue:4,labelWarn:4,labelSecond:24,labelDue:48,externalDays:2};
const init=s=>s.wami11??={orders:[],serial:0,version:1,policy:copy(defaults),policyHistory:[],notifications:[]};
function businessHours(from,to,cal){if(to<=from)return 0;const days=cal?.days||[1,2,3,4,5],start=cal?.start||'08:00',end=cal?.end||'17:00',holidays=cal?.holidays||[];let local=new Date(from+7*H);local.setUTCHours(0,0,0,0);let total=0;for(let n=0;n<3660&&local.getTime()-7*H<to;n++,local.setUTCDate(local.getUTCDate()+1)){const date=local.toISOString().slice(0,10);if(!days.includes(local.getUTCDay())||holidays.includes(date))continue;const a=Date.parse(date+'T'+start+':00+07:00'),b=Date.parse(date+'T'+end+':00+07:00');total+=Math.max(0,Math.min(to,b)-Math.max(from,a));}return total/H}
function addBusinessDays(at,n,cal){let x=at;for(let count=0,guard=0;count<n&&guard<3660;guard++){x+=D;const d=new Date(x+7*H);if((cal?.days||[1,2,3,4,5]).includes(d.getUTCDay())&&!(cal?.holidays||[]).includes(d.toISOString().slice(0,10)))count++;}return x}
function attention(s,o,cal){const now=s.now,p=o.timing,stage=o.status;let elapsed,limits;if(stage==='queued'){elapsed=businessHours(o.progress,now,cal);limits=[p.queueWarn,p.queueDue]}else if(stage==='review'||stage==='preparing'||stage==='correction'&&o.target==='staff'){elapsed=businessHours(o.progress,now,cal);limits=[p.workWarn,p.workDue]}else if(stage==='correction'){elapsed=(now-o.progress)/H;limits=[p.labelWarn,p.labelSecond,p.labelDue]}else if(stage==='waiting'){return now>=o.nextFollowup?{level:1,key:'external',text:'Tindak lanjuti WAMI'}:null}else return null;const level=limits.filter(n=>elapsed>=n).length;if(!level)return null;return {level,key:stage+(o.target||''),text:stage==='correction'&&o.target==='label'?(level===3?'Perbaikan tertunda':'Menunggu perbaikan label'):stage==='queued'?(level===2?'Pengajuan belum ditangani':'Pengajuan menunggu pemeriksaan'):(level===2?'Tindak lanjut melewati batas':'Perlu perkembangan pekerjaan')};}
function tick(s,cal){const m=init(s);for(const o of m.orders){const a=attention(s,o,cal);if(!a)continue;const key=[o.id,o.cycle,a.key,a.level].join(':');if(m.notifications.some(n=>n.key===key))continue;m.notifications.unshift({key,order:o.id,member:o.member,account:o.account,cycle:o.cycle,status:o.status,level:a.level,text:a.text,at:s.now,label:o.status==='correction'&&o.target==='label'});}}
function event(s,o,action,a,p={}){o.events.push({action,at:s.now,actor:a.id,note:p.note||'',public:p.public!==false,reference:p.reference||'',snapshot:p.snapshot||null});}
function owned(a,o){return a.role==='label'&&a.member===o.account}
function act(s,a,action,p={},cal={}){const m=init(s);check(['label','admin','super'].includes(a.role),'Akses tidak tersedia.');
 if(action==='policy'){check(a.role==='super','Hanya Super Admin.');check(p.version===m.version,'Pengaturan berubah. Muat ulang.');for(const k of Object.keys(defaults))check(Number.isInteger(p.policy[k])&&p.policy[k]>0&&p.policy[k]<=720,'Batas waktu tidak valid.');check(p.policy.queueWarn<p.policy.queueDue&&p.policy.workWarn<p.policy.workDue&&p.policy.labelWarn<p.policy.labelSecond&&p.policy.labelSecond<p.policy.labelDue,'Urutan pengingat harus meningkat.');m.policy=copy(p.policy);m.policyHistory.unshift({at:s.now,actor:a.id,policy:copy(p.policy)});m.version++;return;}
 if(action==='create'){check(a.role==='label','Hanya label dapat mengajukan.');check(p.version===m.version,'Daftar berubah. Tinjau kembali pengajuan.');check(p.tracks?.length&&p.tracks.length<=100,'Pilih setidaknya satu lagu.');check(new Set(p.tracks.map(t=>t.key)).size===p.tracks.length,'Lagu dipilih dua kali.');for(const t of p.tracks){check(t.live&&a.scope.includes(t.member),'Lagu belum tayang atau di luar akunmu.');check(!t.registered&&!m.orders.some(o=>o.track===t.key),'Lagu sudah mempunyai catatan WAMI.');check(t.title?.trim()&&t.artist?.trim(),'Data lagu belum lengkap.');}check(Number.isSafeInteger(p.unit)&&p.unit>=0,'Biaya tidak valid.');const ids=[];for(const t of p.tracks){const o={id:'WAMI-'+String(++m.serial).padStart(4,'0'),account:a.member,member:t.member,track:t.key,release:t.release,title:t.title,artist:t.artist,releaseTitle:t.releaseTitle,cover:t.cover||'',isrc:t.isrc||'',composer:t.composer||'',lyricist:t.lyricist||'',performer:t.performer||t.artist,kind:t.kind||'vocal',status:p.unit===0?'queued':'unpaid',amount:p.unit,benefit:p.benefit||'',created:s.now,progress:s.now,version:1,cycle:1,handler:null,web:false,documents:false,timing:copy(m.policy),events:[],reference:'',message:'',internal:''};event(s,o,'submitted',a);m.orders.push(o);ids.push(o.id);}m.version++;return ids;}
 const o=m.orders.find(o=>o.id===p.id);check(o,'Pengajuan tidak ditemukan.');check(a.role!=='label'||owned(a,o),'Pengajuan di luar akunmu.');check(p.version===o.version,'Pengajuan berubah. Buka kembali rincian terbaru.');const staff=a.role!=='label';
 if(action==='pay'){check(owned(a,o)&&o.status==='unpaid','Pembayaran tidak tersedia.');o.status='queued';o.paid=s.now;}
 else if(action==='resubmit'){check(owned(a,o)&&o.status==='correction'&&o.target==='label','Perbaikan tidak tersedia.');for(const k of ['title','artist','composer','lyricist','performer','isrc'])check(typeof p[k]==='string'&&p[k].length<=500,'Data tidak valid.');check(p.title.trim()&&p.artist.trim(),'Lengkapi judul dan artis.');const before=Object.fromEntries(['title','artist','composer','lyricist','performer','isrc'].map(k=>[k,o[k]]));for(const k of Object.keys(before))o[k]=p[k].trim();p.snapshot={before,after:Object.fromEntries(Object.keys(before).map(k=>[k,o[k]]))};o.status='queued';o.handler=null;o.target=null;o.message='';o.web=false;o.documents=false;}
 else{check(staff,'Hanya petugas dapat melakukan tindakan ini.');if(action==='start'){check(o.status==='queued','Pengajuan tidak berada dalam antrean.');o.handler=a.id;o.status='review';}
 else{check(o.handler===a.id||a.role==='super','Pengajuan ditangani petugas lain.');
 if(action==='ready'){check(o.status==='review'&&p.checked,'Periksa kelengkapan data terlebih dahulu.');o.status='preparing';}
 else if(action==='web'||action==='documents'){check(o.status==='preparing'&&!o[action==='web'?'web':'documents']&&p.checked,'Langkah belum dapat dicatat.');o[action==='web'?'web':'documents']=s.now;if(o.web&&o.documents){o.status='waiting';o.nextFollowup=addBusinessDays(s.now,o.timing.externalDays,cal);}}
 else if(action==='correction'){check(['review','preparing','waiting'].includes(o.status),'Perbaikan tidak tersedia.');check(['label','staff'].includes(p.target)&&p.note?.trim(),'Tentukan penanggung jawab dan catatan perbaikan.');o.status='correction';o.target=p.target;o.message=p.target==='label'?p.note.trim():'Data pengajuan sedang diperbaiki petugas.';o.internal=p.target==='staff'?p.note.trim():'';p.public=p.target==='label';}
 else if(action==='staff-fixed'){check(o.status==='correction'&&o.target==='staff'&&p.note?.trim(),'Catat perbaikan yang dilakukan.');o.status='review';o.target=null;o.message='';o.internal='';o.web=false;o.documents=false;p.public=false;}
 else if(action==='accepted'){check(o.status==='waiting'&&p.checked&&p.note?.trim(),'Catat hasil penerimaan WAMI.');o.status='done';o.reference=p.reference?.trim()||'';o.completed=s.now;}
 else if(action==='followup'){check(o.status==='waiting'&&p.note?.trim(),'Catat hasil tindak lanjut.');check(Number.isFinite(p.next)&&p.next>s.now,'Pilih waktu tindak lanjut berikutnya.');o.nextFollowup=p.next;p.public=false;}
 else if(action==='obstacle'){check(['review','preparing','correction'].includes(o.status)&&p.note?.trim(),'Catat kendala pekerjaan.');o.internal=p.note.trim();p.public=false;}
 else if(action==='correct-log'){check(['preparing','waiting'].includes(o.status)&&['web','documents'].includes(p.step)&&o[p.step]&&p.note?.trim(),'Pilih catatan pengiriman yang perlu dikoreksi.');p.snapshot={step:p.step,previous:o[p.step]};o[p.step]=false;o.status='preparing';o.nextFollowup=null;p.public=false;}
 else throw Error('Tindakan tidak tersedia.');}}
 if(action!=='obstacle'){o.progress=s.now;o.cycle++;}o.version++;m.version++;event(s,o,action,a,p);return o.id;
}
const api={init,act,tick,attention,businessHours,addBusinessDays,defaults,copy};root.Wami11=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);

